-- Q4 access audit · 5 Oct 2026 · STAGED — NOT APPLIED.
-- Grants and access rules are Alan's call (red). A lane never applies this file; the coordinator does, after his yes.
-- Project: scintilla-live. Measured state: deliverables/20261005/q4-access-audit/evidence/catalog.json
--
-- WHAT: 63 Scintilla tables have no access rules at all: the public key can read, add, change and delete
--       every row. This switches the rules on and adds ONE rule per table: anyone may read (exactly as today).
-- CLOSES: add / change / delete by the public key or a signed-up user.
-- KEEPS: every read, by every page, unchanged. Jobs (database owner) and edge functions (service key) skip
--        the rules and keep writing.
-- BREAKS: only a writer that uses the PUBLIC key. None found in the Hub, Station or provider code for these tables.
--         Not checked: scripts outside those three code lines. Watch the first day: archive_gap_check, composite_history,
--         crypto_volume, market_calendar, sector_rankings, preflight_log, visual_marks (the ones with recent writes).
begin;
alter table public."adjusted_gaps" enable row level security;
create policy q4_public_read on public."adjusted_gaps" for select to anon, authenticated using (true);
alter table public."archive_gap_check" enable row level security;
create policy q4_public_read on public."archive_gap_check" for select to anon, authenticated using (true);
alter table public."composite_history" enable row level security;
create policy q4_public_read on public."composite_history" for select to anon, authenticated using (true);
alter table public."crypto_backfill_queue" enable row level security;
create policy q4_public_read on public."crypto_backfill_queue" for select to anon, authenticated using (true);
alter table public."crypto_day_gaps" enable row level security;
create policy q4_public_read on public."crypto_day_gaps" for select to anon, authenticated using (true);
alter table public."crypto_depth" enable row level security;
create policy q4_public_read on public."crypto_depth" for select to anon, authenticated using (true);
alter table public."crypto_volume" enable row level security;
create policy q4_public_read on public."crypto_volume" for select to anon, authenticated using (true);
alter table public."data_location_registry" enable row level security;
create policy q4_public_read on public."data_location_registry" for select to anon, authenticated using (true);
alter table public."deep1m_ledger" enable row level security;
create policy q4_public_read on public."deep1m_ledger" for select to anon, authenticated using (true);
alter table public."deep1m_rescue_queue" enable row level security;
create policy q4_public_read on public."deep1m_rescue_queue" for select to anon, authenticated using (true);
alter table public."deep1m_run_plan" enable row level security;
create policy q4_public_read on public."deep1m_run_plan" for select to anon, authenticated using (true);
alter table public."edge_function_inventory" enable row level security;
create policy q4_public_read on public."edge_function_inventory" for select to anon, authenticated using (true);
alter table public."estate_identity" enable row level security;
create policy q4_public_read on public."estate_identity" for select to anon, authenticated using (true);
alter table public."fan_spec" enable row level security;
create policy q4_public_read on public."fan_spec" for select to anon, authenticated using (true);
alter table public."fmp_bandwidth_budget" enable row level security;
create policy q4_public_read on public."fmp_bandwidth_budget" for select to anon, authenticated using (true);
alter table public."fmp_entitlements" enable row level security;
create policy q4_public_read on public."fmp_entitlements" for select to anon, authenticated using (true);
alter table public."fmp_minute_depth" enable row level security;
create policy q4_public_read on public."fmp_minute_depth" for select to anon, authenticated using (true);
alter table public."fmp_publish_lag" enable row level security;
create policy q4_public_read on public."fmp_publish_lag" for select to anon, authenticated using (true);
alter table public."fmp_streaming_notes" enable row level security;
create policy q4_public_read on public."fmp_streaming_notes" for select to anon, authenticated using (true);
alter table public."fmp_streams" enable row level security;
create policy q4_public_read on public."fmp_streams" for select to anon, authenticated using (true);
alter table public."geiger_rollback_20260815" enable row level security;
create policy q4_public_read on public."geiger_rollback_20260815" for select to anon, authenticated using (true);
alter table public."indicator_spec" enable row level security;
create policy q4_public_read on public."indicator_spec" for select to anon, authenticated using (true);
alter table public."industry_rule" enable row level security;
create policy q4_public_read on public."industry_rule" for select to anon, authenticated using (true);
alter table public."known_open_items" enable row level security;
create policy q4_public_read on public."known_open_items" for select to anon, authenticated using (true);
alter table public."market_calendar" enable row level security;
create policy q4_public_read on public."market_calendar" for select to anon, authenticated using (true);
alter table public."market_hours" enable row level security;
create policy q4_public_read on public."market_hours" for select to anon, authenticated using (true);
alter table public."pivot_compare" enable row level security;
create policy q4_public_read on public."pivot_compare" for select to anon, authenticated using (true);
alter table public."preflight_log" enable row level security;
create policy q4_public_read on public."preflight_log" for select to anon, authenticated using (true);
alter table public."ref_data" enable row level security;
create policy q4_public_read on public."ref_data" for select to anon, authenticated using (true);
alter table public."relay_escalations" enable row level security;
create policy q4_public_read on public."relay_escalations" for select to anon, authenticated using (true);
alter table public."relay_inbox" enable row level security;
create policy q4_public_read on public."relay_inbox" for select to anon, authenticated using (true);
alter table public."relay_orders" enable row level security;
create policy q4_public_read on public."relay_orders" for select to anon, authenticated using (true);
alter table public."rule_enforcement" enable row level security;
create policy q4_public_read on public."rule_enforcement" for select to anon, authenticated using (true);
alter table public."scin_anchor_states" enable row level security;
create policy q4_public_read on public."scin_anchor_states" for select to anon, authenticated using (true);
alter table public."scin_confirm_window_tf" enable row level security;
create policy q4_public_read on public."scin_confirm_window_tf" for select to anon, authenticated using (true);
alter table public."scin_consolidation_plan" enable row level security;
create policy q4_public_read on public."scin_consolidation_plan" for select to anon, authenticated using (true);
alter table public."scin_coverage" enable row level security;
create policy q4_public_read on public."scin_coverage" for select to anon, authenticated using (true);
alter table public."scin_data_stores" enable row level security;
create policy q4_public_read on public."scin_data_stores" for select to anon, authenticated using (true);
alter table public."scin_series" enable row level security;
create policy q4_public_read on public."scin_series" for select to anon, authenticated using (true);
alter table public."scin_series_src" enable row level security;
create policy q4_public_read on public."scin_series_src" for select to anon, authenticated using (true);
alter table public."scin_source_rank" enable row level security;
create policy q4_public_read on public."scin_source_rank" for select to anon, authenticated using (true);
alter table public."sector_rankings" enable row level security;
create policy q4_public_read on public."sector_rankings" for select to anon, authenticated using (true);
alter table public."sector_vendor_map" enable row level security;
create policy q4_public_read on public."sector_vendor_map" for select to anon, authenticated using (true);
alter table public."session_continuity" enable row level security;
create policy q4_public_read on public."session_continuity" for select to anon, authenticated using (true);
alter table public."sprint_blockers" enable row level security;
create policy q4_public_read on public."sprint_blockers" for select to anon, authenticated using (true);
alter table public."sprint_findings" enable row level security;
create policy q4_public_read on public."sprint_findings" for select to anon, authenticated using (true);
alter table public."sprint_fmp_ledger" enable row level security;
create policy q4_public_read on public."sprint_fmp_ledger" for select to anon, authenticated using (true);
alter table public."sprint_fmp_research_map" enable row level security;
create policy q4_public_read on public."sprint_fmp_research_map" for select to anon, authenticated using (true);
alter table public."sprint_function_rollback" enable row level security;
create policy q4_public_read on public."sprint_function_rollback" for select to anon, authenticated using (true);
alter table public."sprint_lane_topology" enable row level security;
create policy q4_public_read on public."sprint_lane_topology" for select to anon, authenticated using (true);
alter table public."sprint_volume_deps" enable row level security;
create policy q4_public_read on public."sprint_volume_deps" for select to anon, authenticated using (true);
alter table public."station_frame_progress" enable row level security;
create policy q4_public_read on public."station_frame_progress" for select to anon, authenticated using (true);
alter table public."stream_events" enable row level security;
create policy q4_public_read on public."stream_events" for select to anon, authenticated using (true);
alter table public."stream_heartbeat" enable row level security;
create policy q4_public_read on public."stream_heartbeat" for select to anon, authenticated using (true);
alter table public."ticker_coverage" enable row level security;
create policy q4_public_read on public."ticker_coverage" for select to anon, authenticated using (true);
alter table public."ticker_events" enable row level security;
create policy q4_public_read on public."ticker_events" for select to anon, authenticated using (true);
alter table public."ticker_first_bar" enable row level security;
create policy q4_public_read on public."ticker_first_bar" for select to anon, authenticated using (true);
alter table public."timeframe_registry" enable row level security;
create policy q4_public_read on public."timeframe_registry" for select to anon, authenticated using (true);
alter table public."ts_chart_lines" enable row level security;
create policy q4_public_read on public."ts_chart_lines" for select to anon, authenticated using (true);
alter table public."ts_chart_pivots" enable row level security;
create policy q4_public_read on public."ts_chart_pivots" for select to anon, authenticated using (true);
alter table public."ts_chart_pivots_evidence" enable row level security;
create policy q4_public_read on public."ts_chart_pivots_evidence" for select to anon, authenticated using (true);
alter table public."vendor_symbol_map" enable row level security;
create policy q4_public_read on public."vendor_symbol_map" for select to anon, authenticated using (true);
alter table public."visual_marks" enable row level security;
create policy q4_public_read on public."visual_marks" for select to anon, authenticated using (true);
commit;
