/* STATISTICIAN-2 · page + saved charts. node research/statistics/statistician-2/page.mjs
   Reads deliverables/20260928/statistician-2/data/statistician-2.json, writes STATISTICIAN-2.html and charts/*.svg next to it.
   The BACK / CLOSE pair is placed exactly as scripts/inject-scnav.py would (slot above the h1, snippet before </body>). */
import fs from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
import { lineChart, barChart, stackChart, UP, DN } from "./svg.mjs";
const HERE = path.dirname(fileURLToPath(import.meta.url)), ROOT = path.resolve(HERE, "../../..");
const DIR = path.join(ROOT, "deliverables/20260928/statistician-2"), CH = path.join(DIR, "charts");
const J = JSON.parse(fs.readFileSync(path.join(DIR, "data/statistician-2.json"), "utf8"));
fs.mkdirSync(CH, { recursive: true });
const saved = [];
const save = (name, svg) => { fs.writeFileSync(path.join(CH, name), svg); saved.push(name); return `<figure><img src="charts/${name}" alt="${name}"><figcaption><a href="charts/${name}">charts/${name}</a></figcaption></figure>`; };
const fin = (x) => x != null && Number.isFinite(x);
const n0 = (x) => fin(x) ? Math.round(x).toString() : "—", n1 = (x) => fin(x) ? (Math.round(x * 10) / 10).toString() : "—", n2 = (x) => fin(x) ? (Math.round(x * 100) / 100).toFixed(2) : "—";
const pc = (x) => fin(x) ? `${n1(x)}%` : "—", rng = (a, b) => fin(a) && fin(b) ? `${n1(a)} to ${n1(b)}` : "—", sg = (x) => fin(x) ? (x > 0 ? "+" : "") + n1(x) : "—";
const word = (s) => s ? `<b class="w ${s.replace(/[^a-z]/g, "")}">${s}</b>` : "";
const SAME = "#8A8A9E", DIM = "#4A4A54";
const DASH = [null, "9 6", "3 5", "1 5", "12 4 2 4", "6 3", "2 2", "14 6", "4 8", "8 2 2 2", "1 3", "10 10"];

/* ============================== Q1 ============================== */
const Q1 = J.q1, TYPES = Q1.order.filter((g) => g !== "Fear index");
const g1 = (g, win = "full") => Q1.groups[g][win];
const fig1a = save("q1-floor-share-full.svg", lineChart({ title: "How often each type of security sits at or below an RSI level (share of all its days)", sub: "each line = the middle member of its type, full history · read: at RSI 28, index funds are there about 1% of days, commodities and Bitcoin more than 2%", xLabel: "RSI(14) level", yLabel: "% of days at or below the level",
  series: TYPES.map((g, i) => ({ name: `${g} (${g1(g).n})`, pts: g1(g).floors.filter((f) => f.L <= 40).map((f) => [f.L, f.days?.med ?? null]), dash: DASH[i], width: i < 2 ? 3 : 2 })) }));
const fig1b = save("q1-floor-share-common.svg", lineChart({ title: "The same, on one shared window (from 2013, so every type is measured over the same years)", sub: "Bitcoin from 2013 (the S9 start rule) · the ordering barely changes: it is the type, not the years", xLabel: "RSI(14) level", yLabel: "% of days at or below the level",
  series: TYPES.filter((g) => g1(g, "common").n).map((g, i) => ({ name: `${g} (${g1(g, "common").n})`, pts: g1(g, "common").floors.filter((f) => f.L <= 40).map((f) => [f.L, f.days?.med ?? null]), dash: DASH[i], width: i < 2 ? 3 : 2 })) }));
const fig1c = save("q1-bottom-1pct.svg", barChart({ title: "The RSI that marks the bottom 1% of each type's own history (middle member; label = 10th–90th member spread)", sub: "lower bar = the type goes deeper before it is 'as rare as' SPY's RSI 28 · full history", bars: TYPES.map((g) => { const L = g1(g).ladder["1"]; return { label: g.replace(/ \(.*\)/, "").replace("Indexes (long history)", "Indexes 1928→"), v: L?.med ?? null, col: SAME }; }), yLabel: "RSI(14) at the 1st percentile", valFmt: (v) => n1(v), rotate: true, h: 560, bottom: 170 }));
const fig1d = save("q1-ceiling-share.svg", lineChart({ title: "Ceilings: share of days at or above an RSI level, by type", sub: "the mirror image · at RSI 70 SPY is there about 7% of days, Bitcoin about 12%", xLabel: "RSI(14) level", yLabel: "% of days at or above the level",
  series: TYPES.map((g, i) => ({ name: `${g} (${g1(g).n})`, pts: g1(g).ceilings.filter((f) => f.L >= 60 && f.L <= 85).map((f) => [f.L, f.days?.med ?? null]), dash: DASH[i], width: i < 2 ? 3 : 2 })) }));
const at = (g, L, win = "full") => g1(g, win).floors.find((f) => f.L === L);
const t1 = `<div class="scroll"><table><tr><th>type (members)</th><th>RSI at its 1st pct<br><span class="q">middle member · member spread</span></th><th>5th pct</th><th>median</th><th>95th</th><th>99th</th><th>days at/below 28</th><th>visits to ≤28 per year</th><th>a visit lasts (sessions)</th><th>days at/below 30</th><th>days at/above 70</th><th>from 2013 only: 1st pct · ≤28 days</th></tr>${TYPES.map((g) => { const F = g1(g), C = g1(g, "common"), L = (p) => F.ladder[p]; const a28 = at(g, 28), a30 = at(g, 30), c70 = F.ceilings.find((f) => f.L === 70); return `<tr><td>${g} (${F.n})</td><td><b>${n1(L("1")?.med)}</b> <span class="q">${rng(L("1")?.lo, L("1")?.hi)}</span></td><td>${n1(L("5")?.med)}</td><td>${n1(L("50")?.med)}</td><td>${n1(L("95")?.med)}</td><td>${n1(L("99")?.med)}</td><td><b>${pc(a28.days?.med)}</b> <span class="q">${rng(a28.days?.lo, a28.days?.hi)}</span></td><td>${n1(a28.perYear?.med)}</td><td>${n1(a28.len?.med)}</td><td>${pc(a30.days?.med)}</td><td>${pc(c70.days?.med)}</td><td>${C.n ? `${n1(C.ladder["1"]?.med)} · ${pc(at(g, 28, "common").days?.med)}` : "—"}</td></tr>`; }).join("")}</table></div>`;
const memberRows = (g) => Q1.members[g].map((m) => `<tr><td>${m.sym}</td><td>${m.from} → ${m.to}</td><td>${m.n}</td><td>${n1(m.p1)}</td><td>${n1(m.p5)}</td><td>${n1(m.p50)}</td><td>${n1(m.p95)}</td><td>${n1(m.p99)}</td><td>${pc(m.d28)}</td><td>${n2(m.y28)}</td><td>${pc(m.d70)}</td><td>${n1(m.min)} · ${n1(m.max)}</td></tr>`).join("");
const t1m = `<details><summary>Every member: the same numbers per security (${Object.values(Q1.members).flat().length} securities)</summary><div class="scroll"><table><tr><th>security</th><th>history</th><th>RSI days</th><th>1st pct</th><th>5th</th><th>median</th><th>95th</th><th>99th</th><th>days ≤28</th><th>visits ≤28 / yr</th><th>days ≥70</th><th>lowest · highest RSI ever</th></tr>${Q1.order.map((g) => `<tr><th colspan="12" class="sec">${g}</th></tr>${memberRows(g)}`).join("")}</table></div></details>`;
const spy = Q1.members["Index funds"].find((m) => m.sym === "SPY"), btc = Q1.members["Crypto"][0];

/* ============================== Q2 ============================== */
const Q2 = J.q2, P = Q2.pooled;
const kmPts = (steps, tMax = 250) => { const pts = []; for (let i = 0; i < steps.length; i++) { const [t, S] = steps[i]; if (t > tMax) break; if (i > 0) pts.push([t, 100 * steps[i - 1][1]]); pts.push([t, 100 * S]); } if (pts.length && pts.at(-1)[0] < tMax) pts.push([tMax, pts.at(-1)[1]]); return pts; };
const fig2a = save("q2-wait-by-depth.svg", lineChart({ title: "The base fact: the wait for a new high, by how deep the fall was (SPY + QQQ + IWM, every swing low since 2003)", sub: `${Q2.depth.bins.reduce((s, b) => s + b.n, 0)} lows in five equal-count depth bands · Kaplan–Meier: the share of lows still waiting, censored waits kept · the median wait is where each line crosses 50%`, xLabel: "sessions after the low", yLabel: "% of lows still without a new high", yDomain: [0, 100], xDomain: [0, 250],
  series: Q2.depth.bins.map((b, i) => ({ name: `falls of ${n1(b.from)}–${n1(b.to)}% (${b.n}, median ${b.median ?? "open"} sessions)`, pts: kmPts(b.steps), dash: DASH[i], width: 2.4 })) }));
const fig2b = save("q2-conditions-rho.svg", barChart({ title: "Which conditions at the low changed the wait, once depth is taken out (pooled, rank partial correlation)", sub: "below 0 (green) = more of it meant a FASTER new high · above 0 (red) = slower · only the bars marked luck-proof survive the false-discovery check over 16 conditions", bars: P.rows.map((r) => ({ label: `${r.k}${r.status === "luck-proof" ? " ✓" : r.status === "leaning" ? " ~" : ""}`, v: fin(r.rho) ? r.rho : null, col: fin(r.rho) ? (r.rho < 0 ? UP : DN) : DIM, show: true })), yLabel: "partial rank correlation with the wait", valFmt: (v) => n2(v), rotate: true, h: 560, bottom: 150 }));
const fig2c = Q2.km.pairs.map((p, i) => save(`q2-km-${p.key}.svg`, lineChart({ title: `${p.name}: the wait, falls of 3–10% only`, w: 760, h: 420, sub: `yes ${p.yes.n} lows (median depth ${p.yesDepth}%, median wait ${p.yes.median ?? "open"}) · no ${p.no.n} (depth ${p.noDepth}%, wait ${p.no.median ?? "open"})`, xLabel: "sessions after the low", yLabel: "% still waiting", yDomain: [0, 100], xDomain: [0, 120], series: [{ name: "condition YES", pts: kmPts(p.yes.steps, 120), width: 3 }, { name: "condition NO", pts: kmPts(p.no.steps, 120), dash: "9 6" }] }))).join("");
const t2 = (S) => `<div class="scroll"><table><tr><th>condition at the low</th><th>n lows</th><th>link to the wait with depth held<br><span class="q">rank partial correlation · 90% range over lows</span></th><th>p · adjusted (16 tests)</th><th>status</th><th>top third of the condition<br><span class="q">median wait · median depth</span></th><th>bottom third<br><span class="q">median wait · median depth</span></th></tr>${S.rows.map((r) => `<tr><td>${r.text}<br><span class="q">${r.kind === "outside" ? "outside information" : "computed from the same prices"}</span></td><td>${r.n}</td><td>${fin(r.rho) ? `<b>${sg(r.rho)}</b> <span class="q">${rng(r.lo, r.hi)}</span>` : "—"}</td><td>${n2(r.p)} · ${n2(r.pAdj)}</td><td>${word(r.status)}</td><td>${r.topMed ?? "—"} sessions · ${n1(r.topDepth)}%</td><td>${r.botMed ?? "—"} sessions · ${n1(r.botDepth)}%</td></tr>`).join("")}</table></div>`;
const luck2 = P.rows.filter((r) => r.status === "luck-proof"), lean2 = P.rows.filter((r) => r.status === "leaning");

/* ============================== Q3 ============================== */
const Q3 = J.q3;
const fig3a = save("q3-before-by-depth.svg", barChart({ title: "Put/call peaked BEFORE or ON the low — share of lows, by how deep the fall was (SPY)", sub: "four equal-count depth bands · total put/call (PCC, green) beside equity put/call (PCCE, grey) · label = share; the table gives the 90% range", bars: Q3.byDepth.SPY.bins.flatMap((b) => [{ label: `${n1(b.from)}–${n1(b.to)}% PCC`, v: b.pcc.share, col: UP }, { label: `PCCE`, v: b.pcce.share, col: SAME }]), yLabel: "% of lows with the peak before / on the low", valFmt: (v) => n0(v) + "%", rotate: true, h: 520, bottom: 150 }));
const fig3b = save("q3-frames.svg", barChart({ title: "Which time frame of the put/call ratio predicts a swing low? Hit rate of its peaks (SPY, 2006→)", sub: `a hit = a confirmed SPY swing low within 5 sessions before to 15 after the put/call peak · any day: ${pc(Q3.frames[0].base)} · green = beats any day at the 90% range`, bars: Q3.frames.map((f) => ({ label: `${f.k === 1 ? "daily" : f.k + "-day avg"} (${f.peaks} peaks)`, v: f.hit, col: fin(f.lo) && f.lo > f.base ? UP : SAME })), yLabel: "% of peaks with a low nearby", valFmt: (v) => n1(v) + "%", h: 440 }));
const fig3c = save("q3-levels.svg", lineChart({ title: "Levels: the higher the put/call peak sits in its own history, the more often a low followed (5-day average, SPY)", sub: "x = the peak's own-history percentile threshold · thick = hit rate · thin dashed = how many peaks reached it (right scale not drawn; see table)", xLabel: "peak at or above this own-history percentile", yLabel: "% of peaks with a low nearby", yDomain: [30, 100], yMarks: [{ y: Q3.frames[0].base, label: `any day ${n0(Q3.frames[0].base)}%` }],
  series: Q3.frames.filter((f) => [1, 3, 5, 10].includes(f.k)).map((f, i) => ({ name: `${f.k === 1 ? "daily" : f.k + "-day"}`, pts: f.byPct.map((b) => [b.th, b.hit]), dash: DASH[i], width: f.k === 5 ? 3 : 2 })) }));
const t3a = ["SPY", "QQQ", "IWM"].map((s) => { const B = Q3.byDepth[s]; const cell = (c) => c.withTurn ? `<b>${c.before} of ${c.withTurn}</b> (${pc(c.share)}) <span class="q">${rng(c.lo, c.hi)} · lead ${c.lead ?? "—"}, 90% within ${n0(c.leadHi)}</span>` : "—"; return `<tr><th colspan="4" class="sec">${s} · ${B.n} lows with put/call data</th></tr>${B.bins.map((b) => `<tr><td>falls of ${n1(b.from)}–${n1(b.to)}% (${b.pcc.n})</td><td>${cell(b.pcc)}</td><td>${cell(b.pcce)}</td><td>PCC ${n2(b.pccLevel)} (${n0(b.pccPctMed)}th pct) · PCCE ${n2(b.pcceLevel)}</td></tr>`).join("")}<tr><td><b>not-so-deep (under 10%)</b> (${B.shallow.n})</td><td>${cell(B.shallow)}</td><td>${cell(B.shallowE)}</td><td></td></tr><tr><td><b>deep (10% or more)</b> (${B.deep.n})</td><td>${cell(B.deep)}</td><td>${cell(B.deepE)}</td><td></td></tr><tr><td><b>all</b> (${B.all.n})</td><td>${cell(B.all)}</td><td>${cell(B.allE)}</td><td></td></tr>`; }).join("");
const t3b = `<div class="scroll"><table><tr><th>time frame</th><th>peaks (per year)</th><th>hit rate · 90% range</th><th>p vs any day</th><th>lead (median, middle half)</th><th>SPY lows caught</th><th>at ≥80th pct</th><th>≥90th</th><th>≥95th</th><th>≥99th</th></tr>${Q3.frames.map((f) => `<tr><td>${f.k === 1 ? "daily print" : `${f.k}-session average`}</td><td>${f.peaks} (${n1(f.perYear)})</td><td><b>${pc(f.hit)}</b> <span class="q">${rng(f.lo, f.hi)}</span></td><td>${n2(f.p)}</td><td>${f.lead ?? "—"} (${f.leadIqr.map((x) => x ?? "—").join(" to ")})</td><td>${pc(f.lowsCaught)}</td>${f.byPct.filter((b) => b.th >= 80).map((b) => `<td>${b.n ? `${pc(b.hit)} <span class="q">n ${b.n} · PCC ≈ ${n2(b.level)}</span>` : "—"}</td>`).join("")}</tr>`).join("")}</table></div>`;
const t3c = `<div class="scroll"><table><tr><th>raw PCC at or above</th><th>own percentile (median)</th><th>days</th><th>episodes</th><th>episodes with a low within 15 sessions</th><th>days with a low within 15</th></tr>${Q3.levels.rows.map((r) => `<tr><td>${n2(r.level)}</td><td>${n0(r.pct)}th</td><td>${r.days}</td><td>${r.episodes}</td><td><b>${pc(r.epHit)}</b></td><td>${pc(r.dayHit)}</td></tr>`).join("")}</table></div>`;
const f5 = Q3.frames.find((f) => f.k === 5), f1 = Q3.frames[0];

/* ============================== Q4 ============================== */
const Q4 = J.q4, st = (s) => `${s.side === "above" ? "above" : "BELOW"} · 200-day ${s.slopeUp ? "rising" : "falling"} · 50 ${s.order ? ">" : "<"} 200`;
const fig4a = save("q4-states.svg", barChart({ title: "The 200-day, eight states: median return over the next 63 sessions (24 instruments pooled, 1928→)", sub: `any day ${sg(Q4.base.f63.med)}% · green = the state's 90% range sits above any day, red = below, grey = overlaps · ✓ = survives the false-discovery check over ${Q4.tests} cells`, bars: Q4.states.map((s) => ({ label: `${s.side === "above" ? "above" : "BELOW"} · ${s.slopeUp ? "rising" : "falling"} · 50${s.order ? ">" : "<"}200 · ${n0(s.share)}%${s.f63.pMedSurvives ? " ✓" : ""}`, v: s.f63.med ?? null, col: fin(s.f63.medLo) ? (s.f63.medLo > Q4.base.f63.med ? UP : s.f63.medHi < Q4.base.f63.med ? DN : SAME) : DIM })), yLabel: "median next-63 return, %", valFmt: (v) => sg(v), rotate: true, h: 640, bottom: 250 }));
const fig4b = save("q4-time-below.svg", barChart({ title: "Time already spent below the 200-day: share of the next 63 sessions that were up", sub: `any day ${pc(Q4.base.f63.up)} · green = the bin's 90% range sits above any day, red = below, grey = overlaps · label = median worst fall over the next 126 sessions`, bars: Q4.timeBelow.map((t) => ({ label: `${t.from}–${t.to >= 100000 ? "more" : t.to} below · fall ${n1(t.dd126.med)}%`, v: t.f63.up ?? null, col: fin(t.f63.upLo) ? (t.f63.upLo > Q4.base.f63.up ? UP : t.f63.upHi < Q4.base.f63.up ? DN : SAME) : DIM })), yLabel: "% of next-63 stretches up", valFmt: (v) => n1(v) + "%", rotate: true, h: 560, bottom: 190 }));
const fig4c = save("q4-breaks.svg", barChart({ title: "First break vs repeated break of the 200-day: the next 63 sessions", sub: "first = the first close below after at least 63 sessions above · repeated = a break within 63 sessions of the previous stretch below · median return (bar) · label = share up", bars: Q4.breaks.map((b) => ({ label: `${b.kind} (${b.n}) · ${pc(b.f63.up)} up · worst fall ${n1(b.dd126.med)}%`, v: b.f63.med ?? null, col: SAME })), yLabel: "median next-63 return, %", valFmt: (v) => sg(v), h: 420 }));
const cellTd = (c, key, base) => { const v = c[key]; if (!fin(v)) return `<td>—</td>`; const lo = c[key + "Lo"], hi = c[key + "Hi"]; const cls = fin(lo) && lo > base ? "up" : fin(hi) && hi < base ? "dn" : ""; return `<td class="${cls}"><b>${key === "up" ? pc(v) : sg(v)}</b> <span class="q">${rng(lo, hi)}${c[(key === "up" ? "pUp" : "pMed") + "Survives"] ? " ✓" : ""}</span></td>`; };
const t4a = `<div class="scroll"><table><tr><th>state (share of days)</th><th>days · instrument-years</th><th>next 63: median</th><th>next 63: share up</th><th>next 126: median</th><th>worst fall next 126: median</th><th>worst fall: 10th pct</th></tr><tr><td><b>any day</b></td><td>${Q4.base.f63.n} · ${Q4.base.f63.instYears}</td><td>${sg(Q4.base.f63.med)}</td><td>${pc(Q4.base.f63.up)}</td><td>${sg(Q4.base.f126.med)}</td><td>${n1(Q4.base.dd126.med)}%</td><td>${n1(Q4.base.dd126.p10)}%</td></tr>${Q4.states.map((s) => `<tr><td>${st(s)} (${s.share}%)</td><td>${s.f63.n} · ${s.f63.instYears}</td>${cellTd(s.f63, "med", Q4.base.f63.med)}${cellTd(s.f63, "up", Q4.base.f63.up)}${cellTd(s.f126, "med", Q4.base.f126.med)}${cellTd(s.dd126, "med", Q4.base.dd126.med)}<td>${n1(s.dd126.p10)}%</td></tr>`).join("")}</table></div>`;
const t4b = `<div class="scroll"><table><tr><th>sessions below so far</th><th>days</th><th>next 63: median</th><th>next 63: share up</th><th>next 126: median</th><th>worst fall next 126</th></tr>${Q4.timeBelow.map((t) => `<tr><td>${t.from}–${t.to >= 100000 ? "more" : t.to}</td><td>${t.f63.n}</td>${cellTd(t.f63, "med", Q4.base.f63.med)}${cellTd(t.f63, "up", Q4.base.f63.up)}${cellTd(t.f126, "med", Q4.base.f126.med)}${cellTd(t.dd126, "med", Q4.base.dd126.med)}</tr>`).join("")}</table></div>`;
const t4c = `<div class="scroll"><table><tr><th>depth below × time below</th>${Q4.grid[0].cells.map((c) => `<th>${c.dur[0]}–${c.dur[1] >= 100000 ? "more" : c.dur[1]} sessions below</th>`).join("")}</tr>${Q4.grid.map((g) => `<tr><td><b>${g.dep[0]}–${g.dep[1] >= 100 ? "more" : g.dep[1]}% below</b></td>${g.cells.map((c) => `<td>${c.n < 60 ? `<span class="q">${c.n} days · a list</span>` : `next 126 median <b>${sg(c.medF126)}</b><br>a further 10%+ fall in <b class="${c.shareDD10 > Q4.baseDD10 + 5 ? "dn" : c.shareDD10 < Q4.baseDD10 - 5 ? "up" : ""}">${pc(c.shareDD10)}</b> of days<br><span class="q">${c.n} days · ${c.instYears} instrument-years</span>`}</td>`).join("")}</tr>`).join("")}</table></div>`;
const t4d = `<div class="scroll"><table><tr><th>break</th><th>breaks</th><th>next 63: median</th><th>next 63: share up</th><th>next 126: median</th><th>worst fall next 126: median</th><th>a further 10%+ fall</th></tr>${Q4.breaks.map((b) => `<tr><td>${b.kind}</td><td>${b.n}</td>${cellTd(b.f63, "med", Q4.base.f63.med)}${cellTd(b.f63, "up", Q4.base.f63.up)}${cellTd(b.f126, "med", Q4.base.f126.med)}${cellTd(b.dd126, "med", Q4.base.dd126.med)}<td>${pc(b.shareDD10)} <span class="q">any day ${pc(Q4.baseDD10)}</span></td></tr>`).join("")}</table></div>`;
const worst4 = Q4.states.find((s) => s.side === "below" && !s.slopeUp && !s.order), best4 = Q4.states.find((s) => s.side === "above" && s.slopeUp && s.order);
const tb64 = Q4.timeBelow.find((t) => t.from === 64);

/* ============================== Q5 ============================== */
const Q5 = J.q5, L5 = Q5.lows, H5 = Q5.highs, G5 = Q5.gauge;
const fig5a = save("q5-leader-low-offset.svg", barChart({ title: `When do the leaders bottom against the S&P? Sessions from SPY's swing low to the leader's own swing low (${L5.withOwnLow} leader-lows, ${L5.episodes} SPY lows since 2007)`, sub: "left of 0 (green) = the leader bottomed FIRST · 0 = same session · right (red) = after · the leader is one of that year's top 20 by market cap at the time", bars: L5.offsetHist.map((h) => ({ label: h.o % 5 === 0 ? String(h.o) : "", v: h.n, col: h.o < 0 ? UP : h.o === 0 ? SAME : DN, show: false })), yLabel: "leader-lows", xLabel: "sessions from the SPY low (negative = before)", h: 420 }));
const fig5b = save("q5-gauge-curve.svg", lineChart({ title: "Fear and greed applied to the leaders: what the leaders did against SPY over the next 63 sessions, by the fear gauge", sub: `gauge = average own-percentile of VIX, put/call, SPY RSI (flipped) and breadth (flipped): 100 = maximum fear · ${G5.from} → ${G5.to} · medians per 5-point band`, xLabel: "fear gauge (0 = greed, 100 = fear)", yLabel: "%",
  series: [{ name: "leaders minus SPY, next 63 (median)", pts: G5.curve.map((c) => [c.g, c.rel]), width: 3 }, { name: "leaders' worst fall in the next 63 (median, negative)", pts: G5.curve.map((c) => [c.g, c.ddb]), dash: "9 6" }, { name: "leaders' next-63 return (median)", pts: G5.curve.map((c) => [c.g, c.fb]), dash: "2 5", width: 1.8 }] }));
const fig5c = save("q5-ratio-by-depth.svg", barChart({ title: "How much more do the leaders fall than SPY in the same decline? Leader fall ÷ SPY fall, median by depth band", sub: "1.0 = the leader fell as much as SPY · label = the leaders' own median fall", bars: L5.byDepth.map((b) => ({ label: `SPY falls of ${n1(b.from)}–${n1(b.to)}% (${b.eps} lows) · leaders ${n1(b.own)}%`, v: b.ratio, col: b.ratio > 1 ? DN : UP })), yLabel: "leader fall ÷ SPY fall", valFmt: (v) => n2(v), h: 420 }));
const t5a = `<div class="scroll"><table><tr><th>SPY falls of</th><th>leader-lows (SPY lows)</th><th>leader bottomed before</th><th>after</th><th>leader's own fall (median)</th><th>leader fall ÷ SPY fall</th><th>leader minus SPY, next 63 from the SPY low</th></tr>${L5.byDepth.map((b) => `<tr><td>${n1(b.from)}–${n1(b.to)}%</td><td>${b.n} (${b.eps})</td><td>${pc(b.before)}</td><td>${pc(b.after)}</td><td>${n1(b.own)}%</td><td>${n2(b.ratio)}</td><td>${sg(b.rel63)}</td></tr>`).join("")}<tr><td><b>all</b></td><td>${L5.n} (${L5.episodes})</td><td><b>${pc(L5.before)}</b> <span class="q">same ${pc(L5.same)} · no own low ${pc(L5.noOwnLow)}</span></td><td>${pc(L5.after)}</td><td></td><td><b>${n2(L5.ratio.est)}</b> <span class="q">${rng(L5.ratio.lo, L5.ratio.hi)} · middle half ${n2(L5.ratioDist.p25)}–${n2(L5.ratioDist.p75)}</span></td><td><b>${sg(L5.rel63.est)}</b> <span class="q">${rng(L5.rel63.lo, L5.rel63.hi)} · leaders ahead in ${pc(L5.rel63Up.est)}</span></td></tr></table></div>`;
const t5b = `<div class="scroll"><table><tr><th>fear gauge</th><th>days · months</th><th>leaders minus SPY, next 63 (median)</th><th>leaders next 63</th><th>SPY next 63</th><th>leaders' worst fall next 63</th><th>SPY's worst fall next 63</th></tr><tr><td><b>any day</b></td><td>${G5.n}</td><td>${sg(G5.base.rel)}</td><td>${sg(G5.base.fb)}</td><td>${sg(G5.base.fsp)}</td><td>${n1(G5.base.ddb)}%</td><td>${n1(G5.base.dds)}%</td></tr>${G5.deciles.map((d) => { const c = (m, base) => m ? `<td class="${m.lo > base ? "up" : m.hi < base ? "dn" : ""}"><b>${sg(m.est)}</b> <span class="q">${rng(m.lo, m.hi)}</span></td>` : "<td>—</td>"; return `<tr><td>${d.from}–${d.to}${d.from === 0 ? " (greed)" : d.to === 100 ? " (fear)" : ""}</td><td>${d.n} · ${d.months}</td>${c(d.rel, G5.base.rel)}${c(d.fb, G5.base.fb)}${c(d.fsp, G5.base.fsp)}${c(d.ddb, G5.base.ddb)}${c(d.dds, G5.base.dds)}</tr>`; }).join("")}</table></div>`;
const fearTop = G5.deciles.at(-1), greedBot = G5.deciles[0];

/* ============================== Q6 ============================== */
const Q6 = J.q6, REG = ["yield up · dollar up", "yield up · dollar down", "yield down · dollar up", "yield down · dollar down"];
const fig6 = ["GSPC", "SPY", "LEADERS"].map((key, i) => { const I = Q6.instruments[key], o = I.defs.level; return save(`q6-curve-${key}.svg`, lineChart({ title: `${I.name}: how often the next 63 sessions held a fall of at least x%, by regime (levels vs the 200-day)`, w: 760, h: 440, sub: `${I.from} → ${I.to} · a fall = the deepest close below today's within 63 sessions`, xLabel: "fall of at least x%", yLabel: "% of 63-session windows", yDomain: [0, 70], series: o.curve.map((c, j) => ({ name: c.rg, pts: c.pts, dash: DASH[j], width: c.rg === "any day" ? 1.4 : c.rg === "yield up · dollar up" ? 3.2 : 2 })) })); }).join("");
const fig6b = save("q6-share5.svg", barChart({ title: "Yields up and dollar up (both above their 200-day): share of 63-session windows with a fall of 5% or more", sub: "S&P 500 since 1971, SPY since 2003, the leaders basket since 2007 · beside 'any day' for each · none of the differences survives the false-discovery check", bars: ["GSPC", "SPY", "LEADERS"].flatMap((key) => { const I = Q6.instruments[key], o = I.defs.level; return [{ label: `${key === "GSPC" ? "S&P 1971→" : key === "SPY" ? "SPY" : "leaders"} · yields↑ $↑`, v: o.regimes["yield up · dollar up"].s5, col: DN }, { label: `any day`, v: o.base.s5, col: SAME }, { label: `yields↑ $↓`, v: o.regimes["yield up · dollar down"].s5, col: UP }]; }), yLabel: "% of windows", valFmt: (v) => n0(v) + "%", rotate: true, h: 560, bottom: 200 }));
const t6 = (key, def) => { const I = Q6.instruments[key], o = I.defs[def]; const row = (name, s) => `<tr><td>${name}</td><td>${s.n} · ${s.quarters}${s.share != null ? ` · ${pc(s.share)}` : ""}</td><td>${n1(s.dist.p10)}%</td><td>${n1(s.dist.p25)}%</td><td class="${fin(s.medHi) && s.medHi < o.base.med ? "dn" : fin(s.medLo) && s.medLo > o.base.med ? "up" : ""}"><b>${n1(s.med)}%</b> <span class="q">${rng(s.medLo, s.medHi)}</span></td><td>${n1(s.dist.p75)}%</td><td class="${fin(s.s5Lo) && s.s5Lo > o.base.s5 ? "dn" : fin(s.s5Hi) && s.s5Hi < o.base.s5 ? "up" : ""}"><b>${pc(s.s5)}</b> <span class="q">${rng(s.s5Lo, s.s5Hi)}${s.pS5Survives ? " ✓" : ""}</span></td><td>${pc(s.s10)}</td><td>${sg(s.f63)}</td><td>${o.declines[name === "any day" ? "all" : name].n} · ${n1(o.declines[name === "any day" ? "all" : name].dist?.p50)}% · ${pc(o.declines[name === "any day" ? "all" : name].s10)}</td></tr>`;
  return `<div class="scroll"><table><tr><th>${I.name} · ${I.from} → ${I.to}</th><th>days · quarters · share</th><th>fall: 10th pct (mild)</th><th>25th</th><th>median fall next 63 · 90% range</th><th>75th (bad)</th><th>windows with a 5%+ fall</th><th>10%+ fall</th><th>next-63 return (median)</th><th>swing declines that began here: n · median depth · 10%+</th></tr>${row("any day", o.base)}${REG.map((rg) => row(rg, o.regimes[rg])).join("")}</table></div>`; };
const g6 = Q6.instruments.GSPC.defs.level, l6 = Q6.instruments.LEADERS.defs.level, s6 = Q6.instruments.SPY.defs.level;

/* ============================== Q7 ============================== */
const Q7 = J.q7, S7 = Q7.spx;
const fig7a = save("q7-pairs-1y.svg", barChart({ title: "Where the equal-vs-cap divergence is: one-year change of the equal ÷ cap ratio, every pair", sub: "negative (red) = the cap-weighted side won over the last 252 sessions · label = where today's ratio sits in the pair's own history (percentile)", bars: Q7.pairs.map((p) => ({ label: `${p.label} · ${n1(p.levelPctAll)}th`, v: p.change252, col: p.change252 < 0 ? DN : UP })), yLabel: "% change of equal ÷ cap, one year", valFmt: (v) => sg(v), rotate: true, h: 660, bottom: 270 }));
const fig7b = save("q7-spx-curve.svg", lineChart({ title: "RSP ÷ SPY at every percentile of its own history: what SPY did over the next 63 sessions, and whether equal weight caught up", sub: `${S7.from} → ${S7.to} · 5-point bands of the own-history percentile · today: ${n1(S7.today.pct)}th`, xLabel: "RSP ÷ SPY own-history percentile", yLabel: "median next-63, %", yMarks: [{ y: S7.spyBase[63].med, label: `SPY any day ${sg(S7.spyBase[63].med)}` }],
  series: [{ name: "SPY next 63 (median)", pts: S7.curve.map((c) => [c.p, c.spy63]), width: 3 }, { name: "RSP minus SPY next 63 (median)", pts: S7.curve.map((c) => [c.p, c.catchUp63]), dash: "9 6" }] }));
const t7a = `<div class="scroll"><table><tr><th>pair (equal ÷ cap)</th><th>since</th><th>today's percentile (all · 3y)</th><th>one-year change</th><th>past extremes (lows)</th><th>after past lows: cap side next 63 · next 252 (median)</th><th>equal minus cap next 63 · next 252</th></tr>${Q7.seven.map((p) => `<tr><td><b>${p.label}</b> · ${p.ew} ÷ ${p.cw}</td><td>${p.from}</td><td><b>${n1(p.levelPctAll)}th</b> · ${n1(p.levelPct3y)}th</td><td>${sg(p.change252)}%</td><td>${p.lows}</td><td>${p.after ? `${sg(p.after.cw63)}% · ${sg(p.after.cw252)}%` : "—"}</td><td>${p.after ? `${sg(p.after.ratio63)} · ${sg(p.after.ratio252)}` : "—"}</td></tr>`).join("")}</table></div>`;
const t7b = `<div class="scroll"><table><tr><th>entry (RSP ÷ SPY ≤ 5th pct)</th><th>pct</th><th>SPY next 63</th><th>126</th><th>252</th><th>equal minus cap 63</th><th>126</th><th>252</th><th>leaders next 63</th><th>126</th><th>252</th></tr>${S7.entries.map((e) => `<tr><td>${e.d}</td><td>${n1(e.pct)}</td><td>${sg(e.spy63)}</td><td>${sg(e.spy126)}</td><td>${sg(e.spy252)}</td><td>${sg(e.catchUp63)}</td><td>${sg(e.catchUp126)}</td><td>${sg(e.catchUp252)}</td><td>${sg(e.lead63)}</td><td>${sg(e.lead126)}</td><td>${sg(e.lead252)}</td></tr>`).join("")}<tr><td><b>median (n)</b></td><td></td>${["spy63", "spy126", "spy252", "catchUp63", "catchUp126", "catchUp252", "lead63", "lead126", "lead252"].map((k) => { const s = S7.summ[k]; return `<td><b>${sg(s.med)}</b> <span class="q">n ${s.n} · ${pc(s.up)} up</span></td>`; }).join("")}</tr><tr><td><b>SPY any day</b></td><td></td><td>${sg(S7.spyBase[63].med)}</td><td>${sg(S7.spyBase[126].med)}</td><td>${sg(S7.spyBase[252].med)}</td><td colspan="6"></td></tr></table></div>`;
const t7c = `<div class="scroll"><table><tr><th>the last 252 sessions to ${Q7.sectors1y.d}</th><th>SPY (cap weight)</th><th>RSP (equal weight)</th><th>leaders basket (this year's top 20)</th><th>the middle served stock (${Q7.sectors1y.stocksN})</th><th>served stocks up</th></tr><tr><td>one-year return</td><td><b>${sg(Q7.sectors1y.spy)}%</b></td><td>${sg(Q7.sectors1y.rsp)}%</td><td>${sg(Q7.sectors1y.leaders)}%</td><td>${sg(Q7.sectors1y.stockMed)}%</td><td>${pc(Q7.sectors1y.stockUp)}</td></tr></table></div>`;

/* ============================== Q8 (proposal, from the measured results) ============================== */
const gaugeRows = [
  ["TIDE", "share of names above their 50-day (own percentile) · RSP ÷ SPY (own percentile)", "breadth at the low is luck-proof for the wait (Q2); RSP ÷ SPY extremes are a list (Q7)", "yes: breadth · RSP÷SPY as a reading only", "bottoms · statistician-2"],
  ["FEAR", "VIX own percentile · put/call 5-session average, own percentile · the fear gauge (four percentiles averaged)", "VIX pct at the low: luck-proof (Q2) · put/call 5-day peaks ≥90th: 89% hit vs 43% any day (Q3) · gauge deciles: leaning at the ends (Q5)", "yes: VIX pct, put/call 5-day, the gauge", "bottoms · statistician-2"],
  ["TREND", "side of the 200-day · its slope · 50/200 order · sessions below · depth × duration (Q4)", `worst state (below, falling, 50<200) is ${pc(worst4.f63.up)} up vs ${pc(Q4.base.f63.up)} any day; ${Q4.survivors} of ${Q4.tests} cells survive FDR`, "yes: one line with the state word and the sessions below", "bottoms · statistician-2"],
  ["RATES & DOLLAR", "10-year and DXY vs their 200-day, as a regime label", "yields↑ $↑ is the weakest quadrant everywhere but not luck-proof (Q6)", "reading only, no card", "market regime · statistician-2"],
  ["CREDIT", "HYG ÷ LQD from its high", "credit decline at the low did not change the wait (Q2)", "reading only", "market regime"],
  ["LEADERS", "leader fall ÷ SPY fall in the current decline · leader vs SPY since the last SPY low · give-back of the run", `leaders fall about as much as SPY (ratio ${n2(L5.ratio.est)}) and lag it slightly after the low (${sg(L5.rel63.est)} at 63 sessions, luck-proof)`, "yes: one line", "leaders · statistician-2"],
  ["RSI BY TYPE", "each security's RSI against its OWN type's ladder, not SPY's", `crypto and commodities reach 28 two to three times as often as index funds (Q1)`, "yes: the floor table feeds the Station's RSI percentile", "rsi ladder · statistician-2"],
];
const t8 = `<div class="scroll"><table><tr><th>block</th><th>the measure(s)</th><th>what today's studies say</th><th>a place on the statistics tab?</th><th>where it is measured</th></tr>${gaugeRows.map((r) => `<tr>${r.map((c, i) => `<td>${i === 0 ? `<b>${c}</b>` : c}</td>`).join("")}</tr>`).join("")}</table></div>`;

/* ============================== today ============================== */
const T = { g: G5.today, q4: Q4.today, q6: Q6.today, q7: S7.today, pcc: Q3.levels.today };

/* ============================== the page ============================== */
const html = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Statistician 2 · Alan's second round, measured · 28 Sep 2026</title>
<style>
body{margin:0;background:#07070C;color:#B4B4C6;font:17px/1.55 -apple-system,"Helvetica Neue",Arial,sans-serif;padding:28px 34px 80px;max-width:1500px}
h1{font-size:34px;margin:0 0 6px;color:#C8C8D2}h2{font-size:27px;margin:52px 0 8px;color:#C8C8D2;border-top:1px solid #24242E;padding-top:22px}h3{font-size:20px;margin:30px 0 6px;color:#C8C8D2}
p,li{max-width:1100px}.q{color:#9C9CAE;font-size:13px}code{font:13px ui-monospace,Menlo,monospace;color:#A8A8BA;word-break:break-all}.three div{min-width:0}
ol.lead{font-size:18px;color:#C8C8D2;max-width:1160px;padding-left:24px}ol.lead li{margin:0 0 14px}
.status{border:1px solid #2A2A36;border-left:4px solid #8A8A9E;padding:12px 16px;margin:18px 0;max-width:1100px;color:#C8C8D2}
.ask{border:1px solid #24242E;background:#0B0B12;padding:10px 14px;margin:10px 0 16px;max-width:1100px;color:#C8C8D2;font-style:italic}
.three{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px;max-width:1100px;margin:10px 0 16px}.three div{background:#0B0B12;border:1px solid #24242E;padding:10px 12px}.three b{display:block;font:12px ui-monospace,Menlo,monospace;color:#9C9CAE;letter-spacing:.08em}.three span{font-size:24px;color:#C8C8D2}.three i{font-style:normal;font-size:13px;color:#9C9CAE;display:block}
figure{margin:18px 0}figure img{width:100%;max-width:1400px;height:auto;display:block;border:1px solid #1E1E28}figcaption{font:12px ui-monospace,Menlo,monospace;color:#8A8A9E}figcaption a{color:#9C9CAE}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(560px,1fr));gap:10px}.grid figure{margin:6px 0}
.scroll{overflow-x:auto;max-width:100%}
table{border-collapse:collapse;font-size:14px;margin:10px 0;font-variant-numeric:tabular-nums}th,td{border:1px solid #24242E;padding:6px 9px;text-align:left;vertical-align:top}th{color:#A8A8BA;font-weight:600;font-size:13px;font-family:ui-monospace,Menlo,monospace}
th.sec{background:#101018;color:#C8C8D2;font-family:inherit;font-size:14px}td.up{color:#00FFA3}td.dn{color:#FF2D55}
b.w{font:600 12px ui-monospace,Menlo,monospace;letter-spacing:.08em;text-transform:uppercase;padding:2px 6px;border:1px solid #2A2A36;border-radius:3px;color:#C8C8D2}b.w.luckproof{color:#00FFA3;border-color:#00FFA3}b.w.leaning{color:#C8C8D2}b.w.alist,b.w.notshown{color:#8A8A9E}
details{margin:10px 0}summary{cursor:pointer;color:#A8A8BA}
@media (max-width:700px){body{padding:16px 16px 60px;font-size:16px}h1{font-size:26px}h2{font-size:22px}.grid{grid-template-columns:1fr}.three{grid-template-columns:1fr 1fr}}
</style></head><body>
<h1>Statistician 2: Alan's second round of statistics questions, measured</h1>
<p class="q">L5 · 28 Sep 2026 · daily bars to the ${J.asOf} close, from the local caches of the chart API and the Fly-pulled FMP histories · pivots of ${J.pivotLen} bars · ${J.reps} bootstrap draws per range · research questions, not buy rules · every chart is a saved file in <code>charts/</code>, the numbers in <a href="data/statistician-2.json">data/statistician-2.json</a></p>
<div class="status"><b>STATUS · all eight questions answered on the day's data; seven of them measured, the eighth a proposal built from the seven.</b> Each measured answer comes as the standard asks: how many (independent episodes), how sure (a 90% range from resampling episodes or blocks of days), how big (the shift against any day), and a status word after the false-discovery check over everything tried in that section. Nothing was deployed; no key, database or price table was touched; the Hub's own pages were not edited.</div>

<h2>What we found, in plain words</h2>
<ol class="lead">
<li><b>RSI 28 is not one thing.</b> SPY sits at or below 28 on ${pc(spy.d28)} of its days; Bitcoin ${pc(btc.d28)}, commodities ${pc(at("Commodities", 28).days?.med)}, bonds ${pc(at("Bonds", 28).days?.med)}, sector funds ${pc(at("Sector funds", 28).days?.med)}, single mega caps ${pc(at("Mega caps (≥ $500bn today)", 28).days?.med)}. The RSI that marks the bottom 1% of a type's own history runs from about ${n1(g1("Index funds").ladder["1"]?.med)} for index funds to ${n1(g1("Crypto").ladder["1"]?.med)} for Bitcoin and ${n1(g1("Commodities").ladder["1"]?.med)} for commodities. Read every RSI against its own type's ladder (section 1).</li>
<li><b>Besides depth, ${luck2.length} conditions at the low changed the wait for a new high, and they survive the luck check</b> (SPY + QQQ + IWM pooled, ${P.n} lows): ${luck2.map((r) => `${r.text.split(" (")[0].split(",")[0].toLowerCase()} (${sg(r.rho)})`).join("; ")}. The sign matters: with depth held fixed, ${luck2.filter((r) => r.rho < 0).map((r) => r.text.split(",")[0].split(" (")[0].toLowerCase()).join(", ")} meant a FASTER new high; ${luck2.filter((r) => r.rho > 0).map((r) => r.text.split(",")[0].split(" (")[0].toLowerCase()).join(", ")} meant a slower one. ${P.rows.filter((r) => r.status === "not shown").map((r) => r.k).join(", ")} did not change the wait once depth was taken out (section 2).</li>
<li><b>Put/call peaked before or on ${Q3.byDepth.SPY.shallow.before} of ${Q3.byDepth.SPY.shallow.withTurn} not-so-deep SPY lows (${pc(Q3.byDepth.SPY.shallow.share)}), against ${Q3.byDepth.SPY.deep.before} of ${Q3.byDepth.SPY.deep.withTurn} deep ones (${pc(Q3.byDepth.SPY.deep.share)}).</b> The best time frame is the <b>5-session average</b>: its peaks had a confirmed SPY low nearby ${pc(f5.hit)} of the time (any day ${pc(f5.base)}), and when the peak sat in the top 10% of its own history, ${pc(f5.byPct.find((b) => b.th === 90).hit)} (${f5.byPct.find((b) => b.th === 90).n} peaks). Levels: a 5-day average of about ${n2(f5.byPct.find((b) => b.th === 90).level)} is the 90th percentile, ${n2(f5.byPct.find((b) => b.th === 95).level)} the 95th; today's daily print is ${n2(T.pcc.pcc)} (${n0(T.pcc.pct)}th percentile: no fear) (section 3).</li>
<li><b>The 200-day, richer:</b> of eight states, the one that hurts is <i>below a falling 200-day with the 50 under it</i>: ${pc(worst4.f63.up)} of the next 63 sessions up (any day ${pc(Q4.base.f63.up)}) and a median worst fall of ${n1(worst4.dd126.med)}% over 126 sessions, one in ten worse than ${n1(worst4.dd126.p10)}%. Time already spent below matters in a hump: 64–126 sessions below is the weak zone (${pc(tb64.f63.up)} up). A first break of the 200-day was milder than a repeated one. ${Q4.survivors} of ${Q4.tests} cells survive the false-discovery check (section 4).</li>
<li><b>Leaders across fear and greed:</b> at SPY's swing lows the leaders bottomed the same session ${pc(L5.same)} of the time, before ${pc(L5.before)}, after ${pc(L5.after)}: no lead to trade. They fell about as much as SPY in the same decline (ratio ${n2(L5.ratio.est)}, range ${n2(L5.ratio.lo)} to ${n2(L5.ratio.hi)}) and gave back a median ${n0(H5.giveBack.est)}% of their prior 63-session run. Over the 63 sessions after a SPY low they trailed SPY by ${n1(Math.abs(L5.rel63.est))} points (luck-proof). On the fear gauge, the leaders' edge over SPY was small and ran the wrong way: ${sg(fearTop.rel?.est)} in the fear decile, ${sg(greedBot.rel?.est)} in the greed decile (section 5).</li>
<li><b>Yields up and dollar up:</b> the measure is both above their own 200-day (the regime study's rule; a 63-session change gives the same picture). It is the weakest quadrant for the S&P since 1971, for SPY and for the leaders, on every reading: a 5%+ fall inside the next 63 sessions in ${pc(g6.regimes["yield up · dollar up"].s5)} of windows for the S&P (any day ${pc(g6.base.s5)}), ${pc(s6.regimes["yield up · dollar up"].s5)} for SPY, ${pc(l6.regimes["yield up · dollar up"].s5)} for the leaders (any day ${pc(l6.base.s5)}). But ${Q6.survivors} of ${Q6.tests} regime numbers survive the false-discovery check: the ranges overlap. Today is ${T.q6.regimeLevel} (section 6).</li>
<li><b>The seven pairs at or near their weakest ever:</b> ${Q7.seven.map((p) => `${p.label} (${n1(p.levelPctAll)}th)`).join(", ")}. The divergence is the mega caps: over one year SPY ${sg(Q7.sectors1y.spy)}%, RSP ${sg(Q7.sectors1y.rsp)}%, the middle served stock ${sg(Q7.sectors1y.stockMed)}%. After past RSP÷SPY extremes (${S7.summ.spy63.n} entries, a list), SPY's next year was ${sg(S7.summ.spy252.med)}% and equal weight did not catch up (${sg(S7.summ.catchUp252.med)} points) (section 7).</li>
<li><b>One method:</b> a market-state readout of six blocks (tide, fear, trend, rates & dollar, credit, leaders), each shown as its own-history percentile and a state word, never summed into a score; and which measures earned a card (section 8).</li>
</ol>

<h2>1 · RSI floors and ceilings by type of security</h2>
<div class="ask">"Some securities hit RSI 28 far more often than the S&P (where it's the 1%). Differences in RSIs between types of securities — all of this matters."</div>
<p><b>What we measured.</b> Wilder's RSI(14) on daily closes for ${Object.values(Q1.members).flat().length} securities, grouped by type. For every RSI level from 10 to 50 (floors) and 55 to 95 (ceilings): the share of all days at or below (above) it, how many separate visits a year, and how long a visit lasts. Plus the percentile ladder of each security's own RSI (1st, 2nd, 5th … 99th). A type's number is its middle member; the spread across members is shown beside it, because that spread is itself the finding. Stocks are typed by today's market cap (FMP, 23 Sep), which is a survivor's view; funds, commodities, bonds and Bitcoin by what they are. One shared window (from 2013) checks that the differences are not just different years.</p>
<div class="three"><div><b>HOW MANY</b><span>${Object.values(Q1.members).flat().length}</span><i>securities in ${TYPES.length} types</i></div><div><b>SPY AT OR BELOW 28</b><span>${pc(spy.d28)}</span><i>of its days since ${spy.from.slice(0, 4)} · ${n2(spy.y28)} visits a year</i></div><div><b>BITCOIN</b><span>${pc(btc.d28)}</span><i>${n2(btc.y28)} visits a year · its 1% line is RSI ${n1(btc.p1)}</i></div><div><b>STATUS</b><span>${word("luck-proof")}</span><i>a description of full histories, not a test</i></div></div>
${fig1a}<div class="grid">${fig1b}${fig1c}</div>${fig1d}
<h3>The table</h3>${t1}${t1m}
<p><b>How to read it.</b> "RSI at its 1st pct" is the level below which a type spends 1% of its days: that is the level at which it is as unusual as SPY at 28. Bitcoin and the commodities go five points deeper than the index funds before they are equally rare; the S&P since 1928 goes deeper still because 1929–1932 and 1987 are in it. Single stocks of every size sit at or below 28 about twice as often as the index funds, and the spread across single stocks is wide (small caps ${rng(at("Small caps (< $10bn)", 28).days?.lo, at("Small caps (< $10bn)", 28).days?.hi)}% of days), so a stock's RSI should be read against its own ladder, which the RSI ladder study already builds per security.</p>

<h2>2 · Which conditions at the low gave a faster new high, besides being shallow?</h2>
<div class="ask">"All pullbacks eventually made a new high. Which CONDITIONS gave a faster reach of the new high — besides being shallow?"</div>
<p><b>What we measured.</b> Every swing low of SPY (${Q2.per.SPY.n}), QQQ (${Q2.per.QQQ.n}) and IWM (${Q2.per.IWM.n}) since 2003 by the S9 pivot rule, with the conditions on the day of the low taken from the bottoms study, plus the rate regime and the length of the fall. The outcome is the wait, in sessions, until the high exceeds the swing high that started the fall; a low still waiting is censored, not dropped (${P.censored} of ${P.n}). Depth is the strongest driver of the wait (rank correlation ${n2(P.depthLink?.est)}, range ${rng(P.depthLink?.lo, P.depthLink?.hi)}), so each condition is tested with depth held fixed: a rank partial correlation, its 90% range from resampling lows (the independent unit), and a Benjamini–Hochberg false-discovery check over the ${P.tests} conditions tried. Negative = more of the condition meant a faster new high. Survival curves show the same within one depth band.</p>
<div class="three"><div><b>HOW MANY</b><span>${P.n}</span><i>swing lows, three index funds</i></div><div><b>LUCK-PROOF</b><span>${luck2.length}</span><i>${luck2.map((r) => r.k).join(", ")}</i></div><div><b>LEANING</b><span>${lean2.length}</span><i>${lean2.map((r) => r.k).join(", ") || "none"}</i></div><div><b>NOT SHOWN</b><span>${P.rows.length - luck2.length - lean2.length}</span><i>put/call, VIX3M, credit, cloud line, rates…</i></div></div>
${fig2a}${fig2b}
<h3>Pooled: SPY + QQQ + IWM</h3>${t2(P)}
<p><b>How to read it.</b> "Top third" and "bottom third" are the raw medians, and they are dominated by depth (the deeper lows have the higher VIX, the lower breadth, the lower RSI). The partial correlation is the honest column: with depth held, a higher VIX percentile at the low went with a shorter wait (${sg(P.rows.find((r) => r.k === "vixPct").rho)}), more names above their 50-day with a shorter wait (${sg(P.rows.find((r) => r.k === "a50").rho)}), a less oversold RSI at the low with a shorter wait (${sg(P.rows.find((r) => r.k === "rsiPct").rho)}), and heavier volume with a longer one (${sg(P.rows.find((r) => r.k === "volPct").rho)}). These are small links: a rank correlation of 0.2 moves the median wait by days, not months. The length of the fall (${sg(P.rows.find((r) => r.k === "fallBars").rho)}) and a dollar above its 200-day (${sg(P.rows.find((r) => r.k === "dollarUp").rho)}) went with a longer wait. ${P.rows.filter((r) => r.status === "not shown").map((r) => r.text.split(" (")[0].split(":")[0].toLowerCase()).join("; ")} did not change the wait once depth was out.</p>
<h3>The same within one depth band: falls of 3–10%</h3><p>${Q2.km.n} lows. Each pair holds depth roughly fixed (the median depth of each side is in the subtitle) and asks whether the condition changed the survival curve of the wait.</p>
<div class="grid">${fig2c}</div>
<details><summary>Per instrument: SPY, QQQ, IWM</summary><h3>SPY</h3>${t2(Q2.per.SPY)}<h3>QQQ</h3>${t2(Q2.per.QQQ)}<h3>IWM</h3>${t2(Q2.per.IWM)}</details>

<h2>3 · Put/call before the not-so-deep lows: time frame and levels</h2>
<div class="ask">"Put/call peaked before 21 of 28 deep lows — what about the not-so-deep lows? On what time frame is it predictive, and what levels are we looking for?"</div>
<p><b>What we measured.</b> (a) For every SPY, QQQ and IWM swing low with put/call data (Cboe total PCC and equity-only PCCE, from Nov 2006): did the ratio's own swing high (same 10-bar pivot rule) come before or on the low? By four equal-count depth bands, and for not-so-deep (under 10%) against deep. (b) Time frame: peaks of the daily print and of its 3, 5, 10 and 21-session averages; a hit = a confirmed SPY swing low within 5 sessions before to 15 after the peak; against the base rate of any day having a low in that window. (c) Levels: the hit rate by the peak's own-history percentile, and for raw PCC levels 0.8 to 1.4.</p>
<div class="three"><div><b>NOT-SO-DEEP SPY LOWS</b><span>${Q3.byDepth.SPY.shallow.before} of ${Q3.byDepth.SPY.shallow.withTurn}</span><i>put/call peaked before or on the low · ${rng(Q3.byDepth.SPY.shallow.lo, Q3.byDepth.SPY.shallow.hi)}%</i></div><div><b>DEEP</b><span>${Q3.byDepth.SPY.deep.before} of ${Q3.byDepth.SPY.deep.withTurn}</span><i>${rng(Q3.byDepth.SPY.deep.lo, Q3.byDepth.SPY.deep.hi)}%</i></div><div><b>BEST TIME FRAME</b><span>5-day</span><i>${pc(f5.hit)} of peaks had a low nearby vs ${pc(f5.base)} any day · ${word(f5.p <= 0.01 ? "luck-proof" : "leaning")}</i></div><div><b>LEVEL</b><span>≈ ${n2(f5.byPct.find((b) => b.th === 90).level)}</span><i>5-day average at its 90th percentile: ${pc(f5.byPct.find((b) => b.th === 90).hit)} hit (${f5.byPct.find((b) => b.th === 90).n} peaks)</i></div></div>
${fig3a}<div class="scroll"><table><tr><th>lows by depth</th><th>total put/call (PCC) peaked before / on the low</th><th>equity put/call (PCCE)</th><th>level at the low (median)</th></tr>${t3a}</table></div>
<div class="grid">${fig3b}${fig3c}</div>
<h3>Time frames</h3>${t3b}
<h3>Levels of the daily print</h3><p>The put/call ratio's own percentiles (daily print, ${Q3.levels.from} →): median ${Q3.levels.pctTable.map((p) => `${p.p}th = ${n2(p.level)}`).join(" · ")}. Today ${T.pcc.d}: ${n2(T.pcc.pcc)}, the ${n0(T.pcc.pct)}th percentile.</p>${t3c}
<p><b>About "21 of 28".</b> The bottoms page counted the put/call peak strictly BEFORE the low (21 of the 28 deep SPY lows; 3 more peaked on the same session, 2 after, 1 had no turn of its own and 1 had no put/call data yet). This page counts before-or-on-the-low, among lows with data: 24 of 26. Same lows, one wider count.</p>
<p><b>How to read it.</b> The put/call peak is not a deep-low-only signal: it came before or on about three quarters of the not-so-deep SPY lows too, with a median lead of ${Q3.byDepth.SPY.shallow.lead ?? "—"} sessions. But it also peaks about ${n0(f5.perYear)} times a year on the 5-day average, and ${pc(100 - f5.hit)} of those peaks had no confirmed low near them. The level does the work: the higher the peak in its own history, the higher the hit rate, and a 5-day average above its 90th percentile (about ${n2(f5.byPct.find((b) => b.th === 90).level)}) is where the hit rate leaves the base rate behind. The daily print is noisier; the 21-day average is too slow and misses half the lows.</p>

<h2>4 · The 200-day, richer</h2>
<div class="ask">"The 200-day analysis feels simplistic."</div>
<p><b>What we measured.</b> ${Q4.syms.length} instruments pooled (${Q4.syms.map((s) => s.sym).join(", ")}; the S&P index from 1928, the Nasdaq 100 from 1985, the Russell 2000 from 1987), every day from 1928 to 2026 with a 200-day average: ${Q4.base.f63.n} days, ${Q4.base.f63.instYears} instrument-years. Each day is placed in one of eight states: side of the 200-day × slope of the 200-day over 20 sessions × 50-day above or below the 200-day. Then, for days below: sessions spent below so far, depth × duration as a grid, and whether the break was the first (after 63+ sessions above) or a repeat. Outcomes: the next 63 and 126 sessions' return and the deepest close in the next 126. Every range is a stationary block bootstrap with blocks at least as long as the horizon; the ${Q4.tests} cells are checked together for false discoveries.</p>
<div class="three"><div><b>HOW MANY</b><span>${Q4.base.f63.instYears}</span><i>instrument-years · ${Q4.syms.length} instruments</i></div><div><b>THE STATE THAT HURTS</b><span>${pc(worst4.f63.up)}</span><i>next-63 up when below a falling 200-day with 50 &lt; 200 (any day ${pc(Q4.base.f63.up)}) · ${word(worst4.f63.pUpSurvives ? "luck-proof" : "leaning")}</i></div><div><b>WORST FALL THERE</b><span>${n1(worst4.dd126.med)}%</span><i>median deepest close in 126 sessions · one in ten worse than ${n1(worst4.dd126.p10)}%</i></div><div><b>SURVIVES FDR</b><span>${Q4.survivors} of ${Q4.tests}</span><i>cells whose range clears any day after the luck check</i></div></div>
${fig4a}<h3>Eight states</h3>${t4a}
<div class="grid">${fig4b}${fig4c}</div>
<h3>Time already spent below</h3>${t4b}
<h3>Depth × duration (days below only)</h3><p>Any day: a further 10%+ fall within 126 sessions on ${pc(Q4.baseDD10)} of days. Green = at least 5 points better than that, red = at least 5 points worse.</p>${t4c}
<h3>First break vs repeated break</h3>${t4d}
<p><b>How to read it.</b> Being below the 200-day is not one state. Below a still-rising 200-day the next 63 sessions were better than any day (the fall was recent and the trend intact); below a falling 200-day with the 50 also under it, which is one day in five across this history, the share of up 63-session stretches drops to ${pc(worst4.f63.up)} and the tail opens up (one in ten of those days saw a further ${n1(worst4.dd126.p10)}% fall inside 126 sessions). Time below is a hump: the first few weeks below are ordinary, 64–126 sessions below is the weak zone, and after a year below the outcomes improve again but the samples are small (a few bear markets). The depth × duration grid says the same in one glance: deep AND long is where a further 10% fall becomes more likely than not. A first break was milder than a repeat. Today ${T.q4.SPY.d}: SPY ${T.q4.SPY.side}, 200-day ${T.q4.SPY.slopeUp ? "rising" : "falling"}, 50 ${T.q4.SPY.order ? "above" : "below"} 200, ${n1(T.q4.SPY.dep)}% above.</p>

<h2>5 · The market's fear and greed cycles, applied to the leaders</h2>
<div class="ask">"Timing the fear and greed cycles of the broad market, applied to leaders" — entries and exits.</div>
<p><b>What we measured.</b> The leaders are each calendar year's 20 largest US companies by market cap on that year's first trading day (FMP caps, 2007→; ${Q5.leaders.loaded} names with price history), so a name counts only in the years it was a leader. (a) Lows: for every SPY swing low that ended a fall of 3% or more since 2007 (${L5.episodes} lows), each leader's own swing low nearest the SPY low (±15 sessions): before, same, after; its own fall over the same stretch against SPY's; and its return against SPY over the 63 sessions after the SPY low. (b) Tops: at the SPY swing high that began each fall, the leader's own high offset and how much of its prior 63-session run it gave back. (c) The fear gauge: the average of four own-history percentiles (VIX, put/call, SPY RSI flipped, share of names above their 50-day flipped), 100 = maximum fear, read daily from ${G5.from}; by decile of the gauge, the leaders basket's next-63 return, SPY's, the difference, and each one's worst fall in those 63 sessions. Ranges: lows resampled as episodes; gauge deciles by 63-session blocks; ${G5.tests} decile cells checked together.</p>
<div class="three"><div><b>HOW MANY</b><span>${L5.episodes}</span><i>SPY lows · ${L5.n} leader-lows</i></div><div><b>LEADERS BOTTOM</b><span>${pc(L5.same)}</span><i>same session · before ${pc(L5.before)} · after ${pc(L5.after)}</i></div><div><b>THEY FALL</b><span>${n2(L5.ratio.est)}×</span><i>SPY's fall, ${n2(L5.ratio.lo)} to ${n2(L5.ratio.hi)} · ${word("luck-proof")}</i></div><div><b>AFTER THE LOW</b><span>${sg(L5.rel63.est)}</span><i>points vs SPY over 63 sessions · ${rng(L5.rel63.lo, L5.rel63.hi)} · ${word("luck-proof")}</i></div></div>
${fig5a}<div class="grid">${fig5c}${fig5b}</div>
<h3>At the lows, by depth</h3>${t5a}
<h3>At the tops</h3><p>${H5.episodes} SPY tops, ${H5.n} leader-tops. The leader's own high came before the SPY high ${pc(H5.before)} of the time, the same session ${pc(H5.same)}, after ${pc(H5.after)}. Over the SPY fall that followed, the leaders gave back a median <b>${n0(H5.giveBack.est)}%</b> of their prior 63-session run (${rng(H5.giveBack.lo, H5.giveBack.hi)}; middle half ${n0(H5.giveBackDist.p25)}–${n0(H5.giveBackDist.p75)}%; one in four gave back more than the whole run). Their own fall from top to low: median ${n1(H5.fallDist.p50)}%, one in ten more than ${n1(H5.fallDist.p90)}%, against SPY's median fall of ${n1(H5.spyDepth.p50)}%.</p>
<h3>The fear gauge, by decile</h3><p>Today ${T.g.d}: gauge ${n1(T.g.g)} (VIX ${n0(T.g.vix)}th, put/call ${n0(T.g.pcc)}th, RSI-fear ${n0(T.g.rsi)}th, breadth-fear ${n0(T.g.breadth)}th): fear in breadth, none in options. ${G5.survivors} of ${G5.tests} cells survive the false-discovery check.</p>${t5b}
<p><b>How to read it.</b> There is no timing edge in the leaders around the index's lows: they bottom with it, not before it, and their fall is the index's fall (ratio near 1 at every depth). After the low the leaders trailed SPY slightly for a quarter (${n1(Math.abs(L5.rel63.est))} points at 63 sessions), a small but luck-proof effect, which fits the leaders study's finding that the first bounce is broad. On the gauge the leaders' edge over SPY is within a point either way across the deciles, and where it clears the range it runs against the story (they did best when the market was greedy, not fearful); the fear end is where SPY itself did best, which is the ordinary rebound. What the gauge does say clearly is about risk: the leaders' worst fall in the next 63 sessions is deepest in the fear decile (${n1(fearTop.ddb?.est)}%) and shallowest in the middle, which is the volatility of a falling market, not a leader effect.</p>

<h2>6 · Yields up and dollar up: the measures and the pullback distribution</h2>
<div class="ask">"Yields up and dollar up was the weakest combination over three months — tracked across what time frame, what measure? What kind of pullback at a broad-market level and at a leadership level?"</div>
<p><b>What we measured.</b> The regime study's rule: the 10-year yield above its own 200-day average and the dollar index (DXY) above its own 200-day average, read on each day; and as a check, the 63-session change of each. "Three months" = the next 63 sessions. Two pullback measures on every day: the deepest close below that day's close within the next 63 sessions (a fixed window; every day counts), and the depth of the swing declines that began in each regime (pivot-based, one number per decline). Three instruments: the S&P 500 index from 1971 (when DXY starts), SPY from 2003, and the leaders basket (each year's top 20 at the time, equal weight) from 2007. Ranges by stationary block bootstrap with 63-session blocks; ${Q6.tests} regime cells checked together for false discoveries.</p>
<div class="three"><div><b>TODAY</b><span>${T.q6.regimeLevel}</span><i>10-year ${n2(T.q6.y10)} vs its 200-day ${n2(T.q6.y200)} · DXY ${n2(T.q6.dxy)} vs ${n2(T.q6.d200)}</i></div><div><b>S&P, 5%+ FALL IN 63</b><span>${pc(g6.regimes["yield up · dollar up"].s5)}</span><i>of windows · any day ${pc(g6.base.s5)} · ${g6.regimes["yield up · dollar up"].quarters} quarters</i></div><div><b>LEADERS</b><span>${pc(l6.regimes["yield up · dollar up"].s5)}</span><i>any day ${pc(l6.base.s5)} · median fall ${n1(l6.regimes["yield up · dollar up"].med)}% vs ${n1(l6.base.med)}%</i></div><div><b>SURVIVES FDR</b><span>${Q6.survivors} of ${Q6.tests}</span><i>${word(Q6.survivors ? "luck-proof" : "leaning")} · the weakest quadrant every time, but the ranges overlap</i></div></div>
<div class="grid">${fig6}${fig6b}</div>
<h3>S&P 500 since 1971 · levels vs the 200-day</h3>${t6("GSPC", "level")}
<h3>SPY since 2003</h3>${t6("SPY", "level")}
<h3>Leaders basket since 2007</h3>${t6("LEADERS", "level")}
<details><summary>The check: 63-session change instead of levels</summary>${t6("GSPC", "change")}${t6("SPY", "change")}${t6("LEADERS", "change")}</details>
<p><b>How to read it.</b> The regime is real as a description: in every instrument and on both definitions, yields up with the dollar up had the deepest median fall inside the next quarter and the highest share of 5%+ and 10%+ falls, and the leaders felt it more than the index (${pc(l6.regimes["yield up · dollar up"].s10)} of leader windows held a 10%+ fall against ${pc(l6.base.s10)} any day). As a fact it is not yet luck-proof: the regime lasts for months at a time, so ${g6.regimes["yield up · dollar up"].quarters} quarters are worth far fewer independent observations, and the 90% ranges of the four quadrants overlap. Read it as a reason to be careful, not as a prediction.</p>

<h2>7 · Equal weight vs cap weight: the seven pairs, where the divergence is, and what followed past extremes</h2>
<div class="ask">"Equal weight vs cap weight at or near its weakest ever on seven pairs — which ones, and where is the divergence going on?"</div>
<p><b>What we measured.</b> The regime study's 17 pairs (equal-weight fund ÷ cap-weight fund; sector pairs use the Invesco equal-weight sector funds under their old tickers before 2023). The seven are the pairs whose ratio today sits in the bottom 5% of its own history. For the S&P pair, RSP ÷ SPY from the bars: its own-history percentile (prior days only), every entry into the bottom 5% after 63 sessions away, and what SPY, RSP minus SPY and the leaders basket did over the next 63, 126 and 252 sessions; plus the whole curve (SPY's next 63 at every 5-point band of the ratio's percentile). "Where" is answered two ways: the one-year change of every pair, and one year of SPY against RSP, the leaders basket and the middle served stock.</p>
<div class="three"><div><b>THE SEVEN</b><span>${Q7.seven.length}</span><i>pairs at or under their 5th percentile</i></div><div><b>RSP ÷ SPY TODAY</b><span>${n1(S7.today.pct)}th</span><i>percentile of its history since ${S7.from.slice(0, 4)}</i></div><div><b>PAST EXTREMES</b><span>${S7.summ.spy63.n}</span><i>entries · SPY next 252 ${sg(S7.summ.spy252.med)}% (n ${S7.summ.spy252.n}) · ${word("a list")}</i></div><div><b>ONE YEAR</b><span>${sg(Q7.sectors1y.spy)}%</span><i>SPY · RSP ${sg(Q7.sectors1y.rsp)}% · middle stock ${sg(Q7.sectors1y.stockMed)}%</i></div></div>
<h3>The seven pairs</h3>${t7a}
${fig7a}<h3>Where the divergence is</h3>${t7c}<p>The three broad pairs and the two Nasdaq pairs are the same fact seen five times: the largest companies carried the last year. Among the sector pairs, the extremes are communication services (where the two largest names are the sector), consumer discretionary (Amazon and Tesla) and consumer staples (Walmart and Costco); technology's equal-weight fund is only at its 13th percentile, because the chip names beneath the giants also ran.</p>
<h3>What followed past extremes of RSP ÷ SPY</h3>${fig7b}${t7b}
<p><b>How to read it.</b> ${S7.summ.spy63.n} entries since ${S7.from.slice(0, 4)}, ${S7.summ.spy252.n} with a full year after them: a list, not a rate, and eight of them come from the last two years, so they share one market. In that list SPY's next year was ${sg(S7.summ.spy252.med)}% (any day ${sg(S7.spyBase[252].med)}%), the leaders basket ${sg(S7.summ.lead252.med)}%, and equal weight did not catch up (${sg(S7.summ.catchUp252.med)} points, up in ${pc(S7.summ.catchUp252.up)} of cases). The 2008–2009 entries are the exception, when equal weight then beat cap weight by 19 and 34 points in a year. The curve over every percentile shows no band where SPY's next quarter differs from any day by more than its noise. The regime study's per-pair "lows" tell the same story for the sector pairs: after past extremes the cap-weight side went on rising, and the ratio's recovery, when it came, took a year. An extreme of this ratio is a description of leadership, not a turn signal.</p>

<h2>8 · One consolidated method: a market-state readout, and what earns a place on the statistics tab</h2>
<div class="ask">"All of this needs to feed ONE consolidated method, like the new comps method — consider everything on the Hub and the reports inventory."</div>
<p><b>The proposal.</b> The comps method works because every peer is read on the same scale (its own percentile against the field) and the chart labels the marks, not a side column. The market state should be built the same way: <b>six blocks, each one number on its own-history percentile scale, each with a state word, laid out as one row, never summed into a score.</b> A score hides which block moved and invites a buy signal; a row of percentiles shows the shape of the day (today: breadth fear with no options fear, above a rising 200-day, yields up with the dollar up). The blocks and what today's studies say about each:</p>
${t8}
<p><b>Entry rules for a card</b> (the statistics tab's rules, plus the standard): the horizon is a pivot or a swing, the condition is read over its full distribution, the number carries its three companions (how many, how sure, how big) and its status word after a false-discovery check over everything tried in its study, and a named review that is not part of how the finding was chosen. Under those rules, from this page: the RSI-by-type ladder (a description of full histories), the three luck-proof conditions of section 2, the 5-day put/call peak level of section 3, the eight-state 200-day table of section 4, and the leaders' fall-ratio and lag of section 5 earn cards. The yields-and-dollar quadrant, the fear-gauge deciles and the equal-vs-cap extremes are readings for the strip, not cards: their status is leaning or a list.</p>
<p><b>What the readout is for.</b> Alan's rule from the notes ("after taking profits, move to another good name with lower risk") needs to know the state, not a forecast: section 5 says the leaders fall with the index and give back most of a run at a top, so the readout's TREND and FEAR blocks tell him when the give-back risk is high; section 4 says where being below the 200-day stops being ordinary; section 2 says that at a low, breadth and a spiking VIX are the companions of a quick recovery, and the put/call peak is a companion of the low itself (section 3), not of the wait after it.</p>
<p><b>The reports inventory.</b> Everything on the Hub that measures the market (the regime page's six questions, the bottoms page, the RSI ladder, the leaders page, the sector rotation page, the market map's Geiger) can publish its one number into the same six blocks; the strip proposal on the regime page already draws seven gauges in this shape and needs only the state words and the percentile scale to become this readout. A one-line "today" from each block, with a link to the study that measured it, is the whole tab. Build size after the regime strip: half a day.</p>

<h2>Where each number comes from</h2>
<ul>
<li>Prices: finished daily bars from the chart API (<code>https://scintilla-massive-chart-api.fly.dev/candles?tf=D</code>), read from the copies earlier lanes saved under <code>~/Library/Application Support/scintilla/stats-cache</code> on 27–28 Sep; the S&P 500, Nasdaq 100, Russell 2000, Dow and Nasdaq Composite index histories and the VIX3M, equal-weight sector and dividend-adjusted HYG histories from FMP, pulled inside Fly by the RSI and regime lanes (no key on this Mac). ${Object.keys(J.sources).length} series; the longest cached copy of each was used; weekends dropped, bad wicks clamped, a hole longer than a year starts the series again, and for single stocks a close more than 2× or under ½× the day before, or a hole of more than 20 days, cuts the history at that fault (${Object.values(J.sources).filter((s) => s.faultCut).length} histories cut).</li>
<li>Conditions at the swing lows (VIX, VIX3M, put/call, credit, RSI, breadth, cloud line): the bottoms study's data file <code>deliverables/20260928/bottoms/data/bottoms.json</code>. The 17 equal-vs-cap pairs: <code>research/statistics/data/regime-20260928.json</code>. Market caps by year (the leaders): FMP historical market caps in the leaders lane cache; today's caps for typing the stocks: <code>data/standard-tree-20260924.json</code> (FMP, 23 Sep).</li>
<li>Code: <code>research/statistics/statistician-2/</code> (lib.mjs = the arithmetic, run.mjs = the run, page.mjs = this page and its charts, svg.mjs = the bottoms study's chart helpers with a wider label margin); tests in <code>tests/statistician-2.test.mjs</code>. Pivots, swings and bad-wick clamps are S9's; RSI, moving averages, own percentiles and the bootstrap helpers are the ones the earlier studies and the method standard use.</li>
</ul>
<details><summary>Series used (first and last bar)</summary><div class="scroll"><table><tr><th>series</th><th>source</th><th>from</th><th>to</th><th>bars</th><th>cut at a fault</th></tr>${Object.entries(J.sources).map(([k, s]) => `<tr><td>${k}</td><td>${s.src}</td><td>${s.from}</td><td>${s.to}</td><td>${s.bars}</td><td>${s.faultCut || ""}</td></tr>`).join("")}</table></div></details>

<h2>What could be wrong</h2>
<ul>
<li><b>Survivorship in the stock types (section 1).</b> The ${Object.values(Q1.members).flat().length - Object.values(J.q1.groups).filter((g, i) => Q1.order[i].includes("caps")).length} single stocks are the Hub's names today, typed by today's market cap; a mega cap measured over 2003–2026 was smaller for most of it, and names that failed are absent. The funds, indexes, commodities, bonds and Bitcoin do not have this problem. The shared window from 2013 removes the different-years problem but not this one.</li>
<li><b>Breadth is back-filled from today's names (sections 2 and 5)</b>: ${G5.breadthNames} served names for the fear gauge; the bottoms study's 486 for the conditions at the low. Past breadth reads a little healthier than it was.</li>
<li><b>Swings are known 10 bars late.</b> Every low and every put/call peak here is a confirmed pivot; the base rates measure what was true, not what was visible on the day. The put/call hit window (5 before to 15 after) is a choice; the table shows the base rate for the same window so the comparison is fair, but a different window gives different absolute rates.</li>
<li><b>The pooled 200-day table treats instruments that move together as separate</b> (SPY, DIA, the S&P index, the sectors). The block bootstrap resamples runs within the pooled table, so the ranges are somewhat too narrow; the instrument-years column is the honest size, and the per-state shares of days are dominated by the long index histories.</li>
<li><b>Regimes last for months (section 6)</b>: the 63-session blocks widen the ranges but the four quadrants still share a few long macro eras (1971–1982, 2022–2026), which is why none of them clears the luck check. The leaders basket only starts in 2007 and its quarters are fewer still.</li>
<li><b>The leaders are top-20 from ${Object.keys(Q5.leaders.years)[0]}</b>, chosen from ${Q5.leaders.of} large names another lane pulled; a name that was top-20 in a year but never on that list is missed. Before 2007 there is no leaders series here.</li>
<li><b>Equal-vs-cap entries are a list (section 7)</b>: ${S7.summ.spy63.n} entries, eight of them since 2024, sharing one market. The per-pair "lows" in the seven-pairs table come from the regime study's own rule (a swing of the ratio's 63-session stretch), not from this page's percentile rule.</li>
<li><b>The fear gauge is one of many possible gauges.</b> Four equal-weighted percentiles were fixed before looking at the outcome (no weights were tuned), but a different set of inputs would give different deciles; the deciles' own false-discovery check is over the ${G5.tests} cells of this gauge only.</li>
<li><b>Bootstrap draws:</b> ${J.reps} per range. Ranges move by a few tenths between runs with a different seed; the status words do not.</li>
</ul>

<h2>What was not done</h2>
<ul>
<li>No Hub wiring, no deploy, no database write, no change to any other page. Section 8 is a proposal; the statistics tab prototype and the regime strip are unchanged.</li>
<li>No intraday data; every reading is a daily close. Put/call is one printed number a day.</li>
<li>Section 2 measures the wait to a new high only; the wait to the next swing high (a shorter, pivot-based horizon) and the depth of the bounce were not modelled.</li>
<li>Section 5 does not test an entry or exit rule; it describes when the leaders turned against the index and what they gave back. The "move to a calmer name" comparison is on the leaders page.</li>
<li>The Python checks the method standard names (arch SPA over the 16 conditions of section 2; statsmodels quantile regression for section 6) were not run; the Node bootstrap and Benjamini–Hochberg are the tests here.</li>
<li>No screenshots of the Hub; this page's own proof shots at 1680 and 390 are next to it.</li>
</ul>
</body></html>`;
const snippet = fs.readFileSync(path.join(ROOT, "scripts/scnav-snippet.html"), "utf8").trim();
const withNav = html.replace("<h1>", "<span data-scnav-slot></span><h1>").replace("</body>", snippet + "\n</body>");
fs.writeFileSync(path.join(DIR, "STATISTICIAN-2.html"), withNav);
console.log("wrote STATISTICIAN-2.html +", saved.length, "charts,", Math.round(withNav.length / 1024), "KB");
