<p>These numbers were measured on the Station as it was this morning (bca97fa); §3–5 repeat the whole comparison on today's live Station (64124b6), which I rebased onto. Each change was made alone and measured before the next one (the numbers are in the commits and in §3–5). Price first, then clouds, then the rest — as you asked. <b>Nothing about what the chart shows changed</b>: the same bars, the same clouds, the same six RSI lines, the same Geiger reading with the same checks. Only the <i>order</i> of the requests changed, and two duplicate requests were dropped.</p>
<table><thead><tr><th>#</th><th>Change</th><th>Why</th><th>Measured effect (at the time)</th></tr></thead><tbody>
<tr><td>1</td><td><b>The chart's own Geiger chip waits</b> until its price, clouds, RSI fan and lens reads are done — at most 4 s after the price is on screen.</td><td>That Geiger read was going out at the same moment as the cloud and fan reads and froze them.</td><td>Hub MU, two before/after pairs: fan 6.2–7.1 s → 0.5–2.9 s; clouds 0.2–3.8 s → 0.07–2.6 s. Geiger chip 0–1.6 s later.</td></tr>
<tr><td>2</td><td><b>The fan's daily line reuses the clouds' daily bars</b> instead of asking for them twice more.</td><td>Both draw from the same completed daily closes; the clouds already ask for more of them (450 vs 440).</td><td>Fan reads per chart 13 → 11 (the two daily reads are gone). Same numbers drawn: trimmed to the same newest 440 bars.</td></tr>
<tr><td>3</td><td><b>The Station wall's Geiger read waits</b> until every visible chart has its price and no price or cloud read is still waiting — at most 4 s per new set of names.</td><td>The wall asked for all eight Geigers at 0.5 s, beside the eight price reads; five prices then waited for it.</td><td>TARGETS 8-up, cleaner pair: cold price median 2.7 → 0.5 s (worst 2.9 → 1.0 s), clouds 2.8 → 0.9 s, warm lens 4.2 → 2.6 s. Geiger chips 0.3–0.4 s later.</td></tr>
<tr><td>—</td><td><i>Tried and taken out (1):</i> the Hub's own Geiger-detail read (the GEIGER tab's per-timeframe rows) waiting for the whole chart.</td><td>—</td><td>It then went out at the same moment as the chart's Geiger read and hit its 5-second limit in 4 of 4 runs — the tab would have lost its rows. Reverted.</td></tr>
<tr><td>—</td><td><i>Tried and taken out (2):</i> the same read waiting only for the chart's price line (≤ 1.5 s).</td><td>In one run that read had held the price line to 3.3 s.</td><td>Two before/after pairs showed no gain (price 0.54/0.17 s before, 0.22/0.48 s after on a board-row open; first-second opens noisier after). Reverted. The Hub is unchanged.</td></tr>
</tbody></table>
<p class="d">Files: Station <code>chart/index.html</code> and its byte-identical twin <code>station-shells/chart-v1/index.html</code>, <code>deck/index.html</code>, and tests. Hub: only this page and its measuring tools.</p>
