<div class="table-wrap"><table><thead><tr><th>Suspect</th><th>Verdict</th><th>What the measurement showed</th></tr></thead><tbody>
<tr><td><b>Geiger reads on the chart API</b> (not on the list)</td><td><b>CONFIRMED — the main reason</b></td><td>While the server answers a Geiger read (2.2–5.1 s), every other request waits: /universe 0.11 s → 2.1–5.0 s; a price read 0.2 s → 2.4 s. In the browser, requests sent during a Geiger read all finish the moment it does.</td></tr>
<tr><td>The six-line RSI fan's extra reads (and their widths)</td><td>CONFIRMED — it <i>was</i> the nine seconds</td><td>13 reads per chart, 15–57 KB each (~330 KB): 3H/4H/6H/8H/12H each read twice (400 newest + 680–1,638 for history) plus the daily twice. They went out at the same moment as the chart's own Geiger read, so they waited for it: fan 7.1–9.2 s before. Now 11 reads, sent while no Geiger read is running.</td></tr>
<tr><td>The ownership check (/universe + its fingerprint) before any chart draws</td><td>CONFIRMED as a step, SMALL on its own</td><td>Every chart frame asks /universe (2 KB) before its first price read: normally 0.04–0.1 s, and the fingerprint costs no measurable main-thread time. It became 2.4 s only when it landed during a Geiger read (Hub, opening MU in the first second). Not changed — it guards which names are priced, and removing it saves ~0.1 s.</td></tr>
<tr><td>The dashboard's start-up burst of ~140 database reads</td><td>RULED OUT for the chart</td><td>Bigger than thought — 256 database reads in the first 10 s of a cold Hub load, 70–84 in the 10 s after a board-row click — but they go to the database, not the chart API, and nothing in the chart waited on them. The Hub's own <i>chart-API</i> reads at start-up are another matter: 75–150 one-per-row sparkline reads plus all quotes plus a Geiger read; a warm open in the first second waited 1.8 s behind them.</td></tr>
<tr><td>Lens reads</td><td>CONFIRMED late, now earlier</td><td>TARGETS warm: lens 3.3–5.3 s before (queued behind the wall's Geiger read); after, 2.6 s in the cleaner pair.</td></tr>
<tr><td>The Station's "two at a time" permit</td><td>RULED OUT on first open</td><td>The code admits <b>four</b> data reads at a time; "two" applies only to new chart pages during a rotation. On first open all eight charts loaded their pages at 0.41 s together. The Hub's chart skips permits entirely. Rotation was not measured.</td></tr>
<tr><td>Chart-API /health slowness (14–20 s)</td><td>CONFIRMED slow, NOT a cause</td><td>13.9 s and 17.3 s today. No page calls /health. It is a symptom of the same kind of blocking and is in the server write-up.</td></tr>
<tr><td>Cache misses on the chart API (1,021/1,200)</td><td>MINOR</td><td>Counters: 31,285 hits, 62,238 misses since the last start. A miss costs 0.2–0.45 s for most reads; one cold 3H read waited 4.4 s where 4H took 0.6 s.</td></tr>
<tr><td>Main-thread (the browser's own work)</td><td>RULED OUT</td><td>Inside the chart frames: no task over 50 ms in any run. The whole Hub: 5–9 s of work spread over 20–30 s, longest single task 149 ms.</td></tr>
</tbody></table></div>
