-- CO1 APPLY PREVIEW (6 Oct 2026) — NOT RUN. Additive. The coordinator applies only what Alan approves.
-- 1. a parents table (new, additive): one row per cohort, up to two parents, the open spine.
create table if not exists public.cohort_tree (cohort text primary key, label text not null, parent_1 text not null, parent_2 text, spine text, proposed_by text default 'CO1-20261006');
-- rollback: drop table if exists public.cohort_tree;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('AI_ACCELERATORS','AI ACCELERATORS & LOGIC','AI','SEMIS','SMH/SOXX holdings ∩ FMP ''Semiconductors'', the compute and interconnect chip makers (not memory, not equipment, not analog)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('MEMORY_STORAGE','MEMORY & STORAGE','AI','SEMIS','Roundhill Memory ETF (DRAM) holdings ∩ ours, plus FMP ''Computer Hardware'' storage names') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('SEMICAP_EDA','SEMICAP, MATERIALS & CHIP DESIGN','SEMIS','AI','SMH/SOXX equipment holdings + FMP ''Semiconductors'' equipment names + the two EDA houses (held by SMH)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('ANALOG_RF_POWER','ANALOG, RF & POWER SEMIS','SEMIS',null,'FMP ''Semiconductors'' minus the AI, memory and equipment names: the analog, RF, microcontroller and power-chip makers') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('AI_NETWORKING_OPTICAL','AI NETWORKING & OPTICAL','AI',null,'FMP ''Communication Equipment'' + ''Hardware, Equipment & Parts'' + the optical/compound-semi names (IYZ/SOXX spine): the datacenter''s fibre, switches, connectors and lasers') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('AI_SERVERS_DC_KIT','AI SERVERS & DATACENTER KIT','AI',null,'the server builders and the thermal/power kit inside the hall (FMP ''Computer Hardware'' + ''Electrical Equipment'' hand subset)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('NEOCLOUDS_MINERS','NEOCLOUDS & AI MINERS','AI','CRYPTO','the GPU-cloud builders and the bitcoin miners that turned to AI hosting (FMP ''IT Services'' + ''Capital Markets'' miners; no open fund holds them all — WGMI would, not served)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('DC_PROPERTY','DATACENTER PROPERTY','AI','REAL_ESTATE','FMP ''REIT - Specialty'' + GDS: the landlords of the halls') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('AI_SOFTWARE_DATA','AI SOFTWARE & DATA PLATFORMS','AI','SOFTWARE_INTERNET','IGV holdings ∩ ours + FMP ''Software - Application/Infrastructure'' data & AI names') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('CYBER','CYBERSECURITY','SOFTWARE_INTERNET',null,'CIBR holdings ∩ ours (pure plays only; CSCO/AVGO/MSFT stay in their own cohorts)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('AI_POWERTRAIN','AI POWERTRAIN','AI','ENERGY_POWER','Alan''s definition (Hub comment, 24 Sep): generators selling to hyperscalers, the kit, the reactors, the fuel, the fuel cells, the storage — widened by the same rule to TLN/NRG (generators) and LEU/UUUU (fuel)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('ROBOTICS_AUTOMATION','ROBOTICS & AUTOMATION','AI','INDUSTRIAL','BOTZ holdings ∩ ours, pure plays (NVDA/TSLA/GOOGL/DE stay home)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('SPACE','SPACE','FRONTIER',null,'ARKX holdings ∩ ours + FMP ''Aerospace & Defense'' satellite/launch names') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('QUANTUM','QUANTUM','FRONTIER',null,'QTUM holdings, pure-play subset (QTUM also holds enablers such as NVDA, which stay home)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('AUTONOMY_EVTOL','AUTONOMY, eVTOL & DRONES','FRONTIER',null,'FMP ''Aerospace & Defense'' + ''Airlines'' eVTOL names and the autonomy names in THEMATIC') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('DEFENCE_TECH','DEFENCE TECH','FRONTIER','INDUSTRIAL','the new-generation defence names (drones, software, sensors) — ITA''s small end plus PLTR/AXON') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('MAG7','MAGNIFICENT 7','MARKET',null,'MAGS (Roundhill Magnificent Seven ETF) holdings — the seven, both Alphabet lines') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('INTERNET_PLATFORMS','INTERNET & CONSUMER PLATFORMS','SOFTWARE_INTERNET','CONSUMER','FDN holdings ∩ ours + FMP ''Internet Content & Information'' / ''Travel Services'' / ''Gaming'' platform names') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('PAYMENTS_FINTECH','PAYMENTS & FINTECH','FINANCE','SOFTWARE_INTERNET','IPAY/FINX holdings ∩ ours + FMP ''Financial - Credit Services''') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('CRYPTO_EQUITIES','CRYPTO EQUITIES','CRYPTO',null,'the exchange, the treasury company, the broker with a crypto book, and the miners (FMP ''Capital Markets'' / ''IT Services'' miners). The coins (BTCUSD …) stay in the CRYPTO heading as reference lines; the chart API does not serve them in the 590.') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('NUCLEAR_URANIUM','NUCLEAR & URANIUM','ENERGY_POWER',null,'URA holdings ∩ ours + FMP ''Uranium''') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('SOLAR_RENEWABLE','SOLAR & RENEWABLE','ENERGY_POWER',null,'TAN holdings ∩ ours + FMP ''Solar'' + the clean-energy integrator (ICLN would widen it; not served)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('OIL_UPSTREAM','OIL & GAS · PRODUCERS','ENERGY_POWER',null,'FMP ''Oil & Gas Integrated'' + ''Exploration & Production'' (XOP/IEO spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('OIL_MIDSTREAM','OIL & GAS · PIPELINES','ENERGY_POWER',null,'FMP ''Oil & Gas Midstream''') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('OIL_REFINERS','OIL & GAS · REFINERS','ENERGY_POWER',null,'FMP ''Oil & Gas Refining & Marketing''') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('OIL_SERVICES','OIL & GAS · SERVICES','ENERGY_POWER',null,'FMP ''Oil & Gas Equipment & Services'' (IEZ spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('REGULATED_UTILITIES','REGULATED UTILITIES','ENERGY_POWER',null,'FMP ''Regulated Electric'' + ''Regulated Gas'' + ''Diversified Utilities'' (XLU/VPU spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('POWER_GENERATORS','INDEPENDENT POWER','ENERGY_POWER',null,'FMP ''Independent Power Producers'' minus the reactor developer') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('GRID_ELECTRICAL','GRID & ELECTRICAL EQUIPMENT','ENERGY_POWER','INDUSTRIAL','FMP ''Electrical Equipment & Parts'' + ''Engineering & Construction'' grid builders (PAVE spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('BIG_BANKS_BROKERS','BIG BANKS & BROKERS','FINANCE',null,'FMP ''Banks - Diversified'' + the bulge-bracket ''Capital Markets'' names + the two super-regionals (IYG spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('REGIONAL_BANKS','REGIONAL BANKS','FINANCE',null,'FMP ''Banks - Regional'' (KRE/IAT spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('EXCHANGES_DATA','EXCHANGES & MARKET DATA','FINANCE',null,'FMP ''Financial - Data & Stock Exchanges'' minus COIN (IAI spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('ASSET_MANAGERS','ASSET MANAGERS & ALTS','FINANCE',null,'FMP ''Asset Management'' + the custodian') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('INSURANCE','INSURANCE','FINANCE',null,'FMP ''Insurance - *'' (KIE/IAK spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('BIG_PHARMA','BIG PHARMA','HEALTH',null,'FMP ''Drug Manufacturers - General'' (IHE/XPH spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('BIOTECH','BIOTECH','HEALTH',null,'FMP ''Biotechnology'' (XBI/IBB spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('MEDTECH','MEDTECH','HEALTH',null,'FMP ''Medical - Devices'' + ''Instruments & Supplies'' (IHI spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('TOOLS_DIAGNOSTICS','LIFE-SCIENCE TOOLS & DIAGNOSTICS','HEALTH',null,'FMP ''Medical - Diagnostics & Research''') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('HEALTH_SERVICES','INSURERS & HEALTH SERVICES','HEALTH',null,'FMP ''Healthcare Plans'' + ''Care Facilities'' + ''Distribution'' + ''Health Information'' (IHF spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('PRECIOUS_METALS','PRECIOUS METALS','MATERIALS_METALS',null,'GDX/GDXJ/SIL holdings ∩ ours + FMP ''Gold'' / ''Other Precious Metals''; GLD/SLV are the metal''s reference lines') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('COPPER_STEEL','COPPER & STEEL','MATERIALS_METALS',null,'FMP ''Copper'' + ''Steel'' (COPX spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('CRITICAL_MINERALS','CRITICAL MINERALS & LITHIUM','MATERIALS_METALS',null,'REMX/LIT holdings ∩ ours + FMP ''Industrial Materials'' + the lithium chemicals') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('CHEMICALS_BUILDING','CHEMICALS & BUILDING MATERIALS','MATERIALS_METALS',null,'FMP ''Chemicals*'' + ''Construction Materials'' + ''Agricultural Inputs'' minus the lithium names') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('DEFENCE_PRIMES','AEROSPACE & DEFENCE PRIMES','INDUSTRIAL',null,'ITA holdings ∩ ours, the primes and their suppliers (FMP ''Aerospace & Defense'' minus space/eVTOL/drones)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('MACHINERY_CAPGOODS','MACHINERY & CAPITAL GOODS','INDUSTRIAL',null,'FMP ''Industrial - Machinery'' + ''Agricultural - Machinery'' + ''Conglomerates'' + ''Industrial - Distribution'' + rental (XLI/VIS spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('TRANSPORT','RAIL, FREIGHT & AIRLINES','INDUSTRIAL',null,'IYT/JETS holdings ∩ ours (FMP ''Railroads'' + ''Freight'' + ''Trucking'' + ''Airlines'' minus JOBY)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('HOUSING','HOUSING & HOME IMPROVEMENT','INDUSTRIAL','CONSUMER','XHB/ITB holdings ∩ ours') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('BUSINESS_SERVICES','BUSINESS SERVICES & PAYROLL','INDUSTRIAL',null,'FMP ''Specialty Business Services'' + ''Waste Management'' + the payroll processors') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('AUTOS_EV','AUTOS & EV','CONSUMER',null,'FMP ''Auto - Manufacturers'' + ''Auto - Parts'' (the Chinese EV makers also sit in CHINA)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('RETAIL','RETAIL & E-COMMERCE (US)','CONSUMER',null,'XRT holdings ∩ ours + FMP retail industries, US-listed domestic names (the ADR e-commerce names sit in their region)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('TRAVEL_LEISURE','TRAVEL & LEISURE','CONSUMER',null,'PEJ holdings ∩ ours + FMP ''Travel *'' + ''Entertainment'' live/parks + ''Gambling''') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('RESTAURANTS','RESTAURANTS','CONSUMER',null,'FMP ''Restaurants''') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('STAPLES','CONSUMER STAPLES','CONSUMER',null,'FMP Consumer Defensive industries minus the discount stores (which sit in RETAIL) (XLP/VDC spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('MEDIA_TELECOM','MEDIA & TELECOM','CONSUMER',null,'FMP ''Entertainment'' studios + ''Telecommunications Services'' + ''Advertising'' minus the platforms (XLC/VOX spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('REITS','REITs (property)','REAL_ESTATE',null,'FMP ''REIT - *'' minus the datacenter and tower landlords + the broker (VNQ/XLRE/REZ spine)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('TOWERS','TELECOM TOWERS','REAL_ESTATE',null,'FMP ''REIT - Specialty'' tower owners') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('IT_SERVICES','IT SERVICES & CONSULTING','SOFTWARE_INTERNET',null,'FMP ''Information Technology Services'' + ''Technology Distributors'' minus the miners and neoclouds') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('PACKAGING','PACKAGING','MATERIALS_METALS',null,'FMP ''Packaging & Containers''') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('CHINA','CHINA (ADRs)','INTERNATIONAL',null,'FMP country CN/HK or is_adr, Chinese operating companies (FXI/MCHI/ASHR are the reference lines)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('EUROPE','EUROPE (listed here)','INTERNATIONAL',null,'FMP country NL/GB/SE/BE/CH operating companies and the European ADRs (EZU/EWG/EWU/EFA reference lines)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('ASIA_PACIFIC','ASIA-PACIFIC ex-CHINA','INTERNATIONAL',null,'FMP country TW/HK(Taiwanese)/AU/IL operating companies (EWJ/EWY reference lines; no Japanese or Korean single name is served)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('CANADA','CANADA','INTERNATIONAL',null,'FMP country CA') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('LATAM','LATIN AMERICA','INTERNATIONAL',null,'FMP country UY/BR/CL + the Peru-weighted copper miner') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('IDX_US_BROAD','US BROAD','INDEX_LAYER',null,'the five the Hub already draws, plus the equal-weight and total-market lines') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('IDX_WORLD','WORLD & REGIONS','INDEX_LAYER',null,'VT stands in for MSCI ACWI until URTH/ACWI are served; EFA = developed ex-US, EEM = emerging, EZU = euro area, EWJ = Japan') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('IDX_STYLE','STYLE & FACTOR','INDEX_LAYER',null,'growth, value, momentum, quality, low-vol, dividend') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('IDX_SECTOR_FUNDS','SECTOR FUNDS','INDEX_LAYER',null,'the GICS side of the compare toggle — unchanged, the tree sits beside it') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('IDX_MACRO','MACRO','INDEX_LAYER',null,'rates, credit, dollar, oil, metals, volatility (the futures/yields in today''s MACRO cohort are not in the 590)') on conflict (cohort) do nothing;
insert into public.cohort_tree (cohort,label,parent_1,parent_2,spine) values ('IDX_THEME_FUNDS','THEME FUNDS (each is its cohort''s spine line)','INDEX_LAYER',null,'every theme fund we serve, hung as the reference line of the cohort it defines') on conflict (cohort) do nothing;
-- 2. memberships: rows into public.ticker_cohorts (ticker, cohort). Existing rows are NOT deleted here; GROWTH/THEMATIC/MEGACAP/INTL rows stay until Alan says otherwise.
insert into public.ticker_cohorts (ticker,cohort) values ('ALAB','AI_ACCELERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AMD','AI_ACCELERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ARM','AI_ACCELERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AVGO','AI_ACCELERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CBRS','AI_ACCELERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GFS','AI_ACCELERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('INTC','AI_ACCELERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MRVL','AI_ACCELERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NVDA','AI_ACCELERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('QCOM','AI_ACCELERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RMBS','AI_ACCELERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SIMO','AI_ACCELERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TSM','AI_ACCELERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MU','MEMORY_STORAGE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NTAP','MEMORY_STORAGE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('P','MEMORY_STORAGE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SNDK','MEMORY_STORAGE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('STX','MEMORY_STORAGE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('WDC','MEMORY_STORAGE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ACMR','SEMICAP_EDA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AMAT','SEMICAP_EDA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AMKR','SEMICAP_EDA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ASML','SEMICAP_EDA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CDNS','SEMICAP_EDA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ENTG','SEMICAP_EDA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FORM','SEMICAP_EDA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KLAC','SEMICAP_EDA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LRCX','SEMICAP_EDA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ONTO','SEMICAP_EDA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SNPS','SEMICAP_EDA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TER','SEMICAP_EDA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('UCTT','SEMICAP_EDA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ADI','ANALOG_RF_POWER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MCHP','ANALOG_RF_POWER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MPWR','ANALOG_RF_POWER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NVTS','ANALOG_RF_POWER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NXPI','ANALOG_RF_POWER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ON','ANALOG_RF_POWER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('QRVO','ANALOG_RF_POWER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('STM','ANALOG_RF_POWER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SWKS','ANALOG_RF_POWER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TSEM','ANALOG_RF_POWER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TXN','ANALOG_RF_POWER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VSH','ANALOG_RF_POWER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AAOI','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ANET','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('APH','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AXTI','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CIEN','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('COHR','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CRDO','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CSCO','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FN','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GLW','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LITE','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('POET','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TEL','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('UI','AI_NETWORKING_OPTICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DELL','AI_SERVERS_DC_KIT') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SHAZ','AI_SERVERS_DC_KIT') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SMCI','AI_SERVERS_DC_KIT') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VRT','AI_SERVERS_DC_KIT') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('APLD','NEOCLOUDS_MINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BTDR','NEOCLOUDS_MINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CIFR','NEOCLOUDS_MINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CORZ','NEOCLOUDS_MINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CRWV','NEOCLOUDS_MINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HIVE','NEOCLOUDS_MINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HUT','NEOCLOUDS_MINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IREN','NEOCLOUDS_MINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MARA','NEOCLOUDS_MINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NBIS','NEOCLOUDS_MINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RIOT','NEOCLOUDS_MINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('WULF','NEOCLOUDS_MINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DLR','DC_PROPERTY') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EQIX','DC_PROPERTY') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GDS','DC_PROPERTY') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IRM','DC_PROPERTY') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ADBE','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('APP','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CRM','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DDOG','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FROG','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('INTU','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MDB','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MSFT','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NOW','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NTNX','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ORCL','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PATH','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PLTR','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SNOW','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TWLO','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ZETA','AI_SOFTWARE_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CRWD','CYBER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FTNT','CYBER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NET','CYBER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('OKTA','CYBER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PANW','CYBER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('S','CYBER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ZS','CYBER') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BE','AI_POWERTRAIN') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CCJ','AI_POWERTRAIN') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CEG','AI_POWERTRAIN') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EOSE','AI_POWERTRAIN') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GEV','AI_POWERTRAIN') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LEU','AI_POWERTRAIN') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NRG','AI_POWERTRAIN') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('OKLO','AI_POWERTRAIN') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SMR','AI_POWERTRAIN') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TLN','AI_POWERTRAIN') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('UUUU','AI_POWERTRAIN') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VST','AI_POWERTRAIN') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AUR','ROBOTICS_AUTOMATION') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ISRG','ROBOTICS_AUTOMATION') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('OUST','ROBOTICS_AUTOMATION') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SERV','ROBOTICS_AUTOMATION') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SYM','ROBOTICS_AUTOMATION') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ASTS','SPACE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BKSY','SPACE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LUNR','SPACE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PL','SPACE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RDW','SPACE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RKLB','SPACE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SATL','SPACE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SIDU','SPACE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SPCX','SPACE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SPIR','SPACE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VSAT','SPACE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IONQ','QUANTUM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('QBTS','QUANTUM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('QUBT','QUANTUM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RGTI','QUANTUM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ACHR','AUTONOMY_EVTOL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AUR','AUTONOMY_EVTOL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EH','AUTONOMY_EVTOL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EVTL','AUTONOMY_EVTOL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('JOBY','AUTONOMY_EVTOL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ONDS','AUTONOMY_EVTOL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AVAV','DEFENCE_TECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AXON','DEFENCE_TECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KTOS','DEFENCE_TECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LDOS','DEFENCE_TECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PLTR','DEFENCE_TECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AAPL','MAG7') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AMZN','MAG7') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GOOG','MAG7') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GOOGL','MAG7') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('META','MAG7') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MSFT','MAG7') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NVDA','MAG7') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TSLA','MAG7') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ABNB','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AMZN','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BKNG','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DASH','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DKNG','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GOOG','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GOOGL','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LYFT','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('META','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MTCH','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NFLX','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PINS','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RBLX','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RDDT','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SNAP','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SPOT','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TTWO','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('UBER','INTERNET_PLATFORMS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AFRM','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AXP','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('COF','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FIS','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GPN','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HOOD','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MA','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NU','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PAYC','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PYPL','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SOFI','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SYF','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TOST','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('V','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XYZ','PAYMENTS_FINTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BTDR','CRYPTO_EQUITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CIFR','CRYPTO_EQUITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('COIN','CRYPTO_EQUITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CORZ','CRYPTO_EQUITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HIVE','CRYPTO_EQUITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HOOD','CRYPTO_EQUITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HUT','CRYPTO_EQUITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IREN','CRYPTO_EQUITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MARA','CRYPTO_EQUITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MSTR','CRYPTO_EQUITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RIOT','CRYPTO_EQUITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('WULF','CRYPTO_EQUITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CCJ','NUCLEAR_URANIUM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LEU','NUCLEAR_URANIUM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('OKLO','NUCLEAR_URANIUM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SMR','NUCLEAR_URANIUM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('UUUU','NUCLEAR_URANIUM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AMRC','SOLAR_RENEWABLE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ENPH','SOLAR_RENEWABLE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FSLR','SOLAR_RENEWABLE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NXT','SOLAR_RENEWABLE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RUN','SOLAR_RENEWABLE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SEDG','SOLAR_RENEWABLE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('COP','OIL_UPSTREAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CVX','OIL_UPSTREAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DVN','OIL_UPSTREAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EOG','OIL_UPSTREAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('OXY','OIL_UPSTREAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SM','OIL_UPSTREAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XOM','OIL_UPSTREAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KMI','OIL_MIDSTREAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('OKE','OIL_MIDSTREAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TRGP','OIL_MIDSTREAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('WMB','OIL_MIDSTREAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MPC','OIL_REFINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PSX','OIL_REFINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VLO','OIL_REFINERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BKR','OIL_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FTI','OIL_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SLB','OIL_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AEE','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AEP','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ATO','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CNP','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('D','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DTE','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DUK','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ED','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ES','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ETR','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EVRG','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EXC','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FE','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LNT','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NEE','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NI','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PCG','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PEG','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PNW','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PPL','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SO','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SRE','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('WEC','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XEL','REGULATED_UTILITIES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CEG','POWER_GENERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NRG','POWER_GENERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TLN','POWER_GENERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VST','POWER_GENERATORS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AME','GRID_ELECTRICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EMR','GRID_ELECTRICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ETN','GRID_ELECTRICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FIX','GRID_ELECTRICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GEV','GRID_ELECTRICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HUBB','GRID_ELECTRICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NVT','GRID_ELECTRICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PWR','GRID_ELECTRICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VRT','GRID_ELECTRICAL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BAC','BIG_BANKS_BROKERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('C','BIG_BANKS_BROKERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GS','BIG_BANKS_BROKERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('JPM','BIG_BANKS_BROKERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MS','BIG_BANKS_BROKERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PNC','BIG_BANKS_BROKERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SCHW','BIG_BANKS_BROKERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('USB','BIG_BANKS_BROKERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('WFC','BIG_BANKS_BROKERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CATY','REGIONAL_BANKS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CVBF','REGIONAL_BANKS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FULT','REGIONAL_BANKS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HWC','REGIONAL_BANKS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SFNC','REGIONAL_BANKS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TRMK','REGIONAL_BANKS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('UMBF','REGIONAL_BANKS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CME','EXCHANGES_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ICE','EXCHANGES_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MCO','EXCHANGES_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SPGI','EXCHANGES_DATA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BLK','ASSET_MANAGERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BNY','ASSET_MANAGERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BX','ASSET_MANAGERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KKR','ASSET_MANAGERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AON','INSURANCE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BRK-B','INSURANCE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CB','INSURANCE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MRSH','INSURANCE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PGR','INSURANCE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TRV','INSURANCE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ABBV','BIG_PHARMA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AMGN','BIG_PHARMA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BIIB','BIG_PHARMA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BMY','BIG_PHARMA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GILD','BIG_PHARMA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('JNJ','BIG_PHARMA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LLY','BIG_PHARMA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MRK','BIG_PHARMA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PFE','BIG_PHARMA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ALNY','BIOTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ARGX','BIOTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HALO','BIOTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KRYS','BIOTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MRNA','BIOTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PTGX','BIOTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('REGN','BIOTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RVMD','BIOTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TGTX','BIOTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TWST','BIOTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TXG','BIOTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VRTX','BIOTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ABT','MEDTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BSX','MEDTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DXCM','MEDTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EW','MEDTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GEHC','MEDTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GKOS','MEDTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ISRG','MEDTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MDT','MEDTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RMD','MEDTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SYK','MEDTECH') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DHR','TOOLS_DIAGNOSTICS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IDXX','TOOLS_DIAGNOSTICS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ILMN','TOOLS_DIAGNOSTICS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NTRA','TOOLS_DIAGNOSTICS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TMO','TOOLS_DIAGNOSTICS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BTSG','HEALTH_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CI','HEALTH_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CVS','HEALTH_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ELV','HEALTH_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HCA','HEALTH_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HIMS','HEALTH_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HUM','HEALTH_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MCK','HEALTH_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('UNH','HEALTH_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AEM','PRECIOUS_METALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AU','PRECIOUS_METALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CDE','PRECIOUS_METALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FNV','PRECIOUS_METALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HL','PRECIOUS_METALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KGC','PRECIOUS_METALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NEM','PRECIOUS_METALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PAAS','PRECIOUS_METALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RGLD','PRECIOUS_METALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('WPM','PRECIOUS_METALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CLF','COPPER_STEEL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FCX','COPPER_STEEL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NUE','COPPER_STEEL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RS','COPPER_STEEL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SCCO','COPPER_STEEL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('STLD','COPPER_STEEL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TECK','COPPER_STEEL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ALB','CRITICAL_MINERALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CRML','CRITICAL_MINERALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LAC','CRITICAL_MINERALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MP','CRITICAL_MINERALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SQM','CRITICAL_MINERALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('USAR','CRITICAL_MINERALS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('APD','CHEMICALS_BUILDING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CRH','CHEMICALS_BUILDING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CTVA','CHEMICALS_BUILDING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DOW','CHEMICALS_BUILDING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ECL','CHEMICALS_BUILDING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('JCI','CHEMICALS_BUILDING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LIN','CHEMICALS_BUILDING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MLM','CHEMICALS_BUILDING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PPG','CHEMICALS_BUILDING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SHW','CHEMICALS_BUILDING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VMC','CHEMICALS_BUILDING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ATI','DEFENCE_PRIMES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BA','DEFENCE_PRIMES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GD','DEFENCE_PRIMES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GE','DEFENCE_PRIMES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HEI','DEFENCE_PRIMES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HWM','DEFENCE_PRIMES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LHX','DEFENCE_PRIMES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LMT','DEFENCE_PRIMES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MOG.A','DEFENCE_PRIMES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NOC','DEFENCE_PRIMES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RTX','DEFENCE_PRIMES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TDG','DEFENCE_PRIMES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CAT','MACHINERY_CAPGOODS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CMI','MACHINERY_CAPGOODS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DE','MACHINERY_CAPGOODS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FAST','MACHINERY_CAPGOODS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GWW','MACHINERY_CAPGOODS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HON','MACHINERY_CAPGOODS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ITW','MACHINERY_CAPGOODS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MMM','MACHINERY_CAPGOODS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PCAR','MACHINERY_CAPGOODS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PH','MACHINERY_CAPGOODS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TT','MACHINERY_CAPGOODS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('URI','MACHINERY_CAPGOODS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CSX','TRANSPORT') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DAL','TRANSPORT') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FDX','TRANSPORT') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NSC','TRANSPORT') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ODFL','TRANSPORT') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('UAL','TRANSPORT') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('UNP','TRANSPORT') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('UPS','TRANSPORT') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XPO','TRANSPORT') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DHI','HOUSING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HD','HOUSING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LOW','HOUSING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ADP','BUSINESS_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CTAS','BUSINESS_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PAYC','BUSINESS_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('WM','BUSINESS_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('F','AUTOS_EV') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GM','AUTOS_EV') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LCID','AUTOS_EV') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LI','AUTOS_EV') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NIO','AUTOS_EV') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('QS','AUTOS_EV') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RIVN','AUTOS_EV') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TSLA','AUTOS_EV') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XPEV','AUTOS_EV') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AMZN','RETAIL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('COST','RETAIL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KR','RETAIL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NKE','RETAIL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ORLY','RETAIL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ROST','RETAIL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TGT','RETAIL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TJX','RETAIL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('WMT','RETAIL') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ABNB','TRAVEL_LEISURE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BKNG','TRAVEL_LEISURE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DIS','TRAVEL_LEISURE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DKNG','TRAVEL_LEISURE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HLT','TRAVEL_LEISURE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LYV','TRAVEL_LEISURE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MAR','TRAVEL_LEISURE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RCL','TRAVEL_LEISURE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DPZ','RESTAURANTS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EAT','RESTAURANTS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MCD','RESTAURANTS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SBUX','RESTAURANTS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ADM','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BYND','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CL','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KDP','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KMB','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KO','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KR','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KVUE','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MDLZ','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MNST','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MO','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PEP','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PG','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PM','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SYY','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('USFD','STAPLES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CHTR','MEDIA_TELECOM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CMCSA','MEDIA_TELECOM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DIS','MEDIA_TELECOM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FOXA','MEDIA_TELECOM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('OMC','MEDIA_TELECOM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('T','MEDIA_TELECOM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TMUS','MEDIA_TELECOM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VZ','MEDIA_TELECOM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('WBD','MEDIA_TELECOM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CBRE','REITS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EXR','REITS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('O','REITS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PLD','REITS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PSA','REITS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RHP','REITS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SPG','REITS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VICI','REITS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VTR','REITS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('WELL','REITS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AMT','TOWERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CCI','TOWERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SBAC','TOWERS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ACN','IT_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IBM','IT_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SNX','IT_SERVICES') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AMCR','PACKAGING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PKG','PACKAGING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SW','PACKAGING') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BABA','CHINA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BIDU','CHINA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EH','CHINA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GDS','CHINA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('JD','CHINA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LI','CHINA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NIO','CHINA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PDD','CHINA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XPEV','CHINA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ARGX','EUROPE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ARM','EUROPE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ASML','EUROPE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EVTL','EUROPE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NBIS','EUROPE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NOK','EUROPE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SPOT','EUROPE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('STM','EUROPE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IREN','ASIA_PACIFIC') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SIMO','ASIA_PACIFIC') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TSEM','ASIA_PACIFIC') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TSM','ASIA_PACIFIC') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AEM','CANADA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CCJ','CANADA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FNV','CANADA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KGC','CANADA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LAC','CANADA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PAAS','CANADA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SHOP','CANADA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TECK','CANADA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('WPM','CANADA') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MELI','LATAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('NU','LATAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SCCO','LATAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SQM','LATAM') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SPY','IDX_US_BROAD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('QQQ','IDX_US_BROAD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('QQQE','IDX_US_BROAD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DIA','IDX_US_BROAD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IWM','IDX_US_BROAD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RSP','IDX_US_BROAD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MDY','IDX_US_BROAD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IJR','IDX_US_BROAD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VTI','IDX_US_BROAD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ITOT','IDX_US_BROAD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IWV','IDX_US_BROAD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VT','IDX_WORLD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VXUS','IDX_WORLD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EFA','IDX_WORLD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EEM','IDX_WORLD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EZU','IDX_WORLD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EWJ','IDX_WORLD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EWG','IDX_WORLD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EWU','IDX_WORLD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('EWY','IDX_WORLD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FXI','IDX_WORLD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MCHI','IDX_WORLD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ASHR','IDX_WORLD') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VUG','IDX_STYLE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VTV','IDX_STYLE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MGK','IDX_STYLE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MTUM','IDX_STYLE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('QUAL','IDX_STYLE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SPLV','IDX_STYLE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SCHD','IDX_STYLE') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XLK','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XLF','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XLV','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XLY','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XLP','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XLE','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XLI','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XLB','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XLU','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XLRE','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XLC','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VGT','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VFH','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VHT','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VCR','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VDC','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VDE','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VIS','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VAW','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VPU','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VNQ','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VOX','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IYW','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IYF','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IYH','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IYC','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IYK','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IYE','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IYJ','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IYM','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IDU','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IYR','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IYZ','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RSPT','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RSPF','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RSPH','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RSPD','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RSPS','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RSPG','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RSPN','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RSPM','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RSPU','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RSPR','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('RSPC','IDX_SECTOR_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TLT','IDX_MACRO') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IEF','IDX_MACRO') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SHY','IDX_MACRO') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AGG','IDX_MACRO') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LQD','IDX_MACRO') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('HYG','IDX_MACRO') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('UUP','IDX_MACRO') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('USO','IDX_MACRO') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DBC','IDX_MACRO') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GLD','IDX_MACRO') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SLV','IDX_MACRO') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('VXX','IDX_MACRO') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('AGIX','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ARKX','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('BOTZ','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('CIBR','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('COPX','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('DRAM','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FDN','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('FINX','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GDX','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('GDXJ','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IAI','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IAK','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IAT','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IBB','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IEO','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IEZ','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IGM','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IGV','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IHE','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IHF','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IHI','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IPAY','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ITA','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('ITB','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IYG','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('IYT','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('JETS','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KBE','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KIE','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('KRE','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('LIT','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('MAGS','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PAVE','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('PEJ','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('QTUM','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('REMX','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('REZ','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SIL','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SILJ','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SKYY','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SMH','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('SOXX','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('TAN','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('URA','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XBI','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XHB','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XOP','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XPH','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XRT','IDX_THEME_FUNDS') on conflict do nothing;
insert into public.ticker_cohorts (ticker,cohort) values ('XSD','IDX_THEME_FUNDS') on conflict do nothing;
-- 655 membership rows across 69 cohorts; 63 are cohorts of companies, 6 are index-layer fund sets.
-- rollback: delete from public.ticker_cohorts where cohort in ('AI_ACCELERATORS','MEMORY_STORAGE','SEMICAP_EDA','ANALOG_RF_POWER','AI_NETWORKING_OPTICAL','AI_SERVERS_DC_KIT','NEOCLOUDS_MINERS','DC_PROPERTY','AI_SOFTWARE_DATA','CYBER','AI_POWERTRAIN','ROBOTICS_AUTOMATION','SPACE','QUANTUM','AUTONOMY_EVTOL','DEFENCE_TECH','MAG7','INTERNET_PLATFORMS','PAYMENTS_FINTECH','CRYPTO_EQUITIES','NUCLEAR_URANIUM','SOLAR_RENEWABLE','OIL_UPSTREAM','OIL_MIDSTREAM','OIL_REFINERS','OIL_SERVICES','REGULATED_UTILITIES','POWER_GENERATORS','GRID_ELECTRICAL','BIG_BANKS_BROKERS','REGIONAL_BANKS','EXCHANGES_DATA','ASSET_MANAGERS','INSURANCE','BIG_PHARMA','BIOTECH','MEDTECH','TOOLS_DIAGNOSTICS','HEALTH_SERVICES','PRECIOUS_METALS','COPPER_STEEL','CRITICAL_MINERALS','CHEMICALS_BUILDING','DEFENCE_PRIMES','MACHINERY_CAPGOODS','TRANSPORT','HOUSING','BUSINESS_SERVICES','AUTOS_EV','RETAIL','TRAVEL_LEISURE','RESTAURANTS','STAPLES','MEDIA_TELECOM','REITS','TOWERS','IT_SERVICES','PACKAGING','CHINA','EUROPE','ASIA_PACIFIC','CANADA','LATAM','IDX_US_BROAD','IDX_WORLD','IDX_STYLE','IDX_SECTOR_FUNDS','IDX_MACRO','IDX_THEME_FUNDS');
