# Builds models.json (one row per candidate) from the measured bake-off files. Usage: python3 build_models_json.py <deliverable dir>
import json,sys
D=sys.argv[1]
X=json.load(open(D+'/bakeoff/x-short-text.json')); L=json.load(open(D+'/bakeoff/long-form.json')); T=json.load(open(D+'/bakeoff/transcripts-and-speech.json')); E=json.load(open(D+'/bakeoff/extras.json'))
xr={r['model']:r for r in X['results']}
def lf(sec,key):
    for r in L[sec]:
        if r['method'].startswith(key): return r
HF='https://huggingface.co/'
rows=[]
def add(job,cand,verdict,why,**k): rows.append({'job':job,'candidate':cand,'verdict':verdict,'why':why,**k})
MAC='MacBook (M-series)'; FLYCPU='Fly CPU machine'; 
def xs(m): r=xr[m]; return {'accuracy_on_100_hand_labels':r['accuracy_100'],'macro_f1':r['macro_f1_100'],'opposite_calls_of_100':r['opposite_calls_100'],'ms_per_post':r['ms_per_item']}
J1='1 · short-text finance sentiment (X posts)'
add(J1,'current word list (lm-v1)','REPLACE','Reads nothing on 148 of 300 posts and called the opposite direction 15 times in 100: worse than guessing bullish every time (0.56).',source='supabase/functions/_shared/sentiment-core.mjs + data/news-lexicon/lm-headline-v1.json',licence='ours',needs='nothing',runs_where='Supabase edge function (today)',cost='nothing',measured=xs('current word list (lm-v1)'))
add(J1,'tabularisai/ModernFinBERT','ADOPT','Best small classifier: 0.68, and small enough for one Fly CPU machine or the Mac. Its bullish reads are strong (F1 0.81); its neutral reads are the weak part.',source=HF+'tabularisai/ModernFinBERT ; ModernBERT paper https://arxiv.org/abs/2412.13663',licence='Apache-2.0',needs='CPU, about 1 GB RAM (150 M parameters)',runs_where=MAC+' or '+FLYCPU,cost='Mac: nothing. Fly: about 0.1 to 0.15 s a post (estimate) = minutes a day on a shared-cpu-2x 2 GB (13.39 dollars a month if left on; cents if started per run).',measured=xs('tabularisai/ModernFinBERT'))
add(J1,'mlx-community/Qwen2.5-7B-Instruct-4bit (finance prompt)','ADOPT as the second opinion','Highest score, 0.73, and the only family that reads neutral and bearish posts well. Needs the Mac (5 GB, Metal). Use it to re-read the posts where ModernFinBERT is unsure.',source=HF+'Qwen/Qwen2.5-7B-Instruct ; https://arxiv.org/abs/2412.15115',licence='Apache-2.0',needs='Apple Metal, 5.0 GB peak',runs_where=MAC+' (MLX)',cost='nothing; 0.17 s a post',measured=xs('mlx-community/Qwen2.5-7B-Instruct-4bit'))
add(J1,'mlx-community/Phi-3.5-mini-instruct-4bit','TRY','0.71 with only 2 opposite calls, at 0.12 s a post and 3.8 GB: the cheapest instruct model that held up on short text. It fell apart on long text (see job 2).',source=HF+'microsoft/Phi-3.5-mini-instruct ; https://arxiv.org/abs/2404.14219',licence='MIT',needs='Apple Metal, 3.8 GB peak',runs_where=MAC+' (MLX)',cost='nothing',measured=xs('mlx-community/Phi-3.5-mini-instruct-4bit'))
add(J1,'mlx-community/Mistral-7B-Instruct-v0.3-4bit','TRY','0.71, 2 opposite calls; leans bullish (weak on neutral).',source=HF+'mistralai/Mistral-7B-Instruct-v0.3 ; https://arxiv.org/abs/2310.06825',licence='Apache-2.0',needs='Apple Metal, 5.1 GB peak',runs_where=MAC+' (MLX)',cost='nothing',measured=xs('mlx-community/Mistral-7B-Instruct-v0.3-4bit'))
add(J1,'mlx-community/Meta-Llama-3.1-8B-Instruct-4bit','TRY','0.69; over-calls bearish on short posts. Its strength is transcripts (job 2).',source=HF+'meta-llama/Llama-3.1-8B-Instruct',licence='Llama 3.1 Community Licence (use allowed; read the acceptable-use terms)',needs='Apple Metal, 5.6 GB peak',runs_where=MAC+' (MLX)',cost='nothing',measured=xs('mlx-community/Meta-Llama-3.1-8B-Instruct-4bit'))
add(J1,'mlx-community/Qwen2.5-3B-Instruct-4bit','NO','0.65 and it calls 233 of 300 posts bullish. Its licence is also research-only.',source=HF+'Qwen/Qwen2.5-3B-Instruct',licence='Qwen Research Licence (non-commercial)',needs='Apple Metal, 2.5 GB',runs_where=MAC,cost='nothing',measured=xs('mlx-community/Qwen2.5-3B-Instruct-4bit'))
add(J1,'StephanAkkerman/FinTwitBERT-sentiment','NO','0.64 but 9 opposite calls in 100: it reads 99 of 300 posts as bearish. Trained on tweets, yet the worst on direction errors among the classifiers.',source=HF+'StephanAkkerman/FinTwitBERT-sentiment ; https://github.com/StephanAkkerman/FinTwitBERT',licence='MIT',needs='CPU, under 1 GB',runs_where=FLYCPU,cost='cents',measured=xs('StephanAkkerman/FinTwitBERT-sentiment'))
add(J1,'cardiffnlp/twitter-roberta-base-sentiment-latest','NO','0.59: it knows Twitter but not markets ("puts printing" reads as neutral).',source=HF+'cardiffnlp/twitter-roberta-base-sentiment-latest ; https://arxiv.org/abs/2202.03829',licence='CC-BY-4.0',needs='CPU',runs_where=FLYCPU,cost='cents',measured=xs('cardiffnlp/twitter-roberta-base-sentiment-latest'))
add(J1,'ProsusAI/finbert (the one Grok Bot is testing)','NO for X posts','0.55 — below the always-bullish guess (0.56). It was trained on analyst-style news sentences, and calls 199 of 300 trader posts neutral. This is the finding to send back to the Grok Bot session.',source=HF+'ProsusAI/finbert ; https://arxiv.org/abs/1908.10063',licence='none stated on the model card',needs='CPU, under 1 GB',runs_where=FLYCPU,cost='cents',measured=xs('ProsusAI/finbert'))
add(J1,'yiyanghkust/finbert-tone','NO','0.47. Trained on analyst reports. Its files also need hand-loading in current libraries (no model type in its config).',source=HF+'yiyanghkust/finbert-tone ; Huang, Wang, Yang (2023), Contemporary Accounting Research',licence='none stated on the model card',needs='CPU',runs_where=FLYCPU,cost='cents',measured=xs('yiyanghkust/finbert-tone'))
add(J1,'mrm8488/deberta-v3-ft-financial-news-sentiment-analysis','NO','0.53; calls 206 of 300 neutral.',source=HF+'mrm8488/deberta-v3-ft-financial-news-sentiment-analysis',licence='MIT',needs='CPU',runs_where=FLYCPU,cost='cents',measured=xs('mrm8488/deberta-v3-ft-financial-news-sentiment-analysis'))
add(J1,'mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis','NO','0.59; the fastest (12 ms) but no better than the Twitter model.',source=HF+'mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis',licence='Apache-2.0',needs='CPU',runs_where=FLYCPU,cost='cents',measured=xs('mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis'))
add(J1,'soleimanian/financial-roberta-large-sentiment','NO','0.59 at three times the cost of the small ones.',source=HF+'soleimanian/financial-roberta-large-sentiment',licence='Apache-2.0',needs='CPU, 1.5 GB',runs_where=FLYCPU,cost='cents',measured=xs('soleimanian/financial-roberta-large-sentiment'))
J2='2 · long-form sentiment (news, YouTube transcripts) and which ticker it is about'
def ls(sec,key): r=lf(sec,key); return {'accuracy':r['accuracy'],'macro_f1':r['macro_f1'],'opposite_calls':r['opposite_calls'],'n':r['n'],'ms_per_item':r['ms']}
add(J2,'ModernFinBERT on the stored news row (title + snippet)','ADOPT for news rows','0.71 against 0.60 for always-neutral, with no opposite call in 100, on CPU. Our news rows are short (at most 400 characters), so the short-text winner carries over.',source=HF+'tabularisai/ModernFinBERT',licence='Apache-2.0',needs='CPU, 1 GB',runs_where=FLYCPU+' or '+MAC,cost='592,264 stored rows at 48 ms = about 8 hours of one Mac, once; new rows are a few hundred an hour',measured=ls('news_snippet','ModernFinBERT'))
add(J2,'Mistral-7B-Instruct asked about the filed ticker (news row)','TRY','0.74, the top score, because it is told which ticker to judge; 4 opposite calls. Needs the Mac.',source=HF+'mistralai/Mistral-7B-Instruct-v0.3',licence='Apache-2.0',needs='Apple Metal, 6.1 GB',runs_where=MAC,cost='nothing; 0.21 s a row',measured=ls('news_snippet','Mistral-7B'))
add(J2,'FinBERT with chunking + averaging (full article)','NO','0.62 on full articles against 0.64 for always-neutral: reading the whole article added nothing over the headline row.',source=HF+'ProsusAI/finbert',licence='none stated',needs='CPU',runs_where=FLYCPU,cost='0.2 s an article',measured=ls('news_article','finbert · chunks'))
add(J2,'ModernFinBERT reading a whole article in one pass (8,192 tokens)','NO (not proven)','0.66 against 0.64 for always-neutral on 58 articles: no gain worth fetching article bodies for.',source=HF+'tabularisai/ModernFinBERT',licence='Apache-2.0',needs='CPU, 2 GB',runs_where=MAC,cost='0.4 s an article',measured=ls('news_article','ModernFinBERT · whole'))
add(J2,'Longformer / BigBird finance models','NO','They barely exist: Hugging Face lists one finance Longformer (125 downloads) and no finance BigBird. ModernBERT (8,192 tokens) has taken their place.',source='https://arxiv.org/abs/2004.05150 ; https://arxiv.org/abs/2007.14062 ; Hugging Face model search, 5 Oct 2026',licence='-',needs='-',runs_where='-',cost='-')
add(J2,'instruct model reading a WHOLE transcript (Qwen2.5-7B / Llama-3.1-8B / Mistral-7B / Phi-3.5)','NO','0.35 to 0.45 against 0.50 for always-neutral: given a whole video they call almost everything bullish or bearish and lose the neutral ones.',source='model cards above',licence='see job 1',needs='Apple Metal, 5.6 to 7.2 GB',runs_where=MAC,cost='about 2 s a video',measured={'accuracy_range':'0.35-0.45','n':20})
add(J2,'name list finds the passages that mention the ticker, then Llama-3.1-8B reads only those','TRY (best of the transcript methods)','0.75 on 20 videos (Qwen2.5-7B 0.65) against 0.50 for always-neutral. This is also the answer to "which name is the sentiment about". Caution: 20 labels, made from the same passages, and it still missed all three bearish videos.',source=HF+'meta-llama/Llama-3.1-8B-Instruct',licence='Llama 3.1 Community Licence',needs='Apple Metal, 6.5 GB; the ticker + company-name list',runs_where=MAC,cost='nothing; 0.5 s a video',measured=ls('youtube','Meta-Llama-3.1-8B-Instruct-4bit · reads only'))
add(J2,'FinBERT-family classifiers on transcripts (first 512 tokens, all chunks averaged, or ticker passages averaged)','NO','0.30 to 0.65 with no pattern; the "best" one (finbert-tone, first 512 tokens, 0.65) simply calls 17 of 20 neutral.',source='model cards above',licence='-',needs='CPU',runs_where=FLYCPU,cost='0.1 to 1 s a video',measured={'accuracy_range':'0.30-0.65','n':20})
J3='3 · YouTube transcripts'
c=T['captions_first']; w={(r['engine'].split(' ')[0],r['model'],r.get('cpu_threads')):r for r in T['speech_to_text']['runs']}
add(J3,'youtube-transcript-api (captions first)','ADOPT','Free and instant: %d of %d sample videos answered in about %.1f s each from this MacBook. Our youtube_transcripts table is empty today, so this is the first thing to switch on — from the Mac, because YouTube tends to refuse data-centre addresses.'%(c['answered'],c['videos_tried'],c['median_fetch_s']),source='https://github.com/jdepoix/youtube-transcript-api',licence='MIT',needs='a home internet address',runs_where=MAC,cost='nothing',measured=c)
r=w[('mlx-whisper','whisper-large-v3-turbo',None)]
add(J3,'mlx-whisper large-v3-turbo (videos with no captions)','ADOPT as the fallback','%.0f times faster than real time on Metal: one hour of video in %.1f minutes.'%(r['times_faster_than_real_time'],r['minutes_per_hour_of_video']),source='https://github.com/ml-explore/mlx-examples/tree/main/whisper ; https://arxiv.org/abs/2212.04356',licence='MIT',needs='Apple Metal, about 2 GB',runs_where=MAC,cost='nothing',measured=r)
r=w[('faster-whisper','small',4)]
add(J3,'faster-whisper small (CPU)','TRY for Fly','On 4 Mac CPU threads: %.0f times real time (%.1f minutes per hour of video). On a Fly performance-4x that is an estimated 10 to 15 minutes and 3 to 5 cents per hour of video — not measured on Fly.'%(r['times_faster_than_real_time'],r['minutes_per_hour_of_video']),source='https://github.com/SYSTRAN/faster-whisper',licence='MIT',needs='CPU, 1 GB',runs_where=FLYCPU+' (performance-4x, 8 GB)',cost='about 3 to 5 cents per hour of video (estimate)',measured=r)
add(J3,'whisper.cpp','NO (not needed)','Same models as above through a C++ program; on this Mac mlx-whisper already does an hour in under a minute. Not timed.',source='https://github.com/ggml-org/whisper.cpp',licence='MIT',needs='CPU or Metal',runs_where=MAC,cost='nothing')
J4='4 · embeddings + search (dedupe news, cluster topics, similar posts)'
for r in E['embeddings']['results']:
    m=r['model']
    if 'skipped' in r:
        add(J4,m,'NO for now','Not run: it needs trust_remote_code (it executes code shipped in the model repository).',source=HF+m+' ; https://arxiv.org/abs/2402.01613',licence='Apache-2.0',needs='-',runs_where='-',cost='-'); continue
    v={'BAAI/bge-small-en-v1.5':('ADOPT','Finds the full original of a cut-off repost 95% of the time, at 563 headlines a second on CPU and 384 numbers per text: cheap enough for Fly and small enough for pgvector on our plan.'),'BAAI/bge-m3':('TRY','Best match rate (98.6%) but ten times slower and 1,024 numbers per text; worth it only if we need other languages or long texts.'),'intfloat/e5-base-v2':('TRY','97.8% and 191 a second on CPU: the middle choice.'),'thenlper/gte-base':('NO','Same match rate as e5-base but six times slower on CPU here.'),'Alibaba-NLP/gte-modernbert-base':('NO','No better than bge-small on our test and slow on CPU here.')}[m]
    src={'BAAI/bge-small-en-v1.5':'https://arxiv.org/abs/2309.07597','BAAI/bge-m3':'https://arxiv.org/abs/2402.03216','intfloat/e5-base-v2':'https://arxiv.org/abs/2212.03533','thenlper/gte-base':'https://arxiv.org/abs/2308.03281','Alibaba-NLP/gte-modernbert-base':'https://arxiv.org/abs/2308.03281'}[m]
    add(J4,m,v[0],v[1],source=HF+m+' ; '+src,licence='Apache-2.0' if 'modernbert' in m else 'MIT',needs='CPU; %d M parameters; %d numbers per text'%(r['params_m'],r['dim']),runs_where=FLYCPU+' or '+MAC,cost='cents',measured=r)
add(J4,'pgvector in Supabase (the index)','ADOPT','Already offered by our database (version 0.8.0, not switched on). Keeps the vectors next to the news rows, so "same story?" is one query. Switching it on is an additive change.',source='https://github.com/pgvector/pgvector ; https://supabase.com/docs/guides/database/extensions/pgvector',licence='PostgreSQL licence',needs='`create extension vector` (additive)',runs_where='Supabase',cost='storage only: 384 numbers per row is about 1.5 KB')
add(J4,'a local index (FAISS / hnswlib)','NO','A second store to keep in step with the database, on a Mac that is not always on. Not measured.',source='https://github.com/facebookresearch/faiss',licence='MIT',needs='-',runs_where=MAC,cost='nothing')
J5='5 · named-entity / ticker linking (which company is this about)'
for r in E['ticker_linking']['results']:
    v=('ADOPT as the first pass','Free, instant, and it finds the passages for job 2. On its own it is blunt: 7 of 12 wrong tags caught, 15 good rows rejected.') if 'plain' in r['method'] else ('NO','Costs 9 ms a row and rejects more good rows (18) than plain matching.') if 'spaCy' in r['method'] else ('TRY as the checker','Best of the three: 10 of 12 wrong tags caught, 11 good rows rejected, 55 ms a row on CPU. Use its answer to down-weight a row, not delete it.')
    add(J5,r['method'],v[0],v[1],source='https://spacy.io/models/en' if 'spaCy' in r['method'] else HF+'urchade/gliner_medium-v2.1 ; https://arxiv.org/abs/2311.08526' if 'GLiNER' in r['method'] else 'company_profile (544 names) in our database',licence='MIT' if 'spaCy' in r['method'] else 'Apache-2.0' if 'GLiNER' in r['method'] else 'ours',needs='CPU',runs_where=FLYCPU,cost='cents',measured=r)
add(J5,'FinNER models','NO','Hobby uploads: the most used has 269 downloads.',source='Hugging Face model search "FinNER", 5 Oct 2026',licence='-',needs='-',runs_where='-',cost='-')
J6='6 · time-series / anomaly (the scintillas detector)'
for r in E['anomaly']['results']:
    m=r['method']
    v=('KEEP','It flags 5.8% of name-days — what the rules file intends (about one day in twenty). Nothing public beat it on this test.') if m.startswith('ours') else ('TRY as a second, rarer tier','Half as many flags (2.7%), and the day after one of its flags is 1.31 times a normal day against 1.11 for ours: fewer, sharper scintillas. It is ten lines of arithmetic, not a model.') if m.startswith('robust') else ('NO','Same flag rate and same follow-through as ours (1.11), but only 73% the same flags: a change with no gain.') if m.startswith('EWMA') else ('NO as shipped','Out of the box it flags 44% of name-days. It is built for many-feature streams, not one number a day.')
    add(J6,m,v[0],v[1],source='supabase/functions/scintillas-detect + data/scintilla-rules.json' if m.startswith('ours') else 'Hampel filter / median absolute deviation (Leys et al. 2013, https://doi.org/10.1016/j.jesp.2013.03.013)' if m.startswith('robust') else 'RiskMetrics Technical Document (1996); https://github.com/bashtage/arch' if m.startswith('EWMA') else 'https://github.com/online-ml/river ; https://arxiv.org/abs/2012.04740',licence='ours' if m.startswith('ours') else 'BSD-3' if 'river' in m else '-',needs='nothing',runs_where='Supabase edge function (today)',cost='nothing',measured=r)
add(J6,'Prophet','NO','Built for series with trend and seasons (sales, traffic). Daily price moves have neither; it would fit a flat line and flag on the same spread we already use. Not run.',source='https://github.com/facebook/prophet ; Taylor & Letham (2018), https://doi.org/10.1080/00031305.2017.1380080',licence='MIT',needs='CPU, compiled Stan',runs_where='-',cost='-')
add(J6,'Kats','NO','Prophet-based detectors with heavy, old dependencies and no recent release on PyPI. Not run.',source='https://github.com/facebookresearch/Kats',licence='MIT',needs='-',runs_where='-',cost='-')
add(J6,'tsfresh','NO','It turns a series into hundreds of features for a later model; it is not a detector. Not run.',source='https://github.com/blue-yonder/tsfresh',licence='MIT',needs='-',runs_where='-',cost='-')
J7='7 · where it runs'
add(J7,'MacBook, Metal, MLX (mlx-lm, mlx-whisper)','ADOPT for instruct models and speech','Every 7 to 8 B model loaded in 3 s and used 5 to 7 GB of the 36 GB; a post takes 0.2 s, a whole transcript 2 s, an hour of video under a minute. Nothing to pay. Limit: it only runs while the MacBook is awake.',source='https://github.com/ml-explore/mlx-lm',licence='MIT',needs='this MacBook (Apple M5 Max, 36 GB)',runs_where=MAC,cost='nothing')
add(J7,'Ollama / llama.cpp on the Mac','TRY (not installed, not timed)','Same models as GGUF files behind a local server; useful if several jobs must share one loaded model. Installing Ollama is a system install, which this run was not allowed to do.',source='https://github.com/ollama/ollama ; https://github.com/ggml-org/llama.cpp',licence='MIT',needs='a system install',runs_where=MAC,cost='nothing')
add(J7,'Fly CPU machine (no GPU)','ADOPT for the small classifiers and embeddings','What fits: ModernFinBERT, bge-small, GLiNER, faster-whisper small — all under 2 GB. What does not: any 7 B instruct model at useful speed. Speeds on Fly are estimates; no machine was started.',source=E['fly']['source'],licence='-',needs='shared-cpu-2x 2 GB or performance-2x 4 GB',runs_where=FLYCPU,cost='13.39 dollars a month (shared-cpu-2x 2 GB) if left on; billed by the second, so a job that runs 10 minutes a day costs cents a month')
add(J7,'Fly GPU machine','NO — not on offer','`fly platform vm-sizes` lists no GPU size and Fly\'s GPU pages now redirect to its post "We Were Wrong About GPUs". There is no price per hour and no cold start to quote.',source='https://fly.io/blog/wrong-about-gpu/ ; `fly platform vm-sizes` on 5 Oct 2026',licence='-',needs='-',runs_where='-',cost='-')
json.dump({'schema':'scintilla.m1.models.v1','generated_utc':'2026-10-05','style':'after deliverables/20261003/q2a-rules/adopt.json: one row per candidate, a verdict, the reason, the source','rule':'Open-source only, run on our own machines or free; no paid model API was called.','verdict_counts':{v:sum(1 for r in rows if r['verdict'].split(' ')[0]==v) for v in ['ADOPT','TRY','NO','KEEP','REPLACE']},'caveat':'Accuracies come from small hand-labelled sets by one labeller (100 X posts, 100 news rows, 20 videos). Read gaps under about 10 points (20 for videos) as ties.','rows':rows},open(D+'/models.json','w'),ensure_ascii=False,indent=1)
print(len(rows),'rows')
