# Writes the side files of the M1 review from the measured scratch results. Usage: python3 build_side_files.py <scratch> <deliverable dir>
import json,sys
S,D=sys.argv[1],sys.argv[2]
L=lambda n: json.load(open(S+'/data/'+n))
json.dump({'schema':'scintilla.m1.extras.v1','measured_utc':'2026-10-05','machine':'MacBook Pro, Apple M5 Max, 36 GB',
 'embeddings':{'test':'500 real reposts from the X feed: the cut-off "RT @x: …" text (first 110 characters) must find its full original among 5,500 posts. Speed on 3,000 real news headlines (CPU, 4 threads, re-timed in a clean process; Metal).','vector_index':'pgvector 0.8.0 is offered by our Supabase project and not switched on (pg_available_extensions). Switching it on is an additive change.','results':L('embed_test.json'),'note':'gte-base and gte-modernbert were unexpectedly slow on CPU here (about 30 headlines a second, twice) although they are the same size as e5-base; on Metal they are fast. nomic-embed-text-v1.5 was not run: it needs trust_remote_code (it executes code from the model repository).'},
 'ticker_linking':{'test':'the 100 hand-flagged news rows: 12 are filed under a ticker the story is not about (examples: TGT on "Target Generation", STX on a TJX story, HD on a Devon Energy story, KO on Coca-Cola Europacific Partners, DOW on the Dow Jones index).','results':L('ner_test.json'),'note':'Several "good rows wrongly rejected" are rows whose stored snippet never names the company (quote-list pages, "2 AI stocks" teasers, oil stories filed under USO), so the flag should mark a row for a lower weight, not delete it.'},
 'anomaly':{'test':'89 names, the last 250 daily moves each, daily closes from our chart service (read-only). "next_day_move_vs_normal" = the average size of the day after a flag, divided by the average day: above 1 means the flag marked a name that kept moving.','what_the_rules_file_intends':'data/scintilla-rules.json: 2x the usual day is "about one day in twenty" = 5% of days.',**L('anomaly_test.json')},
 'hugging_face_searches':{'longformer financial':'1 model, 125 downloads (SeanD103/Longformer_for_financial_sentiment_analysis)','bigbird financial / finance':'0 models','FinNER':'5 models, the most used has 269 downloads'},
 'fly':{'gpu':'Not on offer. `fly platform vm-sizes` lists only shared-cpu-1x…8x and performance-1x…16x; fly.io/docs/gpus now redirects to the blog post "We Were Wrong About GPUs" (https://fly.io/blog/wrong-about-gpu/); the pricing page lists no GPU price.','cpu_prices_from_pricing_page':{'shared-cpu-1x 1GB':'6.70 dollars/month','shared-cpu-2x 2GB':'13.39 dollars/month (about 0.019 dollars/hour)','performance-1x 2GB':'33.00 dollars/month','performance-2x 4GB':'66.00 dollars/month (about 0.09 dollars/hour)','extra RAM':'6.00 dollars per GB per month','billing':'by the second while running; a stopped machine costs 0.15 dollars per GB of disk per month'},'source':'https://fly.io/docs/about/pricing/ read 5 Oct 2026','not_measured':'No Fly machine was started in this run: the only existing app that could host one copies the provider keys into the machine, and installing Python packages next to those keys is a risk not worth a timing number. Fly CPU speeds below are estimates from the Mac CPU timings (a Fly core taken as 2.5 to 4 times slower than an M5 Max core).'}},
 open(D+'/bakeoff/extras.json','w'),indent=1)
