"""Write deliverables/20260928/stats-3/STATS-3.html from the six data files, in plain words. Every number on the page is
read from data/q*.json; nothing is typed in by hand. Charts are the PNGs the studies saved in charts/."""
import os, json, html
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.abspath(os.path.join(HERE, "../../..")); DIR = os.path.join(ROOT, "deliverables/20260928/stats-3")
J = {k: json.load(open(os.path.join(DIR, "data", k + ".json"))) for k in ("q1", "q2", "q3", "q4", "q5", "q6")}
Q1, Q2, Q3, Q4, Q5, Q6 = (J[k] for k in ("q1", "q2", "q3", "q4", "q5", "q6"))

def n1(x, sign=False): return "—" if x is None else (f"{x:+.1f}" if sign else f"{x:.1f}")
def n2(x, sign=False): return "—" if x is None else (f"{x:+.2f}" if sign else f"{x:.2f}")
def n0(x, sign=False): return "—" if x is None else (f"{x:+.0f}" if sign else f"{x:.0f}")
def pc(x): return "—" if x is None else f"{x:.1f}%"
def ordn(x):
    if x is None: return "—"
    n = int(round(x)); suf = "th" if 10 <= n % 100 <= 20 else {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th"); return f"{n}{suf}"
def rng(lo, hi, f=n1): return f'<span class="q">{f(lo)} to {f(hi)}</span>' if lo is not None and hi is not None else ""
def word(w): return f'<b class="w {(w or "").replace("-", "").replace(" ", "")}">{html.escape(w or "no data")}</b>'
def cls(v, base=0): return "up" if v is not None and v > base else "dn" if v is not None and v < base else ""
def fig(name, cap=None): return f'<figure><img src="charts/{name}" alt="{name}" loading="lazy"><figcaption><a href="charts/{name}">charts/{name}</a>{(" · " + cap) if cap else ""}</figcaption></figure>'
def tiles(items): return '<div class="three">' + "".join(f"<div><b>{html.escape(k)}</b><span>{v}</span><i>{i}</i></div>" for k, v, i in items) + "</div>"
def table(head, rows): return '<div class="scroll"><table><tr>' + "".join(f"<th>{h}</th>" for h in head) + "</tr>" + "".join("<tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>" for r in rows) + "</table></div>"

# ---------------------------------------------------------------- Q1
pb = {s["name"]: s for s in Q1["pullback"]}; allpb = pb["all (2007→)"]; G = Q1["gridTercile"]; cells = {(c["trend"], c["momentum"]): c for c in G["cells"]}
byType = {b["type"]: b for b in Q1["byType"]}; shift = {s["type"]: s for s in Q1["shiftByType"]}; idx = Q1["indexToday"]
idxRedder = sum(1 for r in idx if r["shift"] < -0.2); idxN = len(idx); spy = next(r for r in idx if r["sym"] == "SPY")
ww = cells[("weak", "weak")]; ss = cells[("strong", "strong")]; sw = cells[("strong", "weak")]
stockTypes = [t for t in Q1["byType"] if "cap" in t["type"]]; rsiW_idx = byType["index fund"]["rsi_width"]; rsiW_stock = byType["large cap (10–200bn)"]["rsi_width"]
q1_lead = (f"<b>The Geiger's own scale does not run narrower for index funds.</b> The composite's 5th–95th band is about {n2(byType['index fund']['width'])} wide for index funds and {n2(byType['large cap (10–200bn)']['width'])} for large caps, because the trend family saturates at ±1 for everything. "
    f"What runs narrower is RSI ({n1(rsiW_idx)} points for index funds against {n1(rsiW_stock)} for large caps), which sits inside the momentum family. Scored against its own history, {idxRedder} of {idxN} index funds would read redder today by more than 0.2, and SPY would read less green ({n2(spy['g'])} printed, {n2(spy['own_scale'])} on its own scale, the {ordn(spy['g_pct'])} percentile). "
    f"Alan's pullback cell (strong trend + weak momentum) is rare ({pc(sw['share'])} of stock-days) and carried no edge against SPY pooled ({n2(allpb['x63']['med'], True)} points over 63 sessions, range {n2(allpb['x63']['lo'])} to {n2(allpb['x63']['hi'])}); in a falling market it was worse ({n2(pb['SPY below its 200-day']['x63']['med'], True)}, {pb['SPY below its 200-day']['x63']['word']}). "
    f"The cell that did carry an edge was the opposite corner, weak trend + weak momentum ({n2(ww['x63']['med'], True)} points, {ww['x63']['word']}), and the composite ladder slopes the same way: the lower the rung, the better the next quarter (section 1).")
q1_html = f"""
<h2 id="q1">1 · The Geiger as a statistic</h2>
<div class="ask">"Measure with the Geiger itself, composite and components; security type and market-cap tranches; screen by Geiger COMPONENTS: strong trend + weak momentum, not a weak composite; index RSIs behave differently — should the Geiger account for it?"</div>
<p><b>What we measured.</b> The Hub's own Geiger maths (the per-rung fan-order trend and the RSI/Williams momentum, Alan's saved Equalizer weights) replayed over every daily history the chart API serves: {Q1['names']} names, the 1d, 3d and 1w rungs. The intraday rungs (3h to 12h) cannot be rebuilt from daily bars, so this is the daily part of the Geiger; the sector-rotation lane checked this replay against the live /geiger (Pearson 0.99). For each name: the composite and each family as an expanding own-history percentile (1..100, prior days only). Forward outcomes pooled over single companies, {Q1['stockRows']:,} name-days on {Q1['stockDates']:,} dates from {Q1['from']}: the next 63 sessions against SPY, the worst fall inside them. The unit that is resampled is the date, in blocks of 63, because names move together. Stocks are typed by today's market cap (FMP company profile): a survivor's view, and for the small-cap tranche the opposite, since a name is small today mostly because it fell there.</p>
{tiles([("NAMES REPLAYED", str(Q1['names']), "1d · 3d · 1w rungs, Alan's weights"), ("PULLBACK CELL", n2(allpb['x63']['med'], True) + " pts", f"next 63 vs SPY · any day {n2(allpb['x63_base']['med'], True)} · {pc(sw['share'])} of days"), ("WEAK + WEAK", n2(ww['x63']['med'], True) + " pts", f"{rng(ww['x63']['lo'], ww['x63']['hi'], n2)} · {ww['x63']['word']}"), ("INDEX FUNDS REDDER", f"{idxRedder} of {idxN}", "on their own-history scale, by more than 0.2")])}
<h3>1a · How wide each type's Geiger runs, and where each sits today</h3>
{fig('q1-width-by-type.png')}
{table(["type (members)", "composite 5th · median · 95th", "width (5th–95th) · member spread", "RSI 5th · 95th · width", "today: composite · own pct · trend · momentum"], [[f"{b['type']} ({b['n']})", f"{n2(b['g_p5'])} · {n2(b['g_p50'])} · {n2(b['g_p95'])}", f"<b>{n2(b['width'])}</b> {rng(b['width_lo'], b['width_hi'], n2)}", f"{n1(b['rsi_p5'])} · {n1(b['rsi_p95'])} · <b>{n1(b['rsi_width'])}</b>", f"<span class='{cls(b['today_g'])}'>{n2(b['today_g'], True)}</span> · {ordn(b['today_g_pct'])} · {n2(b['today_tr'], True)} · {n2(b['today_mo'], True)}"] for b in Q1['byType']])}
<p><b>How to read it.</b> The composite's width is the same for every type within a few hundredths: the trend family is a count of fan pairs in order, which reaches ±1 for an index as easily as for a stock. The RSI band is what differs, and only by a few points ({n1(rsiW_idx)} for index funds, {n1(byType['commodity fund']['rsi_width'])} for commodity funds, about {n1(rsiW_stock)} for stocks). So the answer to "index RSIs run in a narrower range" is: yes, a little, and the Geiger already halves that difference by mixing RSI with Williams %R inside the momentum family.</p>
<h3>1b · Would the index funds read redder today on their own scale?</h3>
{fig('q1-index-own-scale.png')}
{table(["fund", "Geiger today (daily rungs)", "own-history percentile", "on its own scale (2p−1)", "shift", "trend · momentum", "RSI today", "composite 5th · 95th"], [[r['sym'], f"<span class='{cls(r['g'])}'>{n2(r['g'], True)}</span>", f"{ordn(r['g_pct'])}", n2(r['own_scale'], True), f"<span class='{cls(r['shift'])}'>{n2(r['shift'], True)}</span>", f"{n2(r['tr'], True)} · {n2(r['mo'], True)}", n1(r['rsi']), f"{n2(r['g_p5'])} · {n2(r['g_p95'])}"] for r in idx])}
<p><b>How to read it.</b> Two things happen at once. The weak funds (China, mid caps, small caps, equal weight, the Dow) would read redder, because a mildly negative bar is a low reading for a fund that spends most of its life above zero. The strong US funds (SPY, QQQ, VTI) would read <i>less</i> green, because {n2(spy['g'])} is only the {ordn(spy['g_pct'])} percentile of SPY's own composite. Across all {len(Q1['today'])} names the median shift is {n2(shift['large cap (10–200bn)']['shift_med'], True)} for large caps and {n2(shift['index fund']['shift_med'], True)} for index funds: the own-history scale is redder for almost everything, because the composite's history is skewed upward (its median sits at {n2(byType['index fund']['g_p50'], True)} for index funds, not at zero).</p>
<p><b>Proposal, not a change.</b> Keep the Geiger as it is. Add a second, quiet readout beside the bar: the composite's own-history percentile ("{ordn(spy['g_pct'])} of its own history"), and a type ladder (index fund / sector fund / mega cap … / small cap) for the RSI floors, as the statistician-2 page already builds. The bar stays comparable across names; the percentile tells you whether a reading is unusual <i>for that name</i>. Do not rescale the bar by type: the width table above shows the scale is already the same.</p>
<h3>1c · Forward outcomes by family state: Alan's pullback cell</h3>
{fig('q1-grid-tercile.png')}{fig('q1-grid-fifth.png')}
{table(["TREND tercile", "MOMENTUM tercile", "share of stock-days", "next 63 vs SPY, points · 90% range", "status (9 cells)", "next 63, % · share up", "worst fall in 63 · status"], [[c['trend'], c['momentum'], pc(c['share']), f"<b class='{cls(c['x63']['med'], G['base']['x63']['med'])}'>{n2(c['x63']['med'], True)}</b> {rng(c['x63']['lo'], c['x63']['hi'], n2)}", word(c['x63']['word']), f"{n2(c['f63']['med'], True)} · {pc(c['f63']['up'])}", f"{n1(c['dd63']['med'])} · {word(c['dd63']['word'])}"] for c in G['cells']] + [["any day", "", "100%", f"{n2(G['base']['x63']['med'], True)}", "", f"{n2(G['base']['f63']['med'], True)} · {pc(G['base']['f63']['up'])}", n1(G['base']['dd63']['med'])]])}
{fig('q1-pullback-splits.png')}
{table(["the cell, and its alternatives", "dates", "next 63 vs SPY, points · 90% range", "the split's own any-day", "status (8 tests)", "next 63, % · share up", "any day"], [[s['name'], f"{s['x63']['n_dates']:,}", f"<b class='{cls(s['x63']['med'], s['x63_base']['med'])}'>{n2(s['x63']['med'], True)}</b> {rng(s['x63']['lo'], s['x63']['hi'], n2)}", n2(s['x63_base']['med'], True), word(s['x63']['word']), f"{n2(s['f63']['med'], True)} · {pc(s['f63']['up'])}", f"{n2(s['f63_base']['med'], True)} · {pc(s['f63_base']['up'])}"] for s in Q1['pullback']])}
<p><b>How to read it.</b> Strong trend with weak momentum is the corner Alan described, and it is a small corner: the two families move together, so only about one stock-day in a hundred sits there. Pooled, it did not beat the stocks' own any-day ({n2(allpb['x63']['med'], True)} against {n2(allpb['x63_base']['med'], True)}); it leaned up in the first half of the record and down in the second, and when SPY was below its 200-day it was clearly worse ({n2(pb['SPY below its 200-day']['x63']['med'], True)} points, {pb['SPY below its 200-day']['x63']['word']}): a strong-trend name whose momentum breaks in a falling market is a name whose trend is about to break. The edge sits in the opposite corner, weak trend + weak momentum ({n2(ww['x63']['med'], True)}, {ww['x63']['word']}), which is mean reversion in the beaten names, and it is the same thing the composite ladder shows: the lowest rungs of the composite had the best next quarter, the highest the worst. That ladder holds for stocks and, more weakly, for index funds (section 1e). None of this is a buy rule: a {n2(ww['x63']['med'])}-point median edge over a quarter is small next to the {n1(ww['dd63']['med'])}% worst fall those same names carried inside the quarter. On the fifths grid (the bar's own units) the brightest corner, trend 0.6 to 1 with momentum −1 to −0.6, is {next(c for c in Q1['gridFifth']['cells'] if c['trend'] == 4 and c['momentum'] == 0)['x63']['n_dates']} dates: a list, not a rate; the family maths almost never let a fully ordered fan sit with a floored momentum.</p>
<h3>1d · By security type and market-cap tranche</h3>
{fig('q1-pullback-by-type.png')}
{table(["type", "names", "cell share of days", "cell: next 63 vs SPY · 90% range", "the type's any-day vs SPY", "status (9 types)", "cell: next 63 %", "type's any-day %", "composite ladder: rank link (deciles → next 63)"], [[b['type'], b['names'], pc(b['cell_share']), f"<b class='{cls(b['x63']['med'], b['x63_base']['med'])}'>{n2(b['x63']['med'], True)}</b> {rng(b['x63']['lo'], b['x63']['hi'], n2)}", n2(b['x63_base']['med'], True), word(b['x63']['word']), n2(b['f63']['med'], True), n2(b['f63_base']['med'], True), n2(b['ladder_rho'])] for b in Q1['byTypeCell']])}
<p><b>How to read it.</b> The tranche table is where today's-cap typing bites. Mega caps' any-day is {n2(next(b for b in Q1['byTypeCell'] if b['type'].startswith('mega'))['x63_base']['med'], True)} points over SPY (they are the names that became mega caps), small caps' is {n2(next(b for b in Q1['byTypeCell'] if b['type'].startswith('small'))['x63_base']['med'], True)} (they are the names that shrank). Inside each type the pullback cell tracks the type's own any-day: no tranche turns the cell into an edge. The composite ladder's slope is negative (low rungs, better quarter) for every stock tranche with enough names and for index funds; it is flat or positive only for the bond funds and the few mid caps. Tranches by point-in-time cap are a follow-up (F1).</p>
<h3>1e · The composite ladder, 1 to 100</h3>
{fig('q1-ladder.png')}
<p>Rungs of 5 over the composite's own percentile: for single companies the next-63 median runs from {n2(Q1['ladderStocks'][0]['med'])}% at the bottom rung to {n2(Q1['ladderStocks'][-1]['med'])}% at the top (any day {n2(G['base']['f63']['med'])}%); for index funds from {n2(Q1['ladderIndex'][0]['med'])}% to {n2(Q1['ladderIndex'][-1]['med'])}%. The slope is the finding; no single rung is, and the bands overlap along most of the ladder.</p>
"""

# ---------------------------------------------------------------- Q2
C10 = Q2["combos"]["low_10"]["rows"]; C5 = Q2["combos"]["low_5"]["rows"]; C20 = Q2["combos"]["low_20"]["rows"]; H10 = Q2["combos"]["high_10"]["rows"]
def bysig(rows, *names): return next((r for r in rows if sorted(r["signals"]) == sorted(names)), None)
singles10 = [r for r in C10 if r["k"] == 1]; rsi10 = bysig(C10, "RSI (low = fear)"); vix10 = bysig(C10, "VIX level"); pcc10 = bysig(C10, "put/call 5-day"); vixrsi5 = bysig(C5, "VIX level", "RSI (low = fear)"); fg10 = bysig(C10, "fear & greed proxy (low = fear)")
best10 = sorted([r for r in C10 if "fwd_21" in r], key=lambda r: -(r["fwd_21"]["med"] or -99)); lp10 = [r for r in C10 if r.get("fwd_21", {}).get("word") == "luck-proof"]; lpH = [r for r in H10 if r.get("fwd_21", {}).get("word") in ("luck-proof", "leaning")]
PV = Q2["paths"]["VIX level top 10%"]; PP = Q2["paths"]["put/call 5-day top 10%"]; PV50 = Q2["paths"]["VIX over its 50-day top 10%"]; PR = Q2["paths"]["RSI bottom 10%"]
def sig_short(s): return s.split(" (")[0].split(":")[0]
q2_lead = (f"<b>RSI's own percentile is the strongest single fear gauge, and confluence adds size, not certainty.</b> Alone, SPY's RSI in its bottom 10% gave {n2(rsi10['fwd_21']['med'], True)}% over the next 21 sessions (any day {n2(Q2['base']['fwd_21']['p50'], True)}%; {rsi10['fwd_21']['word']}) and a confirmed swing low within reach {pc(rsi10['hit']['rate'])} of the time (any day {pc(Q2['base']['nearLow'])}). "
    f"The VIX level alone gave a similar median ({n2(vix10['fwd_21']['med'], True)}%) with a range three times wider, because it fires inside crashes ({pc(PV['context']['share_deep'])} of its firing days sat more than 10% under the high). "
    f"Of {Q2['combos']['low_10']['tests']} combinations at the top-10% line, {len(lp10)} are luck-proof, all of them containing RSI or breadth or the fear proxy; the best pair adds about {n2(best10[0].get('gain_over_best_single_21') or 0)} points to its better single. At the top-5% line VIX level + RSI gave {n2(vixrsi5['fwd_21']['med'], True)}% ({vixrsi5['runs']} visits, {vixrsi5['fwd_21']['word']}). "
    f"At tops nothing works: no greed combination clears the check over 21 sessions. Alan's framing holds on the tape: VIX extremes fire in the deep declines (median {n1(PV['context']['dd_from_high_med'])}% under the high) and put/call extremes in the shallow-to-middle ones (median {n1(PP['context']['dd_from_high_med'])}%), and in bar-hours put/call's edge is significant from about 20 bar-hours on while the VIX level's is only clear at 13–20 bar-hours and then too wide to call (section 2).")
def combo_rows(rows, top=14):
    rows = sorted([r for r in rows if "fwd_21" in r], key=lambda r: -(r["fwd_21"]["med"] or -99))[:top]
    return table(["signals on at once", "days · visits · years", "SPY next 21, median · 90% range", "status", "next 63", "further fall in 21", "a swing low within −5…+15 sessions", "gain over its best single (21)"], [[" + ".join(sig_short(s) for s in r["signals"]), f"{r['n']} · {r['runs']} · {r['years']}", f"<b>{n2(r['fwd_21']['med'], True)}</b> {rng(r['fwd_21']['lo'], r['fwd_21']['hi'], n2)}", word(r['fwd_21']['word']), f"{n2(r['fwd_63']['med'], True)} {word(r['fwd_63']['word'])}", n1(r['dd_21']['med']), f"{pc(r['hit']['rate'])} {word(r['hit'].get('word'))}", n2(r.get("gain_over_best_single_21"), True) if r["k"] > 1 else "—"] for r in rows])
q2_html = f"""
<h2 id="q2">2 · Confluence: fear &amp; greed, VIX, put/call, RSI, breadth</h2>
<div class="ask">"Confluence (fear &amp; greed + VIX + put/call + RSI + VIX moving averages/clouds); VIX = slow/deep pullbacks, put/call = fast/short pullbacks."</div>
<p><b>What we measured.</b> Seven fear gauges on SPY's daily bars from {Q2['from']} (the first day every gauge exists; Cboe put/call starts then): the VIX level, the VIX against its own 50-day, the VIX cloud (above both its 50- and 200-day averages, or below both), the 5-session average of the total put/call, SPY's RSI, the share of served names above their 50-day, and a fear &amp; greed proxy built like the public one from seven parts (momentum vs the 125-day, 52-week highs minus lows, 20-day advances, put/call, VIX vs its 50-day, stocks vs bonds over 20 days, junk vs investment-grade bonds over 20 days), each part its own expanding percentile, averaged. Every gauge is read as its own-history percentile with no lookahead. Outcomes: SPY's next 5, 21 and 63 sessions, the further fall inside 21, and whether a confirmed swing low (10-bar pivot, 3% or deeper) sat within 5 sessions before to 15 after. Every subset of one, two or three gauges "on" at once was tested at three lines (top 5, 10 and 20% of own history), fear side and greed side: {Q2['combos']['low_10']['tests']} combinations per line, false-discovery corrected together. Ranges come from resampling runs of days; the honest count is visits (separate episodes), printed beside every n.</p>
{tiles([("RSI ALONE, TOP 10%", n2(rsi10['fwd_21']['med'], True) + "%", f"next 21 · any day {n2(Q2['base']['fwd_21']['p50'], True)}% · {rsi10['runs']} visits · {rsi10['fwd_21']['word']}"), ("VIX LEVEL ALONE", n2(vix10['fwd_21']['med'], True) + "%", f"{rng(vix10['fwd_21']['lo'], vix10['fwd_21']['hi'], n2)} · {vix10['fwd_21']['word']}"), ("LUCK-PROOF COMBOS", f"{len(lp10)} of {Q2['combos']['low_10']['tests']}", "top-10% line, next 21 sessions"), ("AT TOPS", f"{len(lpH)}", "greed combinations that clear the check")])}
<h3>2a · Each gauge alone, every rung</h3>
{fig('q2-singles-ladder.png')}
{table(["gauge (top 10% of own history = most fear)", "days · visits", "SPY next 21, median · 90% range", "status", "further fall in 21", "a swing low nearby", "today (own pct)"], [[sig_short(r['signals'][0]), f"{r['n']} · {r['runs']}", f"<b>{n2(r['fwd_21']['med'], True)}</b> {rng(r['fwd_21']['lo'], r['fwd_21']['hi'], n2)}", word(r['fwd_21']['word']), n1(r['dd_21']['med']), f"{pc(r['hit']['rate'])} (any day {pc(Q2['base']['nearLow'])})", n0(Q2['today'].get(r['signals'][0]))] for r in singles10])}
<p><b>How to read it.</b> Every gauge's ladder rises toward the fear end: more fear, better next month, and a higher chance a swing low is near. The gauges that are luck-proof on their own are the ones read against SPY's own tape (RSI, breadth, the proxy) and put/call; the VIX level is not, because its extreme days are the 2008, 2020 and 2022 crashes, a handful of visits with outcomes from {n2(vix10['fwd_21']['lo'], True)} to {n2(vix10['fwd_21']['hi'], True)}% inside a month. Today every gauge sits in the calm half (VIX at its {ordn(Q2['today']['VIX level'])} percentile, put/call at its {ordn(Q2['today']['put/call 5-day'])}, RSI middle); breadth is the exception: the share of names above their 50-day is {n1(Q2['today']['a50'])}%, the {ordn(Q2['today']['breadth: share above 50-day (low = fear)'])} percentile of fear.</p>
<h3>2b · Combinations at the fear end</h3>
{fig('q2-combos-low10.png')}
<h4>Top 10% of own history</h4>{combo_rows(C10)}
<h4>Top 5%</h4>{combo_rows(C5, 10)}
<h4>Top 20%</h4>{combo_rows(C20, 10)}
<p><b>How to read it.</b> "Gain over its best single" is the honest test of confluence: a pair earns its place only if it beats the better of its two parts. At the 10% line the best pairs add 0.1 to 0.4 points to their best single; that is size, and it comes with fewer days. Their ranges do not narrow: confluence picks the same fearful weeks with a second name. The one combination that stands apart is at the 5% line, VIX level + RSI, {n2(vixrsi5['fwd_21']['med'], True)}% over 21 sessions and {n2(vixrsi5['fwd_63']['med'], True)}% over 63, both luck-proof, from {vixrsi5['runs']} visits in {vixrsi5['years']} years: a real crash with the tape oversold. The VIX cloud adds nothing anywhere: "above both averages" is on {bysig(C10, 'VIX cloud: above both averages')['n']} days of the record and every pair that includes it matches the same pair without it.</p>
<h3>2c · At tops</h3>
{combo_rows(H10, 8)}
<p>Greed does not time tops on this record: the best greed combination over 21 sessions is still an ordinary month, and none clears the check (a few clear it over 63 sessions, in the wrong direction: greed was followed by a better quarter, which is the trend). The VIX below both its averages is on {bysig(H10, 'VIX cloud: below both averages')['n']} of the days: it is the normal state of a rising market, not a warning.</p>
<h3>2d · VIX slow and deep, put/call fast and short: the framing on bar-hours</h3>
{fig('q2-bar-hours.png')}{fig('q2-depth-mix.png')}
{table(["gauge at its extreme", "days · visits", "SPY's fall from its high on those days (median · lower quartile)", "share of firings more than 10% under the high", "further fall next 21 · 63", "a run lasts (sessions)", "swing low nearby", "next 21 (median · p vs any day)"], [[k, f"{v['context']['n']} · {v['context']['visits']}", f"{n1(v['context']['dd_from_high_med'])}% · {n1(v['context']['dd_from_high_p25'])}%", pc(v['context']['share_deep']), f"{n1(v['context']['further_fall_21_med'])} · {n1(v['context']['further_fall_63_med'])}", n1(v['context']['run_med']), pc(v['context']['hit_low']), f"{n2(next(p for p in v['path'] if p['h'] == 21)['med'], True)} · {n2(next(p for p in v['path'] if p['h'] == 21)['p'])}"] for k, v in Q2['paths'].items()])}
{table(["gauge", "6.5 h (1 session)", "13 h", "20 h", "32 h (1 week)", "65 h", "137 h (1 month)", "273 h", "410 h (1 quarter)"], [[k] + [f"<span class='{'up' if p['p'] is not None and p['p'] <= 0.1 else ''}'>{n2(p['med'], True)}</span>" for p in v['path']] for k, v in Q2['paths'].items()] + [["any day"] + [n2(p['base'], True) for p in PV['path']]])}
<p><b>How to read it.</b> Green in the bar-hours table means the median clears any day at the 10% line. The put/call extreme's edge is present from about 20 bar-hours (3 sessions) and stays through the quarter; the VIX level's is clear only at 13–20 bar-hours (the bounce after a capitulation day) and then the range opens up. The depth mix says why: VIX extremes are almost all deep declines ({pc(PV['context']['share_deep'])} more than 10% under the high; the top-5% VIX is {pc(Q2['paths']['VIX level top 5%']['context']['share_deep'])}), put/call extremes are mostly 5–20% declines, and the VIX against its own 50-day fires in the shallow ones ({pc(PV50['context']['share_deep'])} deep). So the framing is right, with one amendment: the fast gauge is put/call <i>and</i> VIX-over-its-50-day, and the deep gauge is the VIX level, whose extremes come with a further fall of {n1(PV['context']['further_fall_21_med'])}% inside the next month and a wait that the bottoms study measured in months.</p>
<h4>How early each gauge fired inside a decline, by the depth of the low</h4>
{table(["gauge (top 10%)"] + [f"lows of {b['band']} ({b['lows']})" for b in Q2['leads']['RSI bottom 10%']], [[k] + [f"fired in {pc(b['fired'])} · lead {n0(b['lead_med'])} sessions" for b in rows] for k, rows in Q2['leads'].items()])}
<p>Lead = sessions from the gauge's first firing in the decline to the swing low. The put/call and the VIX level fired in fewer than half of the 5–10% declines; RSI's bottom decile fired in {pc(Q2['leads']['RSI bottom 10%'][1]['fired'])} of them, about {n0(Q2['leads']['RSI bottom 10%'][1]['lead_med'])} sessions early. For the tranche buyer that is the practical reading: RSI percentile is the trigger, put/call is the confirmation in the middle-sized declines, the VIX level says only that a decline is deep.</p>
"""

# ---------------------------------------------------------------- Q3
F = {f["key"]: f for f in Q3["features"]}; WF = Q3["walkForward"]; L = Q3["leadersState"]; YR = Q3["yearReturns"]; byT3 = {r["value"]: r for r in Q3["byType"]}; byM = {r["value"]: r for r in Q3["byMarket"]}
wf2 = WF[1]; wf2rows = {r["flags"]: r for r in wf2["rows"]}; flagsN = len(Q3["flags"])
q3_lead = (f"<b>Below a falling 200-day with the 50 under it, one entry in six fell another 33% within a year, and the one-in-ten line was {n0(Q3['bad_line'])}%.</b> {Q3['n']:,} entries, {Q3['names']} single companies, {Q3['from'][:4]}–{Q3['to'][:4]}; within 126 sessions the 33% line was crossed by {pc(Q3['share_33_126'])}, which is Alan's one in ten. "
    f"What marked the bad decile at entry, luck-proof: a wide usual day (the strongest, {n1(F['usual']['bad_med'])}% against {n1(F['usual']['rest_med'])}%), a deep fall from the 52-week high already ({n0(F['dd_from_high']['bad_med'])}% against {n0(F['dd_from_high']['rest_med'])}%), a steeper 200-day slope, a worse prior year, and a market that was itself falling with the VIX high. RSI, volume and days already below did not mark it. "
    f"Seven flags chosen on 2004–2015 and read on 2016 →: with no flag {pc(wf2rows[0]['share_33'])} fell 33%+, with four or five flags about {pc(wf2rows[4]['share_33'])}. Being in the state did not disqualify a name from leading that year: {pc(L['winner_given_state']['est'])} of names in the state on 1 January were top-decile winners that year (any name {pc(L['winner_base']['est'])}); what did predict winning was having won the year before ({pc(L['winner_given_prevWinner']['est'])}). Alan's line holds on the second half: bet on winners; the state does not forbid a name, it widens its tail (section 3).")
q3_html = f"""
<h2 id="q3">3 · Below a falling 200-day with the 50 under it</h2>
<div class="ask">"200-day falling + 50 below: characteristics of the 1-in-10 that fall hard, leaders in those states. Bet on winners, not reversals of losers."</div>
<p><b>What we measured.</b> For every served single company: the state is the close below its 200-day, the 200-day lower than 20 sessions before, and the 50-day below the 200-day. An entry is the first day in the state (a re-entry inside 21 sessions is the same episode). At entry, thirteen characteristics known that day; afterwards, the worst close within 126 and 252 sessions, the next-year return, and whether the 200-day was reclaimed. The bad decile is the worst tenth of the 252-session fall. Each characteristic is judged by the chance a bad entry has the higher value (0.5 = no difference), with a 90% range from resampling entries and a false-discovery check over the thirteen. Then the standard's walk-forward: flags chosen on entries before 2016, counted on entries from 2016. The histories are today's served names, cut at data faults, so the sample is survivors plus this year's admissions: the bad-decile line is if anything too kind.</p>
{tiles([("ENTRIES", f"{Q3['n']:,}", f"{Q3['names']} names · {Q3['from'][:4]}–{Q3['to'][:4]}"), ("ONE IN TEN", f"{n0(Q3['bad_line'])}%", "worst close within 252 sessions, 10th percentile"), ("FELL 33%+", f"{pc(Q3['share_33'])}", f"within a year · {pc(Q3['share_33_126'])} within 126 sessions"), ("MEDIAN", f"{n1(Q3['dd252']['p50'])}%", f"worst fall in a year · next-year return {n1(Q3['f252']['p50'], True)}% · reclaimed the 200-day within a year {pc(Q3['reclaim_share_252'])}")])}
{fig('q3-outcome-hist.png')}
<h3>3a · What marked the one-in-ten at entry</h3>
{fig('q3-features.png')}
{table(["characteristic at entry", "bad decile (median)", "the rest (median)", "chance a bad entry has the higher value · 90% range", "status (13 tests)"], [[f['name'], n2(f['bad_med']), n2(f['rest_med']), f"<b>{n2(f['auc'])}</b> {rng(f['auc_lo'], f['auc_hi'], n2)}", word(f['word'])] for f in Q3['features']])}
<p><b>How to read it.</b> Far from 0.5 is a mark. The names that went on to fall hardest were already the wild ones: a usual day of {n1(F['usual']['bad_med'])}% against {n1(F['usual']['rest_med'])}% (0.71 is a strong mark for a single number), already {n0(F['dd_from_high']['bad_med'])}% off their high, with a 200-day falling twice as fast, and they entered the state while the market itself was {n1(F['spy_dd']['bad_med'])}% off its high with the VIX at its {ordn(F['vix_pct']['bad_med'])} percentile. The oversold measures (RSI percentile, distance from the 50-day, volume) did not separate them, and neither did the time already spent below the 200-day. In words: the one-in-ten is the volatile name in a long fall inside a falling market, not the quiet name that just slipped under its average.</p>
<h3>3b · Flags chosen on the first half, counted on the second</h3>
{fig('q3-flags-walkforward.png')}
{table(["flag (chosen on 2004–2015 entries)", "fires when", "chance measure on the first half"], [[f['name'], f"{'at or above' if f['dir'] == 'high' else 'at or below'} {n2(f['cut'])}", n2(f['auc_h1'])] for f in Q3['flags']])}
{table(["flags at entry"] + [f"{w['half']} (n {w['n']:,})" for w in WF], [[str(k)] + [next((f"{pc(r['share_33'])} fell 33%+ · worst fall {n1(r['dd252_med'])}% {rng(r['lo'], r['hi'])} · next year {n1(r['f252_med'], True)}% · n {r['n']}" for r in w['rows'] if r['flags'] == k), "—") for w in WF] for k in range(flagsN + 1)])}
<p><b>How to read it.</b> On the half where nothing was chosen, the share that fell 33%+ rises from {pc(wf2rows[0]['share_33'])} with no flag to about {pc(wf2rows[4]['share_33'])} with four or five: the flags carry. The dip at six flags is March 2020, when the three market flags (SPY's fall, the VIX, breadth) fired for everything at once and the whole market recovered; the name's own flags (its usual day, its fall from the high, its prior year, its 200-day slope) are the ones to weight. A rule for the scout tier: an entry into the state with three or more of the name's own flags is the avoid list; with none, the state alone is an ordinary drawdown with a {pc(wf2rows[0]['share_33'])} tail.</p>
<h3>3c · By tranche, market state, sector</h3>
{table(["group", "entries", "share in the bad decile · 90% range", "fell 33%+ within a year", "worst fall (median)", "next year (median)"], [[r['value'], r['n'], f"<b class='{cls(r['bad_share'], 10)}'>{pc(r['bad_share'])}</b> {rng(r['lo'], r['hi'])}", pc(r['share_33']), n1(r['dd252_med']), n1(r['f252_med'], True)] for r in Q3['byType'] + Q3['byMarket'] + Q3['bySector']])}
<p>Today's-cap tranches read the way the survivor problem predicts: the names that are small today are the ones that kept falling ({pc(byT3['small cap (<2bn)']['share_33'])} fell 33%+), the mega caps are the ones that did not. The market state is the honest split: entries while SPY was below its own 200-day fell 33%+ in {pc(byM['SPY below its 200-day']['share_33'])} of cases against {pc(byM['SPY above its 200-day']['share_33'])} when SPY was above. Sectors: staples and utilities almost never ({pc(next(r for r in Q3['bySector'] if r['value'] == 'Consumer Defensive')['share_33'])}, {pc(next(r for r in Q3['bySector'] if r['value'] == 'Utilities')['share_33'])}), technology most ({pc(next(r for r in Q3['bySector'] if r['value'] == 'Technology')['share_33'])}).</p>
<h3>3d · Leaders in the state: does it disqualify a name from leading that year?</h3>
{fig('q3-leaders.png')}
{table(["question", "share · 90% range over resampled years", "n"], [["top-decile winner that year, given in the state on 1 January", f"<b>{pc(L['winner_given_state']['est'])}</b> {rng(L['winner_given_state']['lo'], L['winner_given_state']['hi'])}", L['winner_given_state']['n']], ["winner, given not in the state", f"{pc(L['winner_given_notState']['est'])} {rng(L['winner_given_notState']['lo'], L['winner_given_notState']['hi'])}", L['winner_given_notState']['n']], ["winner, any name", f"{pc(L['winner_base']['est'])}", L['winner_base']['n']], ["winner, given a top-decile winner the year before", f"<b>{pc(L['winner_given_prevWinner']['est'])}</b> {rng(L['winner_given_prevWinner']['lo'], L['winner_given_prevWinner']['hi'])}", L['winner_given_prevWinner']['n']], ["winner, given prior-year winner and not in the state", f"{pc(L['winner_given_prevWinner_notState']['est'])} {rng(L['winner_given_prevWinner_notState']['lo'], L['winner_given_prevWinner_notState']['hi'])}", L['winner_given_prevWinner_notState']['n']], ["in the state on 1 January, given a winner that year", f"{pc(L['state_given_winner']['est'])} {rng(L['state_given_winner']['lo'], L['state_given_winner']['hi'])}", L['state_given_winner']['n']], ["in the state on 1 January, any name", f"{pc(L['state_base']['est'])} {rng(L['state_base']['lo'], L['state_base']['hi'])}", L['state_base']['n']], ["top-20-by-cap leader, given in the state", f"{pc(L['leader_given_state']['est'])} {rng(L['leader_given_state']['lo'], L['leader_given_state']['hi'])}", L['leader_given_state']['n']], ["top-20-by-cap leader, any name", f"{pc(L['leader_base']['est'])} {rng(L['leader_base']['lo'], L['leader_base']['hi'])}", L['leader_base']['n']]])}
{table(["calendar-year return, median · 90% range over years", "in the state on 1 Jan", "not in the state", "prior-year winner", "prior-year winner, not in the state", "top-20-by-cap leader", "all names"], [[""] + [f"<b>{n1(YR[k]['est'], True)}%</b> {rng(YR[k]['lo'], YR[k]['hi'])} · n {YR[k]['n']}" for k in ("in state at start", "not in state", "prior-year winner", "prior-year winner, not in state", "leader (top 20 by cap)", "all")]])}
<p><b>How to read it.</b> Two facts sit side by side. Being in the state on 1 January did not lower a name's chance of being a top-decile winner that year ({pc(L['winner_given_state']['est'])} against {pc(L['winner_base']['est'])}; the range clears the base slightly upward, the reversal names), and its median year was not worse. But the year-before winners became winners again at twice the base rate ({pc(L['winner_given_prevWinner']['est'])}, range {pc(L['winner_given_prevWinner']['lo'])} to {pc(L['winner_given_prevWinner']['hi'])}), and the state hardly changes that ({pc(L['winner_given_prevWinner_notState']['est'])} when not in it). The cap leaders (each year's top 20) were in the state less often than other names ({pc(L['leader_given_state']['est'])} against {pc(L['leader_base']['est'])}). So "bet on winners, not reversals of losers" is right about where the repeatable edge is (persistence), and the state's job is the tail: a name in it carries the {pc(Q3['share_33'])} chance of a further third off, which a winner outside it does not.</p>
<h3>3e · Who is in the state today</h3>
<p>{Q3['today']['in_state_now']} served single companies are in the state at the 25 Sep close. Those with five or more of the seven flags: {", ".join(f"{r['sym']} ({n0(r['dist200'])}% under its 200-day, {n0(r['dd_from_high'])}% off its high)" for r in Q3['today']['names'] if r['flags'] >= 5)}.</p>
<details><summary>Every name in the state today, with its flag count</summary>{table(["name", "type", "under the 200-day", "off its 52-week high", "sessions below", "flags of 7"], [[r['sym'], r['type'], pc(r['dist200']), pc(r['dd_from_high']), r['days_below'], r['flags']] for r in Q3['today']['names']])}</details>
"""

# ---------------------------------------------------------------- Q4
R = Q4["relSPY"]; W4 = Q4["why"]; rules = Q4["rules"]; bt = Q4["bowtie"]; lp_rules = [r for r in rules if r["word"] == "luck-proof"]
q4_lead = (f"<b>Leaders trail SPY after a low because the first bounce belongs to the worst fallers, not because leaders fell more.</b> From the confirmation of {Q4['lows']} SPY swing lows ({Q4['from'][:4]}–{Q4['to'][:4]}), the leaders basket trailed SPY by {n2(abs(R['leaders']['63']['est']))} points over 63 sessions (range {n2(R['leaders']['63']['lo'])} to {n2(R['leaders']['63']['hi'])}, p {n2(R['leaders']['63']['p'])}) and was level by 252 ({n2(R['leaders']['252']['est'], True)}). "
    f"They fell as much as SPY into the low (ratio {n2(W4['fall_ratio']['est'])}), so it is not beta. Equal weight and small caps did not beat SPY after lows either ({n2(R['rsp']['63']['est'], True)}, {n2(R['iwm']['63']['est'], True)}); the worst-decile fallers into the low did ({n2(R['laggards']['63']['est'], True)} at 63, {n2(R['laggards']['126']['est'], True)} at 126), which is where the leaders' lag comes from, and which is inflated by survivorship (today's names survived their falls). "
    f"Rules to test, not advice: shifting part of a leaders book to equal weight after a confirmed low gained nothing ({n2(rules[7]['gain_med'], True)} points for 100% for 63 sessions, not shown); shifting a quarter to the worst fallers for a quarter gained {n2(rules[10]['gain_med'], True)} points per low ({pc(rules[10]['win'])} of lows, {rules[10]['word']}), a number to re-test on a point-in-time universe before believing (section 4).")
q4_html = f"""
<h2 id="q4">4 · Leaders trail SPY for a quarter after bottoms</h2>
<div class="ask">"Leaders trail SPY after bottoms — how to use it for portfolio adjustments. The bow tie: how far should it rebalance, which wing moves."</div>
<p><b>What we measured.</b> The leaders basket is each year's top 20 by market cap at the time (the statistician-2 lists, {Q4['today']['leaders_loaded']} names loaded), equal weight, daily rebalanced, from 2007. The lows are SPY's swing lows of 3% or deeper by the 10-bar pivot rule, {Q4['lows']} of them, and every clock starts at the low's confirmation (10 sessions after it), because that is the first day anyone could have known. Against SPY over 21, 63, 126 and 252 sessions: the leaders, equal weight (RSP), small caps (IWM), and a basket of the worst-decile fallers from the top to the low among the served stocks, built on the day of the low. Ranges from resampling lows. Then the rules: from an all-leaders book, at confirmation move x% into a wing for h sessions and back, gain measured against holding; and the bow tie as a fixed leaders/equal-weight mix, rebalanced against never rebalanced, over the whole period.</p>
{tiles([("LEADERS VS SPY, 63", n2(R['leaders']['63']['est'], True) + " pts", f"{rng(R['leaders']['63']['lo'], R['leaders']['63']['hi'], n2)} · p {n2(R['leaders']['63']['p'])} · {Q4['lows']} lows"), ("BY 252", n2(R['leaders']['252']['est'], True) + " pts", f"{rng(R['leaders']['252']['lo'], R['leaders']['252']['hi'], n2)} · level"), ("WORST FALLERS, 63", n2(R['laggards']['63']['est'], True) + " pts", f"{rng(R['laggards']['63']['lo'], R['laggards']['63']['hi'], n2)} · survivorship-inflated"), ("FALL RATIO", n2(W4['fall_ratio']['est']), f"leaders' fall ÷ SPY's fall into the low · {rng(W4['fall_ratio']['lo'], W4['fall_ratio']['hi'], n2)}")])}
{fig('q4-after-lows.png')}
{table(["basket, against SPY from confirmation", "21 sessions", "63", "126", "252", "the fall into the low"], [[name] + [f"<b class='{cls(R[k][h]['est'])}'>{n2(R[k][h]['est'], True)}</b> {rng(R[k][h]['lo'], R[k][h]['hi'], n2)}" if h in R[k] else "—" for h in ("21", "63", "126", "252", "fall")] for k, name in (("leaders", "leaders (top 20 by cap)"), ("rsp", "equal weight (RSP)"), ("iwm", "small caps (IWM)"), ("laggards", "worst-decile fallers into the low"))])}
{table(["by depth of the low", "lows", "leaders vs SPY, 63", "leaders, 252", "equal weight, 63", "worst fallers, 63"], [[d['band'], d['n'], f"{n2(d['leaders_63']['est'], True)} {rng(d['leaders_63']['lo'], d['leaders_63']['hi'], n2)}", f"{n2(d['leaders_252']['est'], True)} {rng(d['leaders_252']['lo'], d['leaders_252']['hi'], n2)}" if d.get('leaders_252') else "—", f"{n2(d['rsp_63']['est'], True)} {rng(d['rsp_63']['lo'], d['rsp_63']['hi'], n2)}", f"{n2(d['laggards_63']['est'], True)} {rng(d['laggards_63']['lo'], d['laggards_63']['hi'], n2)}"] for d in Q4['byDepth']] + [[s['state'], s['n'], f"{n2(s['leaders_63']['est'], True)} {rng(s['leaders_63']['lo'], s['leaders_63']['hi'], n2)}", "", f"{n2(s['rsp_63']['est'], True)} {rng(s['rsp_63']['lo'], s['rsp_63']['hi'], n2)}", ""] for s in Q4['byState']] + [[h['half'], h['n'], f"{n2(h['leaders_63']['est'], True)} {rng(h['leaders_63']['lo'], h['leaders_63']['hi'], n2)}", f"{n2(h['leaders_252']['est'], True)} {rng(h['leaders_252']['lo'], h['leaders_252']['hi'], n2)}" if h.get('leaders_252') else "—", "", ""] for h in Q4['halves']])}
<p><b>Why.</b> Three candidates, two ruled out. Not beta: the leaders fell {n2(W4['fall_ratio']['est'])} times SPY's fall into the low (range {n2(W4['fall_ratio']['lo'])} to {n2(W4['fall_ratio']['hi'])}), so they had no more ground to make up. Not breadth as such: equal weight and small caps did not beat SPY after the lows ({n2(R['rsp']['63']['est'], True)} and {n2(R['iwm']['63']['est'], True)} at 63 sessions). What beat SPY was the tenth of names that had fallen most into the low: {n2(R['laggards']['63']['est'], True)} points at 63 sessions, {n2(R['laggards']['126']['est'], True)} at 126, {n2(R['laggards']['252']['est'], True)} at 252. The leaders, being cap leaders, are almost never in that tenth, so a cap-weighted index that carries the rebound of its beaten members edges ahead of a basket of its largest members for a quarter, and the gap closes by the year. The bounce-over-fall ratio says the same: leaders recovered {pc(100 * W4['lead_bounce_over_fall']['est'])} of their fall in 63 sessions, SPY {pc(100 * W4['spy_bounce_over_fall']['est'])}. The laggards' number is inflated: the served names are those that survived their own worst falls, so the true rebound of the worst decile is smaller than this (the point-in-time universe, F1, is the fix).</p>
<h3>4a · Rules to test, not advice</h3>
{fig('q4-rules.png')}
{table(["rule, from an all-leaders book at the low's confirmation", "gain over holding, median per low · 90% range", "share of lows where it gained", "status (13 rules)", "first half · second half (median)", "lows"], [[r['rule'], f"<b class='{cls(r['gain_med'])}'>{n2(r['gain_med'], True)}</b> {rng(r['lo'], r['hi'], n2)}", pc(r['win']), word(r['word']), f"{n2(r['h1'], True)} · {n2(r['h2'], True)}", r['n']] for r in rules])}
<p><b>How to read it.</b> Moving into equal weight after a low is a wash at every size and length: the gain is a few tenths of a point with a range across zero and a coin-flip win rate. The rules that clear the check all move into the worst-decile fallers, and the gain grows with the holding period. Before that becomes a rule on the Hub it needs three things: a point-in-time universe (the survivorship problem above), a cost line (the fallers are the illiquid names), and a stop for the fallers that keep falling (section 3 says which ones: the wide usual day, the deep fall from the high). The honest wording today: <i>after a confirmed low, a leaders book that adds a small sleeve of the beaten names for a quarter has beaten one that does not, on a survivor's record</i>.</p>
<h3>4b · The bow tie as a fixed mix</h3>
{fig('q4-bowtie.png')}
{table(["leaders share (rest equal weight)", "yearly return, rebalanced to the mix", "worst fall, rebalanced", "yearly return, never rebalanced", "worst fall, never"], [[f"{int(b['leaders_weight'] * 100)}%", pc(b['rebalanced_daily']['cagr']), pc(b['rebalanced_daily']['maxdd']), pc(b['never']['cagr']), pc(b['never']['maxdd'])] for b in bt])}
<p>Over {bt[0]['from'][:4]} → the leaders wing carried the return ({pc(bt[0]['rebalanced_daily']['cagr'])} a year against {pc(bt[-1]['rebalanced_daily']['cagr'])} for equal weight) and the shallower worst fall; rebalancing against never rebalancing made no difference at any mix, because the two wings ran close enough that the drift stayed small. So which wing moves after a low is the laggards' sleeve, sized small, for about a quarter; the bow tie's fixed weights are a separate, slower decision that this record does not settle (the statistician-2 pairs study found equal weight's catch-ups took a year, and only after 2008–09).</p>
"""

# ---------------------------------------------------------------- Q5
DL = Q5["dnLadder"]; sides = {s["name"]: s for s in Q5["oneSided"]}; todayS = Q5["today"]; like = Q5["likeToday"]; trig = {t["name"]: t for t in Q5["triggers"]}; EV = Q5["events"]; BDS = Q5["byDirBandState"]
tclass = sides["today's class: up share ≤ 0.5% · down share ≥ 4%"]; mirror = sides["mirror: 0 down · up share ≥ 4%"]; clus5 = sides["5-day cluster of down-sigma share in its top 5%"]
topRung = DL["rungs"][-1]; botRung = DL["rungs"][0]
anyDown = trig["any stock · above 200-day · down day 2×+"]; lead_dn = trig["leader · above 200-day · down day"]
q5_lead = (f"<b>A one-sided sigma day like 23 September ({todayS['sep23']['up']} up, {todayS['sep23']['dn']} down of {todayS['sep23']['names']}) says little about the next month and a little about the next ten days: more of the same.</b> Days of that class have come {tclass['n']} times in {tclass['runs']} separate visits since 2003; SPY's next 21 sessions after them were {n2(tclass['fwd_21']['med'], True)}% against {n2(tclass['fwd_21']['base'], True)}% on any day ({tclass['fwd_21']['word']}), and of the {len(DL['rungs'])} rungs of the ladder and {len(Q5['oneSided'])} one-sided definitions, {sum(1 for r in DL['rungs'] if r['fwd_21']['fdr']) + sum(1 for x in Q5['oneSided'] if x['fwd_21']['fdr'])} clear the false-discovery check over 21 sessions and {sum(1 for r in DL['rungs'] if r['fwd_63']['fdr']) + sum(1 for x in Q5['oneSided'] if x['fwd_63']['fdr'])} over 63, none of them the row today sits in. "
    f"What does differ is what comes right after: {pc(tclass['more_ahead'])} of the next ten sessions were themselves top-decile down-sigma days, against {pc(tclass['more_ahead_base'])} on any day, and after a five-day cluster in its top 1% it was {pc(clus5['more_ahead'])}. "
    f"Per name, the {EV['n']:,} sigma events since {EV['from'][:4]} carry no edge as triggers: a 2×+ down day in a name above its 200-day was followed by {n2(anyDown['x21']['med'], True)} points against SPY over 21 sessions ({anyDown['x21']['word']}), the cap leaders' down days by {n2(lead_dn['x21']['med'], True)} ({lead_dn['x21']['word']}), and every cell of direction × size × trend sits within a fraction of a point of any day. A sigma scan is a list of names to look at, not a signal; the page says which rows to print and with what base rate (section 5).")
q5_html = f"""
<h2 id="q5">5 · USUAL DAY history as data</h2>
<div class="ask">"The 23-year USUAL DAY sigma history as a statistical source and a scan/notification signal. Today 0 up / 20 down."</div>
<p><b>What we measured.</b> The two tables the L1 lane filled on 28 Sep, read through the Hub's public key: <code>public.sigma_day_counts</code> ({Q5['counts']['days']:,} sessions, {Q5['counts']['from']} → {Q5['counts']['to']}; the universe grew from {Q5['counts']['names_2004']} names measured to {Q5['counts']['names_now']}, so every comparison is on the share of names, never the count) and <code>public.sigma_events_daily</code> ({EV['n']:,} name-days that fired, {EV['names']} names). The down-share and up-share of names beyond their usual day, each as its own expanding percentile; the one-sided days at every threshold; a five-day cluster; and, per name, what the name did against SPY after its own sigma day, split by direction, size in usual days, trend state and leader status. The table ends at the 25 Sep close, so the 28 Sep reading (0 up / 20 down on the live strip) is compared with its nearest stored day, 23 Sep ({todayS['sep23']['up']} up / {todayS['sep23']['dn']} down, a down share of {pc(todayS['sep23']['dn_share'])}, its {ordn(todayS['sep23']['dn_pct'])} percentile).</p>
{tiles([("DAYS LIKE 23 SEP", f"{tclass['n']}", f"{tclass['runs']} visits · {tclass['years']} years · last {tclass['last']}"), ("SPY NEXT 21", n2(tclass['fwd_21']['med'], True) + "%", f"{rng(tclass['fwd_21']['lo'], tclass['fwd_21']['hi'], n2)} · any day {n2(tclass['fwd_21']['base'], True)}% · {tclass['fwd_21']['word']}"), ("MORE SIGMA DAYS AHEAD", pc(tclass['more_ahead']), f"of the next 10 sessions were top-decile down days · any day {pc(tclass['more_ahead_base'])}"), ("PER-NAME EVENTS", f"{EV['n']:,}", f"{EV['names']} names since {EV['from'][:4]}")])}
{fig('q5-history.png')}
<h3>5a · The down-share ladder, every rung</h3>
{fig('q5-down-ladder.png')}
{table(["share of names with a down-sigma day", "days · visits", "own percentile", "SPY next 5", "next 21 · 90% range · status", "next 63 · status", "worst fall in 21"], [[r['label'], f"{r['n']} · {r['runs']}", f"{ordn(r['pct'])}", n2(r['fwd_5']['med'], True), f"<b class='{cls(r['fwd_21']['med'], DL['base']['fwd_21']['p50'])}'>{n2(r['fwd_21']['med'], True)}</b> {rng(r['fwd_21']['lo'], r['fwd_21']['hi'], n2)} {word(r['fwd_21']['word'])}", f"{n2(r['fwd_63']['med'], True)} {word(r['fwd_63']['word'])}", n1(r['dd_21']['med'])] for r in DL['rungs']] + [["any day", Q5['counts']['days'], "", n2(DL['base']['fwd_5']['p50'], True), n2(DL['base']['fwd_21']['p50'], True), n2(DL['base']['fwd_63']['p50'], True), n1(DL['base']['dd_21']['p50'])]])}
<p>The share takes few distinct values (it is a count over about 500 names), so the ladder is in its own units, every whole percent, rather than percentile rungs. 23 Sep's {pc(todayS['sep23']['dn_share'])} sits in the 5% row, its {ordn(todayS['sep23']['dn_pct'])} percentile.</p>
<h3>5b · One-sided days like today, at every threshold</h3>
{fig('q5-one-sided.png')}
{table(["definition", "days · visits · years", "SPY next 5", "next 21 · 90% range · status", "next 63 · status", "worst fall in 21", "more top-decile down days in the next 10 sessions"], [[s['name'], f"{s['n']} · {s['runs']} · {s['years']}", f"{n2(s['fwd_5']['med'], True)} <span class='q'>({pc(s['fwd_5']['up'])} up)</span>", f"<b class='{cls(s['fwd_21']['med'], s['fwd_21']['base'])}'>{n2(s['fwd_21']['med'], True)}</b> {rng(s['fwd_21']['lo'], s['fwd_21']['hi'], n2)} {word(s['fwd_21']['word'])}", f"{n2(s['fwd_63']['med'], True)} {word(s['fwd_63']['word'])}", f"{n1(s['dd_21']['med'])} <span class='q'>(any day {n1(s['dd_21']['base'])})</span>", f"{pc(s['more_ahead'])} <span class='q'>(any day {pc(s['more_ahead_base'])})</span>"] for s in Q5['oneSided']])}
<p><b>How to read it.</b> A day when no name has an up-sigma and many have a down-sigma is a broad, orderly sell day. Its next month and quarter sit a little above any day's at every threshold, which is the ordinary rebound after a down day, and none of it clears the check: read the status word before the number. The steadier fact is the clustering: after such a day, {pc(tclass['more_ahead'])} of the next ten sessions were themselves top-decile down-sigma days, against {pc(tclass['more_ahead_base'])} on any day. The mirror image (0 down, many up) is the bounce day, and the two-sided day (both wings beyond 2%) is the dispersion day. The {like['n']} days like 23 Sep sat a median {n1(like['spy_dd_from_high_med'])}% under SPY's high with the VIX at its {ordn(like['vix_pct_med'])} percentile and SPY above its 200-day {pc(like['spy_above200_share'])} of the time; the last ones were {", ".join(like['dates'][-6:])}.</p>
<h3>5c · Per-name sigma events as triggers</h3>
{fig('q5-triggers.png')}
{table(["trigger (single companies)", "events · dates · names", "next 5 vs SPY", "next 21 vs SPY · 90% range · status", "next 63 vs SPY · status", "21, first half · second half"], [[t['name'], f"{t['n']:,} · {t['dates']:,} · {t['names']}", n2(t['x5']['med'], True), f"<b class='{cls(t['x21']['med'], BDS['base']['x21']['med'])}'>{n2(t['x21']['med'], True)}</b> {rng(t['x21']['lo'], t['x21']['hi'], n2)} {word(t['x21']['word'])}", f"{n2(t['x63']['med'], True)} {word(t['x63']['word'])}", f"{n2(t['x21_h1']['med'], True)} · {n2(t['x21_h2']['med'], True)}"] for t in Q5['triggers']] + [["any sigma event", f"{BDS['base']['x21']['n_rows']:,}", n2(BDS['base']['x5']['med'], True), n2(BDS['base']['x21']['med'], True), n2(BDS['base']['x63']['med'], True), ""]])}
<details><summary>By direction, size in usual days and trend state ({len(BDS['cells'])} cells)</summary>{table(["direction · size · state", "events · dates", "next 5 vs SPY", "next 21 vs SPY · 90% range · status", "next 63 vs SPY · status"], [[c['key'], f"{c['n']:,} · {c['dates']:,}", n2(c['x5']['med'], True), f"<b class='{cls(c['x21']['med'], BDS['base']['x21']['med'])}'>{n2(c['x21']['med'], True)}</b> {rng(c['x21']['lo'], c['x21']['hi'], n2)} {word(c['x21']['word'])}", f"{n2(c['x63']['med'], True)} {word(c['x63']['word'])}"] for c in BDS['cells']])}</details>
<details><summary>By direction, trend state and leader status ({len(Q5['byDirLeader']['cells'])} cells) · by direction and security type ({len(Q5['byDirType']['cells'])} cells)</summary>{table(["direction · state · leader", "events · dates", "next 21 vs SPY · status", "next 63 vs SPY · status"], [[c['key'], f"{c['n']:,} · {c['dates']:,}", f"{n2(c['x21']['med'], True)} {rng(c['x21']['lo'], c['x21']['hi'], n2)} {word(c['x21']['word'])}", f"{n2(c['x63']['med'], True)} {word(c['x63']['word'])}"] for c in Q5['byDirLeader']['cells']])}{table(["direction · type", "events · dates", "next 21 vs SPY · status", "next 63 vs SPY · status"], [[c['key'], f"{c['n']:,} · {c['dates']:,}", f"{n2(c['x21']['med'], True)} {rng(c['x21']['lo'], c['x21']['hi'], n2)} {word(c['x21']['word'])}", f"{n2(c['x63']['med'], True)} {word(c['x63']['word'])}"] for c in Q5['byDirType']['cells']])}</details>
<p><b>How to read it.</b> The pooled medians sit within a quarter of a point of any day in every row, in both halves, and the one cell that clears the check (3–4× usual down days above the 200-day, over 63 sessions) is a fraction of a point the wrong way. The "raw only" rows are the names whose usual day is so wide that a big move is still under 2× it; they lag afterwards, which is the section-3 finding again (the wide usual day marks the names that keep falling). The leaders' sigma days are no different from anyone else's.</p>
<p><b>The scan proposal.</b> USUAL DAY already shows the day's sigma names, and this record says the list is worth reading for attention, not for direction: a sigma day in a name is where the news is, not a signal about the next month. So: keep the list, print beside each name its trend state (above or below its 200-day, 50 over 200 or not) and its own usual day, because those are the two things sections 3 and 5 found to matter, and do not print a forward number, because there is none to print. The one line the day strip itself has earned is the clustering: "days like this were followed by another top-decile down day in {pc(tclass['more_ahead'])} of the next ten sessions (any day {pc(tclass['more_ahead_base'])})". The leaders' rows ({EV['leader_rows']:,} events) are in the table above for completeness; they carry nothing.</p>
"""

# ---------------------------------------------------------------- Q6
GC = Q6["GCUSD"]; DX = Q6["DXY"]; X = Q6["cross"]; gepi = GC["episodes"]; last = gepi[-1]; big = sorted(gepi, key=lambda e: e["fall_after"])[:5]; top5 = [r for r in GC["ladder"] if r["from"] >= 60]
q6_lead = (f"<b>Gold's parabolic run already broke: it peaked on {last['peak_date']} at {n0(last['peak'])} ({n0(last['ext_at_peak'])}% above its 200-day, {n0(last['ret252_at_peak'])}% up on the year) and has fallen {n1(abs(last['fall_after']))}% since, with no new high {last['sessions_to_trough']} sessions later; today it sits {n1(abs(GC['today']['ext200']))}% <i>under</i> its 200-day, the {ordn(GC['today']['ext_pct'])} percentile of its own extension.</b> "
    f"In {GC['years']:.0f} years gold had {len(gepi)} such runs (extension in its top 5% of own history). What followed the peak: a median fall of {n1(abs(sorted([e['fall_after'] for e in gepi])[len(gepi) // 2]))}%, and the wait for a new high ran from a month (1978, 2024) to {n0(gepi[4]['recover_sessions'] / 252)} years after 1980 and {n0(gepi[8]['recover_sessions'] / 252)} years after 2011. Read as a ladder, though, extension was not a sell signal: the top rungs' next year was {n0(top5[-1]['f252']['med'], True)}% to {n0(max(r['f252']['med'] for r in top5), True)}% (any day {n0(GC['base']['f252']['p50'], True)}%), because runs ran on; the bad rungs are the deep-below ones, where gold is now. "
    f"The dollar is not extended: {n1(DX['today']['ext200'], True)}% from its 200-day, the {ordn(DX['today']['ext_pct'])} percentile; its {len(DX['episodes'])} past extensions were followed by a median year of {n1(DX['ladder'][-1]['f252']['med'], True)}%. Gold's best years came with the dollar deep under its 200-day ({n1(X['rows'][0]['gold_f252']['med'], True)}% when the dollar was in its bottom decile, luck-proof); at the dollar's rung today the gold year was {n1(next(r for r in X['rows'] if r['from'] <= X['today_dxy_ext_pct'] < r['to'])['gold_f252']['med'], True)}% (section 6).")
q6_html = f"""
<h2 id="q6">6 · Gold's parabolic runs, and the dollar's extension</h2>
<div class="ask">"Gold: sigma event today; parabolic-run history — what followed, how long to recover; the dollar may be extended."</div>
<p><b>What we measured.</b> Gold futures (continuous, FMP, {GC['from'][:4]} →, {GC['n']:,} sessions) and the ICE dollar index ({DX['from'][:4]} →, {DX['n']:,} sessions). Extension = the distance from the 200-day average, read as an expanding own-history percentile. No cut-off chooses the runs: every rung of the ladder is reported; the "parabolic" list is the top 5% of the ladder, merged into separate runs when closer than 63 sessions, and each run is shown one by one with its peak, the fall after it, the sessions to the trough and the wait for a new high (Kaplan–Meier where still open). Outcomes per rung: the next 63, 126 and 252 sessions and the worst fall inside a year, with block-bootstrap ranges and a false-discovery check over the {len(GC['ladder']) * 4} cells. Then gold's next year by the dollar's extension decile.</p>
{tiles([("GOLD TODAY", f"{n0(GC['today']['c'])}", f"{n1(GC['today']['ext200'], True)}% from its 200-day · {ordn(GC['today']['ext_pct'])} pct · RSI {n0(GC['today']['rsi'])}"), ("THE RUN THAT BROKE", f"{n0(abs(last['fall_after']))}% off", f"peak {last['peak_date']} at {n0(last['peak'])} · {last['sessions_to_trough']} sessions to the low so far"), ("PARABOLIC RUNS", f"{len(gepi)}", f"since {GC['from'][:4]} · {GC['n_top5']} days · {n0(GC['eff_n_top5'])} effective"), ("DOLLAR TODAY", f"{n1(DX['today']['c'])}", f"{n1(DX['today']['ext200'], True)}% from its 200-day · {ordn(DX['today']['ext_pct'])} pct · RSI {n0(DX['today']['rsi'])}")])}
{fig('q6-GCUSD-runs.png')}
<h3>6a · Every parabolic run in gold, one by one</h3>
{table(["run (top-5% extension days)", "peak", "at the peak: above 200-day · 1-year gain · RSI", "fall after the peak", "sessions to the trough", "wait for a new high", "next 63 · 252 · 504 from the peak"], [[f"{e['from']} → {e['to']} ({e['days']} days)", f"{e['peak_date']} · {n0(e['peak'])}", f"{n0(e['ext_at_peak'])}% · {n0(e['ret252_at_peak'])}% · {n0(e['rsi_at_peak'])}", f"<b class='dn'>{n1(e['fall_after'])}%</b>", e['sessions_to_trough'], (f"{e['recover_sessions']} sessions ({e['recover_sessions'] / 252:.1f} y)" if e['recovered'] else f"still waiting ({e['sessions_to_trough']}+ sessions)"), f"{n1(e['f63'], True)} · {n1(e['f252'], True)} · {n1(e['f504'], True)}"] for e in gepi])}
<p><b>How to read it.</b> Thirteen runs in {GC['years']:.0f} years, a list, not a rate. Two of them were the famous ones: January 1980 ({n0(gepi[4]['ext_at_peak'])}% above the 200-day, RSI {n0(gepi[4]['rsi_at_peak'])}), followed by a {n0(abs(gepi[4]['fall_after']))}% fall and a {n0(gepi[4]['recover_sessions'] / 252)}-year wait; August 2011, a {n0(abs(gepi[8]['fall_after']))}% fall and {n0(gepi[8]['recover_sessions'] / 252)} years. The rest fell 5 to 30% and recovered within a year and a half. The 2025–26 run was the third-widest extension on the list ({n0(last['ext_at_peak'])}% above the 200-day, a {n0(last['ret252_at_peak'])}% year), and its fall so far ({n1(abs(last['fall_after']))}%) already matches the middle of the list; whether the wait is 2006's ({gepi[5]['recover_sessions']} sessions) or 2011's is exactly what a list of thirteen cannot say.</p>
<h3>6b · The ladder: what followed each rung of extension</h3>
{fig('q6-GCUSD-ladder.png')}
{table(["extension rung (own pct)", "days", "extension (median)", "next 63", "next 126", "next 252 · 90% range · FDR", "worst fall in 252 · FDR", "wait for a new high (median sessions)"], [[f"{r['from']}–{r['from'] + 5}", r['n'], pc(r['ext_med']), n1(r['f63']['med'], True), n1(r['f126']['med'], True), f"<b class='{cls(r['f252']['med'], GC['base']['f252']['p50'])}'>{n1(r['f252']['med'], True)}</b> {rng(r['f252']['lo'], r['f252']['hi'])}{' ✓' if r['f252']['fdr'] else ''}", f"{n1(r['dd252']['med'])}{' ✓' if r['dd252']['fdr'] else ''}", n0(r['recover_med'])] for r in GC['ladder']] + [["any day", GC['n'], "", n1(GC['base']['f63']['p50'], True), n1(GC['base']['f126']['p50'], True), n1(GC['base']['f252']['p50'], True), n1(GC['base']['dd252']['p50']), n0(GC['base']['recover_med'])]])}
<p><b>How to read it.</b> Gold trends. The rungs above the 60th percentile of extension were followed by years of +12 to +22% (any day {n1(GC['base']['f252']['p50'], True)}%), most of them clearing the false-discovery check, and the worst fall inside those years was shallower than any day's. The bad rungs are at the bottom: deep under the 200-day (the 0–5 rung, {n0(GC['ladder'][0]['ext_med'])}% under) the next year was {n1(GC['ladder'][0]['f252']['med'], True)}% with a {n1(GC['ladder'][0]['dd252']['med'])}% worst fall, and the 20–50 rungs, where gold is today ({ordn(GC['today']['ext_pct'])}), were flat to negative. In words: the parabola is the danger only at its peak day, and the peak is known afterwards; on the ladder, extension was persistence, and the place to be careful is where gold is now, the months after the break.</p>
<h3>6c · The dollar</h3>
{fig('q6-DXY-runs.png')}{fig('q6-DXY-ladder.png')}
{table(["dollar extension rung", "days", "extension (median)", "next 63", "next 252 · 90% range · FDR", "worst fall in 252 · FDR"], [[f"{r['from']}–{r['from'] + 5}", r['n'], pc(r['ext_med']), n1(r['f63']['med'], True), f"<b class='{cls(r['f252']['med'], DX['base']['f252']['p50'])}'>{n1(r['f252']['med'], True)}</b> {rng(r['f252']['lo'], r['f252']['hi'])}{' ✓' if r['f252']['fdr'] else ''}", f"{n1(r['dd252']['med'])}{' ✓' if r['dd252']['fdr'] else ''}"] for r in DX['ladder']] + [["any day", DX['n'], "", n1(DX['base']['f63']['p50'], True), n1(DX['base']['f252']['p50'], True), n1(DX['base']['dd252']['p50'])]])}
<details><summary>The dollar's {len(DX['episodes'])} past extensions, one by one</summary>{table(["run", "peak", "above 200-day · 1-year · RSI", "fall after", "sessions to trough", "wait for a new high", "next 63 · 252"], [[f"{e['from']} → {e['to']}", f"{e['peak_date']} · {n1(e['peak'])}", f"{n1(e['ext_at_peak'])}% · {n1(e['ret252_at_peak'])}% · {n0(e['rsi_at_peak'])}", f"{n1(e['fall_after'])}%", e['sessions_to_trough'], (f"{e['recover_sessions']} sessions" if e['recovered'] else "still waiting"), f"{n1(e['f63'], True)} · {n1(e['f252'], True)}"] for e in DX['episodes']])}</details>
<p><b>How to read it.</b> The dollar does not carry an extension the way gold does: its top rung (95th+) was followed by a median year of {n1(DX['ladder'][-1]['f252']['med'], True)}% (any day {n1(DX['base']['f252']['p50'], True)}%), and its {len(DX['episodes'])} extensions were followed by falls of 6 to 18% and waits of months to years (2022's is still open after {DX['episodes'][-1]['sessions_to_trough']} sessions). Deep under its 200-day it kept falling (the bottom rung's next year {n1(DX['ladder'][0]['f252']['med'], True)}%), so the asymmetry is the finding: stretched high reverts, stretched low runs on. Today it is {n1(DX['today']['ext200'], True)}% from its 200-day, the {ordn(DX['today']['ext_pct'])} percentile, with a one-year change of {n1(DX['today']['ret252'], True)}%: not an extension by this measure. "Extended" on the Station's shorter lenses (RSI {n0(DX['today']['rsi'])} today) is a different clock and was not tested here.</p>
<h3>6d · Gold's next year by the dollar's extension</h3>
{fig('q6-gold-by-dollar.png')}{fig('q6-today.png')}
{table(["dollar extension decile", "days", "dollar's distance from its 200-day (median)", "gold's next 252 · 90% range", "FDR (10 tests)"], [[f"{r['from']}–{r['to']}", r['n'], pc(r['dxy_ext_med']), f"<b class='{cls(r['gold_f252']['med'], X['base_gold_f252'])}'>{n1(r['gold_f252']['med'], True)}</b> {rng(r['gold_f252']['lo'], r['gold_f252']['hi'])}", "✓" if r['gold_f252']['fdr'] else ""] for r in X['rows']] + [["any day", X['n'], "", n1(X['base_gold_f252'], True), ""]])}
<p>Gold's year is best when the dollar is deep under its 200-day (the bottom decile, {n1(X['rows'][0]['gold_f252']['med'], True)}%, the one cell that clears the check) and worst when the dollar is stretched high. Today the dollar sits in the {X['today_dxy_ext_pct']:.0f}th percentile, a middle rung where gold's year was {n1(next(r for r in X['rows'] if r['from'] <= X['today_dxy_ext_pct'] < r['to'])['gold_f252']['med'], True)}%: no signal either way from the dollar.</p>
"""

# ---------------------------------------------------------------- follow-ups, sources, wrong, not done
follow = f"""
<h2 id="follow">Follow-ups: drivers, not literal answers</h2>
<ol>
<li><b>F1 · The point-in-time universe, once, on Fly.</b> Sections 1d, 3c and 4 all bend under today's-cap typing (mega caps look strong because they became mega caps; small caps look doomed because they shrank; the laggards' rebound is measured on survivors). One Fly one-off over the R2 day files (the scout design's nightly file) gives monthly membership and cap from 2003. Re-run 1d, 3, 4 and 5 on it. Cost: one job, one evening; every later study inherits it.</li>
<li><b>F2 · The Geiger percentile readout.</b> Not a change to the bar: a second small number, "the Nth percentile of its own history", computed nightly for every served name from the replay in this lane (the maths are the Hub's, 0.15 s per name). It answers "is this unusual for this name" without touching the Equalizer. Proposal for the Geiger tab and the Station chip.</li>
<li><b>F3 · Mean reversion in the beaten names, as a study of its own.</b> The strongest pooled edge on this page is the opposite of the pullback cell: weak trend + weak momentum, the low composite rungs, the worst-decile fallers after a low. It needs the cost line, the point-in-time universe and the section-3 flags as its stop before it becomes a card. Design: the scout tier screens it; the Hub shows only the base rate.</li>
<li><b>F4 · Confluence as a two-gauge readout, not a score.</b> The record says RSI percentile triggers and put/call confirms, the VIX level only sizes the decline. A "fear pair" line on the regime strip proposal (statistician-2, section 8): RSI percentile and put/call 5-day percentile side by side, with the 21-session base rate for the pair printed. No composite, because the proxy added nothing over its best part.</li>
<li><b>F5 · The sigma-day cluster on the USUAL DAY strip.</b> The one steady thing about a day like today is that more such days follow. Print it: "days like this were followed by another top-decile down day in {pc(tclass['more_ahead'])} of the next ten sessions (any day {pc(tclass['more_ahead_base'])})". Data is already in the table; it is a one-line change with a test.</li>
<li><b>F6 · Persistence of winners, measured properly.</b> Section 3d found prior-year winners repeat at twice the base rate. That is the momentum factor, and it deserves the alphalens treatment the method page proposed: monthly ranking by 12-month return, quantile forward returns, turnover, on the F1 universe. It is the "bet on winners" half of Alan's sentence, with a number.</li>
<li><b>F7 · The lag of the leaders, measured from the low itself vs from confirmation.</b> Statistician-2 found −1.5 points from the low; this page −0.4 from confirmation, ten sessions later. The difference is the first ten sessions, which nobody can trade. A short note that reconciles the two numbers and fixes which one goes on the stats tab.</li>
<li><b>F8 · Gold's break, tracked.</b> The 2025–26 run is the third-widest on the list and its fall so far sits in the middle of the list. A small tracker on the commodities room: sessions since the peak, fall so far, and the two comparable cases (2006, 2011) drawn beside it. Research, not a call.</li>
<li><b>F9 · Intraday rungs.</b> The Geiger replay here covers the daily rungs only (about two-fifths of the Equalizer's weight). The intraday history needed to replay the 3h–12h rungs exists on the chart API for a few months; a stored history of published readings (the geiger-review lane's stored-history speed test) is the way to get the full composite as a statistic. Ask: keep every nightly /geiger publish.</li>
<li><b>F10 · Steal what works.</b> Read on GitHub for this lane: the public fear &amp; greed reconstructions (seven parts, own percentiles) were reused here; the block bootstrap and false-discovery tools from <code>arch</code> and <code>statsmodels</code> were reimplemented in 200 lines of numpy so the studies run on this Mac with no install. The next thing to borrow is <code>alphalens-reloaded</code> for F6, and the RRG reimplementation the sector lane already did for the wings.</li>
</ol>
"""
about = f"""
<h2 id="about">About this page</h2>
<p><b>What it shows.</b> Six questions from Alan's 28 Sep afternoon notes, each measured on the full record with base rates and ranges, ten follow-ups, and nothing that changes the Hub.</p>
<p><b>Where the numbers come from.</b> Daily bars for every served name and the macro series (VIX, put/call, dollar, gold, yields) from the chart API <code>https://scintilla-massive-chart-api.fly.dev/candles?tf=1d</code> at the 25 Sep close, fetched once on 28 Sep into a local cache; VIX3M and the dividend-adjusted HYG/LQD from the regime lane's Fly pull of FMP (cached); the two sigma tables and the company profiles (market cap, fund flag, sector) from Supabase through the Hub's public read key, read only; the year-by-year top-20 leader lists from the statistician-2 data file. The Geiger replay imports the Hub's own per-rung maths (<code>deliverables/20260927/geiger-review/geiger-replay.mjs</code>) through the sector-rotation lane's daily-history function. Code: <code>research/statistics/stats-3/</code> (lib.py the arithmetic, pooled.py the date-block bootstrap, one file per question, build_page.py this page); numbers in <a href="data/q1.json">data/q1.json</a> … <a href="data/q6.json">q6.json</a>; every chart is a PNG in <code>charts/</code>. Tests: <code>tests/stats-3.test.mjs</code> (the Python RSI against the Hub's rsiLast to nine decimals, the percentile, the false-discovery rule against the Node method library, the pivot swings, the page's images and data files, the grey-only palette).</p>
<p><b>How sure.</b> Every conditional number carries the standard's three: how many (independent episodes: visits, lows, entries, dates in blocks of 63, or years), how sure (a 90% range from resampling those units, never single days), how big (the shift against any day), and a word after the false-discovery check over everything tried in that table. Pooled stock tables resample dates, not name-days, so a crash counts once.</p>
<p><b>What could be wrong.</b> (1) <i>Survivorship</i>: the stock universe is today's served names; sections 1d, 3, 4 and 5c measure survivors, and the today's-cap tranches are biased in both directions (said in each place). (2) <i>Daily Geiger only</i>: the intraday rungs carry about three-fifths of the Equalizer's weight and are not in the replay. (3) <i>Fault cuts</i>: 77 histories are cut at a price fault (the bottoms lane's rule); META before June 2022 is not spliced here. (4) <i>The fear proxy</i> is a reconstruction, not CNN's number; its parts are the public ones but the weights and windows are this lane's. (5) <i>Put/call</i> starts in November 2006, so every confluence number covers 20 years, not 23. (6) <i>Gold and the dollar</i> are FMP continuous series; the 1970s prints are daily closes with no volume, and the extension percentile in the first years compares against a short history. (7) <i>The laggards basket</i> ignores costs and liquidity. (8) The 28 Sep sigma reading is not in the stored table yet; the page compares it with 23 Sep.</p>
<p><b>What was not done.</b> Nothing was deployed; no key, database write or price table was touched; the Hub's own pages were not edited; the Geiger was not changed. The point-in-time universe (F1) was not built. The intraday rungs were not replayed. No proposal here is a buy or sell rule.</p>
"""
lead = "".join(f"<li>{x}</li>" for x in (q1_lead, q2_lead, q3_lead, q4_lead, q5_lead, q6_lead))
CSS = open(os.path.join(ROOT, "deliverables/20260928/statistician-2/STATISTICIAN-2.html")).read().split("<style>")[1].split("</style>")[0]
page = f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Stats 3 · the Geiger as a statistic, confluence, winners · 28 Sep 2026</title>
<style>{CSS}h4{{font-size:16px;margin:18px 0 4px;color:#C8C8D2}}.three span .q{{font-size:13px;color:#9C9CAE}}td.up,span.up,b.up{{color:#00FFA3}}td.dn,span.dn,b.dn{{color:#FF2D55}}</style></head><body>
<span data-scnav-slot></span><h1>Stats 3: the Geiger as a statistic, confluence, and the conditions that separate winners</h1>
<p class="q">N2 · 28 Sep 2026 · daily bars to the 2026-09-25 close from the chart API, the sigma tables through the Hub's public key, the Hub's own Geiger maths replayed · pivots of 10 bars · ranges from resampled runs of days, lows, entries or years · research questions, not buy rules · every chart is a saved PNG in <code>charts/</code>, the numbers in <code>data/</code></p>
<div class="status"><b>STATUS · all six questions measured on the full record; nothing deployed, nothing changed on the Hub.</b> Each answer comes as the method standard asks: how many, how sure, how big, and a status word after the false-discovery check over everything tried. Ten follow-ups at the end, written as drivers. The Geiger was measured, not changed; the proposal in section 1 is a readout beside the bar.</div>
<h2>What we found, in plain words</h2>
<ol class="lead">{lead}</ol>
{q1_html}{q2_html}{q3_html}{q4_html}{q5_html}{q6_html}{follow}{about}
</body></html>"""
open(os.path.join(DIR, "STATS-3.html"), "w").write(page); print("wrote STATS-3.html", len(page))
