/* CP4 (7 Oct 2026) · THE COMPS TAB READS THE ENGINE'S ARTIFACT. The Hub's per-ticker COMPS view used to build the set, read the
   tables and price the company in the browser — a second engine beside the cards' and the tool's (Alan: "You said one source of
   truth, but I just found another"). Now it reads names/<TICKER>.json, written by the one engine, and draws: the blend (low · centre
   · high, before and after the debt discount), the football field, each yardstick's row with its weight and the consistency flag,
   growth two ways and PEG, the peers that price it with the four sources' dots and their closeness weight, the old set beside the
   new, the flags, debt, the long-term channel and the Geiger in its own year. It computes nothing: a live price only re-reads the
   forward P/E (price ÷ the engine's earnings) and the distance to the centre. A name the artifact does not carry falls back to the
   older in-browser reader (comps-c5/tab.mjs), and says so at the top.
   CP5 (7 Oct): the tab also prints the one line that says a centre is NOT A TARGET (when the engine wrote one), the outlier rule's
   cases in words — who is left out for being priced far above the group, which cheap peer stays — and the line each peer sits on. */
import { ARTIFACT_PATH, NAME_PATH, forwardOn, upsideOn, geigerPercentile, yardstickRows, footballFieldSVG, voteDots, flagWords } from "/lib/comps-artifact.mjs";
const esc = (s) => String(s == null ? "" : s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const x1 = (v, d = 1) => (v == null || !Number.isFinite(Number(v)) ? "—" : Number(v).toFixed(d) + "×"), pct = (v) => (v == null || !Number.isFinite(Number(v)) ? "—" : (v >= 0 ? "+" : "−") + Math.abs(Number(v)).toFixed(0) + "%"), px = (v) => (v == null || !Number.isFinite(Number(v)) ? "—" : Number(v) >= 100 ? Math.round(Number(v)).toLocaleString("en-US") : Number(v).toFixed(2));
const WORDS = { "000660.KS": "SK hynix", "005930.KS": "Samsung", "285A.T": "Kioxia" }, tk = (t) => WORDS[t] || t;
export const CSS = `.ce{font:12px/1.45 ui-monospace,Menlo,monospace;color:#c8c8d0}.ce .sec{border:1px solid #2a2a33;border-radius:6px;padding:10px 12px;margin:8px 0;background:#121218}.ce .hd{display:flex;gap:10px;align-items:baseline;flex-wrap:wrap;margin-bottom:6px}.ce .hd b{font-size:13px;letter-spacing:.08em}.ce .hd span{color:#8a8a96;font-size:11px}
.ce .big{font-size:22px;font-weight:600}.ce table{border-collapse:collapse;width:100%}.ce th{font-weight:500;color:#8a8a96;text-align:right;font-size:11px;padding:3px 6px;border-bottom:1px solid #2a2a33;letter-spacing:.06em}.ce th:first-child,.ce td:first-child{text-align:left}.ce td{text-align:right;padding:3px 6px;border-bottom:1px solid #1e1e26;white-space:nowrap}.ce tr.far td{color:#9a9aa6}.ce tr.np td{opacity:.55}
.ce .chip{display:inline-block;border:1px solid #3a3a46;border-radius:10px;padding:0 7px;margin:2px 3px 2px 0;font-size:11px;color:#c8c8d0}.ce .chip.adj{border-style:dashed;color:#9a9aa6}.ce .chip.old{color:#7a7a86}.ce .flag{color:#b8a46a}.ce .nat{margin:8px 0 2px;padding:7px 10px;border:1px solid #6e6440;border-radius:6px;color:#d2c48e;background:#1a1810;white-space:normal}.ce .nat b{letter-spacing:.08em}.ce .case{margin:3px 0;white-space:normal}.ce .case i{font-style:normal;color:#8a8a96;letter-spacing:.06em;font-size:11px;margin-right:6px}.ce .case.out i{color:#b04a4a}.ce .case.kept i{color:#3c9a5f}.ce .up{color:#3c9a5f}.ce .dn{color:#b04a4a}.ce small{color:#8a8a96;font-size:11px}.ce .two{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ce.narrow .two{grid-template-columns:1fr}.ce .dots{letter-spacing:.1em;font-size:11px}.ce details.sc-pagespecs{margin-top:10px}.ce details.sc-pagespecs summary{cursor:pointer;color:#8a8a96;font-size:11px;letter-spacing:.1em}.ce .scroll{overflow-x:auto}`;
function ensureCSS() { if (!document.getElementById("ce-css")) { const s = document.createElement("style"); s.id = "ce-css"; s.textContent = CSS; document.head.appendChild(s); } }
const fetchJson = (u) => fetch(u, { cache: "no-store" }).then((r) => (r.ok ? r.json() : null)).catch(() => null);
/** Try the artifact for one name. Returns the full reading or null. */
export async function readingOf(ticker) { return fetchJson(NAME_PATH(ticker)); }
/** Draw the engine's reading into root. livePrice: today's price when the page has one (else the engine's close). */
export function render(root, r, { livePrice = null, index = null } = {}) {
  ensureCSS(); root.classList.add("ce"); root.classList.toggle("narrow", root.clientWidth < 620);
  const T = r.ticker, p = livePrice > 0 ? livePrice : r.price, F = forwardOn(r, p), U = upsideOn(r, p), rows = yardstickRows(r), b = r.blend || {}, d = r.debt || {}, g = r.growth || {}, ch = r.channel || {}, ge = r.geiger;
  const livePctl = ge && livePrice > 0 && window.SC_LIVE_GEIGER && window.SC_LIVE_GEIGER[T] != null ? geigerPercentile(ge, window.SC_LIVE_GEIGER[T]) : null, liveG = window.SC_LIVE_GEIGER && window.SC_LIVE_GEIGER[T];
  const cls = (v) => (v == null ? "" : v >= 0 ? "up" : "dn");
  const peers = (r.peers || []).filter((q) => q.has_figures !== false), priced = peers.filter((q) => q.priced), notPriced = peers.filter((q) => !q.priced);
  const oldSet = r.sets && r.sets.old || [], newSet = r.sets && r.sets.now || [], cp3 = r.sets && r.sets.cp3;
  const peerRow = (q) => `<tr class="${q.priced ? "" : "np"}"><td><b>${esc(tk(q.ticker))}</b> <small>${esc(q.same_business ? "same business" : "adjacent")}${q.seated && q.seat_line ? " · seated on its " + esc(q.seat_line) + " line" : q.in_old_set ? "" : " · new"}</small></td><td class="dots" title="FMP peers · Massive related · same industry · shared fund">${voteDots(q.votes)}</td><td>${q.weight == null ? "—" : Math.round(q.weight * 100) + "%"}</td><td>${esc(q.pe_fwd_text || x1(q.pe_fwd))}</td><td>${pct(q.growth_eps)}</td><td>${q.peg == null ? "—" : Number(q.peg).toFixed(2)}</td><td>${x1(q.ev_ebitda)}</td><td>${q.debt && q.debt.net_debt_ebitda != null ? x1(q.debt.net_debt_ebitda) : "—"}</td><td><small>${esc(q.outlier ? "left out: priced far above the group" : q.spared ? "cheap: kept" : q.priced ? "" : "not priced")}</small></td></tr>`;
  const h = [];
  h.push(`<div class="sec"><div class="hd"><b>THE BLEND · every yardstick together</b><span>${esc(r.name)} · ${esc(r.line)} · the engine's reading of the ${esc(r.price_is)}${livePrice > 0 ? " · forward P/E and the distance to the centre on today's price" : ""}</span></div>
    <div class="two"><div><div class="big ${cls(U && U.upside_pct)}">${U ? pct(U.upside_pct) : "no range"} <small>to the centre ${px(b.centre)}</small></div><div>range ${px(b.low)} · <b>${px(b.centre)}</b> · ${px(b.high)} <small>per share</small></div>${r.not_a_target && r.not_a_target.words ? `<div class="nat"><b>NOT A TARGET</b> · ${esc(String(r.not_a_target.words).replace(/^Not a target\.\s*/, ""))}</div>` : ""}
      <div><small>${d.discount && d.discount.pct > 0 ? `before the debt discount: centre ${px(b.centre_before_debt)} (${pct(U && U.upside_before_debt_pct)}) · ${esc(d.discount.words)}` : esc((d.discount && d.discount.words) || "")}</small></div>
      <div><small>priced on ${priced.length} peers (${esc(r.sets && r.sets.rule || "")})${b.thin ? " · <span class=flag>thin</span>" : ""}${b.fragile ? " · <span class=flag>fragile</span>" : ""}</small></div></div>
      <div>${footballFieldSVG(r, p)}</div></div></div>`);
  h.push(`<div class="sec"><div class="hd"><b>EACH YARDSTICK</b><span>the company · its peers' median · the price that median implies · the weight it carries (prior × coverage × fit, cut where the consistency check flags it)</span></div><div class="scroll"><table><thead><tr><th>yardstick</th><th>${esc(T)}</th><th>peers' median</th><th>implied</th><th>vs price</th><th>weight</th><th>note</th></tr></thead><tbody>
    ${rows.map((y) => `<tr class="${y.consistency && y.consistency.far ? "far" : ""}${(y.weight || 0) > 0 ? "" : " np"}"><td>${esc(y.word)}${y.credit ? ` <small>growth credit ×${y.credit}</small>` : ""}</td><td>${y.key === "peg" ? (y.own == null ? "—" : Number(y.own).toFixed(2)) : x1(y.own)}</td><td>${y.key === "peg" ? (y.median == null ? "—" : Number(y.median).toFixed(2)) : x1(y.median)}</td><td><b>${px(y.implied)}</b></td><td class="${cls(y.implied != null && p > 0 ? y.implied / p - 1 : null)}">${y.implied != null && p > 0 ? pct((y.implied / p - 1) * 100) : "—"}</td><td><b>${y.weight_pct}%</b>${y.weight_before_check != null && Math.round(y.weight_before_check * 100) !== y.weight_pct ? ` <small>was ${Math.round(y.weight_before_check * 100)}%</small>` : ""}</td><td><small>${esc(y.off ? "left out: " + y.off : y.consistency && y.consistency.far ? y.consistency.why : "")}</small></td></tr>`).join("")}</tbody></table></div></div>`);
  h.push(`<div class="sec two"><div><div class="hd"><b>GROWTH, TWO WAYS · PEG</b></div><div>reported → next four quarters <b class="${cls(g.reported_to_next_pct)}">${pct(g.reported_to_next_pct)}</b></div><div>next four → the four after <b class="${cls(g.next_to_following_pct)}">${pct(g.next_to_following_pct)}</b> <small>revenue ${pct(g.revenue_following_pct)}</small></div><div>forward P/E <b>${esc(F ? F.text : "—")}</b> <small>${esc(F && F.basis || "")}</small></div><div>PEG <b>${r.peg && r.peg.value != null ? Number(r.peg.value).toFixed(2) : "—"}</b> <small>${esc(r.peg && r.peg.credit && r.peg.credit.credit > 1 ? `growth credit ×${r.peg.credit.credit}: ${Math.round(r.peg.credit.own)}% against the peers' ${Math.round(r.peg.credit.peers)}%` : r.peg && r.peg.credit && r.peg.credit.peers != null ? `no growth credit: ${Math.round(r.peg.credit.own)}% against the peers' ${Math.round(r.peg.credit.peers)}%` : "")}</small></div>${(g.one_off || []).length ? `<div><small class="flag">${esc(g.one_off.join("; "))}</small></div>` : ""}</div>
    <div><div class="hd"><b>DEBT · CHANNEL · GEIGER</b></div><div>net debt ÷ EBITDA <b>${d.net_debt_ebitda == null ? "—" : x1(d.net_debt_ebitda, 2)}</b> <small>${esc(d.word || "")}${d.debt_fcf_years != null ? ` · ${d.debt_fcf_years} years of free cash flow to repay all debt` : ""} · interest cover ${d.interest_cover == null ? "not on file" : x1(d.interest_cover)}</small></div>${d.warn ? `<div><small class="flag">${esc(d.warn)}</small></div>` : ""}
      <div>long-term channel <b>${ch.position_pct == null ? "—" : Math.round(ch.position_pct) + "% up"}</b> <small>${esc(ch.words || "")}</small></div>
      <div>Geiger ${liveG != null ? `<b>${Number(liveG).toFixed(2)}</b> now · the <b>${livePctl == null ? "—" : livePctl}</b>th percentile of its own year today` : ge ? `<b>${Number(ge.close).toFixed(2)}</b> at the close · the <b>${ge.pctl_close}</b>th percentile of its own year` : "—"} <small>${esc(ge && ge.year ? `${ge.year.n} trading days, ${ge.year.from} → ${ge.year.to}` : "")}</small></div></div></div>`);
  h.push(`<div class="sec"><div class="hd"><b>THE PEERS · who prices it and why</b><span>dots: FMP peers · Massive related · same industry · shared fund · weight = closeness (size, growth, margin) × business</span></div><div class="scroll"><table><thead><tr><th>peer</th><th>sources</th><th>weight</th><th>forward P/E</th><th>growth</th><th>PEG</th><th>EV/EBITDA</th><th>net debt ÷ EBITDA</th><th></th></tr></thead><tbody>${priced.map(peerRow).join("")}${notPriced.map(peerRow).join("")}</tbody></table></div>
    <div style="margin-top:8px"><small>the set as the sources kept it (old):</small> ${oldSet.map((t) => `<span class="chip old">${esc(tk(t))}</span>`).join("")}</div>${cp3 ? `<div><small>the set stated by hand this morning:</small> ${cp3.map((t) => `<span class="chip old">${esc(tk(t))}</span>`).join("")}</div>` : ""}<div><small>the method's set (now):</small> ${newSet.map((t) => `<span class="chip ${(r.sets.adjacent || []).includes(t) ? "adj" : ""}">${esc(tk(t))}</span>`).join("")}</div></div>`);
  const cases = r.outlier_cases || [], capPct = r.peg && r.peg.growth_cap_pct;
  if (cases.length) h.push(`<div class="sec"><div class="hd"><b>OUTLIERS · expensive ones only</b><span>a peer is left out only when it is priced far above the group; a cheap peer always stays</span></div>${cases.map((c) => `<div class="case ${c.verdict === "kept" ? "kept" : "out"}"><i>${esc(c.verdict === "kept" ? "KEPT" : c.verdict === "left out" ? "LEFT OUT" : "ONE YARDSTICK")}</i>${esc(c.words)}</div>`).join("")}</div>`);
  const flags = flagWords(r).filter((f) => !/^Not a target/.test(f)); if (flags.length) h.push(`<div class="sec"><div class="hd"><b>FLAGS</b></div>${flags.map((f) => `<div class="flag">· ${esc(f)}</div>`).join("")}</div>`);
  h.push(`<details class="sc-pagespecs"><summary>PAGE SPECS</summary><div><small>Every figure on this tab is read from one file the comps engine wrote (${esc(NAME_PATH(T))}); the tab computes nothing of its own. The blend is the weighted median of every peer's implied price on every yardstick; each yardstick's weight is a prior (growth and PEG first, then forward P/E, EV/EBITDA, trailing P/E, the sales multiples) × its coverage × its fit in this set, cut where its implied price sits far from the other yardsticks'. ${capPct ? `The growth yardstick (PEG) counts growth up to ${esc(capPct)}% a year, for the company and for every peer alike; growth beyond that adds to the yardstick's weight, not to its price. ` : ""}Outliers: a multiple is left out of its yardstick only when it sits far above the group (more than 3.5 typical spreads above the middle, on a log scale), and a peer is left out of every yardstick only when it is that far above on three or more of the five; a cheap peer or multiple is never left out. A centre is marked "not a target" when more than half of its distance from today's price comes from the growth yardstick, or when every same-business peer is a fraction of the company's size. Peers come from the four sources' votes and the business lines in the filings: a business line of the company with no peer of its own in the set seats its two best; same-business peers set the price when four or more exist, adjacent peers blend in at 0.35 and together never more than half the same-business weight; each peer weighs by its closeness in size, growth and margin. The debt discount takes 3% / 6% / 10% off the centre for net debt above 2.5 / 4 / 6 times EBITDA, plus 1% a year of free cash flow beyond five that repaying the debt would take. A foreign reporter's figures are all in dollars at one rate, per ADR. The long-term channel is the Lab's reviewed rails where on file, else a channel computed from the name's own weekly bars, and it says which. The Geiger's percentile is today's value in today's year.</small></div></details>`);
  root.innerHTML = h.join("");
}
/** Mount: artifact first; returns true when the artifact answered, false when the caller should fall back. */
export async function mountFromArtifact(root, opts) {
  const T = String(opts.ticker).toUpperCase(), r = await readingOf(T); if (!r || !r.ok) return false;
  const live = opts.livePrices && opts.livePrices[T] && Number(opts.livePrices[T].price || opts.livePrices[T]) > 0 ? Number(opts.livePrices[T].price || opts.livePrices[T]) : null;
  render(root, r, { livePrice: live }); return true;
}
