/* ADMISSION V2 (27 Sep) — the tier column, the loader list, LIKED, and the generated rows.
   The hidden gate this closes: five FMP loaders picked their names from composite_staged, frozen at
   386 names since 24 Aug, so an admitted name got a price and a Geiger and never any fundamentals,
   events, news or market cap. Every loader now walks one list, and that list honours the tier. */
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const read = (p) => fs.readFileSync(new URL("../" + p, import.meta.url), "utf8");
const MIG = "supabase/migrations/";

const LOADERS = ["fmp-fundamentals", "fmp-events", "news-feed", "mcap-refresh", "fmp-backfill", "fmp-analyst"];

test("every FMP loader walks fmp_full_universe and none walks composite_staged for its names", () => {
  for (const f of LOADERS) {
    const src = read("supabase/functions/" + f + "/index.ts");
    assert.match(src, /sb\.from\('fmp_full_universe'\)\.select\('ticker'\)/, f + " does not read the full-treatment list");
    assert.doesNotMatch(src, /from\('composite_staged'\)\.select\('ticker'\)/, f + " still picks names from the frozen table");
  }
});

test("the list is active, full-treatment, equity-or-fund only — the tier is honoured in one place", () => {
  const sql = read(MIG + "20260927_admission_v2_role.sql");
  assert.match(sql, /add column if not exists role text not null default 'full'/);
  assert.match(sql, /check \(role in \('full', 'geiger_only'\)\)/);
  const view = sql.slice(sql.indexOf("create or replace view public.fmp_full_universe"));
  for (const clause of [/active = true/, /role = 'full'/, /type not in \('crypto', 'future', 'index', 'rate'\)/, /ticker not like '%USD'/])
    assert.match(view, clause);
  assert.doesNotMatch(sql, /\b(update|delete|drop)\b/i, "the forward migration must be additive");
  assert.match(read(MIG + "20260927_admission_v2_role_ROLLBACK.sql"), /drop column if exists role/);
});

test("the tickers rows are generated, additive, source-marked, and count-checked", () => {
  const sql = read(MIG + "20260927_admission_v2_tickers.sql");
  assert.match(sql, /^-- GENERATED by scripts\/build-canonical-universe\.mjs/);
  assert.match(sql, /where not exists \(select 1 from public\.tickers t where t\.ticker = v\.ticker\)/);
  assert.doesNotMatch(sql, /\bupdate public\.tickers\b/i);
  const rows = [...sql.matchAll(/\('([A-Z.]+)','([A-Z_]+)','(stock|etf)','(full|geiger_only)'\)/g)];
  const count = Number(sql.match(/if n <> (\d+) then/)[1]);
  const geo = Number(sql.match(/if g <> (\d+) then/)[1]);
  assert.equal(rows.filter((r) => r[4] === "geiger_only").length, geo);
  for (const r of rows) if (r[3] === "etf") assert.notEqual(r[2], "THEMATIC", r[1] + ": funds do not go to THEMATIC");
  for (const held of ["SIVE", "BJK", "TMRC", "CLSK"]) assert.ok(!rows.some((r) => r[1] === held), held + " was held by the gap report");
  assert.ok(count >= 420, "the set only grows from the 420");
  assert.match(read(MIG + "20260927_admission_v2_tickers_ROLLBACK.sql"), /delete from public\.tickers where source = 'admission-v2-20260927'/);
});

test("the read engine reports the identity the rows were generated for", () => {
  const digest = read(MIG + "20260927_admission_v2_tickers.sql").match(/for the set ([a-f0-9]{64})/)[1];
  assert.match(read("supabase/functions/read-engine/index.ts"), new RegExp(`HUB_PINNED_UNIVERSE_SHA256='${digest}'`));
});

test("LIKED gets the 56, additively, and says so if it does not", () => {
  const sql = read(MIG + "20260927_admission_v2_liked.sql");
  const names = sql.slice(sql.indexOf("unnest(array["), sql.indexOf("]) as v")).match(/'([A-Z]+)'/g);
  assert.equal(names.length, 56);
  assert.match(sql, /where not exists \(select 1 from public\.hub_favorites f/);
  assert.match(sql, /if n <> 56 then raise exception/);
  assert.doesNotMatch(sql, /\b(update|delete)\b/i);
});
