import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { HORIZONS, quantile, meanSd, rankPct, forwardBands, rollingLevelBands, todayStats } from "../scripts/projection-cloud/stats.mjs";

/* September 23: the projection cloud joins under /prototypes/projection-cloud/ - a chart with no bars and no price line,
   only each instrument's own history as percentile and sigma bands behind today and carried forward, with a z-score of
   where today sits. The page is generated by scripts/projection-cloud/build.mjs from the chart API's daily closes and is
   self-contained: the statistics are computed at build time and embedded with provenance. These tests pin the maths,
   the embedded data's shape and honesty, and the house rules for a public review page. */

const at = (p) => new URL("../prototypes/projection-cloud/" + p, import.meta.url);
const page = fs.readFileSync(at("index.html"), "utf8");
const css = (page.match(/<style>([\s\S]*?)<\/style>/) || [])[1] || "";
const data = JSON.parse((page.match(/<script id="cloud-data" type="application\/json">([\s\S]*?)<\/script>/) || [])[1]);
const js = (page.match(/<script>([\s\S]*?)<\/script>/) || [])[1] || "";

test("the statistics are what the method section says they are", () => {
  assert.equal(quantile([1, 2, 3, 4, 5], 0.5), 3);
  assert.equal(quantile([1, 2, 3, 4], 0.5), 2.5);
  assert.equal(quantile([10, 20], 0.25), 12.5);
  const { mu, sd } = meanSd([2, 4, 4, 4, 5, 5, 7, 9]);
  assert.equal(mu, 5);
  assert.ok(Math.abs(sd - Math.sqrt(32 / 7)) < 1e-12, "sample standard deviation");
  assert.equal(rankPct([1, 2, 3, 4], 2), 50);
  assert.equal(rankPct([1, 2, 3, 4], 0), 0);
  assert.equal(rankPct([1, 2, 3, 4], 9), 100);

  /* a series that grows by the same ratio every session: every forward ratio at horizon h is exactly that ratio^h,
     so every percentile and every sigma line collapses onto it */
  const c = []; for (let i = 0; i < 80; i++) c.push(Math.pow(2, i / 10));
  for (const r of forwardBands(c, { horizons: [1, 5, 10], min: 10 })) {
    const want = Math.pow(2, r.h / 10);
    for (const k of ["p05", "p25", "p50", "p75", "p95", "mu", "s1lo", "s1hi", "s2lo", "s2hi"]) assert.ok(Math.abs(r[k] - want) < 1e-9, k + " at h=" + r.h);
    assert.equal(r.n, 80 - r.h, "one sample per session that has a session h later");
  }
  /* a horizon with too few samples is left empty, never invented */
  assert.deepEqual(forwardBands([1, 2, 3], { horizons: [1] }), [{ h: 1, n: 2 }]);

  /* rolling bands of a flat series are the constant; k runs from the oldest drawn session down to today */
  const flat = new Array(300).fill(7), fd = flat.map((_, i) => "d" + i);
  const rb = rollingLevelBands(flat, fd, { win: 250, back: 500, step: 4 });
  assert.equal(rb[0].k, 50); assert.equal(rb[rb.length - 1].k, 0); assert.equal(rb[rb.length - 1].d, "d299");
  for (const p of rb) assert.deepEqual(p.q, [7, 7, 7, 7, 7]);

  /* today at the top of a rising year: 100th percentile of its trailing year, positive z, the stated one-year change */
  const up = []; for (let i = 0; i < 600; i++) up.push(100 + i);
  const t = todayStats(up, up.map((_, i) => "d" + i), { from: 0, win: 250 });
  assert.equal(t.level, 699); assert.equal(t.date, "d599"); assert.equal(t.pct_level_1y, 100);
  assert.ok(t.z_1y > 1.5); assert.ok(Math.abs(t.ret_1y - (699 / 449 - 1)) < 1e-12);
});

test("the embedded data is the brief's six instruments, in its order, with ordered bands and provenance", () => {
  assert.deepEqual(data.instruments.map((i) => i.sym), ["US10Y", "DXY", "SPY", "KO", "WMT", "AAPL"]);
  assert.deepEqual(data.horizons, HORIZONS);
  assert.deepEqual(data.windows.map((w) => w.key), ["all", "y20", "y10"]);
  for (const i of data.instruments) {
    assert.ok(i.sessions >= 5000, i.sym + " carries deep history");
    assert.match(i.first, /^\d{4}-\d{2}-\d{2}$/); assert.match(i.last, /^\d{4}-\d{2}-\d{2}$/);
    assert.ok(["FMP", "MASSIVE"].includes(i.provider), i.sym + " names its provider");
    assert.ok(i.price_basis && i.provider_symbol, i.sym + " names its basis and provider symbol");
    for (const key of ["all", "y20", "y10"]) {
      const w = i.windows[key]; assert.ok(w, i.sym + " " + key);
      assert.equal(w.bands.length, HORIZONS.length);
      for (const b of w.bands) {
        if (b.p05 == null) { assert.ok(b.n < 30, "an empty horizon is empty for lack of samples"); continue; }
        assert.ok(b.p05 <= b.p25 && b.p25 <= b.p50 && b.p50 <= b.p75 && b.p75 <= b.p95, i.sym + " " + key + " h=" + b.h + " percentiles ordered");
        assert.ok(b.s2lo <= b.s1lo && b.s1lo <= b.mu && b.mu <= b.s1hi && b.s1hi <= b.s2hi, i.sym + " " + key + " h=" + b.h + " sigma ordered");
        assert.ok(b.n >= 30);
      }
      assert.ok(w.today.level > 0); assert.equal(w.today.date, i.last);
      assert.ok(w.today.pct_level_1y >= 0 && w.today.pct_level_1y <= 100);
      assert.ok(w.today.ret_1y_pct >= 0 && w.today.ret_1y_pct <= 100);
    }
    const r = i.rolling;
    assert.equal(r[r.length - 1].k, 0); assert.equal(r[r.length - 1].d, i.last); assert.ok(r[0].k >= 250);
    for (const p of r) for (let q = 1; q < 5; q++) assert.ok(p.q[q - 1] <= p.q[q], i.sym + " rolling quantiles ordered at k=" + p.k);
    /* the page prints each instrument's provenance where a reader can see it */
    assert.match(page, new RegExp("<tr><td>" + i.sym + "</td><td>" + i.provider + " · "), i.sym + " in the sources table");
  }
  assert.match(page, /Daily closes served by the Scintilla chart API \(https:\/\/scintilla-massive-chart-api\.fly\.dev\)/);
  assert.match(page, /read once when this page was built: \d{4}-\d{2}-\d{2}T/);
});

test("the deep history the brief names is really there: US10Y to 1962, DXY to 1971, the equities to 2003", () => {
  const by = Object.fromEntries(data.instruments.map((i) => [i.sym, i]));
  assert.ok(by.US10Y.first <= "1962-01-05", "US10Y " + by.US10Y.first);
  assert.ok(by.DXY.first <= "1971-01-31", "DXY " + by.DXY.first);
  for (const s of ["SPY", "KO", "WMT", "AAPL"]) assert.ok(by[s].first <= "2003-12-31", s + " " + by[s].first);
});

test("no price line: the page carries bands, medians, sigma lines and today's dot, never the close series", () => {
  for (const cls of ['"cloud1"', '"cloud2"', '"med"', '"sig"', '"now-dot"', '"now-line"']) assert.ok(js.includes(cls), "renderer draws " + cls);
  for (const i of data.instruments) { assert.equal(i.series, undefined); assert.equal(i.closes, undefined); }
  let longest = 0;
  JSON.stringify(data, (k, v) => { if (Array.isArray(v)) longest = Math.max(longest, v.length); return v; });
  assert.ok(longest <= 130, "no array long enough to be a price series (longest " + longest + ")");
  /* the window filter is one row above everything it scopes, and every drawn value is also in a table */
  assert.match(page, /<div class="filters" role="group"[\s\S]*?data-win="all"[\s\S]*?data-win="y20"[\s\S]*?data-win="y10"/);
  assert.ok(js.includes('"details"') && js.includes('"tv"'), "a table twin per instrument");
});

test("the page is never a dead end: two links back to /prototypes/, off-site links open in a new tab", () => {
  assert.equal((page.match(/href="\/prototypes\/"/g) || []).length, 2, "top and bottom");
  for (const m of page.matchAll(/<a\b([^>]*href="https?:[^"]*"[^>]*)>/g))
    assert.match(m[1], /target="_blank"[^>]*rel="noopener"|rel="noopener"[^>]*target="_blank"/, "off-site link opens in a new tab: " + m[1]);
  const hosts = new Set([...page.matchAll(/href="https?:\/\/([^/"]+)/g)].map((m) => m[1]));
  assert.deepEqual([...hosts].sort(), ["scintillahub.ai"], "links go to the product only");
});

test("self-contained and public-safe: no request, no storage, no key, no path, no person", () => {
  assert.match(page, /<meta name="robots" content="noindex,nofollow">/);
  assert.doesNotMatch(page, /<script[^>]+src=|<link[^>]+href=|<iframe|fetch\(|XMLHttpRequest|WebSocket|localStorage|sessionStorage|document\.cookie/i);
  assert.doesNotMatch(page, /eyJ[A-Za-z0-9_-]{10,}\.|apikey|service_role|Authorization/i);
  for (const re of [/[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+\.[A-Za-z.]{2,}/, /\/Users\/|~\//, /quota|utiliz|five.hour|weekly usage/i, /intake\b.*:|service.role|anon key/i])
    assert.doesNotMatch(page, re, "no private material on the public page: " + re);
  assert.doesNotMatch(page, /\bcomposed\b/i, "the owner never sees the word composed");
});

test("the stylesheet is balanced and monochrome: no white, no near-white, one accent hue", () => {
  let depth = 0;
  for (let i = 0; i < css.length; i++) {
    if (css.startsWith("@media", i)) assert.equal(depth, 0, "an @media block opens inside another block at offset " + i);
    if (css[i] === "{") depth++;
    if (css[i] === "}") { depth--; assert.ok(depth >= 0, "unbalanced } at offset " + i); }
  }
  assert.equal(depth, 0, "every block is closed");
  for (const bad of ["#fff", "#ffffff", "#f2f2f8", "#c6c8de", "#e2e4f0"]) assert.ok(!css.toLowerCase().includes(bad), "near-white in the palette: " + bad);
  assert.doesNotMatch(css, /(?:^|[;{\s])(?:color|background|background-color|border|border-color|fill|stroke)\s*:\s*[^;{}]*\bwhite\b(?!-)/i, "the colour keyword white is used");
  for (const m of css.matchAll(/#([0-9a-fA-F]{6})\b/g)) {
    const [r, g, b] = [0, 2, 4].map((i) => parseInt(m[1].slice(i, i + 2), 16));
    assert.ok(0.2126 * r + 0.7152 * g + 0.0722 * b < 205, "#" + m[1] + " is too close to white for the Scintilla palette");
  }
  for (const bad of ["#00ffa3", "#ff8a00", "#ff2d55", "#ffe500", "#2d9cff", "#8b5cf6"]) assert.ok(!css.toLowerCase().includes(bad), "a second accent hue is on the page: " + bad);
  /* the renderer paints only with the stylesheet's tokens */
  for (const m of js.matchAll(/#[0-9a-fA-F]{3,6}\b/g)) assert.fail("a literal colour in the renderer: " + m[0]);
  assert.doesNotMatch(js, /\bwhite\b/i);
});
