import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const at = (p) => new URL("../prototypes/report-library/" + p, import.meta.url);
const page = fs.readFileSync(at("index.html"), "utf8");
const css = (page.match(/<style>([\s\S]*?)<\/style>/) || [])[1] || "";

/* September 23: the recovered company reports, deduplicated into ONE report and marked against the Hub.
   The page is generated by scripts/build-report-library.py from the section list inside it, so the counts on the
   page are the list's counts. These tests hold the page to the house rules: monochrome with no white, self-contained,
   public-safe, and never a dead end. */
test("the counts on the page are the counts of the sections on it", () => {
  const secs = [...page.matchAll(/<article class="sec" id="s(\d+)" data-status="(HAVE|PARTIAL|NONE)">/g)];
  const n = (s) => secs.filter((m) => m[2] === s).length;
  const stat = (label) => +((page.match(new RegExp('<b>(\\d+)</b><span>' + label + '</span>')) || [])[1]);
  assert.equal(stat("distinct sections"), secs.length);
  assert.equal(stat("have on Hub"), n("HAVE"));
  assert.equal(stat("partial"), n("PARTIAL"));
  assert.equal(stat("don&#8217;t have"), n("NONE"));
  assert.equal(stat("sections found") - stat("duplicates removed"), secs.length, "found minus duplicates is the distinct list");
  secs.forEach((m, i) => assert.equal(+m[1], i + 1, "sections are numbered in order"));
  for (const m of page.matchAll(/<article class="sec"[\s\S]*?<\/article>/g)) {
    assert.match(m[0], /<dt>Found in<\/dt><dd>[^<]+\(/, "every section names the reports it was found in");
    assert.match(m[0], /<dt>On the Hub<\/dt><dd>[^<]{6,}/, "every section says where it is on the Hub, or that it is not");
    assert.match(m[0], /<dt>Should we have it\?<\/dt><dd class="judge">[^<]{3,}/, "every section carries a judgement");
  }
});

test("every contents link lands on a group and every group links back to the top", () => {
  const toc = (page.match(/<nav class="toc"[^>]*>([\s\S]*?)<\/nav>/) || [])[1] || "";
  const ids = [...toc.matchAll(/href="#([a-z]+)"/g)].map((m) => m[1]);
  assert.deepEqual(ids, ["identity", "price", "fund", "debt", "comps", "sent", "events", "risk"], "the digest shape, in order");
  for (const id of ids) assert.match(page, new RegExp('<section class="grp" id="' + id + '">'), id + " exists");
  assert.equal((page.match(/href="#top"/g) || []).length, ids.length + 1, "a way up from every group");
  assert.match(page, /id="top"/);
});

test("the page is never a dead end: two links back to /prototypes/, and every off-site link opens in a new tab", () => {
  assert.equal((page.match(/href="\/prototypes\/"/g) || []).length, 2, "top and bottom");
  for (const m of page.matchAll(/<a\b([^>]*href="https?:[^"]*"[^>]*)>/g))
    assert.match(m[1], /target="_blank"[^>]*rel="noopener"|rel="noopener"[^>]*target="_blank"/, "off-site link opens in a new tab: " + m[1]);
  const hosts = new Set([...page.matchAll(/href="https?:\/\/([^/"]+)/g)].map((m) => m[1]));
  assert.deepEqual([...hosts].sort(), ["allocation.scintillahub.ai", "scintillahub.ai"], "links go to the products only");
});

test("self-contained and public-safe: no request, no storage, no key, no path, no person", () => {
  assert.match(page, /<meta name="robots" content="noindex,nofollow">/);
  assert.doesNotMatch(page, /<script[^>]+src=|<link[^>]+href=|<iframe|fetch\(|XMLHttpRequest|WebSocket|localStorage|sessionStorage|document\.cookie/i);
  assert.doesNotMatch(page, /eyJ[A-Za-z0-9_-]{10,}\.|apikey|service_role|Authorization/i);
  for (const re of [/[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+\.[A-Za-z.]{2,}/, /\/Users\/|~\//, /quota|utiliz|five.hour|weekly usage/i, /intake\b.*:|service.role|anon key/i])
    assert.doesNotMatch(page, re, "no private material on the public page: " + re);
});

test("the stylesheet is balanced and monochrome: no white, no near-white, one accent hue", () => {
  let depth = 0;
  for (let i = 0; i < css.length; i++) {
    if (css.startsWith("@media", i)) assert.equal(depth, 0, "an @media block opens inside another block at offset " + i);
    if (css[i] === "{") depth++;
    if (css[i] === "}") { depth--; assert.ok(depth >= 0, "unbalanced } at offset " + i); }
  }
  assert.equal(depth, 0, "every block is closed");
  for (const bad of ["#fff", "#ffffff", "#f2f2f8", "#c6c8de", "#e2e4f0"]) assert.ok(!css.toLowerCase().includes(bad), "near-white in the palette: " + bad);
  assert.doesNotMatch(css, /(?:^|[;{\s])(?:color|background|background-color|border|border-color|fill|stroke)\s*:\s*[^;{}]*\bwhite\b(?!-)/i, "the colour keyword white is used");
  for (const m of css.matchAll(/#([0-9a-fA-F]{6})\b/g)) {
    const [r, g, b] = [0, 2, 4].map((i) => parseInt(m[1].slice(i, i + 2), 16));
    assert.ok(0.2126 * r + 0.7152 * g + 0.0722 * b < 205, "#" + m[1] + " is too close to white for the Scintilla palette");
  }
  for (const bad of ["#00ffa3", "#ff8a00", "#ff2d55", "#ffe500", "#2d9cff", "#8b5cf6"]) assert.ok(!css.toLowerCase().includes(bad), "a second accent hue is on the page: " + bad);
  /* the three marks read without colour: each carries a glyph and a word */
  for (const [cls, word] of [["have", "Have on Hub"], ["partial", "Partial"], ["none", "Don&#8217;t have"]])
    assert.match(page, new RegExp('<span class="mark ' + cls + '"><span class="g" aria-hidden="true">&#\\d+;</span>' + word + "</span>"), cls + " mark has glyph and word");
});
