import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const at = (p) => new URL("../prototypes/report-library/" + p, import.meta.url);
const page = fs.readFileSync(at("index.html"), "utf8");
const css = (page.match(/<style>([\s\S]*?)<\/style>/) || [])[1] || "";

/* September 23: the recovered company reports written out as ONE report for a ticker, as cards under tabs.
   Alan's words: "a comprehensive report, what we have on Hub, what we don't", and it must stop talking about
   which versions were canonical or tested. The page is generated by scripts/build-report-library.py from the
   section list inside it, so the counts on the page are that list's counts. */

const cards = [...page.matchAll(/<article class="card" id="([sg])(\d+)" data-status="(HAVE|PARTIAL|NONE)">[\s\S]*?<\/article>/g)];
const sections = cards.filter((m) => m[1] === "s");
const stat = (label) => +((page.match(new RegExp("<b>(\\d+)</b><span>" + label + "</span>")) || [])[1]);

test("the counts on the page are the counts of the sections on it", () => {
  const n = (k) => sections.filter((m) => m[3] === k).length;
  assert.equal(stat("sections in the report"), sections.length);
  assert.equal(stat("on the Hub"), n("HAVE"));
  assert.equal(stat("partly there"), n("PARTIAL"));
  assert.equal(stat("not on the Hub"), n("NONE"));
  sections.forEach((m, i) => assert.equal(+m[2], i + 1, "the report is numbered straight through"));
  assert.equal(new Set(cards.map((m) => m[1] + m[2])).size, cards.length, "one element, one id");
});

test("every card says what it is, where it is and whether it is worth having", () => {
  for (const m of cards) {
    assert.match(m[0], /<span class="mark (have|partial|none)"><span class="g" aria-hidden="true">&#\d+;<\/span>(On the Hub|Partly there|Not on the Hub)<\/span>/, "a mark that reads without colour");
    assert.match(m[0], /<h3>[^<]{8,}<\/h3>/, "a title");
    assert.match(m[0], /<p class="what">[^<]{20,}<\/p>/, "plain words for what it is");
    assert.match(m[0], /<span class="rk">Where it is<\/span><span class="rv">[^<]{4,}/, "where it is on the Hub, or that it is not");
    assert.match(m[0], /<span class="rk">Worth having\?<\/span><span class="rv judge">[^<]{3,}/, "a one-line answer");
    assert.match(m[0], /<p class="seen"[^>]*>In \d+ of your reports?<\/p>/, "how many of his reports carried it");
  }
});

test("every tab opens a room, and the report lists every section in reading order", () => {
  const tabs = [...page.matchAll(/<button type="button" role="tab" data-tab="([a-z]+)"[^>]*>([^<]+)<span>(\d+)<\/span>/g)];
  assert.ok(tabs.length >= 10, "the report, a room per part, what is missing, and where it came from");
  assert.equal(tabs.filter((t) => /aria-selected="true"/.test(t[0])).length, 1, "exactly one room is open on arrival");
  assert.equal(tabs[0][2].trim(), "The report", "the whole report is the first room");
  for (const t of tabs) assert.match(page, new RegExp('<section class="panel" id="t-' + t[1] + '"'), t[2] + " has a room");
  const rows = [...page.matchAll(/<a class="ol" href="#s(\d+)" data-tab="([a-z]+)">/g)];
  assert.equal(rows.length, sections.length, "every section is in the report, once");
  rows.forEach((r, i) => assert.equal(+r[1], i + 1, "in reading order"));
  for (const r of rows) {
    const panel = (page.match(new RegExp('<section class="panel" id="t-' + r[2] + '"[\\s\\S]*?</section>')) || [])[0] || "";
    assert.ok(panel.includes('id="s' + r[1] + '"'), "section " + r[1] + " is in the room its line points at");
  }
});

test("Alan's page does not talk about our versions, tests or commits", () => {
  const text = page.replace(/<style>[\s\S]*?<\/style>/, "").replace(/<script>[\s\S]*?<\/script>/, "").replace(/<[^>]+>/g, " ");
  for (const re of [/\bv\d+(\.\d+)*\b/i, /\bcanonical\b/i, /\btest(ed|ing)?\b/i, /\b[0-9a-f]{7,40}\b/, /byte-level|duplicates removed|sections found/i])
    assert.doesNotMatch(text, re, "bookkeeping language on the page: " + re);
});

test("the page is never a dead end: two links back to /prototypes/, and every off-site link opens in a new tab", () => {
  assert.equal((page.match(/href="\/prototypes\/"/g) || []).length, 2, "top and bottom");
  for (const m of page.matchAll(/<a\b([^>]*href="https?:[^"]*"[^>]*)>/g))
    assert.match(m[1], /target="_blank"[^>]*rel="noopener"|rel="noopener"[^>]*target="_blank"/, "off-site link opens in a new tab: " + m[1]);
  const hosts = new Set([...page.matchAll(/href="https?:\/\/([^/"]+)/g)].map((m) => m[1]));
  assert.deepEqual([...hosts].sort(), ["allocation.scintillahub.ai", "scintillahub.ai", "station.scintillahub.ai"], "links go to the products only");
});

test("self-contained and public-safe: no request, no storage, no key, no path, no person", () => {
  assert.match(page, /<meta name="robots" content="noindex,nofollow">/);
  assert.doesNotMatch(page, /<script[^>]+src=|<link[^>]+href=|<iframe|fetch\(|XMLHttpRequest|WebSocket|localStorage|sessionStorage|document\.cookie/i);
  assert.doesNotMatch(page, /eyJ[A-Za-z0-9_-]{10,}\.|apikey|service_role|Authorization/i);
  for (const re of [/[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+\.[A-Za-z.]{2,}/, /\/Users\/|~\//, /quota|utiliz|five.hour|weekly usage/i, /intake\b.*:|service.role|anon key/i])
    assert.doesNotMatch(page, re, "no private material on the public page: " + re);
});

test("the cards reflow and the type scales with the screen", () => {
  assert.match(css, /\.grid\{display:grid;grid-template-columns:repeat\(auto-fill,minmax\(min\(100%,[^)]+\),1fr\)\)/, "as many columns as fit, never a fixed count");
  assert.match(css, /font-size:clamp\(/, "type grows with the screen");
  assert.doesNotMatch(css, /[;{]\s*max-width:\s*(7|8|9)\d\dpx/, "no fixed narrow box (a media query is not a box)");
});

test("the stylesheet is balanced and monochrome: no white, no near-white, one accent hue", () => {
  let depth = 0;
  for (let i = 0; i < css.length; i++) {
    if (css.startsWith("@media", i)) assert.equal(depth, 0, "an @media block opens inside another block at offset " + i);
    if (css[i] === "{") depth++;
    if (css[i] === "}") { depth--; assert.ok(depth >= 0, "unbalanced } at offset " + i); }
  }
  assert.equal(depth, 0, "every block is closed");
  for (const bad of ["#fff", "#ffffff", "#f2f2f8", "#c6c8de", "#e2e4f0"]) assert.ok(!css.toLowerCase().includes(bad), "near-white in the palette: " + bad);
  assert.doesNotMatch(css, /(?:^|[;{\s])(?:color|background|background-color|border|border-color|fill|stroke)\s*:\s*[^;{}]*\bwhite\b(?!-)/i, "the colour keyword white is used");
  for (const m of css.matchAll(/#([0-9a-fA-F]{6})\b/g)) {
    const [r, g, b] = [0, 2, 4].map((i) => parseInt(m[1].slice(i, i + 2), 16));
    assert.ok(0.2126 * r + 0.7152 * g + 0.0722 * b < 205, "#" + m[1] + " is too close to white for the Scintilla palette");
  }
  for (const bad of ["#00ffa3", "#ff8a00", "#ff2d55", "#ffe500", "#2d9cff", "#8b5cf6"]) assert.ok(!css.toLowerCase().includes(bad), "a second accent hue is on the page: " + bad);
});
