/* N1 · PULLBACK PLAYBOOK — writes deliverables/20260928/pullback-playbook/PULLBACK-PLAYBOOK.html from data/pullback-playbook.json.
   node research/statistics/pullback-playbook/page.mjs   (no network; plain words for Alan; every number names its source) */
import fs from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
const HERE = path.dirname(fileURLToPath(import.meta.url)), ROOT = path.resolve(HERE, "../../..");
const DIR = path.join(ROOT, "deliverables/20260928/pullback-playbook");
const J = JSON.parse(fs.readFileSync(path.join(DIR, "data/pullback-playbook.json"), "utf8"));
const s1 = J.s1, s2 = J.s2, s3 = J.s3, s4 = J.s4, s5 = J.s5, live = J.live;
const f = (x, d = 1) => (x == null || !Number.isFinite(+x) ? "—" : (+x).toFixed(d));
const sg = (x, d = 1) => (x == null || !Number.isFinite(+x) ? "—" : (x > 0 ? "+" : "") + (+x).toFixed(d));
const col = (x) => (x == null || !Number.isFinite(+x) ? "" : x >= 0 ? "up" : "dn");
const S = (x, d = 1) => `<span class="${col(x)}">${sg(x, d)}</span>`;
const pct = (x) => { if (x == null || !Number.isFinite(+x)) return "—"; const n = Math.round(+x), m = n % 100; const sfx = m >= 11 && m <= 13 ? "th" : n % 10 === 1 ? "st" : n % 10 === 2 ? "nd" : n % 10 === 3 ? "rd" : "th"; return `${n}${sfx}`; };
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;");
const fig = (name, cap) => `<figure><img src="charts/${name}" alt="${esc(cap)}"><figcaption>${esc(cap)}</figcaption></figure>`;
const tbl = (head, rows) => `<div class="scroll"><table><thead><tr>${head.map((h) => `<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.map((r) => `<tr>${r.map((c) => `<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
const word = (t) => (!t ? "no data" : t.n < 20 ? "a list" : t.survives ? "luck-proof" : t.p <= 0.1 ? "leaning" : "not shown");
const rng = (t, d = 2) => (t ? `${sg(t.diff ?? t.mean, d)} (90% range ${sg(t.lo, d)} to ${sg(t.hi, d)}; ${word(t)})` : "—");

const D = s1.depth, B = s1.breadth, V = s1.vix, P = s1.pcc, R = s1.rsi, SG = s1.sigma, BT = s1.bowtie.today, AN = s1.analogs, A20 = AN.variants["20"], LD = s1.ladder, Y = s1.yieldsUp;
const W = s2.wing, IR = s2.indexRange, wide = W.wide;
const SPY3 = s4.instruments.SPY.byDepth["3"], QQQ3 = s4.instruments.QQQ.byDepth["3"], LEAD3 = s4.instruments.LEADERS.byDepth["3"], NDX3 = s4.instruments["^NDX"]?.byDepth["3"];
const liveAt = live ? new Date(live.taken_utc).toISOString().slice(11, 16) + " UTC" : null;
const curve = (nm, xs = [1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 15]) => LD[nm].curve.filter((r) => xs.includes(r.x) && r.n >= 5);

const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Pullback playbook · N1 · 28 Sep 2026</title>
<style>
body{margin:0;background:#07070C;color:#B4B4C6;font:17px/1.55 -apple-system,"Helvetica Neue",Arial,sans-serif;padding:28px 34px 80px;max-width:1500px}
h1{font-size:34px;margin:0 0 6px;color:#C8C8D2}h2{font-size:26px;margin:46px 0 8px;color:#C8C8D2;border-top:1px solid #1E1E28;padding-top:22px}h3{font-size:19px;margin:26px 0 6px;color:#C8C8D2}
p,li{max-width:1080px}.q{color:#9C9CAE;font-size:13px}
ol.lead{font-size:19px;color:#C8C8D2;max-width:1120px;padding-left:24px}ol.lead li{margin:0 0 12px}
.status{border:1px solid #2A2A36;border-left:4px solid #8A8A9E;padding:12px 16px;margin:18px 0;max-width:1080px;color:#C8C8D2}
.prop{border:1px solid #2A2A36;border-left:4px solid #C8C8D2;padding:12px 16px;margin:14px 0;max-width:1080px}.prop b{color:#C8C8D2}
code{font:14px ui-monospace,Menlo,monospace;color:#BEBECE}
.scroll{overflow-x:auto;max-width:100%}
table{border-collapse:collapse;font-size:14px;margin:10px 0;font-variant-numeric:tabular-nums}th,td{border:1px solid #24242E;padding:6px 9px;text-align:left;vertical-align:top;max-width:520px}th{color:#A8A8BA;font-weight:600;font-size:13px;font-family:ui-monospace,Menlo,monospace}
figure{margin:14px 0;max-width:1400px}figure img{display:block;width:100%;height:auto;background:#0B0B12;border:1px solid #1E1E28}figcaption{color:#9C9CAE;font-size:12px;margin-top:4px;font-family:ui-monospace,Menlo,monospace}
.up{color:#00FFA3}.dn{color:#FF2D55}
.tiles{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;max-width:1400px;margin:14px 0}
.tile{background:#0B0B12;border:1px solid #1E1E28;padding:12px 14px}.tl{font:12px ui-monospace,Menlo,monospace;color:#A0A0B2;text-transform:uppercase;letter-spacing:.05em}.tv{font-size:28px;font-weight:700;color:#D2D2D2;margin:4px 0}.ts{font-size:13px;color:#A0A0B2}
dl{max-width:1120px}dt{color:#C8C8D2;font-weight:600;margin-top:12px}dd{margin:2px 0 0 0}
a{color:#C8C8D2}
@media(max-width:600px){figure{overflow-x:auto}figure img{min-width:900px}body{padding:20px 16px 60px;font-size:16px}h1{font-size:26px}h2{font-size:22px}ol.lead{font-size:17px}table{font-size:12px}th,td{padding:5px 6px}code{overflow-wrap:anywhere}.tiles{grid-template-columns:repeat(2,1fr)}.tv{font-size:22px}}
</style></head><body>
<h1>Pullback playbook: where this pullback is, how the bow tie rebalances, a narrowness gauge, and tranches back-tested</h1>
<p class="q">N1 · 28 Sep 2026 · bars to ${J.asOf} (Friday's close) from the chart API cache${liveAt ? `; today's readings from the chart API's live quotes at ${liveAt}` : ""} · built ${J.generated.slice(0, 16).replace("T", " ")} UTC · research, not advice · nothing here predicts · the numbers live in <code>data/pullback-playbook.json</code></p>

<div class="status"><b>STATUS</b> · every section ran on real data; nothing was deployed, no key, database write or price table was touched. Built on the sector-rotation, statistician-2, leaders, bottoms and regime studies (cited where used, not redone). ${Object.keys(s4.instruments).length} instruments × ${s4.design.depths.length} trigger depths × ${Object.keys(s4.design.strategies).length} tranche strategies were simulated; the Geiger of eleven sector funds and seven index funds was replayed day by day since 2007 with the Hub's own maths (the replay matches the sector-rotation lane's, which matched the live <code>/geiger</code> rung for rung). Thirteen charts saved as images. Every average carries a 90% resampled range; "luck-proof" means the false-discovery check (10%) was passed; "not shown" means the range includes the any-day figure.</div>

<h2>What this page says, in plain words</h2>
<ol class="lead">
<li><b>This is a breadth pullback, not an index pullback.</b> SPY closed Friday ${f(D.SPY.depth)}% below its high of ${D.SPY.highDate}${D.SPY.live ? ` (live today ${f(D.SPY.live.depthLive)}%)` : ""}; QQQ ${f(D.QQQ.depth)}%. Meanwhile equal weight (RSP) is ${f(D.RSP.depth)}% down, small caps (IWM) ${f(D.IWM.depth)}%, and only ${f(B.a50, 0)}% of the ${B.names} served names are above their 50-day (${pct(B.a50Pct)} percentile since 2007). The seven index funds' Geigers are spread ${f(IR.range, 2)} apart — the ${pct(IR.rangePct)} percentile of that gap's history: SPY and QQQ read +${f(IR.today.SPY, 2)} and +${f(IR.today.QQQ, 2)} while IWM, MDY and RSP read ${f(IR.today.IWM, 2)}, ${f(IR.today.MDY, 2)} and ${f(IR.today.RSP, 2)}.</li>
<li><b>Fear is not in the price yet.</b> The put/call's 5-day average is ${f(P.avg5, 2)}, the ${pct(P.avg5Pct)} percentile since 2006 (low = complacent). VIX ${V.live ? `is ${f(V.live.price, 2)} live` : `closed ${f(V.close, 2)}`} — the ${pct(V.live ? V.live.pctAll : V.pctAll)} percentile since 1990, above ${V.live ? V.live.linesBelow : V.linesBelow} of its own thirteen fan lines, and its ratio to the 3-month VIX is ${f(V.ratio, 2)} (calm). SPY's RSI is ${f(R.SPY.rsi, 0)} (${pct(R.SPY.pctAll)} percentile); RSP's and IWM's are ${f(R.RSP.rsi, 0)} and ${f(R.IWM.rsi, 0)} (${pct(R.RSP.pctAll)} and ${pct(R.IWM.pctAll)}). USUAL DAY's 0 up / 20 down so far today is a ${pct(SG.todayNetPct)}-percentile day, not an extreme: ${SG.zeroUpAndAsManyDown} sessions since 2003 had no name up and at least as many down.</li>
<li><b>History's nearest days did not agree on what came next.</b> The 20 days most like today on seven gauges saw a median further fall of ${f(A20.summary.moreDown60.med)}% within 60 sessions (a tenth of them ${f(A20.summary.moreDown60.q10)}% or worse), a median low ${A20.summary.sessionsToLow60.med} sessions later, and SPY ${sg(A20.summary.f126.med)}% after six months (up ${f(A20.summary.f126.up, 0)}% of the time). Against all days none of that is different (section 1.6). What the analogs did agree on: the bow tie narrowed in ${f(100 - A20.summary.wing72.up, 0)}% of them within a quarter.</li>
<li><b>The bow tie narrows by the red wing rising, not the green wing falling.</b> After the widest tenth of readings since 2007 (${wide.dWing72.n} separate starts), the red wing's average Geiger rose ${sg(wide.dRed72.med, 2)} over the next quarter and ${sg(wide.dRed252.med, 2)} over a year (the year figure is luck-proof), while the green wing's moved ${sg(wide.dGreen72.med, 2)} and ${sg(wide.dGreen252.med, 2)}. The wing itself fell back to its median in a median ${W.backToMedian.medianSessions} sessions. The index did its usual thing (SPY ${sg(wide.spy72.med)}% over the quarter against ${sg(wide.spy72.allMed)}% on all days; not different), and equal weight went on trailing: ${sg(wide.rspMinusSpy252.med)} points against SPY over the following year (luck-proof). Rebalancing, in the record, meant the weak sectors stopped weakening; it did not mean cap weight gave the lead back.</li>
<li><b>A narrowness gauge reads ${f(s3.today.narrow, 0)} today, the ${pct(s3.today.pct)} percentile since 2008.</b> It is the mean of six own-history percentiles (bow-tie wing, equal-vs-cap 63-day change, % above the 50-day, index-fund Geiger range, and the two Nasdaq / Russell equal-vs-cap pairs). In its narrowest tenth, SPY's next six months were ordinary (${sg(s3.deciles[9].spy126?.med)}%) and equal weight trailed by a further ${sg(s3.deciles[9].rspMinusSpy126?.med)} points; the leaders basket led by ${sg(s3.deciles[9].leadersMinusSpy126?.med)}. Section 3 says how <code>/allocation</code> should use it: position caps that tighten as it rises, slower tranche pacing until a fear gauge turns, and a leader bias rather than a catch-up bet.</li>
<li><b>Tranches trade return for less pain.</b> On SPY's ${SPY3.n} campaigns triggered 3% below the high since 2003, buying everything at the trigger returned a median ${sg(SPY3.strategies.single.ret126.med)}% after six months with a worst mark-to-cost of ${f(SPY3.strategies.single.worst126.med)}%; the fan ladder returned ${sg(SPY3.strategies.fan.ret126.med)}% with a worst of ${f(SPY3.strategies.fan.worst126.med)}% and ${f(SPY3.strategies.fan.tim.med, 0)}% of the money in the market over the window. The pain reduction is luck-proof on SPY and the leaders; the return cost is luck-proof on the Nasdaq-100 since 1985 (${NDX3 ? NDX3.n : "—"} campaigns, ${NDX3 ? sg(NDX3.strategies.fan.vsSingle.ret126.mean) : "—"} points at six months). The money that did reach a level was bought ${sg(SPY3.strategies.fan.depImprovement.med)}% cheaper than the trigger; what hurts the ladders is the ${f(SPY3.strategies.fan.forced.med, 0)}% left waiting for levels that never came. The state-sized variant (front tranche grows with the VIX percentile) kept most of the pain benefit with less of the return cost (section 4).</li>
<li><b>Wednesday:</b> PCE for August prints at 08:30 ET (${s5.pce.next[0] ? `core MoM estimate ${s5.pce.next[0].estimate}, previous ${s5.pce.next[0].previous}` : ""}); MU reports after the close. On the ${s5.pce.onFile} PCE days on file (from June 2024) SPY's absolute move averaged ${f(s5.pce.summary.absMove, 2)}% against ${f(s5.pce.summary.absMoveAllDays3y, 2)}% on all days. On MU's ${s5.mu.all.n} reaction days since 2004 MU moved ${f(s5.mu.all.muAbs)}% in absolute terms and was up ${f(s5.mu.all.muUp, 0)}% of the time; SPY's median move was ${sg(s5.mu.all.spyMed, 2)}% (${sg(s5.mu.inPullback.spyMed, 2)}% when SPY was already 3% or more off its high, n = ${s5.mu.inPullback.n}). Facts only; the sample is what the Hub holds.</li>
</ol>

<h2>1 · Where this pullback is</h2>
<h3>1.1 · Depth so far</h3>
${tbl(["fund", "Friday close", "252-session high", "high date", "sessions since", "depth Friday", ...(D.SPY.live ? ["live today", "depth live", "day so far"] : []), "depth vs its own days"], ["SPY", "QQQ", "IWM", "RSP", "LEADERS"].map((k) => { const d = D[k]; return [k === "LEADERS" ? "Leaders basket (top-20 by cap, equal weight)" : k, f(d.close, 2), f(d.high, 2), d.highDate, d.sessionsSinceHigh, S(d.depth, 2), ...(D.SPY.live ? [d.live ? f(d.live.price, 2) : "—", d.live ? S(d.live.depthLive, 2) : "—", d.live ? S(d.live.dayPct, 2) : "—"] : []), pct(d.depthPctOfDays) + " percentile of all days' depth"]; }))}
<p class="q">Depth = close ÷ the highest close of the prior 252 sessions − 1. "Live" is the chart API's last trade at ${liveAt ?? "—"}; the day is not over. The leaders basket is each year's top-20 S&P names by market cap on 1 January, equal weight, from the leaders lane's FMP caps (members this year: ${J.sources.LEADERS.thisYear.join(", ")}).</p>
${fig("c1-gauges-today.png", "Chart 1 · seven gauges, each placed in its own history. Red marks the side of each gauge that usually reads stretched (low put/call, low breadth, high wing).")}

<h3>1.2 · Breadth: % above the 50-day and 200-day, for the served names, by sector and by size</h3>
<div class="tiles"><div class="tile"><div class="tl">above the 50-day</div><div class="tv">${f(B.a50)}%</div><div class="ts">${B.names} served names with a 50-day · ${pct(B.a50Pct)} percentile since 2007</div></div><div class="tile"><div class="tl">above the 200-day</div><div class="tv">${f(B.a200)}%</div><div class="ts">same names</div></div><div class="tile"><div class="tl">the Hub's own 23 Sep snapshot</div><div class="tv">36.8%</div><div class="ts">data/breadth/latest.json (364 names above the 50-day)</div></div><div class="tile"><div class="tl">bow-tie wing</div><div class="tv">+${f(BT.wing, 2)}</div><div class="ts">${pct(BT.wingPct)} percentile (sector-rotation study)</div></div></div>
${tbl(["sector (GICS)", "names", "% above 50-day", "% above 200-day"], Object.entries(B.bySector).sort((a, b) => b[1].a50 - a[1].a50).map(([k, v]) => [k, v.n, `<span class="${v.a50 >= 50 ? "up" : "dn"}">${f(v.a50)}%</span>`, `<span class="${v.a200 >= 50 ? "up" : "dn"}">${f(v.a200)}%</span>`]))}
${tbl(["size (today's cap)", "names", "% above 50-day", "% above 200-day"], Object.entries(B.byCap).map(([k, v]) => [k, v.n, `<span class="${v.a50 >= 50 ? "up" : "dn"}">${f(v.a50)}%</span>`, `<span class="${v.a200 >= 50 ? "up" : "dn"}">${f(v.a200)}%</span>`]))}
<p class="q">Measured here from the chart API's daily bars for the Hub's served names (the candles-f5 cache, to ${J.asOf}); sector and cap from data/standard-tree-20260924.json. The history behind the percentile is the same names measured backwards, so the early years overstate breadth (survivors only). The B1 whole-market table (every US common stock) sits on the candidate/breadth branch, not on live, so it is not read here. ${B.hubSnapshot.split(";")[0]}.</p>

<h3>1.3 · VIX and its own fan; the ratio to the 3-month VIX; put/call; RSI</h3>
${tbl(["gauge", "Friday", "today (live)", "own-history percentile", "read"], [
  ["VIX", f(V.close, 2), V.live ? f(V.live.price, 2) : "—", `${pct(V.pctAll)} Friday${V.live ? ` · ${pct(V.live.pctAll)} live` : ""} (since ${V.from})`, `Friday it sat below all thirteen of its fan lines (next above: ${V.nextAbove ? `${V.nextAbove[0]} at ${f(V.nextAbove[1], 2)}` : "—"})${V.live ? `; live it is above ${V.live.linesBelow} of 13 — the fast lines (e21 ${f(V.ema21, 2)}) but not the 50-day (${f(V.sma50, 2)}) or the 200-day (${f(V.sma200, 2)})` : ""}`],
  ["VIX ÷ 3-month VIX", f(V.ratio, 2), "—", `${pct(V.ratioFromRegime?.pctAll)} (regime study)`, "below 1 = calm; the regime study found 10.9% of days inverted since 2006, last on " + (V.ratioFromRegime?.lastInverted ?? "—")],
  ["Put/call, 5-day average (Cboe total)", f(P.avg5, 2), "printed after tonight's close", `${pct(P.avg5Pct)} since ${P.from}`, `last five: ${P.last5.map((x) => x[1]).join(", ")}; its own 50th / 90th / 99th percentiles are ${P.levels["50"]} / ${P.levels["90"]} / ${P.levels["99"]}. Statistician-2 found the 5-day put/call peak the most useful frame before shallow lows (its 90th percentile, 1.20, caught 89% of them)`],
  ...["SPY", "QQQ", "IWM", "RSP"].map((k) => [`RSI(14) · ${k}`, f(R[k].rsi), "—", `${pct(R[k].pctAll)} all history · ${pct(R[k].pct3y)} last 3 years`, k === "SPY" ? "mid-range" : R[k].pctAll < 10 ? "in its bottom tenth" : R[k].pctAll > 70 ? "upper range" : "mid-range"]),
])}
<h3>1.4 · USUAL DAY: today's 0 up / 20 down against 23 years of sessions</h3>
<div class="tiles"><div class="tile"><div class="tl">today so far</div><div class="tv">0 ↑ 20 ↓</div><div class="ts">of ${SG.today.m} names · net ${f(SG.today.net)}% of names · ${pct(SG.todayNetPct)} percentile of ${SG.sessions} sessions</div></div><div class="tile"><div class="tl">down-share percentile</div><div class="tv">${pct(SG.todayDnPct)}</div><div class="ts">${f(SG.today.dnShare)}% of names beyond their usual day on the downside</div></div><div class="tile"><div class="tl">sessions with none up</div><div class="tv">${SG.zeroUpDays}</div><div class="ts">${SG.zeroUpAndAsManyDown} of them with at least as many down as today</div></div><div class="tile"><div class="tl">SPY after days this one-sided</div><div class="tv">${sg(SG.likeToday["63"].like.med)}%</div><div class="ts">median over 63 sessions, ${SG.picks} separate days · all days ${sg(SG.likeToday["63"].all.med)}% · difference ${rng(SG.likeToday["63"])}</div></div></div>
${tbl(["session", "up", "down", "names measured"], SG.last10.map((r) => [r[0], r[1], r[2], r[3]]))}
<p class="q">Source: <code>public.sigma_day_counts</code> (one row per session since ${SG.from}, each name's close against its previous close measured against its own 60-session usual day, written by the USUAL DAY lane's backfill), read the way the Hub page reads it. Today's 0 / 20 is the live detector's count at about 13:30 ET as Alan read it; it is not a closed session and is not in the table. Recent sessions with none up and at least as many down as today: ${SG.zeroUpAndAsManyDownDates.slice(-6).map((r) => `${r[0]} (${r[1]} down)`).join(", ")}.</p>
${fig("c3-sigma-history.png", "Chart 3 · every session's net (up − down as a share of names measured), 2003 →, with today's line.")}
<p>By decile of that net, SPY's next 21 and 63 sessions: ${SG.deciles.map((r) => `decile ${r.decile} (${f(r.lo)} to ${f(r.hi)}): ${sg(r.f21.med)} / ${sg(r.f63.med)}`).join("; ")}. The one-sided days (decile 1) were followed by ordinary returns; the USUAL DAY count is a description of today, not a signal on its own.</p>

<h3>1.5 · Each day it continues: the depth ladder</h3>
<p>Every pullback from a closing high in the S&P 500 since ${LD["^GSPC"].from.slice(0, 4)} (${LD["^GSPC"].episodes} completed) and in SPY since 2003 (${LD.SPY.episodes}). Read the row for the depth already reached; the current SPY pullback began ${LD.SPY.current?.start ?? "—"}, reached ${f(LD.SPY.current?.depth)}% at its low of ${LD.SPY.current?.lowDate ?? "—"}, and reached that low ${LD.SPY.current?.above200AtLow ? "above" : "below"} its 200-day.</p>
${tbl(["reached (closing, %)", "S&P 500 episodes", "median final depth", "middle half", "went ≥ 5 pts deeper", "the low was within 1 pt", "median sessions still to the low", "SPY episodes", "SPY median final depth", "SPY went ≥ 5 deeper"], curve("^GSPC").map((r) => { const s = LD.SPY.curve.find((x) => x.x === r.x) || {}; return [r.x, r.n, f(r.finalMed), `${f(r.finalQ[1])} – ${f(r.finalQ[3])}`, `${f(r.pGoesOn5, 0)}%`, `${f(r.lowWithin1, 0)}%`, r.toLowMed, s.n ?? "—", s.n >= 5 ? f(s.finalMed) : "—", s.n >= 5 ? `${f(s.pGoesOn5, 0)}%` : "—"]; }))}
<p class="q">Conditioned on the market state first (rule R7): the state that matters is where price stood WHEN the depth was reached (every pullback starts above a rising 200-day, so the state at the high is no split). S&P 500: ${[3, 5, 8].map((x) => { const b = LD["^GSPC"].byReach[x]; return `reached ${x} still above the 200-day → median final ${f(b.above200.finalMed)}, ${f(b.above200.pGoesOn5, 0)}% went 5 deeper (n ${b.above200.n}); reached ${x} already below it → median final ${f(b.below200.finalMed)}, ${f(b.below200.pGoesOn5, 0)}% (n ${b.below200.n})`; }).join("; ")}. SPY's current episode reached its low ${LD.SPY.current?.above200AtLow ? "above" : "below"} the 200-day and sits ${LD.SPY.current?.above200Now ? "above" : "below"} it now. The current episode is open and is not counted (rule R9). QQQ and the Nasdaq-100 index curves are in the JSON.</p>
${fig("c2-depth-ladder.png", "Chart 2 · once a pullback has reached x, how deep did it end? Median final depth (line), middle half (band), and the share that went at least 5 points deeper (dotted).")}

<h3>1.6 · The analogs: days with a similar confluence, and what they did</h3>
<p>Each day since ${AN.from} was placed on seven gauges as an own-history percentile: SPY's depth from its high, SPY's RSI, VIX, the put/call 5-day average, % above the 50-day, the bow-tie wing, and USUAL DAY's net. Today reads ${AN.keys.map((k) => `${k} ${f(AN.today[k], 0)}`).join(" · ")}. The nearest days (root-mean-square distance across the gauges, at least 40 sessions apart, nothing from the last 60 sessions):</p>
${tbl(["date", "distance", "SPY depth then", "further fall within 60", "sessions to that low", "SPY +21", "SPY +63", "SPY +126", "RSP − SPY, 63", "wing change, 72"], A20.list.map((x) => [x.d, f(x.dist), S(x.depthThen, 2), S(x.moreDown60, 2), x.sessionsToLow60, S(x.f21, 2), S(x.f63, 2), S(x.f126, 2), S(x.rspRel63, 2), S(x.wing72, 2)]))}
${tbl(["nearest K", "further fall, median (10th pct)", "sessions to the low", "SPY +63 median", "SPY +126 median (up %)", "RSP − SPY 63", "wing narrowed within 72", "further fall vs all days", "SPY +126 vs all days"], Object.values(AN.variants).map((v) => [v.k, `${f(v.summary.moreDown60.med)} (${f(v.summary.moreDown60.q10)})`, v.summary.sessionsToLow60.med, sg(v.summary.f63.med), `${sg(v.summary.f126.med)} (${f(v.summary.f126.up, 0)}%)`, sg(v.summary.rspRel63.med), `${f(100 - (v.summary.wing72?.up ?? 0), 0)}%`, rng(v.tests.moreDown60), rng(v.tests.f126)]))}
${fig("c4-analogs.png", "Chart 4 · the 20 nearest days: further fall within 60 sessions, SPY 63 sessions later, equal weight minus SPY over 63 sessions. Dashed = the all-days median.")}
<p>Reading: nothing in the analogs separates from any day once the ranges are drawn (the sample is ${A20.list.length} days, and they include 21 Feb 2020 as well as 21 Apr 2017). Two things recur: the tie narrowed, and equal weight did not catch up over the following quarter.</p>
<p class="q">Is this "the one" or too early inside the yields-up / dollar-up window? Statistician-2 measured it: in the ${Y.today.regimeLevel} regime (both above their 200-day) SPY's typical drawdown-from-high was ${f(Y.spy.defs.level.regimes["yield up · dollar up"].med)}% against ${f(Y.spy.defs.level.base.med)}% on all days, with ${f(Y.spy.defs.level.regimes["yield up · dollar up"].s5, 0)}% of days 5% or more under the high against ${f(Y.spy.defs.level.base.s5, 0)}% — wider, but the ranges overlap (not shown). Today: 10-year ${Y.today.y10}% vs its 200-day ${Y.today.y200}%, dollar ${Y.today.dxy} vs ${Y.today.d200}. The regime says deeper pullbacks have been more common; it does not say this one has further to go.</p>

<h2>2 · The bow tie: how far it rebalances, over what time, by which wing</h2>
<p>The sector-rotation study defined the tie (the shorter of the green and red wings of the eleven SPDR sector Geigers) and found today's +${f(BT.wing, 2)} the widest in the record. This section replays the same Geiger day by day (${W.n} sessions since ${W.from}, weekly in the earlier study) and asks what happened next at every horizon, by decile of the wing's own percentile, and for the widest tenth against all days.</p>
${fig("c5-wing-daily.png", "Chart 5 · the shorter wing every session since 2007 with its median; today " + f(W.today.wing, 2) + ".")}
${tbl(["after the widest tenth (" + wide.dWing72.n + " starts)", "16 sessions", "38", "72", "126", "252"], [
  ["wing change (median; all days)", ...[16, 38, 72, 126, 252].map((h) => `${sg(wide["dWing" + h].med, 2)} (${sg(wide["dWing" + h].allMed, 2)}) · ${word(wide["dWing" + h])}`)],
  ["green wing: change of its average Geiger", ...[16, 38, 72, 126, 252].map((h) => `${sg(wide["dGreen" + h].med, 2)} (${sg(wide["dGreen" + h].allMed, 2)}) · ${word(wide["dGreen" + h])}`)],
  ["red wing: change of its average Geiger", ...[16, 38, 72, 126, 252].map((h) => `${sg(wide["dRed" + h].med, 2)} (${sg(wide["dRed" + h].allMed, 2)}) · ${word(wide["dRed" + h])}`)],
  ["top-3 minus bottom-3 sector return, pts", ...[16, 38, 72, 126, 252].map((h) => `${sg(wide["topMinusBottom" + h].med)} (${sg(wide["topMinusBottom" + h].allMed)}) · ${word(wide["topMinusBottom" + h])}`)],
  ["SPY return, %", ...[16, 38, 72, 126, 252].map((h) => `${sg(wide["spy" + h].med)} (${sg(wide["spy" + h].allMed)}) · ${word(wide["spy" + h])}`)],
  ["RSP minus SPY, pts", ...[16, 38, 72, 126, 252].map((h) => `${sg(wide["rspMinusSpy" + h].med)} (${sg(wide["rspMinusSpy" + h].allMed)}) · ${word(wide["rspMinusSpy" + h])}`)],
  ["spread of the seven index funds' returns (IQR), pts", ...[16, 38, 72, 126, 252].map((h) => `${f(wide["idxDisp" + h].med)} (${f(wide["idxDisp" + h].allMed)}) · ${word(wide["idxDisp" + h])}`)],
])}
<p><b>How far and how fast.</b> The wing came back to its median (${f(W.medianWing, 2)}) in a median ${W.backToMedian.medianSessions} sessions from a widest-tenth start (${W.backToMedian.censored} start still open). Over a quarter it fell ${sg(wide.dWing72.med, 2)} — luck-proof, and mostly what extremes do.</p>
<p><b>Which wing.</b> The red wing rose at every horizon (${sg(wide.dRed38.med, 2)} at 38 sessions, ${sg(wide.dRed252.med, 2)} at a year; the 38- and 252-session figures pass the false-discovery check against all days) while the green wing's average barely moved. In Geiger terms the weak sectors stop reading weak; the strong ones keep reading strong.</p>
<p><b>What it meant for the indexes.</b> SPY's returns after wide ties were ordinary at every horizon (not shown against all days), and the spread of the seven index funds' returns was not wider than usual. What did differ: equal weight kept losing to cap weight — ${sg(wide.rspMinusSpy252.med)} points over the following year (${rng(wide.rspMinusSpy252)}). Alan's "rebalancing by definition means mixed index performance" holds in the sense that the wings converge in Geiger terms; it does not show up as the cap-weighted index stalling while equal weight catches up. ${W.tests} comparisons were made; ${W.survivors} survive the false-discovery check (the wing changes, two red-wing changes, and the one-year equal-vs-cap figure).</p>
${fig("c6-which-wing.png", "Chart 6 · by decile of the wing's own percentile: the green wing's change, the red wing's change, and the wing itself, 16 and 72 sessions later.")}
<h3>2.1 · The index-fund Geiger range, today and historically</h3>
<div class="tiles">${IR.funds.map((s) => `<div class="tile"><div class="tl">${s}</div><div class="tv ${col(IR.today[s])}">${sg(IR.today[s], 2)}</div><div class="ts">${IR.fundPct[s] ? pct(IR.fundPct[s].pct) + " percentile of its own Geiger" : ""}</div></div>`).join("")}<div class="tile"><div class="tl">range, best − worst</div><div class="tv">${f(IR.range, 2)}</div><div class="ts">${pct(IR.rangePct)} percentile since ${IR.from} · median ${f(IR.quantiles["50"], 2)}, 90th ${f(IR.quantiles["90"], 2)}, 99th ${f(IR.quantiles["99"], 2)}</div></div></div>
${fig("c7-index-range.png", "Chart 7 · the index-fund Geiger range every session since 2007; today " + f(IR.range, 2) + ".")}
<p>By decile of the range, SPY's next quarter and RSP − SPY: ${IR.deciles.map((r) => `${r.decile}: ${sg(r.spy63.med)} / ${sg(r.rspMinusSpy63.med)}`).join("; ")}. The wider the range between the index funds, the more equal weight went on trailing over the next quarter (deciles 3–10 negative). A Geiger tab for the index funds that shows each fund's percentile and this range is a small build (the replay is <code>research/statistics/sector-rotation/lib.mjs</code>); proposed below.</p>

<h2>3 · Narrowness: a measurable gauge, and how the allocation tool should use it</h2>
<h3>3.1 · The gauge</h3>
<p><b>NARROW</b> = the mean of six own-history percentiles, each read so that higher = narrower: ${s3.components.map((c, i) => `(${i + 1}) ${c}`).join("; ")}. A reading needs at least three of the six. Today: ${s3.today.parts.map((p, i) => `(${i + 1}) ${p == null ? "—" : f(p, 0)}`).join(", ")} → <b>${f(s3.today.narrow, 0)}</b>, the ${pct(s3.today.pct)} percentile since ${s3.from}.</p>
${fig("c8-narrowness.png", "Chart 8 · NARROW every session since 2008; today " + f(s3.today.narrow, 0) + ".")}
${tbl(["NARROW decile", "range", "SPY +63", "SPY +126", "RSP − SPY, 63", "RSP − SPY, 126", "leaders − SPY, 126", "SPY worst within 63"], s3.deciles.map((r) => [r.decile, `${f(r.lo, 0)}–${f(r.hi, 0)}`, S(r.spy63?.med), S(r.spy126?.med), S(r.rspMinusSpy63?.med), S(r.rspMinusSpy126?.med), S(r.leadersMinusSpy126?.med), S(r.dd63?.med)]))}
<p>Narrowest tenth against all days (${s3.topPicks} separate starts): SPY +126 ${rng(s3.top.spy126)}; RSP − SPY over 126 ${rng(s3.top.rspMinusSpy126)}; leaders − SPY over 126 ${rng(s3.top.leadersMinusSpy126)}; SPY's worst within 63 ${rng(s3.top.dd63)}. None of the six survive the false-discovery check: the gauge describes the regime, it does not forecast the index. Its consistent message across deciles is that equal weight kept trailing after narrow readings — the same persistence the sector-rotation study found at multi-year spans.</p>
${fig("c9-narrow-followed.png", "Chart 9 · by NARROW decile: SPY 126 sessions later, equal weight minus SPY, leaders basket minus SPY.")}
<h3>3.2 · The seven weakest equal-vs-cap pairs (from statistician-2, not redone)</h3>
${tbl(["pair (equal ÷ cap)", "level percentile, all history", "1-year change", "stretch vs its 1-year mean", "past extremes", "cap-weight fund +63 after them", "cap fund +252", "equal ÷ cap +63 (rebalancing)", "equal ÷ cap +252"], s3.seven.rows.map((r) => [`${r.label} (${r.ew} ÷ ${r.cw})`, pct(r.levelPctAll), S(r.change252), S(r.stretch), r.lows, S(r.after.cw63), S(r.after.cw252), S(r.after.ratio63), S(r.after.ratio252)]))}
<p>Statistician-2's reading stands: after past extremes of the S&P pair (${s3.seven.spx.summ.spy63.n} entries at the 5th percentile) SPY rose a median ${sg(s3.seven.spx.summ.spy126.med)}% in six months, the leaders basket ${sg(s3.seven.spx.summ.lead126.med)}%, and equal weight's catch-up over the same span was ${sg(s3.seven.spx.summ.catchUp126.med)} points (up ${f(s3.seven.spx.summ.catchUp126.up, 0)}% of the time). Over the past year SPY is ${sg(s3.seven.sectors1y.spy)}%, RSP ${sg(s3.seven.sectors1y.rsp)}%, the leaders basket ${sg(s3.seven.sectors1y.leaders)}%, and the median served stock ${sg(s3.seven.sectors1y.stockMed)}% (${f(s3.seven.sectors1y.stockUp, 0)}% of them up). Top-10 contribution share (leaders study): ${s3.top10.years.filter((y) => y.share10 != null).map((y) => `${y.year} ${f(y.share10, 0)}%${y.partial ? " so far" : ""}`).join(", ")}.</p>
<h3>3.3 · Proposal: how <code>/allocation</code> should read NARROW (not built)</h3>
<div class="prop"><b>Where it plugs in.</b> The allocation page already runs heat → sectors (tape heat × rotation × cohorts) → knockout, with a breadth leg whose weight is a slider. NARROW is a fourth reading on the same footing, computed nightly by this study's run (one JSON line per day) and read by the page like the breadth snapshot, with its date printed.</div>
<div class="prop"><b>1 · Position caps that tighten with narrowness.</b> Single-name cap = base cap × (1 − 0.5 × NARROW/100), so at today's ${f(s3.today.narrow, 0)} a 10% base cap becomes ${f(10 * (1 - 0.5 * s3.today.narrow / 100))}%. Reason: in a narrow tape the winners are few and the giants carry the index by arithmetic (leaders study); a cap that shrinks as narrowness rises stops one name from becoming the portfolio, without forbidding the leaders.</div>
<div class="prop"><b>2 · Tranche pacing keyed to fear, not to narrowness alone.</b> Narrow readings did not forecast the index (3.1), but the put/call and VIX did mark shallow lows (statistician-2, bottoms). Pace = the state-sized ladder of section 4: the first tranche's share = max(equal share, VIX own-percentile ÷ 200), the rest at the fan lines below. Today the VIX percentile is ${f(V.live ? V.live.pctAll : V.pctAll, 0)} and the put/call is at its ${pct(P.avg5Pct)} percentile, so the front tranche stays small and the ladder waits; when the put/call 5-day average crosses its own 90th percentile (${P.levels["90"]}) the front share rises.</div>
<div class="prop"><b>3 · Leader bias, not catch-up.</b> After narrow readings equal weight kept trailing (3.1, 2), and after wide ties the red wing rose in Geiger terms without cap weight giving back the lead. So the sector leg should keep its leader bias (the tape heat × rotation score as it is) and the knockout should not admit a name only because its sector is the red wing and "due". A red-wing name earns admission by its own Geiger components: trend turning up with weak momentum (Alan's screen), which is what "the red wing rises" looks like name by name.</div>
<div class="prop"><b>4 · What the page prints.</b> NARROW and its percentile, the six components, the cap it implies, and the pacing state (waiting / front-loading) with the two triggers named. A tranche that fired writes a line in the actions list with its level and rung name, the same as the existing actions.</div>

<h2>4 · The tranche playbook, back-tested (research, not advice)</h2>
<p><b>The fan.</b> The Lab's EMA/SMA Fan (Pine v19, the "Lengths" group) has thirteen lines: EMA 2, 3, 5, 8, 13, 21, 34, 50; SMA 50, 100, 150, 200 daily; and the 200-week SMA. Alan's memory of 13 is right. The Station's nested clouds draw four of them (e13, e21, s50, s200) and the Geiger reads nine. Here every line is computed from daily closes (the weekly one from completed weeks) and a level for day i is the line's value at the close of day i−1, exactly as the Pine reads the previous completed bar.</p>
<p><b>The design.</b> A campaign opens at the first close a stated depth below the 252-session high (one per pullback; the next needs a new high). Money = 1, spread over ${s4.design.window} sessions. ${Object.entries(s4.design.strategies).map(([k, v]) => `<b>${k}</b>: ${v}`).join(". ")}. ${s4.design.rules}. Outcomes: average cost against the trigger close; return on cost at 63, 126 and 252 sessions; the worst mark-to-cost within 126 sessions (the pain); time in market (average share of the money deployed over the window); the share left unfilled and bought at the window's close; and, separately, the cost and return of the money that did reach a level.</p>
${fig("c10-tranches.png", "Chart 10 · campaigns triggered 3% below the high on SPY and QQQ: medians per strategy for cost improvement, worst mark-to-cost, return at 126 sessions and time in market.")}
${["SPY", "QQQ", "LEADERS", "^NDX"].filter((k) => s4.instruments[k]).map((k) => { const I = s4.instruments[k], B3 = I.byDepth["3"]; return `<h3>4.${["SPY", "QQQ", "LEADERS", "^NDX"].indexOf(k) + 1} · ${k === "LEADERS" ? "Leaders basket" : k === "^NDX" ? "Nasdaq-100 index (long history, 1985 →)" : k} · ${B3.n} campaigns at 3% since ${I.from.slice(0, 4)}</h3>` + tbl(["strategy", "rungs", "cost vs trigger", "money that reached a level", "its cost vs trigger", "its return +126", "return +63", "+126", "+252", "worst mark-to-cost (126)", "time in market", "forced at the end", "vs single: worst", "vs single: +126", "vs single: +252"], ["single", "dca", "fan", "pivots", "rsi", "all", "state"].map((s) => { const o = B3.strategies[s], v = o.vsSingle || {}; return [s, f(o.rungs?.med, 0), S(o.improvement?.med, 2), `${f(o.depShare?.med, 0)}%`, S(o.depImprovement?.med, 2), S(o.depRet126?.med), S(o.ret63?.med), S(o.ret126?.med), S(o.ret252?.med), S(o.worst126?.med), `${f(o.tim?.med, 0)}%`, `${f(o.forced?.med, 0)}%`, s === "single" ? "—" : rng(v.worst126), s === "single" ? "—" : rng(v.ret126), s === "single" ? "—" : rng(v.ret252)]; })) + `<p class="q">${I.tests} comparisons against single entry across ${Object.keys(I.byDepth).length} trigger depths; ${I.survivors} survive the false-discovery check. Medians shown; "vs single" is the mean paired difference with its 90% range. By state at the trigger: ${Object.entries(B3.strategies.fan.byState).map(([st, v]) => `${st} n ${v.n}: fan +126 ${sg(v.ret126?.med)} vs single ${sg(B3.strategies.single.byState[st]?.ret126?.med)}, worst ${f(v.worst126?.med)} vs ${f(B3.strategies.single.byState[st]?.worst126?.med)}`).join("; ")} — a 3% trigger almost always fires while price is still above the 200-day, so the "below a falling 200-day" state (the 1-in-10 hard falls) is not reached by this design and needs a deeper trigger (the 7% and 10% rows in the JSON).</p>`; }).join("")}
${fig("c11-by-depth.png", "Chart 11 · SPY, by trigger depth: cost improvement and worst mark-to-cost for the DCA, fan, RSI and state-sized ladders; single entry's worst as the line.")}
<p><b>What the back-test says.</b> (1) Levels buy cheaper when they come: the money that reached a fan line, a pivot or an RSI rung was bought ${sg(SPY3.strategies.fan.depImprovement.med)}% to ${sg(SPY3.strategies.all.depImprovement.med)}% under the trigger on SPY, and its six-month return was ${sg(SPY3.strategies.fan.depRet126.med)}% to ${sg(SPY3.strategies.all.depRet126.med)}% against ${sg(SPY3.strategies.single.ret126.med)}% for the trigger buy. (2) Levels often never come: ${f(SPY3.strategies.fan.forced.med, 0)}% (fan) to ${f(SPY3.strategies.pivots.forced.med, 0)}% (pivots) of the money was still waiting at 60 sessions and bought at that day's close, usually higher. That is the whole cost of the ladders, and on the Nasdaq-100's ${NDX3?.n ?? "—"} campaigns since 1985 it is luck-proof: ${NDX3 ? sg(NDX3.strategies.fan.vsSingle.ret126.mean) : "—"} points at six months for the fan, ${NDX3 ? sg(NDX3.strategies.rsi.vsSingle.ret126.mean) : "—"} for the RSI ladder. (3) The pain benefit is real and luck-proof on SPY and the leaders: worst mark-to-cost improves by ${sg(SPY3.strategies.fan.vsSingle.worst126.mean)} (fan) to ${sg(SPY3.strategies.all.vsSingle.worst126.mean)} (all) points, and only ${f(SPY3.strategies.all.tim.med, 0)}% to ${f(SPY3.strategies.rsi.tim.med, 0)}% of the money sits in the market over the window. (4) Time DCA is the worst of both: no cheaper cost (${sg(SPY3.strategies.dca.improvement.med)}%), no pain benefit, and the return cost. (5) The state-sized ladder (front tranche grows with the VIX percentile) kept the pain benefit (${sg(SPY3.strategies.state.vsSingle.worst126.mean)}) with the smallest return cost among the ladders on the Nasdaq-100 (${NDX3 ? sg(NDX3.strategies.state.vsSingle.ret126.mean) : "—"}), and returned ${sg(SPY3.strategies.state.ret252.med)}% at a year on SPY against ${sg(SPY3.strategies.single.ret252.med)}% for single entry.</p>
<div class="prop"><b>Proposal · the playbook as a rule set.</b> Trigger at 3% below the high (the depth ladder says the median such pullback ends at ${f(LD["^GSPC"].curve.find((r) => r.x === 3)?.finalMed)}% and ${f(LD["^GSPC"].curve.find((r) => r.x === 3)?.pGoesOn5, 0)}% go 5 points deeper). Front tranche = max(equal share, VIX percentile ÷ 200), at the trigger close. The rest at the fan lines below the trigger, one limit each, plus the last swing low and the rising diagonal when they sit under the lowest fan line. Add an RSI rung (own percentile ≤ 5) that fills at the close whatever the price. Unfilled money after 60 sessions: keep it, do not force it — the back-test forced it only to compare on equal money; in practice that cash is the next campaign's front tranche. Re-size by market state: below a falling 200-day, halve every tranche and double the window (the 1-in-10 hard falls; not reached at a 3% trigger, so this rule is untested here and is the next study).</div>
${fig("c12-example.png", "Chart 12 · a worked campaign on SPY after the 3% trigger of " + (s4.example?.d ?? "—") + ": every rung, the fills at levels (triangles) and the rungs still waiting at 60 sessions (crosses).")}
<p class="q">The worked example (${s4.example?.d ?? "—"}, trigger ${f(s4.example?.trigger, 2)}, average cost ${f(s4.example?.avgCost, 2)}) is the honest picture of a shallow pullback: ${s4.example ? s4.example.fills.filter((x) => !x.forced).length : "—"} of ${s4.example?.fills.length ?? "—"} rungs filled at their levels (${s4.example ? s4.example.fills.filter((x) => !x.forced).map((x) => `${x.rung} ${f(x.px, 2)}`).join(", ") : ""}); the rest waited for lows that did not come while the index recovered.</p>

<h2>5 · Wednesday: PCE and MU, facts only</h2>
<p><b>On the calendar.</b> ${s5.pce.next.map((r) => `${r.event} (estimate ${r.estimate ?? "—"}, previous ${r.previous ?? "—"})`).join("; ")} — all at ${s5.pce.next[0]?.time_utc ?? "12:30"} UTC (08:30 ET) on Wednesday 30 September, from the Hub's economic calendar. MU's call dates on file run quarterly (${s5.mu.rows.filter((r) => r.kind.startsWith("call")).map((r) => r.kind.slice(5)).join(", ")}); Alan's note puts this quarter's report on Wednesday after the close.</p>
${tbl(["PCE release day", "SPY move that day", "day's range", "SPY depth the day before", "in a ≥3% pullback", "the week (5 sessions)"], s5.pce.rows.map((r) => [r.d, S(r.move, 2), f(r.range, 2), S(r.depthBefore, 2), r.inPullback3 ? "yes" : "", S(r.week, 2)]))}
<p>${s5.pce.onFile} releases on file (${s5.pce.from} →). SPY's absolute move on PCE days averaged ${f(s5.pce.summary.absMove, 2)}% against ${f(s5.pce.summary.absMoveAllDays3y, 2)}% on all days of the last three years; up ${f(s5.pce.summary.upShare, 0)}% of the time. The ${s5.pce.summary.inPullback.length} releases that landed inside a 3%-or-deeper pullback: ${s5.pce.summary.inPullback.map((r) => `${r.d} (${f(r.depthBefore)}% down before): day ${sg(r.move, 2)}%, week ${sg(r.week, 2)}%`).join("; ")}. ${s5.pce.note}.</p>
${tbl(["MU reaction day", "how the date is known", "MU", "SMH", "SPY", "SPY depth the day before", "in a ≥3% pullback", "SPY next 5"], s5.mu.rows.slice(-24).map((r) => [r.reactionDay, r.kind, S(r.mu, 2), S(r.smh, 2), S(r.spy, 2), S(r.depthBefore, 2), r.inPullback3 ? "yes" : "", S(r.spyNext5, 2)]))}
<p>All ${s5.mu.all.n} reaction days (${s5.mu.known} dated calls, ${s5.mu.inferred} inferred from volume): MU's absolute move ${f(s5.mu.all.muAbs)}%, up ${f(s5.mu.all.muUp, 0)}% of the time; SMH median ${sg(s5.mu.all.smhMed, 2)}%; SPY median ${sg(s5.mu.all.spyMed, 2)}%, next five sessions ${sg(s5.mu.all.spyNext5Med, 2)}%. When SPY was already 3% or more off its high (n ${s5.mu.inPullback.n}): MU ${f(s5.mu.inPullback.muAbs)}% absolute, up ${f(s5.mu.inPullback.muUp, 0)}%; SPY ${sg(s5.mu.inPullback.spyMed, 2)}%, next five ${sg(s5.mu.inPullback.spyNext5Med, 2)}%. When it was not (n ${s5.mu.notInPullback.n}): MU up ${f(s5.mu.notInPullback.muUp, 0)}%; SPY ${sg(s5.mu.notInPullback.spyMed, 2)}%, next five ${sg(s5.mu.notInPullback.spyNext5Med, 2)}%. ${s5.mu.note}</p>
${fig("c13-wednesday.png", "Chart 13 · SPY on MU's reaction days (left) and on PCE days (right); a tick marks days when SPY was already 3% or more off its high.")}

<h2>6 · Proposals beyond the brief</h2>
<ul>
<li><b>A nightly "where the pullback is" line.</b> This run takes ${J.reps ? "under a minute" : "a minute"} on cached bars. Run it after the close on Fly (the bars come from the chart API, no key) and append one row per day — depth, breadth, VIX percentile and fan position, put/call 5-day percentile, RSI percentiles, USUAL DAY net, wing, index-fund range, NARROW — to a small additive table. The Hub's stats tab reads the last row; the allocation page reads NARROW and the pacing state from it.</li>
<li><b>An index-funds Geiger tab</b> (Alan, 13:30: "Index-funds bow tie tab; index Geiger range"): the seven funds as a strip like the sector bow tie, each with its own-history percentile, and the range's percentile as the headline. The replay exists; the page is small.</li>
<li><b>The deep-state tranche study.</b> Triggers at 7% and 10% with the window doubled and tranches halved below a falling 200-day, measured on the 1-in-10 hard falls that statistician-2 characterised. The 3% design cannot see that state.</li>
<li><b>Breadth by cohort every day, from the served names</b> — the % above the 50-day by GICS sector and size tranche above is a one-liner on the same nightly job, and it is what Alan asked for at 13:30 ("% above 50-day by cohort now").</li>
<li><b>Which wing, name by name.</b> Section 2 says the red wing rises in Geiger terms. The next question is which components move first (trend or momentum) in red-wing names that go on to lead — the "strong trend + weak momentum" screen Alan wants, tested on the past red wings.</li>
</ul>

<h2>7 · Where each number comes from</h2>
${tbl(["series", "source", "from", "to", "bars"], Object.entries(J.sources).filter(([k]) => ["SPY", "QQQ", "IWM", "RSP", "VIX", "PCC", "^GSPC", "^NDX", "^VIX3M", "LEADERS", "MU", "SMH", "XLK", "XLU", "DIA", "MDY", "VTI", "QQQE", "EQAL", "IWB"].includes(k)).map(([k, v]) => [k, esc(v.src), v.from, v.to, v.bars]))}
<p class="q">Plus ${Object.keys(J.sources).length - 20} more served names for breadth (the candles-f5 cache). Public tables read the way the Hub page reads them, copied into <code>research/statistics/data/pullback-playbook-20260928/</code>: <code>sigma_day_counts</code> (${SG.sessions} sessions), <code>econ_calendar</code> (PCE rows), <code>earnings_call_transcripts</code> (MU call dates). Live quotes: the chart API's <code>/quote</code> and <code>/macro</code> at ${liveAt ?? "—"}. Cited studies: sector-rotation (the bow tie and its wing history), statistician-2 (the seven pairs, put/call frames, the yields-up regime), leaders (top-10 shares, the leaders basket definition), regime (VIX ÷ 3-month VIX), bottoms (the pullback list this page's analogs were checked against).</p>

<h2>8 · What could be wrong</h2>
<ul>
<li><b>Breadth history is survivors only.</b> The % above the 50-day is measured on today's served list backwards, so early years read healthier than they were. The whole-market table on the B1 branch fixes this once it is on live.</li>
<li><b>Today's readings are live, not closes.</b> SPY's depth, VIX's fan position and USUAL DAY's 0 / 20 are from about 13:50 UTC; the close can differ. The put/call for today does not exist until tonight.</li>
<li><b>The analogs are a description.</b> Seven gauges, equal weights, root-mean-square distance: a different choice of gauges gives a different twenty. That is why three K's are shown and nothing separates from any day.</li>
<li><b>The bow-tie replay reads completed 3-day and weekly buckets only</b> (the same rule the sector-rotation lane used), and the 1d rung is fast: the "back to median in ${W.backToMedian.medianSessions} sessions" is partly the 1d rung's own speed.</li>
<li><b>The tranche design forces unfilled money in at 60 sessions</b> so strategies compare on equal money; a real campaign would keep the cash. The "money that reached a level" columns show the other side. Fills assume a limit at the line's prior-close value gets the line price (or the open on a gap); real fills can be worse. No costs, no dividends, no slippage.</li>
<li><b>Pivots and diagonals are one definition</b> (symmetric 10-bar swings; the diagonal through the last two lows; the parallel at the deepest gap between them). The Station's diagonals may be drawn differently; the Lab should confirm.</li>
<li><b>MU's earlier report days are inferred</b> from volume (the highest-volume day in each quarterly window, at least twice its prior month). A few could be wrong days. The eight dated calls are exact.</li>
<li><b>PCE history is short</b> (June 2024 →). Older release days are not inferred.</li>
<li><b>Multiple testing.</b> ${W.tests + Object.keys(s3.top).length + Object.values(s4.instruments).reduce((s, i) => s + i.tests, 0) + Object.values(AN.variants).reduce((s, v) => s + Object.keys(v.tests).length, 0)} comparisons were made on this page; the false-discovery check was applied within each section, not across the whole page.</li>
</ul>

<h2>9 · What was not done</h2>
<ul>
<li>Nothing was deployed and the allocation page was not changed: section 3.3 is a proposal.</li>
<li>The deep-state (below a falling 200-day) tranche rule is stated but not tested (section 4).</li>
<li>The whole-market breadth (B1) was not read: it is not on the live branch.</li>
<li>Kimi's and other public tranche / DCA repositories were not searched this lane; the design here is Alan's own description (fan, diagonals, supports, RSI) made measurable.</li>
<li>Today's close was not waited for; re-running <code>node research/statistics/pullback-playbook/run.mjs</code> after the bars update refreshes every number and chart (<code>charts.py</code>, <code>page.mjs</code>).</li>
</ul>
<p class="q">Files: <code>research/statistics/pullback-playbook/{lib,run,page}.mjs</code>, <code>charts.py</code>; <code>tests/pullback-playbook.test.mjs</code>; this page, <code>data/pullback-playbook.json</code>, <code>charts/*.png</code>.</p>
</body></html>`;
fs.writeFileSync(path.join(DIR, "PULLBACK-PLAYBOOK.html"), html);
console.log("wrote", path.join(DIR, "PULLBACK-PLAYBOOK.html"), (html.length / 1024) | 0, "KB");
