/* CP4 · the page for Alan: deliverables/20261007/comps-engine/COMPS-ENGINE.html — pictures first, plain words, the twelve names before → after,
   each yardstick's weight and the consistency flags, the peer sets old → new, the defaults he accepts, what was not done. Reads the artifact. */
import { readFileSync, writeFileSync, existsSync } from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
const HERE = path.dirname(fileURLToPath(import.meta.url)), OUT = path.resolve(HERE, "../COMPS-ENGINE.html"), DATA = path.resolve(HERE, "../data"), SHOTS = path.resolve(HERE, "../shots");
const J = (p) => JSON.parse(readFileSync(p, "utf8")), IDX = J(DATA + "/comps.json"), full = (t) => J(`${DATA}/names/${t}.json`);
const esc = (s) => String(s == null ? "" : s).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));
const pct = (v) => (v == null ? "—" : (v >= 0 ? "+" : "−") + Math.abs(v).toFixed(0) + "%"), px = (v) => (v == null ? "—" : v >= 100 ? Math.round(v).toLocaleString("en-US") : v.toFixed(2)), x1 = (v) => (v == null ? "—" : Number(v).toFixed(1) + "×");
const W = { "000660.KS": "SK hynix", "005930.KS": "Samsung", "285A.T": "Kioxia" }, tk = (t) => W[t] || t;
/* what Alan read on the live Hub at 12:50 ET, in his words; the rest is the engine's reproduction of the live Hub's own rule (every switch off, fiscal-year basis) */
const ALAN_LIVE = { TSM: "centre 269 (below the price)", GOOGL: "+31%", AMZN: "+63%", MU: "+274% (4,022)", AVGO: "+5.6%", NVDA: "+17%" };
const WHY = {
  GOOGL: "the method's advertising peers are Meta and a tail of far smaller names; Meta alone carries the reading (fragile), the trailing year carries one-off gains and is cut, and the growth yardstick prices it below the others — so the blend sits under the price.",
  AMZN: "the Chinese retailers and the two other clouds price it; the sales multiples are cut (its margin is far from the stores'), the growth yardstick is cut for sitting far above the rest, and the debt discount takes a little off.",
  AVGO: "the method keeps Palantir and the equipment makers' neighbours in its set; every yardstick but PEG sits far below the growth yardstick, which is capped and cut yet still carries the centre — read it as the market's price for growth, not a target.",
  NVDA: "only three same-business peers, so the whole chip set prices it on closeness; the growth yardstick and EV/EBITDA at the small designers' multiples lift it — the same warning as this morning: their price for growth, not a target.",
  TSM: "the two foundries are too few, so the chip set prices it on closeness, all figures in dollars at one rate (31.7) per ADR; the sales multiples are cut for its 56% margin — the EV rows no longer sit far from the rest.",
  VST: "priced on the four independent power producers with the regulated utilities blending in at 0.35; the debt discount (3.0× EBITDA, heavy) takes the upside to about nothing.",
  MU: "the memory line prices it — SanDisk, Western Digital, Seagate, SK hynix, Samsung, Kioxia — with the chip names blending in; the growth yardstick (its PEG) carries the centre up from this morning's +13%.",
  ORCL: "Microsoft and Amazon are its only same-business peers and the software names are capped at half their weight; the growth yardstick is cut; the debt discount of 8% (3.2× EBITDA, free cash flow cannot repay) is explicit.",
  DLR: "a property trust: P/FFO carries most of the weight; the earnings yardsticks are cut; the debt discount (4.8×, very heavy) takes the centre under the price.",
  EQIX: "the same: P/FFO and EV/EBITDA lead, the debt discount (5.0×) is 6% plus the free-cash-flow years; the reading stays below the price.",
  SNDK: "the memory line prices it; its forward P/E sits far above where the foreign makers' multiples put it and is cut; the reading stays below the price, less so than this morning.",
  WDC: "the memory line prices it with the hardware names blending in; the growth yardstick (57% growth into the following year, capped at 40 for the line) carries it back above the price.",
};
const T12 = IDX.twelve.filter((t) => IDX.names[t] && IDX.names[t].ok);
const rows12 = T12.map((t) => { const s = IDX.names[t], r = full(t); return `<tr><td><b>${t}</b><br><small>${esc(s.name)}</small></td><td>${px(s.price)}</td><td>${esc(ALAN_LIVE[t] || (s.before.live_as_it_stands.upside_pct == null ? "—" : pct(s.before.live_as_it_stands.upside_pct) + "*"))}</td><td>${pct(s.before.cp3.upside_pct)}</td><td class="${s.blend.upside_pct >= 0 ? "up" : "dn"}"><b>${pct(s.blend.upside_pct)}</b><br><small>centre ${px(s.blend.centre)} · ${px(s.blend.low)}–${px(s.blend.high)}${s.debt.discount_pct ? ` · before debt ${pct(s.blend.upside_before_debt_pct)}` : ""}</small></td><td>${esc(s.forward.text)}<br><small>growth ${pct(s.growth)} · PEG ${s.peg == null ? "—" : s.peg.toFixed(2)}</small></td><td><small>${esc(WHY[t] || "")}</small></td></tr>`; }).join("");
const weightRows = T12.map((t) => { const r = full(t), y = r.yardsticks, c = (k) => (y[k] ? `${Math.round((y[k].weight || 0) * 100)}%${y[k].consistency && y[k].consistency.far ? " ⚑" : ""}${y[k].off ? " ·off" : ""}` : "—"); return `<tr><td><b>${t}</b></td><td>${c("pe_ttm")}</td><td>${c("pe_fwd")}</td><td>${c("ev_ebitda")}</td><td>${c("ev_sales")}</td><td>${c("ps")}</td><td>${c("peg")}${y.peg && y.peg.credit ? `<br><small>credit ×${y.peg.credit}</small>` : ""}</td><td>${c("p_ffo")}</td><td><small>${esc(Object.values(r.consistency || {}).filter((x) => x.far).map((x) => x.words).join(" · ") || "—")}</small></td></tr>`; }).join("");
const setRows = T12.map((t) => { const r = full(t), s = r.sets; const chips = (L, cls = "") => (L || []).map((x) => `<span class="chip ${cls}${(s.same_business || []).includes(x) && cls === "" ? " same" : ""}">${esc(tk(x))}</span>`).join(""); return `<tr><td><b>${t}</b><br><small>${esc(r.line)}</small></td><td>${chips(s.old, "old")}</td><td>${s.cp3 ? chips(s.cp3, "old") : "<small>none stated</small>"}</td><td>${chips(s.now)}<br><small>${esc(s.rule)}${s.outliers.length ? " · outliers out: " + s.outliers.map(tk).join(", ") : ""}</small></td><td><small>${esc(((s.check && s.check.now && s.check.now.flags) || []).join(" · ") || "—")}</small></td></tr>`; }).join("");
const shot = (f, cap) => (existsSync(`${SHOTS}/${f}`) ? `<figure><img src="shots/${f}" alt="${esc(cap)}" loading="lazy"><figcaption>${esc(cap)}</figcaption></figure>` : "");
const NAV = existsSync(path.resolve(HERE, "../../../../scripts/scnav-snippet.html")) ? readFileSync(path.resolve(HERE, "../../../../scripts/scnav-snippet.html"), "utf8") : "";   /* the BACK / CLOSE pair every Hub page carries (scripts/inject-scnav.py places the same snippet) */
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The comps round — one engine</title>
<style>:root{--bg:#0e0e12;--panel:#141419;--line:#2a2a33;--txt:#d4d4da;--dim:#8a8a96;--up:#3c9a5f;--dn:#b04a4a;--flag:#b8a46a}body{margin:0;background:var(--bg);color:var(--txt);font:13px/1.5 ui-monospace,Menlo,monospace}main{max-width:1600px;margin:0 auto;padding:16px}h1{font-size:18px;letter-spacing:.12em;margin:8px 0 4px}h2{font-size:13px;letter-spacing:.14em;color:var(--dim);margin:26px 0 8px;border-bottom:1px solid var(--line);padding-bottom:4px}p{max-width:980px}table{border-collapse:collapse;width:100%;background:var(--panel)}th{text-align:left;color:var(--dim);font-weight:500;font-size:11px;letter-spacing:.08em;padding:6px 8px;border-bottom:1px solid var(--line);vertical-align:bottom}td{padding:6px 8px;border-bottom:1px solid #1e1e26;vertical-align:top;font-size:12px}small{color:var(--dim);font-size:11px}.up{color:var(--up)}.dn{color:var(--dn)}.scroll{overflow-x:auto}.chip{display:inline-block;border:1px solid #3a3a46;border-radius:10px;padding:0 6px;margin:1px 2px;font-size:11px}.chip.old{color:#7a7a86}.chip.same{border-color:#8a8a96}figure{margin:10px 0;background:var(--panel);border:1px solid var(--line);border-radius:6px;padding:6px}figure img{width:100%;display:block}figcaption{color:var(--dim);font-size:11px;padding:6px 2px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media (max-width:760px){.grid{grid-template-columns:1fr}main{padding:12px 16px}td,th{padding:5px 6px}}.flag{color:var(--flag)}details.sc-pagespecs{margin-top:30px}details.sc-pagespecs summary{cursor:pointer;color:var(--dim);letter-spacing:.12em;font-size:11px}</style></head><body><main>
${NAV}<div data-scnav-slot style="display:flex;gap:8px;min-height:40px;margin:0 0 6px"></div><h1>THE COMPS ROUND — ONE ENGINE ON EVERY SCREEN</h1><p><small>7 October 2026 · readings on the 6 October close · built ${esc(IDX.built_utc.slice(0, 16).replace("T", " "))} UTC · ${IDX.counts.ok} companies priced by one program; the Hub's COMPS tab, the cards, the knockout and the allocation tool read its file.</small></p>
<h2>PICTURES</h2><div class="grid">${shot("tool-1680-mu.png", "The allocation tool at 1680: Micron's ticker clicked — its peers with the four sources' dots, each yardstick, the football field, growth two ways, PEG, debt, the long-term channel and the Geiger in its own year.")}${shot("tool-1680-lrcx.png", "The allocation tool at 1680: any ticker opens, not only the ten — Lam Research.")}${shot("hub-tab-1680-tsm.png", "The Hub's COMPS tab at 1680, reading the engine's file for TSMC: every figure in dollars at one rate, per ADR; the EV rows no longer sit far from the rest.")}${shot("tool-390-mu.png", "The allocation tool on a phone (390): Micron's reading.")}${shot("page-1680.png", "This page at 1680.")}${shot("page-390.png", "This page on a phone (390).")}</div>
<h2>THE TWELVE NAMES, BEFORE → AFTER</h2><p>“Before, live” is what Alan read on the live Hub at 12:50 ET today where he read it; for the other names it is the engine's reproduction of the live Hub's own rule (every switch off, the fiscal-year forward basis, the sources' own set), marked *. “This morning” is the one-basis reading with the hand-written peer sets. “Now” is this round: the method's peers, the reassessed football field, the consistency check and the debt discount.</p>
<div class="scroll"><table><thead><tr><th>name</th><th>close</th><th>before, live Hub</th><th>this morning</th><th>now · to the centre</th><th>forward P/E · growth · PEG</th><th>what moved it</th></tr></thead><tbody>${rows12}</tbody></table></div>
<h2>EACH YARDSTICK'S WEIGHT, AND THE CONSISTENCY FLAGS</h2><p>The weight is a prior (PEG 2.0, forward P/E 1.5, EV/EBITDA 1.0, trailing P/E 0.6, EV/sales 0.5, P/S 0.4; for a property trust P/FFO 2.0 leads) × the share of peers carrying the multiple × how well that multiple prices the peers themselves — then cut where the yardstick's implied price sits more than 1.5× away from the other yardsticks' middle (⚑): to half at 1.5×, a tenth at 3×. Growth and PEG weigh most, as Alan asked; the PEG line counts growth up to 40% a year, faster growth is credited through the weight. “off” = the sales multiples left out because the margin is more than twice the peers'.</p>
<div class="scroll"><table><thead><tr><th>name</th><th>trailing P/E</th><th>forward P/E</th><th>EV/EBITDA</th><th>EV/sales</th><th>P/S</th><th>PEG</th><th>P/FFO</th><th>consistency flags</th></tr></thead><tbody>${weightRows}</tbody></table></div>
<h2>PEER SETS, OLD → NEW</h2><p>The four sources still vote and every peer shows its dots. The business line from the filings decides who shares the business; four or more same-business peers set the price and the adjacent peers blend in at 0.35 (together never more than half the same-business weight); every peer weighs by its closeness in size, growth and margin. The eight sets stated by hand this morning are shown, and no longer price anything.</p>
<div class="scroll"><table><thead><tr><th>name · its lines</th><th>the set as the sources kept it</th><th>stated by hand this morning</th><th>the method's set now (solid border = same business)</th><th>automatic checks</th></tr></thead><tbody>${setRows}</tbody></table></div>
<h2>THE DEFAULTS WE ROLL WITH</h2><p><b>Micron:</b> the blend of the memory line with its PEG credit — reads ${pct(IDX.names.MU.blend.upside_pct)} to a centre of ${px(IDX.names.MU.blend.centre)} on the memory makers (SanDisk, Western Digital, Seagate, SK hynix, Samsung, Kioxia) with the chip names blending in. <b>Vistra:</b> priced against the independent power producers (Constellation, NRG, Talen, Oklo); the regulated utilities blend in at 0.35; ${pct(IDX.names.VST.blend.upside_pct)} after a 3% debt discount. <b>Oracle:</b> an explicit debt discount — ${esc(full("ORCL").debt.discount.words)}; ${pct(IDX.names.ORCL.blend.upside_pct)} to ${px(IDX.names.ORCL.blend.centre)} against ${pct(IDX.names.ORCL.blend.upside_before_debt_pct)} before it. Interest cover joins the day the interest column is filled: the statements job now writes it; the additive column and its rollback are written and not applied.</p>
<h2>WHAT WAS NOT DONE, AND WHAT TO KNOW</h2><p>· The chip leaders (Nvidia, Broadcom, TSMC) still read far above the price: their same-business peers are too few or priced on another growth story, so the growth yardstick carries them even capped and cut. These are the market's price for growth, not targets; the flags say so on each. · The live Hub's own numbers at 12:50 ET are Alan's reading of six names; the other six “before” figures are the engine's reproduction of that rule, not a screenshot of the live page. · The long-term channel is the Lab's reviewed rails for one name; for every other name it is a channel computed from the name's own weekly bars, and says so. · The knockout's tools read the engine's feed file (knockout-comps.json); the knockout itself was not re-run in this round. · The Hub's own CARDS tab (another branch) is not yet pointed at the engine's cards file. · Qualcomm and Arm are cut from the designers' sets as price outliers by the older rule; Qualcomm is the kind of peer Alan named for Nvidia and Broadcom, and that rule deserves a look.</p>
<details class="sc-pagespecs"><summary>PAGE SPECS</summary><div><p>One program — the comps engine — reads the Hub's tables once (the knockout's snapshot of 7 Oct, estimates re-read with both periods), prices every company on the 6 Oct close and writes one file per name and one index. Forward P/E is the dashboard's: price ÷ the next four quarters of expected earnings; a foreign reporter's earnings, revenue, EBITDA and net debt are in dollars at the supplier's own paired rate (TSMC: 31.7 Taiwan dollars per dollar) and per ADR (1 ADR = 5 shares). Growth is the four quarters after the next four over the next four; PEG is that forward P/E over that growth, and is called PEG everywhere. Property trusts carry P/FFO. Where the knockout's own rule found one-off gains in the reported year (Alphabet, Amazon) the EV/EBITDA row is read on EBITDA without them. The blend is the weighted median of every peer's implied price on every yardstick; low and high are the weighted 25th and 75th. The debt discount is the knockout's steps (3% / 6% / 10% off the centre above 2.5 / 4 / 6× EBITDA) plus 1% per year of free cash flow beyond five that repaying all debt would take (5% when free cash flow cannot repay it). Thin = fewer than four peers behind the centre; fragile = one peer's removal moves the centre more than 10%. The Geiger's own year is filed as percentiles so a screen places today's value in today's year. Nothing was written to any table; the table design is a dry run.</p></div></details>
</main></body></html>`;
writeFileSync(OUT, html); console.log("page →", OUT, html.length, "bytes");
