/* The study catalogue (F5). Each spec follows the quant-loop plan's five parts — inputs · history · rule · verdict ·
   display — plus the classical source, the data we have against the data we need, and how we could fool ourselves.
   Every study describes frequencies with their samples; none predicts. Status: measured here (descriptive counts on
   this page), S6/S7 (another lane owns it), ready (the data is in hand), needs (a provider or tool is missing). */

export const GROUPS = [
  { key: "levels", title: "A · Levels and percentiles", intro: "Where a reading sits in the name's own history, and where past pullbacks ended. Four of these are measured on this page." },
  { key: "channels", title: "B · Parallel channels", intro: "Alan's channel stack combines four published TradingView methods: Auto Parallel Channels (HTF) by TradeSymbiotic, Auto Parallel Channel by sohaibnori, a transparent APC geometry mirror, and sunnywilson93's Auto Channel Detector. Every one of them is pivots plus a parallel offset, so every one can be rebuilt from daily or hourly bars without TradingView. The one discipline that matters: a pivot is only known after its right-hand bars close (25 bars late for method B, 3 for method C), and a study that uses it earlier is cheating." },
  { key: "diagonals", title: "C · Diagonals and wedges", intro: "The diagonal indicator on the Station is Trendoscope's Auto Chart Patterns (a private visual fork, CC BY-NC-SA 4.0): a ZigZag (length 8, depth 55) feeding five pivots into a line fit that labels 13 shapes — ascending, descending and ranging channels; rising and falling wedges, expanding and contracting; converging, diverging, ascending and descending triangles. The names describe geometry, never a breakout direction." },
  { key: "confluence", title: "D · Confluence", intro: "Alan, 26 Sep: \"no single piece is an edge … measure in a consolidated way whether they are.\" Every confluence study is read against the same condition's ordinary baseline, as S6b does, and discovered on one half of history and confirmed on the other." },
  { key: "events", title: "E · Events", intro: "Dated events with a clock: reports, dividends, index changes, macro releases, option expiries." },
  { key: "breadth", title: "F · Breadth and rotation", intro: "The cohort against the market, and the market's own participation. Built on the taxonomy's 30 branches and the 314 companies." },
  { key: "volume", title: "G · Volume conviction", intro: "Relative volume only (the rulebook's Q-2): raw share counts are forbidden across names and across splits." },
  { key: "regime", title: "H · Regime conditioning and the qualitative inputs", intro: "The same counts split by the weather they happened in, including the two qualitative inputs Alan asked for: the AI cycle read and news that moves leaders." },
];

export const SPECS = [
  /* ── A · levels ── */
  { id: "A1", group: "levels", title: "Percentile, Z and σ lines: which one fires as often as it says", status: "measured here", statusKey: "measured",
    question: "Does a line drawn at \"the name's own 10th percentile\" fire about 10% of the time on days it has not seen, for every name and every family, and do the Z and σ versions?",
    inputs: "RSI(14), Williams %R(14), distance to the 200-day, the daily move in usual days; 362 names and BTCUSD; finished daily bars from the chart API.",
    history: "Each name from its history start (2003 for most) to 25 Sep 2026; lines drawn from the prior 3 years or all prior history; firing counted over the last 12 months, the last 3 years and the whole history.",
    rule: "For every day, draw each line from the days before it only; count the days and the episodes (a new one after five quiet sessions) when today's reading is beyond the line.",
    verdict: "A line is self-calibrating when its out-of-sample firing share sits inside nominal ± the binomial tolerance for its count, with a block bootstrap (20-session blocks) because one selloff moves every name at once. The loop adds the intervals; this page reports the medians and the middle half across names.",
    display: "One table per family: fixed line against own P (3y, all), Z and σ, medians and middle halves, companies and funds apart; the per-name firing lists in the data file.",
    source: "Wilder, <i>New Concepts in Technical Trading Systems</i> (1978) for RSI and its 70/30; Chande &amp; Kroll, <i>The New Technical Trader</i> (1994) for normalising an oscillator to its own range (StochRSI); the rulebook's U-3 percentile mode.",
    data: "Have: everything. Need: nothing for the counts; the loop's bootstrap for the intervals.",
    risk: "Calibration is not usefulness: a line that fires 10% of the time can still say nothing about what follows. Choosing the window after seeing the result is a forking path; the 3-year window was fixed by the package before this page. The line itself drifts with the regime (SPY's own 10th-percentile RSI moved from about 38 in 2023 to about 41 in 2026).",
    measured: "Yes — chapter 1, first table." },
  { id: "A2", group: "levels", title: "Each name's usual pullback", status: "measured here", statusKey: "measured",
    question: "When this name pulled back from a high set above its 200-day, how deep did it go, and where were RSI and the averages at the low?",
    inputs: "Closes, the 200- and 50-day averages, RSI(14), the usual day, per name.",
    history: "All history per name; the last 3 years shown beside it.",
    rule: "An episode runs from a high to the close that regains it (or 250 sessions). It counts when the high was at or above its 200-day and the lowest close sat at least 2.5 usual days below the high. At the low: depth in % and in usual days, RSI and its own percentile, distance to both averages, sessions from high to low.",
    verdict: "Descriptive bands only (median and middle half). The low is chosen with hindsight, so these bands describe where pullbacks ended; they are never a trigger. The live-knowable version is A3.",
    display: "One row per name: usual depth, RSI at the low, the averages at the low, and today's drawdown as a multiple of the usual depth.",
    source: "Dow's thirds via Edwards &amp; Magee, <i>Technical Analysis of Stock Trends</i> (1948); Grimes, <i>The Art and Science of Technical Analysis</i> (2012) for impulse and retracement; the rulebook's S-8 and S-9.",
    data: "Have: everything.", risk: "Hindsight lows; survivors only; the 2.5-usual-day and 250-session thresholds are mine and change the counts. A young name (NBIS, 4 pullbacks) cannot have a usual pullback yet.",
    measured: "Yes — chapter 1, the pullback table." },
  { id: "A3", group: "levels", title: "Leader-relative pullbacks: a 5% dip on a leader against a 30% dip on a laggard", status: "measured here", statusKey: "measured",
    question: "Alan: \"in some scenarios a 5% pullback on a leader is better than a 30% pullback in a laggard.\" What happened after each, counted the same way?",
    inputs: "Companies only; closes; the 200-day; the usual day; leader rank = the 120-session return minus SPY's, ranked among companies that day.",
    history: "2003–2026, split 2003–2016 (discover) and 2017–2026 (confirm).",
    rule: "Trigger = the first close in an episode (high at or above its 200-day) at 5, 10, 20 or 30% below the high, or at the name's own usual depth (median of its completed pullbacks that ended before the trigger, at least five). Outcomes: return 60 sessions later, deepest close inside those 60, both also in the name's usual days × √60, and whether the high came back inside 60. Baseline: every fifth session of the same leader class.",
    verdict: "Descriptive. A class-and-depth row matters only if it separates from its own class's ordinary sessions in both halves of history; the loop adds a block bootstrap by calendar month.",
    display: "The trigger table beside the baseline rows, counts and months first.",
    source: "O'Neil, <i>How to Make Money in Stocks</i> (1988) for buying leaders on pullbacks; Jegadeesh &amp; Titman (1993) and Moskowitz &amp; Grinblatt (1999) for momentum and industry momentum.",
    data: "Have: everything. Need: historical index membership to repair survivorship (the laggard rows are the most flattered — laggards that died are absent).",
    risk: "Survivorship, overlapping triggers from one selloff (the months column shows how few independent episodes there are), and the leader rank uses today's universe.",
    measured: "Yes — chapter 1, the leader table." },
  { id: "A4", group: "levels", title: "The RSI range shift by trend state", status: "measured here (first cut)", statusKey: "measured",
    question: "How far does a name's usual RSI range move up in an up-trend and down in a down-trend?",
    inputs: "RSI(14), the close against its 200-day (first cut); the rulebook's S-4 trend verdict once the swing bake-off exists.",
    history: "All history per name.", rule: "Own 10th and 90th RSI percentiles on days above the 200-day and on days below it, per name and pooled.",
    verdict: "Descriptive. If the shift is large and common, rulebook v3's RSI lines are drawn per trend state (chapter 1 recommends this).",
    display: "Two numbers per name beside the unconditioned line.",
    source: "Brown, <i>Technical Analysis for the Trading Professional</i> (1999) and Cardwell's RSI range rules as Brown reports them; the rulebook's I-6 range-shift law.",
    data: "Have: everything.", risk: "Circularity: the same closes set both RSI and the trend state. Measured with a price average here; the rulebook wants its own trend verdict, which is not built yet.",
    measured: "Yes — companies' median 10th percentile is about 42.5 above the 200-day and about 31.5 below it." },
  { id: "A5", group: "levels", title: "RSI and Williams %R: one witness or two (S2)", status: "measured here (first cut)", statusKey: "measured",
    question: "Are RSI(14) and Williams %R(14) the same evidence counted twice?",
    inputs: "Both series on the same bars, every name.", history: "All history; the two halves separately in the loop.",
    rule: "Spearman rank correlation of the two series; the loop adds the agreement rate of their extreme states and the lift.",
    verdict: "The book's placeholder threshold is 0.9 (the loop crew ratifies it). Above it: one witness. Below it but high: seat them as one until the extremes agreement is measured.",
    display: "One row per name; a histogram across the universe.",
    source: "Williams, <i>How I Made One Million Dollars Last Year Trading Commodities</i> (1973); Lane on the stochastic; the rulebook's I-2 and I-8.",
    data: "Have: everything.", risk: "Correlation of whole series overstates or understates agreement at the extremes, which is where the rules read them.",
    measured: "Yes — median 0.85 across companies (middle half 0.843 to 0.858)." },
  { id: "A6", group: "levels", title: "What followed a two-usual-day move", status: "measured here (first cut)", statusKey: "measured",
    question: "After a name's own ≥ 2 usual-day day, how often was it higher five sessions later, against any day?",
    inputs: "Daily moves in prior usual days; closes.", history: "All history per name; pooled across companies.",
    rule: "Every day with a move of two usual days or more (each side), the close five sessions later; the baseline is every fifth session.",
    verdict: "Descriptive; the loop counts every tenth day to avoid overlap and bootstraps.",
    display: "Per name in the morning template's sigma line; pooled in chapter 1.",
    source: "Mandelbrot (1963) on fat tails; Engle (1982) on volatility clustering; the Hub's own sigma history study (M68).",
    data: "Have: everything. Need: the report dates flagged on each bar, because many two-usual-day days are report days.",
    risk: "Report days dominate the tails; overlapping five-day windows; survivors.",
    measured: "Yes — pooled over companies: after a two-usual-day drop, higher five sessions later on 53.9% of 38,000 days, against 53.6% for any fifth session." },

  /* ── B · channels ── */
  { id: "B1", group: "channels", title: "Rail touches: what happened after price reached a channel's lower rail", status: "needs the detector port (S7 builds it)", statusKey: "s7",
    question: "When the close first reaches the lower rail of a live parallel channel, how often does it next reach the midline, the upper rail, or break the lower rail?",
    inputs: "Daily bars (and 4H from the chart API's hourly spans); the channel detector ported from Alan's stack — method B (sohaibnori: pivots 25/25, two highs and the latest confirmed low, linear price, seven rails at −0.12, 0, 0.12, 0.5, 0.88, 1, 1.12) and method C (APC mirror: pivots 3/3, log price, span 5–150 bars, width at least 0.5%).",
    history: "2003–2026 daily; the hourly depth the API serves for 4H.",
    rule: "Channels only as of their confirmation bar (the last pivot's right-hand bars closed). A touch = the low inside the rail ± max(2 ticks, 0.10 × ATR14 frozen at confirmation). Outcome = first of: close beyond the midline, touch of the upper rail, close below the lower rail minus the tolerance; with the bars taken.",
    verdict: "Frequencies with counts per method, per timeframe, per direction of the channel; against the same count for random dates inside the same channels.",
    display: "One table per method: count, first-outcome shares, median bars; the parity sample beside it.",
    source: "Edwards &amp; Magee (1948) on trend channels and the return line; Murphy, <i>Technical Analysis of the Financial Markets</i> (1999), ch. 4; Lo, Mamaysky &amp; Wang, \"Foundations of Technical Analysis\" (Journal of Finance, 2000) for detecting patterns from bars.",
    data: "Have: bars. Need: the JS port (S7 item 3 ports the parallel-channel script and tests it on three hand-checked cases); the channel-method audit of 25 Sep documents methods B and C exactly.",
    risk: "Using a pivot before it is confirmed (lookahead); redrawn rails (the rulebook's D-6 says geometry is immutable once drawn); four methods × four timeframes is sixteen chances to find something." },
  { id: "B2", group: "channels", title: "Channel exits and the throwback", status: "needs the detector port", statusKey: "needs",
    question: "After a confirmed close through a rail, how often does price come back to the broken rail within 3 to 15 bars, and how often does the break hold?",
    inputs: "The B1 channels; closes, highs, lows; the retest clock.", history: "As B1.",
    rule: "Break = first completed close beyond the rail ± tolerance after confirmation. Retest = touch of the broken rail's band starting at least one bar later; held = a close back on the break side within three bars; failed = a close back through first. Every clock value 3–15 reported.",
    verdict: "A Wilson interval widened for overlap; Bulkowski's published throwback rates shown as the seed column beside our count.",
    display: "Seed against loop, per method and clock.",
    source: "Bulkowski, <i>Encyclopedia of Chart Patterns</i> (2nd ed., 2005) for throwback and pullback rates; the rulebook's D-7 and B-5 (study S4 in F3).",
    data: "Have: bars. Need: B1's detector.", risk: "Choosing the clock after seeing the counts; wick versus close definitions." },
  { id: "B3", group: "channels", title: "Channel walks", status: "needs the detector port", statusKey: "needs",
    question: "When price walks one rail (three or more defended touches without tagging the midline), how long does the walk last and how does it end?",
    inputs: "B1 channels, touch episodes.", history: "As B1.",
    rule: "Stamp WALK(n) at the n-th defended touch without a midline tag (the rulebook's D-7); record the bars to the first midline tag or exit, and which.",
    verdict: "Survival curve of walk length; share ending in an exit against the far side.", display: "One survival curve per direction, direct-labelled.",
    source: "The rulebook's D-7; Raschke &amp; Connors, <i>Street Smarts</i> (1995) on trend persistence.",
    data: "Have: bars. Need: B1.", risk: "A walk is only known after it has lasted; counting it from the first touch is lookahead." },
  { id: "B4", group: "channels", title: "The regression channel as the no-pivot baseline", status: "ready", statusKey: "ready",
    question: "Do pivot-built channels (B1) tell us anything a plain regression channel does not?",
    inputs: "Closes; a 100-bar least-squares line and ± 2 standard deviations of its residuals, frozen at each bar.", history: "2003–2026.",
    rule: "The same touch and outcome counting as B1 on the regression rails, frozen as of the bar (no refitting backwards).",
    verdict: "B1's rows count only where they differ from the regression baseline in both halves of history.",
    display: "B1's table with the baseline column beside each row.",
    source: "Raff's regression channel (Gilbert Raff, 1991); Bollinger, <i>Bollinger on Bollinger Bands</i> (2001).",
    data: "Have: everything.", risk: "A regression refits every bar; the frozen-at-bar version must be the one counted." },

  /* ── C · diagonals ── */
  { id: "C1", group: "diagonals", title: "The 13 Trendoscope shapes: census, then what followed against matched controls", status: "Phase 0–1 done; Phase 2 needs Alan's preregistration", statusKey: "needs",
    question: "How often does each of the 13 shapes appear, and after confirmation, how often does it break each way, how far, compared with the same names on the same kind of days without the shape?",
    inputs: "The canonical replay of the detector (branch hub/trendoscope-stats-20260924): ZigZag 8/55, 5 pivots, error and flat 20%, bar ratio 0.382, avoid-overlap on, retention 20, no repaint; 4H extended session primary, regular session separate, 1D, 3H, 1H.",
    history: "The pilot cohort by SHA-256 seed, then the full cohort in the packet.",
    rule: "The packet's §4 defaults: tolerance max(2 ticks, 0.10 × ATR14 at confirmation); break = first close beyond a rail after confirmation; outcomes at one formation duration and at 5–80 bars; MFE/MAE from the next bar's open.",
    verdict: "Against matched non-pattern controls and permuted labels; Benjamini–Hochberg at q = 0.10 across secondary cells; symbol-time block bootstrap.",
    display: "Tables A–I of the packet; one row per shape, counts first.",
    source: "Trendoscope's Auto Chart Patterns libraries; Bulkowski (2005); Lo, Mamaysky &amp; Wang (2000); the statistical evaluation packet of 23 Sep.",
    data: "Have: Phase 0–1 replay, census and geometry; the parity sample for the coordinator's TradingView spot check. Need: Alan's Phase 2 decisions (primary endpoint per family, holdout), and the 4H extended-session depth the API holds.",
    risk: "Reading \"Ascending\" as up; overlapping and nested patterns; retention changes acceptance (20 is detector state, not display)." },
  { id: "C2", group: "diagonals", title: "The third touch: does a validated diagonal hold more often than a two-point line?", status: "needs the swing bake-off", statusKey: "needs",
    question: "How often does a line through two confirmed swings earn a defended third touch, and do validated lines hold at the next test more often than proposals?",
    inputs: "Confirmed swings (the SW-F / SW-R bake-off winner), log-price lines, the rulebook's D-1 and D-2.", history: "2003–2026 daily.",
    rule: "Propose on the second anchor's confirmation; validate on the first defended episode after it; record the fate of the next test for validated lines and for proposals.",
    verdict: "Two proportions with overlap-widened intervals; the claim in the book stands only if the difference clears in both halves.",
    display: "Validated against proposed, per slope bucket (C3).",
    source: "Edwards &amp; Magee (1948); Murphy (1999), ch. 4; Bulkowski, <i>Trading Classic Chart Patterns</i> (2002).",
    data: "Have: bars. Need: the frozen swing detector (D7 in F3).", risk: "Survivorship of drawn lines — people remember the lines that worked." },
  { id: "C3", group: "diagonals", title: "Slope against time to break", status: "needs the swing bake-off", statusKey: "needs",
    question: "Do steeper diagonals break sooner, as the classical warning says?",
    inputs: "C2's validated lines; slope in usual days per bar (VOLU, the rulebook's U-2).", history: "2003–2026.",
    rule: "Bars from validation to the first confirmed break, by slope tercile.", verdict: "Survival curves by tercile; a log-rank test.",
    display: "Three curves, direct-labelled.", source: "Edwards &amp; Magee on steep trendlines; Murphy's fan principle; the rulebook's D-3.",
    data: "Have: bars. Need: C2.", risk: "Slope in screen degrees means nothing; only the unit-per-bar slope counts." },
  { id: "C4", group: "diagonals", title: "Wedges: which way they actually break", status: "ready on the six-pattern engine; Trendoscope after C1", statusKey: "ready",
    question: "How often does a rising (falling) contracting wedge break down (up), against the folklore?",
    inputs: "The six-pattern engine (patterns-20260923: symmetric pivots k = 5, 20-day cooloff) and, later, Trendoscope's contracting wedges.", history: "2003–2026, 38 names today; the full universe next.",
    rule: "Break direction and 20-bar outcome per wedge type, with prior-trend context (with-trend against against-trend).",
    verdict: "Bulkowski's tabulated direction rates as the seed column beside our count; one primary endpoint per family.",
    display: "Seed against loop, per wedge type and context.", source: "Bulkowski (2005), wedge chapters; the rulebook's P-7.",
    data: "Have: the engine and its frozen evidence. Need: nothing for the first run.", risk: "The two engines define a wedge differently; never merge their counts." },

  /* ── D · confluence ── */
  { id: "D1", group: "confluence", title: "RSI at its own low + a channel's lower rail + a prior horizontal level", status: "S7 measures it inside the report window; the loop runs the ordinary version", statusKey: "s7",
    question: "When three independent reasons line up at one price, how much more often did the next 20 sessions end higher than for each alone, and than for the same days without them?",
    inputs: "Own RSI percentile (A1 line), B1's lower rail, a horizontal level (a pivot of the last 120 sessions within 1%), the 200-day state.",
    history: "2003–2016 discover, 2017–2026 confirm, both reported.",
    rule: "The triple, each pair and each single, on the first session each condition set is met; outcome 20 sessions later; baseline = the same state's ordinary sessions.",
    verdict: "A combination counts only with at least 200 events in each half and a lift over its own baseline in both; the number of combinations tried is printed on the page.",
    display: "The S6b layout: condition, count, share higher, median, the baseline beside it, the difference.",
    source: "The rulebook's L-11 (confluence clusters); Murphy's confirmation principle; the S6b method.",
    data: "Have: bars; S6b's worked example. Need: B1's rails.", risk: "The garden of forking paths — three conditions with three thresholds each is 27 cells before pairs. Preregister the thresholds (this page's A1 lines) before counting." },
  { id: "D2", group: "confluence", title: "Level clusters: does a price with two reasons hold more often?", status: "needs level machinery", statusKey: "needs",
    question: "Do overlapping level zones (swing, gap edge, prior period, round number) hold at the next test more often than single levels?",
    inputs: "Levels per the rulebook's L-1 to L-3 and L-13; zones per L-4.", history: "2003–2026.",
    rule: "Test episodes at clusters against single levels of the same quality; defended share.",
    verdict: "Two proportions; the cluster counted once, never twice.", display: "Cluster size against defended share.",
    source: "Edwards &amp; Magee on support and resistance; Osler, \"Support for Resistance\" (Federal Reserve Bank of New York, 2000).",
    data: "Have: bars. Need: the level birth code.", risk: "Double-counting one defense as two." },
  { id: "D3", group: "confluence", title: "The average touch with the RSI low (the classic pullback entry)", status: "S7 inside the report window; ready for ordinary windows", statusKey: "s7",
    question: "When a close touches the 20-, 50- or 200-day average from above while RSI sits at its own low, what followed, against the same state's ordinary days?",
    inputs: "Averages, own RSI percentile, the 200-day state.", history: "Discover / confirm split.",
    rule: "First qualifying session; outcome 20 and 60 later; baseline as D1.", verdict: "As D1.", display: "As D1.",
    source: "Granville, <i>A Strategy of Daily Stock Market Timing</i> (1960) on price and the average; Brock, Lakonishok &amp; LeBaron (Journal of Finance, 1992) on moving-average rules; the rulebook's I-4 (an average is test-grade, not claim-grade).",
    data: "Have: everything.", risk: "The average is built from the closes being judged against it (I-4's self-reference)." },

  /* ── E · events ── */
  { id: "E1", group: "events", title: "The run-up into the report (S6, S6b) and better entries inside it (S7)", status: "S6 and S6b done; S7 running", statusKey: "exists",
    question: "Do names rise into their reports, in which states more, and does a better entry inside the 20 sessions add anything?",
    inputs: "Report dates from public.earnings_events (exported read-only); daily bars.", history: "19,382 reports on 324 names (S6b).",
    rule: "S6: close 20 sessions before to the last close before. S6b: the same, split by the state at the window's start, against that state's ordinary 20 sessions. S7: first trigger inside the window, exit at the last close before the report.",
    verdict: "S6b's lift over the same state's ordinary stretches; S7's combinations with at least 200 trades in both halves.",
    display: "The S6b table (worked example in chapter 1).",
    source: "Frazzini &amp; Lamont, \"The Earnings Announcement Premium and Trading Volume\" (2007); Barber, De George, Lehavy &amp; Trueman (Journal of Financial Economics, 2013); Savor &amp; Wilson (2016).",
    data: "Have: dates and bars. Need: the report time (before the open / after the close) for most of history — 74 of MU's 79 reports carry no time.",
    risk: "Survivors; the day a report trades on is a guess when the time is missing." },
  { id: "E2", group: "events", title: "After the report: drift by surprise", status: "ready", statusKey: "ready",
    question: "After a beat or a miss, how often did the next 5, 20 and 60 sessions continue the report day's direction?",
    inputs: "eps_actual, eps_estimate, surprise_pct from the export; bars.", history: "All reports with an estimate.",
    rule: "Surprise terciles; returns from the report-day close; against the same name's ordinary windows.", verdict: "Descriptive with overlap-aware intervals.",
    display: "Terciles × horizons, counts first.", source: "Ball &amp; Brown (1968); Bernard &amp; Thomas (1989) on post-earnings-announcement drift.",
    data: "Have: everything but the timing flag (E1).", risk: "The estimate's timestamp; the drift has shrunk since it was published." },
  { id: "E3", group: "events", title: "The ex-dividend day", status: "needs the dividend dates on bars", statusKey: "needs",
    question: "How does price behave around the ex-date, in the name's usual days, against the dividend's size?",
    inputs: "Ex-dates and amounts (the Hub's dividends table); split-adjusted, not dividend-adjusted bars (as served).", history: "All dated dividends.",
    rule: "Ex-day move minus the dividend, in usual days; the five sessions each side.", verdict: "Descriptive.", display: "By yield bucket.",
    source: "Campbell &amp; Beranek (1955); Elton &amp; Gruber (Review of Economics and Statistics, 1970).",
    data: "Have: bars. Need: bar.exDiv on each bar (registered in the rulebook as T-9, not served) or the dividends table history.",
    risk: "An ex-day drop read as a gap or a sigma event (the rulebook's E-8 stand-down exists for this)." },
  { id: "E4", group: "events", title: "Index additions and the quarterly rebalance", status: "needs index-change history", statusKey: "needs",
    question: "What happened to names between the announcement and the effective date of an S&amp;P 500 addition, and in rebalance weeks?",
    inputs: "Announcement and effective dates; the third Friday of March, June, September, December; the Russell reconstitution in late June.", history: "As far as the change list goes.",
    rule: "Returns from announcement to effective date and 20 sessions after, against the cohort.", verdict: "Descriptive; small counts said plainly.",
    display: "One row per event type.", source: "Shleifer (1986); Harris &amp; Gurel (1986); Madhavan (2003) on the Russell reconstitution; Petajisto (2011).",
    data: "Have: calendar dates (computable). Need: historical S&amp;P 500 constituent changes (the provider offers them).", risk: "Added names are survivors by construction." },
  { id: "E5", group: "events", title: "Macro days: the pre-FOMC drift, CPI and payrolls", status: "needs dated history", statusKey: "needs",
    question: "How did SPY, QQQ and the cohorts move on and before scheduled macro releases?",
    inputs: "FOMC decision dates, CPI and payroll dates; bars.", history: "FOMC dates since 1994 are public; CPI and payrolls as far as the calendar holds.",
    rule: "The 24 hours before FOMC, the release day, the day after; against ordinary days.", verdict: "Descriptive; about eight FOMC events a year.",
    display: "Event type × window.", source: "Lucca &amp; Moench, \"The Pre-FOMC Announcement Drift\" (Journal of Finance, 2015); Savor &amp; Wilson (2013).",
    data: "Have: the live econ calendar (the Hub's ECONOMIC room). Need: its history depth, or the public FOMC calendar.", risk: "Few events; the drift was published and may have faded." },
  { id: "E6", group: "events", title: "Option-expiry weeks", status: "ready", statusKey: "ready",
    question: "Do expiry weeks (third Fridays, and the quarterly ones) behave differently in usual days?",
    inputs: "Calendar; bars.", history: "2003–2026.", rule: "Weekly return and range in usual days: expiry weeks against the rest.",
    verdict: "Descriptive; many cells, so Benjamini–Hochberg.", display: "One row per week type.",
    source: "Stoll &amp; Whaley (1987); Ni, Pearson &amp; Poteshman (Journal of Financial Economics, 2005) on pinning.",
    data: "Have: everything.", risk: "A weak effect found by trying many calendars." },

  /* ── F · breadth and rotation ── */
  { id: "F1", group: "breadth", title: "Does a cohort's lead persist?", status: "ready (first cut in the template)", statusKey: "ready",
    question: "When a cohort's 20-session return against SPY sits in its own top tenth, what did the next 20 and 60 sessions do?",
    inputs: "The taxonomy's 30 branches, equal-weighted from members' daily moves (clipped at ±40%); SPY.", history: "2004–2026.",
    rule: "Own percentile of the cohort's relative 20-session return; outcome 20 and 60 sessions later against SPY.", verdict: "Descriptive with a month-block bootstrap.",
    display: "Cohort × percentile bucket; the rotation line in the template shows today's placement.",
    source: "Moskowitz &amp; Grinblatt, \"Do Industries Explain Momentum?\" (Journal of Finance, 1999); Jegadeesh &amp; Titman (1993).",
    data: "Have: everything. Need: the cohort labels as they were then (today's labels applied backwards is lookahead).", risk: "Today's members chosen because they did well." },
  { id: "F2", group: "breadth", title: "Breadth at its own extremes", status: "ready (first cut in the template)", statusKey: "ready",
    question: "When the share of companies above their 50- or 200-day sits at its own low or high, what did SPY and the equal-weight index do next?",
    inputs: "Our 314 companies' closes and averages; SPY; RSP.", history: "From 2004 (enough names with a 200-day).",
    rule: "Own percentile of the share above each average; outcome 20 and 60 sessions later.", verdict: "Descriptive.",
    display: "The breadth line in the template; the study table in the loop.",
    source: "Zweig, <i>Winning on Wall Street</i> (1986) for the breadth thrust; the McClellan oscillator; the rulebook's U-5.",
    data: "Have: survivors' breadth. Need: historical constituents for honest breadth — survivors make the past look broader than it was.",
    risk: "Survivorship is at its worst here." },
  { id: "F3", group: "breadth", title: "Equal weight against the index, and concentration", status: "ready", statusKey: "ready",
    question: "When RSP − SPY or MAGS − SPY sits at its own extreme, what followed?",
    inputs: "RSP, SPY, MAGS (from November 2023 only after the splice guard).", history: "RSP 2003–2026; MAGS short.",
    rule: "Own percentile of the 20-session spread; outcome 20 and 60 later.", verdict: "Descriptive; MAGS stated as too short.",
    display: "Two rows.", source: "Plyakha, Uppal &amp; Vilkov (2012) on equal- versus value-weighted portfolios; the heat's own concentration voter.",
    data: "Have: everything.", risk: "MAGS's history is too short to say much." },
  { id: "F4", group: "breadth", title: "Lead–lag: the AI accelerators against the market", status: "ready", statusKey: "ready",
    question: "Did moves in the leader cohort show up in SPY or the laggard cohorts days later?",
    inputs: "Cohort indexes; SPY.", history: "2004–2026.", rule: "Cross-correlation of daily moves at lags 1–10, and the 5-session version.",
    verdict: "Descriptive with a bootstrap; a lag counts only in both halves.", display: "One curve per pair.",
    source: "Hou, \"Industry Information Diffusion and the Lead-Lag Effect\" (Review of Financial Studies, 2007); Menzly &amp; Ozbas (2010).",
    data: "Have: everything.", risk: "Overlapping windows manufacture lead–lag." },

  /* ── G · volume ── */
  { id: "G1", group: "volume", title: "Relative volume on breaks", status: "ready once breaks exist", statusKey: "ready",
    question: "Do breaks of levels and rails on high relative volume fail less often than those on low?",
    inputs: "Volume as served (v), a median baseline (the rulebook's ratified Q-2 method; the length is a registry parameter), the break events of B2 and the L cards.", history: "2003–2026.",
    rule: "Failure within 10 bars by relative-volume tercile of the break bar.", verdict: "Two proportions per tercile pair, both halves.",
    display: "Tercile × failure share.", source: "Karpoff (1987) on volume and price; Gervais, Kaniel &amp; Mingelgrin, \"The High-Volume Return Premium\" (Journal of Finance, 2001); the rulebook's Q-7.",
    data: "Have: volume. Need: the break events.", risk: "Report days carry the biggest volume (stand them down per Q-9)." },
  { id: "G2", group: "volume", title: "Volume at the usual-pullback trigger", status: "ready", statusKey: "ready",
    question: "At A3's live-knowable trigger, did high or dried-up relative volume change what followed?",
    inputs: "A3's triggers; relative volume on the trigger bar and its five-bar average.", history: "2003–2026.",
    rule: "A3's outcomes split by relative-volume tercile.", verdict: "As A3.", display: "A3's table with the tercile column.",
    source: "Wyckoff's selling climax (via Pruden, <i>The Three Skills of Top Trading</i>, 2007); O'Neil on volume drying up in a pullback; the rulebook's Q-5 and Q-6.",
    data: "Have: everything.", risk: "Using the hindsight low instead of the trigger would leak the answer." },
  { id: "G3", group: "volume", title: "Effort against result", status: "ready", statusKey: "ready",
    question: "Do high-volume, narrow-range days (absorption) mark turns more often than chance?",
    inputs: "Relative volume and the bar's range in usual days.", history: "2003–2026.",
    rule: "Absorption = volume in the top tenth and range in the bottom third; outcome 10 sessions later against ordinary days.", verdict: "Descriptive.",
    display: "One row per side.", source: "Wyckoff; Tom Williams, <i>Master the Markets</i> (1993); the rulebook's Q-4.",
    data: "Have: everything.", risk: "Thresholds chosen after looking." },

  /* ── H · regime and qualitative ── */
  { id: "H1", group: "regime", title: "Every study above, split by the market's weather", status: "ready for the price regimes; the heat needs a stored history", statusKey: "ready",
    question: "Does a row that looks good pooled survive inside each regime, or only in one?",
    inputs: "SPY above or below its 200-day; the VIX's own percentile (FMP, from 1990); the heat's own percentile once stored; later the rulebook's four regime states (S3 in F3).",
    history: "As each study.", rule: "Each study's table repeated per regime cell.", verdict: "Every cell is a trial (the rulebook's X-R3); Benjamini–Hochberg across cells.",
    display: "One extra column on every study page.",
    source: "Faber, \"A Quantitative Approach to Tactical Asset Allocation\" (2007); Whaley (2000) on the VIX; the rulebook's X-2 and X-5.",
    data: "Have: SPY, VIX. Need: a daily stored heat with its voters (the allocation tool computes it live and keeps no history).", risk: "Many cells, few events in each." },
  { id: "H2", group: "regime", title: "The name's own volatility regime", status: "ready", statusKey: "ready",
    question: "When a name's usual day sits in its own top tenth, what followed, and do the A-group lines behave differently?",
    inputs: "The usual day and its own percentile.", history: "All history.", rule: "A1–A3 split by the usual day's own tercile.", verdict: "As each study.",
    display: "A column.", source: "Engle (1982); Bollerslev (1986); Moreira &amp; Muir, \"Volatility-Managed Portfolios\" (Journal of Finance, 2017).",
    data: "Have: everything.", risk: "Volatility spikes cluster in a handful of months." },
  { id: "H3", group: "regime", title: "The AI cycle read as a regime column", status: "needs the operator input to exist", statusKey: "needs",
    question: "Once Alan has set the AI cycle state on dated mornings, how did the leaders, the cohorts and every A–G study behave under each state?",
    inputs: "operator_inputs rows (proposed on this page): name = ai_cycle, state, reason, set_at; bars.",
    history: "From the first morning Alan sets it. Past periods only if Alan labels them himself, stored as hindsight labels, never mixed with live ones.",
    rule: "Each study's table repeated by the state in force on the event date.", verdict: "Descriptive; for months the counts will be small and the page says so.",
    display: "A column, with the dates each state was set and why.",
    source: "Shiller, <i>Irrational Exuberance</i> (2000) and <i>Narrative Economics</i> (2019); Baker &amp; Wurgler, \"Investor Sentiment and the Cross-Section of Stock Returns\" (Journal of Finance, 2006).",
    data: "Have: nothing yet. Need: the operator_inputs table and time.", risk: "Labelling the past with hindsight; tiny samples; changing the state because of the numbers it is meant to condition." },
  { id: "H4", group: "regime", title: "News that moves leaders, tagged and counted", status: "needs the tags", statusKey: "needs",
    question: "After a tagged headline on a leader (customer concentration, a hyperscaler deal naming a preferred provider, an export control, a guidance change), how did the name move against its cohort on the day and over 1, 5 and 20 sessions?",
    inputs: "Tagged news events (proposal below): ticker, counterparty, tag, direction as the headline states it, first-seen time; bars; the cohort index.",
    history: "From when tagging starts; backfill from the Hub's news table as far as its timestamps are trustworthy.",
    rule: "Abnormal return = the name's return minus its cohort's, from the first session that could trade on the headline.",
    verdict: "Event-study counts per tag with overlap-aware intervals; the count first.", display: "Tag × horizon.",
    source: "Fama, Fisher, Jensen &amp; Roll (1969); MacKinlay, \"Event Studies in Economics and Finance\" (Journal of Economic Literature, 1997); Tetlock, \"Giving Content to Investor Sentiment\" (Journal of Finance, 2007).",
    data: "Have: the news feed and the Loughran–McDonald headline lexicon. Need: the tags, a dedupe cluster per story, and trustworthy first-seen times.",
    risk: "We tag what we remember; pre-market against intraday timing; the lexicon's tone is not the event." },
];
