"""Build deliverables/20260928/research-3/RESEARCH-3.html from data/*.json. Plain words; every number read from the JSON; no clock other than the build stamp."""
import json, os, datetime as dt, html
HERE = os.path.dirname(os.path.abspath(__file__)); OUT = os.path.normpath(os.path.join(HERE, "../../../deliverables/20260928/research-3"))
J = {k: json.load(open(os.path.join(OUT, "data", f"q{k}-{n}.json"))) for k, n in ((1, "regime"), (2, "geiger"), (3, "short"), (4, "playbook"), (5, "names"), (6, "public"))}
q1, q2, q3, q4, q5, q6 = (J[i] for i in range(1, 7))
def f(x, d=1, sign=False, pct=""):
    if x is None: return "—"
    s = f"{x:+.{d}f}" if sign else f"{x:.{d}f}"; return s + pct
def ud(x, d=1, pct="%"):
    if x is None: return "—"
    return f'<span class="{"up" if x >= 0 else "dn"}">{x:+.{d}f}{pct}</span>'
def ordn(p):
    if p is None: return "—"
    n = int(round(p)); suf = "th" if 10 <= n % 100 <= 20 else {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th"); return f"{n}{suf}"
def verdict(p, n):
    if p is None or n < 8: return '<span class="word">TOO FEW</span>'
    return '<span class="word">LUCK-PROOF</span>' if p <= 0.05 else ('<span class="word">LEANING</span>' if p <= 0.2 else '<span class="word">NOT SHOWN</span>')
def rng(c, d=1): return f"{f(c['median'], d, True)}% (90% range {f(c['lo'], d, True)} to {f(c['hi'], d, True)}, base {f(c['base_median'], d, True)}%)"
def cell(c, d=1, pct="%"):
    if not c or c.get("median") is None: return "—"
    return f"{ud(c['median'], d, pct)} <span class='q'>[{f(c.get('lo'), d, True)}, {f(c.get('hi'), d, True)}] n{c['n']} · base {f(c['base_median'], d, True)}</span>"
P = []
P.append(f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Research 3 · Alan's evening questions · 28 Sep 2026</title>
<style>
body{{margin:0;background:#07070C;color:#B4B4C6;font:17px/1.55 -apple-system,"Helvetica Neue",Arial,sans-serif;padding:28px 34px 80px;max-width:1500px}}
h1{{font-size:34px;margin:0 0 6px;color:#C8C8D2}}h2{{font-size:26px;margin:46px 0 8px;color:#C8C8D2}}h3{{font-size:19px;margin:26px 0 6px;color:#C8C8D2}}
p,li{{max-width:1080px}}.q{{color:#9C9CAE;font-size:13px}}
ol.lead{{font-size:19px;color:#C8C8D2;max-width:1120px;padding-left:24px}}ol.lead li{{margin:0 0 12px}}
.status{{border:1px solid #2A2A36;border-left:4px solid #8A8A9E;padding:12px 16px;margin:18px 0;max-width:1080px;color:#C8C8D2}}
code{{font:14px ui-monospace,Menlo,monospace;color:#BEBECE}}.scroll{{overflow-x:auto;max-width:100%}}
table{{border-collapse:collapse;font-size:14px;margin:10px 0;font-variant-numeric:tabular-nums}}th,td{{border:1px solid #24242E;padding:6px 9px;text-align:left;vertical-align:top}}th{{color:#A8A8BA;font-weight:600;font-size:13px;font-family:ui-monospace,Menlo,monospace}}
.chart{{display:block;background:#0B0B12;border:1px solid #1E1E28;margin:12px 0;max-width:1400px;height:auto}}
.up{{color:#00FFA3}}.dn{{color:#FF2D55}}
.card{{border:1px solid #24242E;background:#0B0B12;padding:14px 18px;margin:12px 0;max-width:1120px}}.card h3{{margin:0 0 6px}}.k{{font:12px ui-monospace,Menlo,monospace;letter-spacing:.08em;color:#8A8A9E}}
.card p{{margin:6px 0}}a{{color:#C0C0CE}}
.word{{display:inline-block;font:12px ui-monospace,Menlo,monospace;letter-spacing:.1em;border:1px solid #2A2A36;padding:1px 7px;border-radius:2px;color:#C8C8D2}}
dl{{max-width:1120px}}dt{{color:#C8C8D2;font-weight:600;margin-top:10px}}dd{{margin:2px 0 0 0}}
@media(max-width:600px){{body{{padding:20px 16px 60px;font-size:16px}}h1{{font-size:26px}}h2{{font-size:22px}}ol.lead{{font-size:17px}}table{{font-size:12px}}th,td{{padding:5px 6px}}code{{overflow-wrap:anywhere}}}}
</style></head><body>
<span data-scnav-slot></span><h1>Research 3: Alan's evening questions, answered like a statistician</h1>
<div class="q">P5 · 28 Sep 2026 · daily and intraday bars from the chart API to the 28 Sep close (VIX, rates and the dollar to 25 Sep, their daily bar publishes overnight; Cboe put/call to 25 Sep) · equal-weight sector histories from the regime lane's FMP pull (run on Fly) stitched to the chart API · point-in-time top-20 leaders from the N9 cache · built {dt.datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC · research, not advice · <b>no buy or sell calls on this page</b></div>
<div class="status"><b>STATUS · run on real data, pushed to a branch, not deployed.</b> All six questions ran. The Geiger maths on this page is a port of the live publisher, and it reproduces the live <code>/geiger</code> reading for SPY and QQQ to six decimals on all seven rungs (test pinned). The point-in-time universe (deliverables/20260928/point-in-time) has not landed on the live branch; where a study needs survivorship-free names (Q1 leaders, Q4 leaders below the 200-day) it reads the N9 lane's local cache of the same data and says so. Every chart is a saved PNG in <code>charts/</code>, every number is read from <code>data/*.json</code>, and every study writes its inputs, its cells tried and its false-discovery check.</div>
<h2>What this page says, in plain words</h2>
<ol class="lead">""")
sp = {t["label"]: t for t in q1["pairs"]}; low = [t for t in q1["pairs"] if t["pctile"] <= 5]; high = [t for t in q1["pairs"] if t["pctile"] >= 95]
both = [s for s in q1["split"]["studies"] if s["name"].startswith("one pair")][0]; b63 = both["h"]["63"]["spy"]; b252 = both["h"]["252"]["spy"]; ewn = q1["ew_normal"]; sw = q1["swing"]; g_less = sw["groups"]["down day, EW fell less by ≥0.15 (today's shape)"]
P.append(f"""<li><b>The lopsided pairs are a leadership-concentration reading, not a crash reading.</b> {len(low)} pairs sit in their bottom 5% (S&amp;P, Russell 1000, communication services, both Nasdaq-100 funds{', staples' if any(t['label']=='Consumer staples' for t in low) else ''}) while utilities sit at the {ordn(sp['Utilities']['pctile'])} and health care at the {ordn(sp['Health care']['pctile'])}. Days with one sector pair in its bottom 5% and another in its top 5% at once have happened on {both['days']} days since 2007 ({both['episodes']} spells). After them SPY's next 63 sessions were {ud(b63['median'])} against {f(b63['base_median'], 1, True)}% on any day (p {f(b63['p'], 2)}), and the next year {ud(b252['median'])} against {f(b252['base_median'], 1, True)}%: <b>weaker than usual, not a collapse, with wide ranges</b>. Equal weight trailing IS the normal state since 2015: it lost to cap weight over one year on {ewn['share_since_2015']*100:.0f}% of days since 2015 (against {ewn['share_2003_2014']*100:.0f}% in 2003–14). Today's shape, a down day where equal weight fell less, is common ({sw['share_of_down_days_ew_fell_less']*100:.0f}% of down days) and told nothing about the next month; the heavy names did not sell off on those days (leaders lagged SPY on {sw['leaders_minus_spy_on_such_days']['share_leaders_worse']*100:.0f}% of them, a median {f(sw['leaders_minus_spy_on_such_days']['median'],2,True)} points).</li>""")
pc = q2["percentile"]; ch = q2["change"]; cn0 = q2["corner"]; po0 = cn0["pooled"]
P.append(f"""<li><b>The Geiger moved a lot today because 40% of its weight finishes inside the day.</b> The 3h, 4h and 6h rungs carry {q2['intraday_weight_share']*100:.0f}% of Alan's Equalizer weight, and their momentum half (RSI and Williams over 14 bars, that is 5 to 10 sessions) flips within hours. Friday's close read +{pc['friday']:.2f}; the daily bar's finish took it to +0.63, the overnight 6h/12h bars to +0.52, then each intraday bar cut it: +0.49, +0.45, +0.39, +0.34, +0.30, +0.31 and +0.29 at the close. Alan's +0.55 → +0.33 → +0.41 are three of those publications. A close-to-close change of {ch['today']:+.2f} is the {ordn(ch['pctile_of_abs_change'])} percentile of the composite's own daily changes (median {ch['median_abs_change']:.2f}); SPY's −0.7% explains only {ch['expected_from_spy_move']:+.2f} of it, the rest is the intraday momentum resetting. <b>Own-history percentile:</b> +{pc['today']:.2f} is the {ordn(pc['pctile_since_2013'])} percentile of every close since 2013 (the composite lives above zero {pc['share_above_zero']*100:.0f}% of the time; its median is +{pc['quantiles_since_2013']['50']:.2f}), so today is ordinary, Friday's +{pc['friday']:.2f} was the {ordn(pc['friday_pctile'])}. The "opposite corner" (weak trend, momentum turning up), pooled over {cn0['names']} names, was followed by a median {po0['corner_rising']['median']:+.1f}% over 21 sessions in rising markets (any rising-market day {po0['base_rising']['median']:+.1f}%) and {po0['corner_falling']['median']:+.1f}% in falling markets (any falling-market day {po0['base_falling']['median']:+.1f}%): {'an edge in both, larger in the falling market' if (po0['corner_falling']['median']-po0['base_falling']['median']) > (po0['corner_rising']['median']-po0['base_rising']['median']) > 0 else 'an edge in both, larger in the rising market' if (po0['corner_rising']['median']-po0['base_rising']['median']) > (po0['corner_falling']['median']-po0['base_falling']['median']) > 0 else 'a small edge in rising markets only' if (po0['corner_rising']['median']-po0['base_rising']['median']) > 0 else 'no edge over the base'}, and neither clears the luck check (section 2.3). The futures Geigers differ from SPY/QQQ mainly because their intraday histories on the chart API are only weeks long, so their fan has fewer lines and their 12h momentum spans days, not weeks (section 2.5).</li>""")
vx = q3["vix"]; pcl = q3["putcall"]; tf = q3["rules"]["today"]
P.append(f"""<li><b>Today's VIX jump was ordinary-large, and the put/call is complacent, not fearful.</b> +{vx['change_pct']:.1f}% is {vx['x_usual']:.1f}× the VIX's usual day (±{vx['usual_day_60']:.1f}%) and the {ordn(vx['pctile_of_all_changes'])} percentile of all daily changes since 1995: it happens about {vx['per_year']:.0f} times a year. From a calm level, such jumps were followed by a median {ud(q3['vix_after']['VIX up ≥ 8% from a calm level (<20)']['h']['f5']['median'],2)} in SPY over 5 sessions (base {f(q3['vix_after']['VIX up ≥ 8% from a calm level (<20)']['h']['f5']['base_median'],2,True)}%), nothing special. The five-day put/call ({pcl['pcc5']:.2f}, latest print 25 Sep) is at the {ordn(pcl['pcc5_pct'])} percentile: <b>low</b>, which is the opposite of the fear reading a short-term bounce rule wants. The rule set to TEST (section 3) tried {q3['rules']['tests']} cells; <b>none survived the false-discovery check</b>, and the one that fits today (VIX spike + Geiger speed with the Geiger still positive) came out at or below the base rate.</li>""")
fc = q4["financials_after_cut"]; dsn = q4["dow_spx_ndx"]; st = q4["staples"]; ld = q4["leaders_below_200"]
TK = "narrow & rising rates (today's kind)"; today_reg = dsn["regimes"][TK]["pairs"]; tk_days = dsn["regimes"][TK]["days"]
P.append(f"""<li><b>Playbook theses:</b> financials after the first cut is <b>three cases, three answers</b> (2007 crushed; 2019 flat for six months, then the 2020 crash landed inside the year; 2024 flat to slightly up), so no rule. Rate-sensitive washouts (XLU, XLRE, VNQ, VPU at their bottom-1% RSI) were followed by above-base 63-session returns in every fund, and whether the 10-year had already turned made little difference; XLU's RSI today ({q4['washouts']['XLU']['rsi_today']:.0f}) is in its bottom 1%. In today's regime (narrow breadth and rising rates, {tk_days} such days since 2003) the Dow beat the S&amp;P by a median {f(today_reg['dia_spy_f63']['median'],1,True)} points over 63 sessions and the Nasdaq by {f(today_reg['qqq_spy_f63']['median'],1,True)}, both inside their ranges. WMT and COST are defensive on bad days (they beat SPY on {st['WMT']['on_spy_days_below_minus1p5']['share_beat_spy']*100:.0f}% and {st['COST']['on_spy_days_below_minus1p5']['share_beat_spy']*100:.0f}% of SPY's −1.5% days) and their own fast 10% drops were followed by above-base returns; today they are {f(st['WMT']['today']['drawdown_from_252d_high_pct'],0)}% and {f(st['COST']['today']['drawdown_from_252d_high_pct'],0)}% under their year highs, 90 sessions after the high, which is a slow slide, not a knife. Leaders below their 200-day while the market is above kept leading only when they were still ahead over 63 sessions (median {f(ld['states']['leader below its 200-day, market above, still leading over 63d']['ex63']['median'],1,True)} points vs SPY next 63); the ones that had stopped leading did not come back ({f(ld['states']['leader below its 200-day, market above, no longer leading']['ex63']['median'],1,True)}).</li>""")
vs = q5["vst"]["state"]; ve = q5["vst"]["earnings_summary"]; vk = q5["vst"]["knife"]; orc = q5["orcl"]["state"]; sw5 = q5["software"]
P.append(f"""<li><b>VST</b> has missed the consensus EPS on {ve['misses']} of its last {ve['reports']} reports (the last one by 53%, the Feb one by 76%) while its adjusted EBITDA guidance held and the AWS (~3,800 MW nuclear), Meta (2,600 MW) and Cogentrix (5,500 MW, $4.7bn) deals stacked up; the street's average target sits near $225 against $138 (Guggenheim $300). It is {f(vs['drawdown_from_252d_high'],0)}% under its year high, {f(vs['dist_200d_pct'],0)}% below its 200-day, Geiger {f(vs['live_geiger']['composite'],2,True)}. Its own falling-knife history is short: {vk['-30']['episodes']} times it sat 30% under its year high; what followed is listed, not averaged. <b>ORCL</b> fell {f(orc['day_pct'],1)}% today ({f(orc['x_usual'],1)}× its usual day) on the Project Jupiter force-majeure and credit stories; it is {f(orc['drawdown_from_252d_high'],0)}% under its high. <b>The software bucket</b> is measured best by <b>{sw5['best_fund']['BUCKET_EW']}</b> (iShares software), with SKYY (cloud) the closest fund for MDB, SHOP, SNOW, ORCL and LYFT; on the tree all nine sit in the AI_SOFTWARE branch. But the nine move together at only {sw5['mean_pairwise_corr_inside']:.2f} correlation, so it is a theme, not a cohort.</li>""")
lm = q6["lmw"]; hl = q6["harvey_liu"]
P.append(f"""<li><b>Public work:</b> Lo–Mamaysky–Wang's kernel-regression pattern finder, rebuilt on {lm['names']} of our names since 2003, finds {lm['hits']:,} pattern completions. As in the paper, several patterns' one-day return distributions differ from all days (the paper's test), but the next-21-session medians after every pattern sit within a point of the base and the shapes do not turn into a return edge. Harvey–Liu's haircut on the rules published today: the 1928 trend rules keep about three quarters of their Sharpe; every rule from the 2003-to-today window loses most or all of it once the tests tried are counted. That is the honest scale for every table on this page.</li>
</ol>""")
# ---------------------------------------------------------------- Q1
P.append(f"""<h2 id="q1">1 · The lopsided equal-weight pairs: what does the combination mean?</h2>
<p class="k">THE QUESTION</p><p>Some pairs sit at their lowest ever (S&amp;P, communication services, Nasdaq-100) while equal-weight health care and utilities sit at their strongest. What did that combination mean before? Is equal weight trailing the normal state? What happened to the cap-weight leaders when breadth swung like this? Today: SPY −0.70%, QQQ −0.94%, RSP −0.53% on Alan's screen (the chart API's finished bars say SPY {f(sw['today']['spy'],2,True)}%, RSP {f(sw['today']['rsp'],2,True)}%).</p>
<p><b>What we measured.</b> The regime lane's pairs (equal-weight fund ÷ cap-weight fund, sector pairs under the Invesco funds' old tickers before 2023 from the FMP pull, stitched to the chart API's bars), each ratio's own-history percentile using prior days only. The "split" is, each day, the highest sector-pair percentile minus the lowest. "Both tails" is a day with at least one sector pair in its bottom 5% and another in its top 5%. Outcomes are SPY, equal minus cap weight (RSP − SPY) and the point-in-time top-20 leaders basket minus SPY over 21, 63, 126 and 252 sessions, with stationary block bootstrap ranges and base rates beside them.</p>
<img class="chart" src="charts/q1-1-pairs-today.png" alt="every pair's percentile today" width="100%">
<div class="scroll"><table><tr><th>pair</th><th>own percentile today</th><th>one-year change</th><th>history</th><th>lowest on</th><th>highest on</th></tr>""")
for t in sorted(q1["pairs"], key=lambda x: x["pctile"]): P.append(f"<tr><td>{t['label']} ({t['ew']} ÷ {t['cw']})</td><td>{ordn(t['pctile'])}</td><td>{ud(t['one_year_pct'])}</td><td>{t['from']} → {t['to']}</td><td>{t['low_date']}</td><td>{t['high_date']}</td></tr>")
spl = q1["split"]
P.append(f"""</table></div>
<div class="card"><h3>What the combination meant before {verdict(b63['p'], both['episodes'])}</h3>
<p><b>How many:</b> the split (strongest minus weakest sector pair) is {spl['today']:.0f} points today, the {ordn(spl['pctile'])} percentile of its history since {spl['history_from']}. "Both tails" days: {both['days']} of {spl['n_days']} days ({both['episodes']} spells). <b>How big:</b> SPY's next 63 sessions after a both-tails day were a median {ud(b63['median'])} (range {f(b63['lo'],1,True)} to {f(b63['hi'],1,True)}) against {f(b63['base_median'],1,True)}% on any day; the next year {ud(b252['median'])} against {f(b252['base_median'],1,True)}%. <b>How sure:</b> p = {f(b63['p'],2)} over 63 sessions, so the weaker-than-usual reading is {'luck-proof' if b63['p']<=0.05 else 'leaning' if b63['p']<=0.2 else 'not shown'}; the spells cluster (2008, 2020, 2022, and this year), so the honest count is the spells, not the days.</p>
<p><b>In plain words:</b> when one sector's equal-weight fund is at its strongest against its cap-weight fund while another's is at its weakest, the market is being carried by a few heavy names in one place and abandoned in another. Historically that was a late, narrow tape: the index kept rising more often than not but by less than usual, and the mean outcome hides a few bad spells. It is a reason to size by breadth, not a signal on its own.</p></div>
<img class="chart" src="charts/q1-2-sector-split.png" alt="sector split history" width="100%">
<div class="scroll"><table><tr><th>state</th><th>spells</th><th>SPY next 21</th><th>SPY next 63</th><th>SPY next 252</th><th>EW − CW next 63</th><th>leaders − SPY next 63</th></tr>""")
for s in spl["studies"]: P.append(f"<tr><td>{s['name']}</td><td>{s['episodes']}</td><td>{cell(s['h']['21']['spy'])}</td><td>{cell(s['h']['63']['spy'])}</td><td>{cell(s['h']['252']['spy'])}</td><td>{cell(s['h']['63']['ew_minus_cw'])}</td><td>{cell(s['h']['63'].get('lead_minus_spy'))}</td></tr>")
ent = q1["ratio_bottom5_entries"]
P.append(f"""</table></div>
<h3>Is equal weight trailing the normal state?</h3>
<p>Yes, since 2015. RSP ÷ SPY rose from {ewn['ratio_2003']:.3f} in 2003 to a peak of {ewn['ratio_peak']:.3f} on {ewn['ratio_peak_date']} and sits at {ewn['ratio_today']:.3f} today, the {ordn(ewn['ratio_pctile'])} percentile of its own past (its lowest since the fund's start is {sp['S&P 500']['low_date']}). Over rolling one-year windows equal weight lost to cap weight on {ewn['share_of_days_ew_behind_1y']*100:.0f}% of all days since 2004, {ewn['share_2003_2014']*100:.0f}% of days in 2003–14 and {ewn['share_since_2015']*100:.0f}% of days since 2015. Today's one-year change ({ewn['today_1y_change']:+.1f}%) is the {ordn(ewn['today_1y_pctile'])} percentile of one-year changes: worse than usual, far from the worst ({ewn['worst_1y']:+.1f}% on {ewn['worst_1y_date']}). So "trailing" is the ordinary state of the last decade; what is unusual is the level, not the pace.</p>
<img class="chart" src="charts/q1-3-rsp-spy.png" alt="RSP over SPY since 2003" width="100%">
<p><b>After the ratio's own bottom-5% entries</b> (first day in the bottom 5% after 63 sessions away; {ent['episodes']} entries: {', '.join(ent['dates'])}): SPY's next year was {', '.join(f'{v:+.0f}%' for v in ent['h']['252']['spy']['values'])} (base {f(ent['h']['252']['spy']['base_median'],1,True)}%), equal weight minus cap weight {', '.join(f'{v:+.0f}' for v in ent['h']['252']['ew_minus_cw']['values'])} points (it did not catch up), leaders minus SPY {', '.join(f'{v:+.0f}' for v in ent['h']['252']['lead_minus_spy']['values'])}. Four finished cases is a list, not a statistic; it agrees with the statistician-2 page's ten entries.</p>
<h3>What happened to the cap-weight leaders when breadth swung like this?</h3>
<p><b>Today's shape</b> is a down day on which equal weight fell less than the index (gap {f(sw['today']['gap'],2,True)} points). That is {sw['share_of_down_days_ew_fell_less']*100:.0f}% of all down days of 0.5% or more since 2003. On those days the leaders basket (point-in-time top 20 by market cap) lagged SPY on {sw['leaders_minus_spy_on_such_days']['share_leaders_worse']*100:.0f}% of them by a median {f(sw['leaders_minus_spy_on_such_days']['median'],2,True)} points: <b>the heavy names gave back a little, they did not sell off</b>. What followed:</p>
<div class="scroll"><table><tr><th>day type</th><th>days</th><th>SPY next 5</th><th>SPY next 21</th><th>SPY next 63</th><th>EW − CW next 21</th><th>leaders − SPY next 21</th><th>leaders − SPY next 63</th></tr>""")
for name, g in sw["groups"].items(): P.append(f"<tr><td>{name}</td><td>{g['days']}</td><td>{cell(g['h']['5']['spy'],2)}</td><td>{cell(g['h']['21']['spy'])}</td><td>{cell(g['h']['63']['spy'])}</td><td>{cell(g['h']['21']['ew_minus_cw'],2,' pts')}</td><td>{cell(g['h']['21'].get('lead_minus_spy'),2,' pts')}</td><td>{cell(g['h']['63'].get('lead_minus_spy'),2,' pts')}</td></tr>")
bs = sw["breadth_swing_20d"]
P.append(f"""</table></div>
<img class="chart" src="charts/q1-4-after-swing-days.png" alt="after swing days" width="100%">
<p><b>A bigger swing, 20 sessions long</b> (equal weight beating cap weight by {bs['threshold_pts']:.1f} points or more over 20 sessions, its top 5%; {bs['episodes']} spells): SPY's next 63 were {cell(bs['h']['63']['spy'])}, leaders minus SPY {cell(bs['h']['63']['lead_minus_spy'],2,' pts')}. Today's 20-session gap is {bs['today_gap20']:+.1f} points, the other way: equal weight has been losing, and one day of falling less does not change that.</p>
<p class="q">Sources: chart API daily bars (RSP, SPY, QQQ, QQQE, DIA, sector funds); regime lane FMP pull for the equal-weight sector funds before 2023 (RSPT…RSPC under their old tickers, QQEW, EQAL, IWB); N9 point-in-time cache for the leaders basket (top 20 by full market cap at the prior year-end). Percentiles use prior days only. What could be wrong: the FMP head is scaled onto the chart API's first bar so the join is continuous; the old-ticker histories are FMP's mapping; the leaders basket is to 25 Sep.</p>""")
# ---------------------------------------------------------------- Q2
tp = q2["today_path"]; fut = q2["futures"]; cn = q2["corner"]
P.append(f"""<h2 id="q2">2 · Geiger mechanics: why it moved today, its own-history percentile, the opposite corner, the futures gap</h2>
<p class="k">THE DEFINITION, VERIFIED</p><p>Per timeframe, TREND = the order of the 9-line fan (EMA 5/8/13/21/34, SMA 50/100/150/200) → (2 × pairs in order − 8) ÷ 8, so it can only take the values −1, −0.75 … +1. MOMENTUM = RSI(14) scaled from 23→77 and Williams %R(14) scaled from −90→−10, mixed 60/40, clipped to ±1. Each rung's composite is 50/50 of the two. The seven rungs are weighted by Alan's Equalizer: 3h {q2['weights']['3h']:.2f}, 4h {q2['weights']['4h']:.2f}, 6h {q2['weights']['6h']:.2f}, 12h {q2['weights']['12h']:.2f}, D {q2['weights']['1d']:.2f}, 3D {q2['weights']['3d']:.2f}, W {q2['weights']['1w']:.2f}. Each rung reads its newest 230 finished bars. This page's port reproduces the live <code>/geiger</code> for SPY and QQQ on every rung to six decimals (test <code>tests/research-3-20260928.test.mjs</code>).</p>
<h3>2.1 · Why +0.55 → +0.33 → +0.41 while SPY fell 0.7%</h3>
<p>The intraday rungs (3h, 4h, 6h) carry <b>{q2['intraday_weight_share']*100:.0f}%</b> of the weight; with the 12h rung, {q2['with_12h']*100:.0f}%. Their momentum half looks back 14 bars, which on the 3h rung is about five sessions and on the 6h rung about ten, so a two-day dip drives their RSI and Williams from the top of the range to the bottom. Their trend half is a count of fan pairs in order, so it moves in steps of 0.25. The daily, 3-day and weekly rungs barely moved today (all three still read their fan fully in order, TREND +1). Here is the composite each time a rung's bar finished on 28 Sep (UTC), which is when the publisher would have re-read it:</p>
<div class="scroll"><table><tr><th>bar finished (UTC)</th><th>composite</th><th>change</th><th>3h</th><th>4h</th><th>6h</th><th>12h</th><th>D</th><th>3D</th><th>W</th><th>which rung moved it</th></tr>""")
for r in tp:
    pieces = r.get("pieces", {}); mover = ", ".join(f"{k} {v:+.3f}" for k, v in sorted(pieces.items(), key=lambda kv: -abs(kv[1])) if abs(v) >= 0.005)
    P.append(f"<tr><td>{r['stamp_utc']}</td><td><b>{r['composite']:+.3f}</b></td><td>{ud(r.get('change'),3,'') if 'change' in r else '—'}</td>" + "".join(f"<td>{r['rungs'][k]:+.2f}</td>" for k in ("3h", "4h", "6h", "12h", "1d", "3d", "1w")) + f"<td>{mover or '—'}</td></tr>")
P.append(f"""</table></div>
<img class="chart" src="charts/q2-3-today-path.png" alt="today's path" width="100%">
<p><b>How unusual is a {ch['today']:+.2f} day?</b> Since mid-2013 (when all seven rungs exist) the composite's median close-to-close change is {ch['median_abs_change']:.2f} in absolute terms; {ch['share_of_days_change_beyond_0_3']*100:.0f}% of days move it by 0.30 or more. Today is the {ordn(ch['pctile_of_abs_change'])} percentile. SPY's own day explains {ch['r2']*100:.0f}% of the composite's daily change (slope {ch['slope_per_1pct']:+.2f} per 1%); for a −0.74% day the fitted change is {ch['expected_from_spy_move']:+.2f}. The other {abs(ch['today']-ch['expected_from_spy_move']):.2f} came from where the intraday momentum was standing on Friday (near its ceiling after four up days), not from the size of today's fall. <b>That is the mechanic: the Geiger is a position in a range, and it moves most when it starts near an edge.</b></p>
<h3>2.2 · Its own-history percentile, with pictures</h3>
<div class="card"><h3>Today +{pc['today']:.2f} is the {ordn(pc['pctile_since_2013'])} percentile; Friday's +{pc['friday']:.2f} was the {ordn(pc['friday_pctile'])}</h3>
<p><b>How many:</b> every SPY close since July 2013, {ch['n']:,} of them, each with all seven rungs replayed from the bars that had finished by that close. <b>The shape:</b> the composite lives above zero {pc['share_above_zero']*100:.0f}% of the time, because SPY spends most of its life with its fan in order. Its median is +{pc['quantiles_since_2013']['50']:.2f}; the 25th percentile is {pc['quantiles_since_2013']['25']:+.2f}, the 10th {pc['quantiles_since_2013']['10']:+.2f}, the 5th {pc['quantiles_since_2013']['5']:+.2f}, the 1st {pc['quantiles_since_2013']['1']:+.2f}; the 75th is +{pc['quantiles_since_2013']['75']:.2f}, the 90th +{pc['quantiles_since_2013']['90']:.2f}, the 95th +{pc['quantiles_since_2013']['95']:.2f}. So "+0.29" is not "slightly bullish": it is a little under the middle of where SPY usually sits. QQQ today +{pc['qqq_today']:.2f} is its {ordn(pc['qqq_pctile'])}.</p>
<p><b>Reading it by decile (SPY's next 21 and 63 sessions, medians, base {q2['base']['f21']:+.2f}% and {q2['base']['f63']:+.2f}%):</b></p>
<div class="scroll"><table><tr><th>decile</th><th>composite from</th><th>to</th><th>days</th><th>next 21 median</th><th>next 63 median</th><th>next 21 up</th></tr>""")
for d in q2["deciles"]: P.append(f"<tr><td>{d['decile']}</td><td>{d['lo']:+.2f}</td><td>{d['hi']:+.2f}</td><td>{d['n']}</td><td>{ud(d['f21'])}</td><td>{ud(d['f63'])}</td><td>{d['up21']*100:.0f}%</td></tr>")
P.append(f"""</table></div>
<p><b>In plain words:</b> low readings came before better months (the bottom decile's next 21 sessions were a median {q2['deciles'][0]['f21']:+.1f}% against {q2['deciles'][-1]['f21']:+.1f}% for the top decile), which is mean reversion in an index that keeps rising, not a timing tool: the up-share is 64–71% in every decile. The Geiger's own history says where you are in the range; it does not say the direction of the next step.</p></div>
<img class="chart" src="charts/q2-1-composite-history.png" alt="composite history" width="100%">
<img class="chart" src="charts/q2-2-percentile-and-speed.png" alt="percentile and speed" width="100%">
<h3>2.3 · The opposite corner: weak trend, momentum turning up</h3>
<p><b>Definition (daily rung, where the history is long and clean):</b> {cn['definition']}</p>
<div class="scroll"><table><tr><th>set</th><th>rising market · spells</th><th>next 21, median</th><th>base (any day, rising)</th><th>verdict</th><th>falling market · spells</th><th>next 21, median</th><th>base (falling)</th><th>verdict</th></tr>""")
for sym, r in cn["indexes"].items():
    a, b = r["rising"], r["falling"]
    P.append(f"<tr><td>{sym}</td><td>{a['episodes']}</td><td>{ud(a['median'])} <span class='q'>[{f(a['lo'],1,True)}, {f(a['hi'],1,True)}]</span></td><td>{f(a['base_median'],1,True)}%</td><td>{verdict(a['p'], a['episodes'])}</td><td>{b['episodes']}</td><td>{ud(b['median'])} <span class='q'>[{f(b['lo'],1,True)}, {f(b['hi'],1,True)}]</span></td><td>{f(b['base_median'],1,True)}%</td><td>{verdict(b['p'], b['episodes'])}</td></tr>")
po = cn["pooled"]
P.append(f"""<tr><td><b>all {cn['names']} names pooled</b></td><td>{po['corner_rising']['n']}</td><td>{ud(po['corner_rising']['median'])} <span class='q'>[{f(po['corner_rising']['lo'],1,True)}, {f(po['corner_rising']['hi'],1,True)}]</span></td><td>{f(po['base_rising']['median'],1,True)}%</td><td>{verdict(po['corner_rising'].get('p_vs_base'), po['corner_rising']['n'])}</td><td>{po['corner_falling']['n']}</td><td>{ud(po['corner_falling']['median'])} <span class='q'>[{f(po['corner_falling']['lo'],1,True)}, {f(po['corner_falling']['hi'],1,True)}]</span></td><td>{f(po['base_falling']['median'],1,True)}%</td><td>{verdict(po['corner_falling'].get('p_vs_base'), po['corner_falling']['n'])}</td></tr>
<tr><td>strong trend + weak momentum (Alan's screen), pooled</td><td>{po['sw_rising']['n']}</td><td>{ud(po['sw_rising']['median'])} <span class='q'>[{f(po['sw_rising']['lo'],1,True)}, {f(po['sw_rising']['hi'],1,True)}]</span></td><td>{f(po['base_rising']['median'],1,True)}%</td><td>{verdict(po['sw_rising'].get('p_vs_base'), po['sw_rising']['n'])}</td><td>{po['sw_falling']['n']}</td><td>{ud(po['sw_falling']['median'])} <span class='q'>[{f(po['sw_falling']['lo'],1,True)}, {f(po['sw_falling']['hi'],1,True)}]</span></td><td>{f(po['base_falling']['median'],1,True)}%</td><td>{verdict(po['sw_falling'].get('p_vs_base'), po['sw_falling']['n'])}</td></tr>
</table></div>
<img class="chart" src="charts/q2-4-opposite-corner.png" alt="opposite corner" width="100%">
<p><b>In plain words:</b> pooled over {cn['names']} names, the opposite corner in a rising market was followed by a median {po['corner_rising']['median']:+.1f}% over 21 sessions against {po['base_rising']['median']:+.1f}% for any rising-market day; in a falling market {po['corner_falling']['median']:+.1f}% against {po['base_falling']['median']:+.1f}%. The edge, where there is one, is in the rising market, and it is the size of a normal month's noise. Alan's screen (strong trend, weak momentum: a pullback inside an uptrend) reads {po['sw_rising']['median']:+.1f}% in rising markets. The single-index rows have few spells (SPY {cn['indexes']['SPY']['rising']['episodes']} in a rising market) and should be read as lists.</p>
<h3>2.4 · Futures Geigers above (or below) SPY and QQQ: what the gap means</h3>
<p>The Hub's futures are <b>ESUSD</b> and <b>NQUSD</b> (FMP continuous contracts on the CME clock); the ticker <code>ES</code> in the served universe is Eversource Energy, a utility, and its Geiger ({-0.75:+.2f} tonight) has nothing to do with the S&amp;P. The futures are not in the <code>/geiger</code> artifact; Station computes their bars' Geiger itself. Replaying the same maths on the chart API's futures bars tonight:</p>
<div class="scroll"><table><tr><th>rung</th><th>weight</th><th>ESUSD bars on the API (from)</th><th>fan lines ES / SPY</th><th>ESUSD composite</th><th>SPY composite</th><th>NQUSD bars (from)</th><th>fan lines NQ / QQQ</th><th>NQUSD composite</th><th>QQQ composite</th></tr>""")
for k in ("3h", "4h", "6h", "12h", "1d", "3d", "1w"):
    e = fut["ESUSD"]["rungs"][k]; n = fut["NQUSD"]["rungs"][k]
    P.append(f"<tr><td>{k}</td><td>{e['weight']:.2f}</td><td>{e['fut_bars']} ({e['history_from']})</td><td>{e['fut_fan_lines']} / {e['cash_fan_lines']}</td><td>{ud(e['fut_composite'],2,'')}</td><td>{ud(e['cash_composite'],2,'')}</td><td>{n['fut_bars']} ({n['history_from']})</td><td>{n['fut_fan_lines']} / {n['cash_fan_lines']}</td><td>{ud(n['fut_composite'],2,'')}</td><td>{ud(n['cash_composite'],2,'')}</td></tr>")
P.append(f"""<tr><td><b>weighted</b></td><td></td><td></td><td></td><td><b>{fut['ESUSD']['composite']:+.2f}</b></td><td><b>{pc['today']:+.2f}</b></td><td></td><td></td><td><b>{fut['NQUSD']['composite']:+.2f}</b></td><td><b>{pc['qqq_today']:+.2f}</b></td></tr></table></div>
<img class="chart" src="charts/q2-5-futures-gap.png" alt="futures gap" width="100%">
<p><b>What the gap means.</b> Three things, none of them "the futures know something": (1) the futures' intraday bars on the chart API start on {fut['ESUSD']['rungs']['3h']['history_from']} (3h, 6h, 12h) and {fut['ESUSD']['rungs']['4h']['history_from']} (4h), so their 12h rung has {fut['ESUSD']['rungs']['12h']['fut_bars']} bars and can only form {fut['ESUSD']['rungs']['12h']['fut_fan_lines']} of the 9 fan lines, the 3h rung {fut['ESUSD']['rungs']['3h']['fut_fan_lines']}: a shorter fan swings between −1 and +1 on fewer pairs, and a 14-bar momentum on 12h futures bars looks back a week; (2) futures bars run on the CME clock (23 hours), so a "6h" bar contains the overnight session and the fan is anchored differently from SPY's cash-hours bars; (3) the daily rung is the fair comparison, and there the two agree: the daily-rung gap tonight is {fut['ESUSD']['daily_rung_gap_today']:+.2f} for ES vs SPY and {fut['NQUSD']['daily_rung_gap_today']:+.2f} for NQ vs QQQ, against a median absolute gap of {fut['ESUSD']['daily_rung_gap_median_abs_250d']:.2f} and {fut['NQUSD']['daily_rung_gap_median_abs_250d']:.2f} over the last 250 sessions. <b>Until the futures' intraday histories are backfilled to 230 bars per rung, a futures Geiger above or below the cash fund is mostly a data-length artefact.</b> That backfill is a keyed job for Fly (follow-up F2).</p>""")
# ---------------------------------------------------------------- Q3
va = q3["vix_after"]; pa = q3["putcall_after"]; gr = q3["rules"]["grid"]
P.append(f"""<h2 id="q3">3 · The short-term adjustment mechanic: put/call, the VIX, Geiger speed</h2>
<h3>3.1 · Today's VIX move against its own history</h3>
<div class="card"><h3>+{vx['change_pct']:.1f}% ({vx['prev']:.2f} → {vx['close']:.2f}, high {vx['high']:.2f}) is {vx['x_usual']:.1f}× the VIX's usual day and the {ordn(vx['pctile_of_all_changes'])} percentile of all its daily changes since 1995</h3>
<p><b>How many:</b> {vx['from_1995_n']:,} VIX sessions. The VIX's usual day (median absolute daily change over the prior 60 sessions, the Hub's USUAL DAY rule) is ±{vx['usual_day_60']:.1f}%, so today is not a sigma day by the Hub's own 2× rule. A rise of at least {vx['change_pct']:.1f}% happens on {vx['share_of_days_at_least_this_up']*100:.0f}% of days, about {vx['per_year']:.0f} times a year; among up days it is the {ordn(vx['pctile_of_up_changes'])} percentile. The level, {vx['close']:.2f}, is the {ordn(vx['level_pctile_since_1995'])} percentile of the VIX since 1995: low.</p>
<p><b>What followed jumps like it:</b></p>
<div class="scroll"><table><tr><th>condition</th><th>spells</th><th>SPY next 1</th><th>SPY next 5</th><th>SPY next 21</th><th>VIX next 5 (its own %)</th></tr>""")
for name, g in va.items(): P.append(f"<tr><td>{name}</td><td>{g['episodes']}</td><td>{cell(g['h']['f1'],2)}</td><td>{cell(g['h']['f5'],2)}</td><td>{cell(g['h']['f21'])}</td><td>{cell(g['h']['vix_f5'])}</td></tr>")
P.append(f"""</table></div>
<p><b>In plain words:</b> a VIX jump of today's size from a calm level was followed by an ordinary SPY week and a VIX that gave back most of the jump within five sessions (median {va['VIX up ≥ 8% from a calm level (<20)']['h']['vix_f5']['median']:+.1f}%). The bigger jumps (15%+) are the ones with a bounce attached, and even those sit inside their ranges.</p></div>
<img class="chart" src="charts/q3-1-vix-jump.png" alt="VIX jump" width="100%">
<h3>3.2 · Put/call: five-day vs one day, and today's reading</h3>
<p>Cboe's total put/call (PCC) one-day print moves a median {pcl['one_day_noise']['median_abs_day_change_pcc']:.2f} from one day to the next, and one day's value correlates with the next at only {pcl['one_day_noise']['autocorr_pcc_1']:.2f}; the five-day average moves {pcl['one_day_noise']['median_abs_day_change_pcc5']:.2f} and correlates at {pcl['one_day_noise']['autocorr_pcc5_1']:.2f}. That is why the Hub's sentiment card averages five days: the single print is mostly noise from that day's expiries and index hedges. Intraday (the Hub's IBKR running totals) is noisier still and starts at 0.6 at 09:30 every day, as the put/call audit showed.</p>
<div class="card"><h3>Latest print ({pcl['latest_print']}): total {pcl['pcc']:.2f} ({ordn(pcl['pcc_pct'])} percentile), five-day {pcl['pcc5']:.2f} ({ordn(pcl['pcc5_pct'])}), equity five-day {pcl['pcce5']:.2f} ({ordn(pcl['pcce5_pct'])}), equity 20-day {pcl['pcce20']:.2f} ({ordn(pcl['pcce20_pct'])})</h3>
<p>These are <b>low</b> readings: fewer puts per call than on 9 days out of 10 since 2006. Low put/call is complacency, and the studies below say complacent five-day readings were followed by ordinary returns, while fearful ones (five-day at its 80th–90th) were followed by better-than-base weeks. Today's regime is therefore the wrong one for a "fear bounce" rule; if a short-term adjustment is to be made it must lean on the VIX and the Geiger's speed, and section 3.3 shows those alone did not beat the base. The Hub's own 28 Sep reader ran during the session (index chains showed SPX put/call 1.34 at 13:57 ET); Cboe's 28 Sep print was not yet in the chart API at 23:00Z and is not used.</p></div>
<div class="scroll"><table><tr><th>condition</th><th>spells</th><th>SPY next 5</th><th>SPY next 21</th></tr>""")
for name, g in pa.items(): P.append(f"<tr><td>{name}</td><td>{g['episodes']}</td><td>{cell(g['h']['5'],2)}</td><td>{cell(g['h']['21'])}</td></tr>")
P.append(f"""</table></div>
<img class="chart" src="charts/q3-2-putcall.png" alt="put/call" width="100%">
<h3>3.3 · A short-term adjustment rule set, TO TEST (not advice)</h3>
<p>The three ingredients, written so a machine can test them:</p><ul>""" + "".join(f"<li>{s}</li>" for s in q3["rules"]["plain"]) + f"""</ul>
<p><b>Today:</b> A (fear) is <b>{'on' if tf['A'] else 'off'}</b> (five-day put/call at the {ordn(tf['A_putcall_5d_pct_25sep'])}); B (spike) is <b>{'on' if tf['B'] else 'off'}</b> ({tf['B_vix_x_usual']:.2f}× usual, the rule needs 2×); C (speed) is <b>{'on' if tf['C'] else 'off'}</b> (composite {tf['C_geiger_change']:+.2f} on the day, still positive). So today matches "C with the Geiger still above zero" and nearly matches "B & C".</p>
<div class="scroll"><table><tr><th>cell</th><th>spells</th><th>SPY next 5</th><th>up</th><th>SPY next 21</th><th>up</th><th>survives FDR 10%?</th></tr>""")
for r in gr:
    up5 = '—' if r['f5']['share_up'] is None else f"{r['f5']['share_up']*100:.0f}%"; up21 = '—' if r['f21']['share_up'] is None else f"{r['f21']['share_up']*100:.0f}%"
    P.append(f"<tr><td>{r['rule']}</td><td>{r['episodes']}</td><td>{cell(r['f5'],2)}</td><td>{up5}</td><td>{cell(r['f21'])}</td><td>{up21}</td><td>{'yes' if (r['f5']['bh_pass'] or r['f21']['bh_pass']) else 'no'}</td></tr>")
P.append(f"""</table></div>
<img class="chart" src="charts/q3-3-rule-grid.png" alt="rule grid" width="100%">
<p><b>What the grid says.</b> {q3['rules']['tests']} cells were tried on {q3['rules']['window']}. The fear cells (A, A2, A&amp;B) have the highest medians (five-day put/call at its 90th followed by a median {[r for r in gr if r['rule'].startswith('A2 ·')][0]['f21']['median']:+.1f}% over 21 sessions against {gr[0]['f21']['base_median']:+.1f}%), but with 45 to 83 spells their ranges are wide and <b>none survives the false-discovery check</b>. The speed cells (C, C2) sit at or below the base: a fast Geiger drop is a description of the last two days, not a forecast. <b>The rule set worth keeping for a test</b> is the fear-plus-spike pair (A &amp; B, or A2 &amp; B2), tested forward from here on a fixed protocol: it is the only combination whose whole 90% range sat above zero at 21 sessions, and it is not on today.</p>
<p class="q">Sources: chart API daily bars (SPY, VIX to 25 Sep; today's VIX from Alan's screen, the API's 30-minute bars agree on the 16.58 high and read 16.10 at the last bar); chart API PCC/PCCE/PCCI (Cboe printed daily ratios since 2006); the SPY Geiger composite replayed from section 2. What could be wrong: put/call is joined by date to the VIX/Geiger of the same day, so a "fear" print is known only after that close; the window is 13 years, one and a half cycles.</p>""")
# ---------------------------------------------------------------- Q4
P.append(f"""<h2 id="q4">4 · Playbook theses to test</h2>
<h3>4.1 · Financials after the first rate cut of a cycle</h3>
<p>Our fund histories start in September 2003, so the 1995, 1998 and 2001 first cuts are outside the data; that leaves {fc['n']} cases. Each is the fund minus SPY, in points, from the day of the cut:</p>
<div class="scroll"><table><tr><th>first cut</th><th>XLF − SPY: 21 · 63 · 126 · 252 sessions</th><th>KRE − SPY</th><th>KBE − SPY</th><th>IYF − SPY</th></tr>""")
for r in fc["rows"]: P.append(f"<tr><td>{r['cut']} · {r['label']}</td>" + "".join(f"<td>{' · '.join(ud(r[s][h],1,'') for h in ('21','63','126','252'))}</td>" if s in r else "<td>—</td>" for s in ("XLF", "KRE", "KBE", "IYF")) + "</tr>")
P.append(f"""</table></div>
<img class="chart" src="charts/q4-1-financials-first-cut.png" alt="financials after the first cut" width="100%">
<p><b>In plain words:</b> three cuts, three different worlds. 2007's cut was the start of the crisis and financials lost {abs(fc['rows'][0]['XLF']['252']):.0f} points to the index in a year; 2019's and 2024's were mid-cycle insurance cuts: financials tracked the index within a few points for six months, and then 2019's year ran into the 2020 crash (XLF −24 points at 252 sessions, KRE −40) while 2024's ended flat. On any random 252-session window since 2003 XLF minus SPY is a median {fc['base_xlf_minus_spy_252']['median']:+.1f} points and positive {fc['base_xlf_minus_spy_252']['share_positive']*100:.0f}% of the time. <b>Thesis status: untestable on our data (n = 3), and the three cases disagree.</b> What the cut does say is <i>why</i> it was made; the playbook test to keep is "first cut with credit calm (HYG−LQD spread not widening) vs first cut with credit stressed", which needs the 1990s cases from an index-level source (follow-up F4).</p>
<h3>4.2 · Rate-sensitive washouts when yields turn</h3>
<p>For XLU, XLRE, VNQ and VPU: the first day RSI(14) sits in its own bottom 1% (and bottom 5%), split by whether the 10-year had already fallen over the prior 10 sessions, and, as a hindsight best case, by whether yields then fell over the next 21. Outcome is the fund's next 63 sessions.</p>
<div class="scroll"><table><tr><th>fund · RSI today (own pct) · bottom-1% line</th><th>bottom 1%</th><th>bottom 5%</th><th>bottom 5%, 10-year already falling</th><th>bottom 5%, 10-year still rising</th><th>bottom 5%, yields then fell (hindsight)</th></tr>""")
for s, v in q4["washouts"].items():
    g = v["groups"]; keys = list(g.keys())
    P.append(f"<tr><td>{s} · RSI {v['rsi_today']:.0f} ({ordn(v['rsi_pct_today'])}) · {v['bottom1_rsi_level']:.0f}</td>" + "".join(f"<td>{cell(g[k]['h']['63'])} <span class='q'>spells {g[k]['episodes']}</span></td>" for k in keys) + "</tr>")
P.append(f"""</table></div>
<img class="chart" src="charts/q4-2-washouts.png" alt="washouts" width="100%">
<p><b>In plain words:</b> washed-out rate-sensitive funds bounced in every fund and every split, by 3 to 6 points over 63 sessions against a base of 1 to 2½; the whole 90% range clears the base for XLRE and VNQ (luck-proof), while XLU and VPU lean the same way with ranges that reach down to the base. Whether the 10-year had already turned did not sort the outcomes cleanly (VNQ and XLRE did better when yields were already falling, XLU and VPU did not care). The hindsight column shows the ceiling of the thesis: even knowing yields would fall added only a point or two. <b>Today XLU and XLRE are in their bottom 1% of RSI</b> ({q4['washouts']['XLU']['rsi_today']:.0f} and {q4['washouts']['XLRE']['rsi_today']:.0f}) with the 10-year at a ten-year high: this is the setup the thesis describes, and the history says "bounce more likely than not, size unknown".</p>
<h3>4.3 · Dow vs S&amp;P vs Nasdaq in narrow / rising-rate regimes</h3>
<p>Narrow = RSP ÷ SPY fell over 63 sessions by more than its bottom fifth ({dsn['today']['narrow_threshold']*100:.1f}%); rising rates = the 10-year rose over 63 sessions by more than its top fifth ({dsn['today']['rising_threshold_bp']:.0f}bp). Today: breadth {dsn['today']['narrow63']*100:+.1f}% ({'narrow' if dsn['today']['narrow_flag'] else 'not narrow'}), 10-year {dsn['today']['y63_bp']:+.0f}bp ({'rising' if dsn['today']['rising_flag'] else 'not rising'}). Outcome = next 63 sessions, fund minus fund, in points.</p>
<div class="scroll"><table><tr><th>regime</th><th>days</th><th>Dow − S&amp;P</th><th>Nasdaq − S&amp;P</th><th>Dow − Nasdaq</th></tr>""")
for name, g in dsn["regimes"].items(): P.append(f"<tr><td>{name}</td><td>{g['days']}</td><td>{cell(g['pairs']['dia_spy_f63'],1,' pts')}</td><td>{cell(g['pairs']['qqq_spy_f63'],1,' pts')}</td><td>{cell(g['pairs']['dia_qqq_f63'],1,' pts')}</td></tr>")
P.append(f"""</table></div>
<img class="chart" src="charts/q4-3-dow-spx-ndx.png" alt="Dow vs S&amp;P vs Nasdaq" width="100%">
<p><b>In plain words:</b> across 2003 → today the Nasdaq beat the S&amp;P by a median {dsn['regimes']['all days']['pairs']['qqq_spy_f63']['median']:+.1f} points a quarter and the Dow lagged by {dsn['regimes']['all days']['pairs']['dia_spy_f63']['median']:+.1f}. In the narrow-and-rising-rates regime ({tk_days} days, a handful of spells) the Dow did better than its usual ({today_reg['dia_spy_f63']['median']:+.1f}) and the Nasdaq worse than its usual ({today_reg['qqq_spy_f63']['median']:+.1f}), which is the thesis, but both ranges include zero and the days come from three or four episodes (2005–06, 2018, 2022, now). <b>Thesis status: leaning the right way, not proven.</b></p>
<h3>4.4 · WMT and COST: defensive, or falling knives?</h3>
<div class="scroll"><table><tr><th>name</th><th>beta to SPY</th><th>on SPY days ≤ −1.5%: own median · beat SPY · up</th><th>on SPY months ≤ −3%: own median · beat SPY</th><th>today: under year high · sessions since · RSI · 63d vs SPY</th><th>fast 10% drop from year high: spells · next 63 · next 126</th></tr>""")
for s, v in st.items():
    d = v["on_spy_days_below_minus1p5"]; m = v["on_spy_months_below_minus3"]; t = v["today"]; k = v["knife"]
    P.append(f"<tr><td>{s}</td><td>{v['beta_to_spy']:.2f}</td><td>{ud(d['median_own'],2)} (SPY {d['median_spy']:+.2f}%) · {d['share_beat_spy']*100:.0f}% · {d['share_up']*100:.0f}%</td><td>{ud(m['median_own'])} (SPY {m['median_spy']:+.1f}%) · {m['share_beat_spy']*100:.0f}%</td><td>{t['drawdown_from_252d_high_pct']:+.0f}% · {t['sessions_since_252d_high']} · {t['rsi']:.0f} · {t['vs_spy_63']:+.1f} pts</td><td>{k['episodes']} · {cell(k['h']['63'])} · {cell(k['h']['126'])}</td></tr>")
P.append(f"""</table></div>
<img class="chart" src="charts/q4-4-staples.png" alt="staples" width="100%">
<p><b>In plain words:</b> on SPY's bad days WMT and COST fall about half as much and beat the index four times in five: that is what "defensive" measures, and it holds. Their own fast drops (10% off the year high within 15 sessions, {st['WMT']['knife']['episodes']} and {st['COST']['knife']['episodes']} times since 2003) were followed by above-base returns over 63 and 126 sessions, so historically their knives were caught. <b>But today is not that pattern:</b> both are 90 sessions past their high, sliding {abs(st['WMT']['today']['drawdown_from_252d_high_pct']):.0f}% and {abs(st['COST']['today']['drawdown_from_252d_high_pct']):.0f}% slowly while the index rose, which is a de-rating (a leadership rotation out of expensive staples), not a knife. The defensive test still passes; the knife test does not apply.</p>
<h3>4.5 · Leaders below the 200-day that still lead</h3>
<p>Point-in-time top-20 names by full market cap at each prior year-end (N9 cache, {ld['names_years']} name-years, 2007 → 2026). State on each day: below its own 200-day while SPY is above its 200-day; "still leading" = its 63-session return beats SPY's. Outcome = the name minus SPY over the next 63 and 126 sessions; the unit is the first day of each run per name.</p>
<div class="scroll"><table><tr><th>state</th><th>share of leader-days</th><th>spells</th><th>next 63 minus SPY</th><th>up</th><th>next 126 minus SPY</th></tr>""")
for name, g in ld["states"].items():
    if name == "all leader-days": continue
    P.append(f"<tr><td>{name}</td><td>{g['share_of_leader_days']*100:.0f}%</td><td>{g['ex63']['episodes']}</td><td>{ud(g['ex63']['median'],1,' pts')} <span class='q'>[{f(g['ex63']['lo'],1,True)}, {f(g['ex63']['hi'],1,True)}]</span></td><td>{g['ex63']['share_up']*100:.0f}%</td><td>{ud(g['ex126']['median'],1,' pts')} <span class='q'>[{f(g['ex126']['lo'],1,True)}, {f(g['ex126']['hi'],1,True)}]</span></td></tr>")
below_now = [t for t in ld["today_top20"] if t["below_200d"]]
P.append(f"""</table></div>
<img class="chart" src="charts/q4-5-leaders-below-200.png" alt="leaders below 200" width="100%">
<p><b>In plain words:</b> a leader that dipped below its 200-day while the market stayed above, but was <i>still ahead of the index over the past quarter</i>, went on to beat SPY by a median {ld['states']['leader below its 200-day, market above, still leading over 63d']['ex63']['median']:+.1f} points over the next 63 sessions (base for all leader-days {ld['base_ex63_median_all_days']:+.1f}); the same dip in a leader that had <i>already stopped leading</i> was followed by {ld['states']['leader below its 200-day, market above, no longer leading']['ex63']['median']:+.1f}. The 200-day is not the tell; the relative strength is. Today, of this year's top 20 as of 25 Sep, {', '.join(f"{t['sym']} ({t['r63_minus_spy']:+.0f} pts vs SPY over 63)" for t in below_now)} are below their 200-day, and every one of them has also stopped leading: the history says "no reason to expect them back on relative strength alone".</p>
<p class="q">Sources: chart API daily bars; N9 point-in-time cache (membership from FMP, caps from FMP month-ends, bars from Massive, built on Fly on 28 Sep); US10Y from the chart API's FMP macro series. What could be wrong: the rate cycles are three; "narrow" and "rising" thresholds are this sample's own fifths; the knife definition (10% within 15 sessions of the high) is one of many.</p>""")
# ---------------------------------------------------------------- Q5
rx = q5["vst"]["earnings"]
P.append(f"""<h2 id="q5">5 · Names: VST, ORCL, the software bucket</h2>
<h3>5.1 · VST deep dive: earnings misses against AI power deals</h3>
<div class="card"><h3>VST {vs['close']:.2f} · {vs['drawdown_from_252d_high']:+.0f}% from its year high ({vs['high_252_date']}) · {vs['dist_200d_pct']:+.0f}% vs its 200-day · RSI {vs['rsi']:.0f} ({ordn(vs['rsi_pct'])} of its own) · Geiger {vs['live_geiger']['composite']:+.2f} (trend {vs['live_geiger']['trend']:+.2f}, momentum {vs['live_geiger']['momentum']:+.2f}) · YTD {vs['ytd']:+.0f}% · one year {vs['one_year']:+.0f}%</h3>
<p><b>The reports.</b> Vistra has missed consensus EPS on {ve['misses']} of its last {ve['reports']} reports (FMP export). The misses are not operating misses: the reported figure carries the mark-to-market of its hedge book (Q4 2025 net income $944m included an $808m unrealised hedge loss), so GAAP EPS swings with forward power curves while adjusted EBITDA, the number the company guides on, has run at or above plan. Full-year 2025 ongoing adjusted EBITDA was $5,912m; 2026 guidance is $6.8bn to $7.6bn, reaffirmed in Q1 and Q2 2026 with "at or above the midpoint"; the 2027 midpoint opportunity is $7.4bn to $7.8bn. Q2 2026 (7 Aug): revenue $4.02bn (−5.5% y/y), adjusted EBITDA $1.77bn (+30% y/y), EPS $0.76 vs $1.61 expected. Q1 2026 (7 May): adjusted EBITDA $1.494bn, revenue $5.64bn (in line), EPS $2.87 vs $1.32.</p>
<p><b>The deals.</b> AWS: ~3,800 MW of nuclear (Comanche Peak 20-year PPA up to 1,200 MW plus related facilities, and the 200 MW Oak Hill solar PPA). Meta: 20-year PPAs for more than 2,600 MW across the PJM nuclear fleet. Cogentrix: ~5,500 MW of gas generation for $4.7bn, closing mid-to-late 2026. Lotus Infrastructure: 2,600 MW closed November 2025. Up to $1bn committed to the Helix data-centre platform. Management said Cogentrix and the Meta PPAs alone could add about $700m to the 2027 EBITDA midpoint, and neither is in guidance yet.</p>
<p><b>Why it fell anyway.</b> Two reasons in the reports and the coverage: ERCOT forward power curves came in "meaningfully lower" (Vistra's Texas fleet is merchant), and management guided toward the low end of the 2027 range on the call. The whole independent-power group fell together (Constellation −21% YTD, NRG −30%, Talen −21%), so this is a sector de-rating of the AI-power trade more than a Vistra story. Analysts: mean target about $225 (67% above the price) with a street high of $320; 18 buys, 1 underperform, 1 sell; Guggenheim (Pourreza) $300; fair-value estimates have drifted down (about $314 → $308) and there were six downward 2027 EPS revisions in a month.</p>
<p><b>Reaction history</b> (own bars; before-open reports move the same day): misses were followed by a median day of {ve['median_reaction_on_miss']:+.1f}%, beats {ve['median_reaction_on_beat']:+.1f}%; the surprise size correlates with the reaction at {ve['corr_surprise_reaction']:+.2f}, which is to say the headline miss is not what moves it. Last reports:</p>
<div class="scroll"><table><tr><th>date</th><th>EPS actual</th><th>estimate</th><th>surprise</th><th>day's move</th><th>next 21 sessions</th></tr>""")
for r in rx[-8:]: P.append(f"<tr><td>{r['date']} {r['report_time'] or ''}</td><td>{r['eps_actual']}</td><td>{r['eps_estimate']}</td><td>{ud(r['surprise_pct'],0)}</td><td>{ud(r['reaction_pct'])}</td><td>{ud(r['next_21_pct'])}</td></tr>")
k30 = vk["-30"]; k20 = vk["-20"]
P.append(f"""</table></div>
<p><b>Falling-knife test on its own history</b> (VST's bars start {vs['first_bar']}; first day at least 20%, 30% or 40% under its year high after having been within 5% of it in the prior 60 sessions):</p>
<div class="scroll"><table><tr><th>depth</th><th>spells (dates)</th><th>next 63 (each)</th><th>next 126 (each)</th><th>next 252 (each)</th><th>further fall within 126 (each)</th><th>base next 63 · up</th></tr>""")
for thr, g in vk.items(): P.append(f"<tr><td>{thr}%</td><td>{g['episodes']} ({', '.join(g['dates'])})</td><td>{', '.join(f'{x:+.0f}%' for x in g['h']['63']['values']) or '—'}</td><td>{', '.join(f'{x:+.0f}%' for x in g['h']['126']['values']) or '—'}</td><td>{', '.join(f'{x:+.0f}%' for x in g['h']['252']['values']) or '—'}</td><td>{', '.join(f'{x:.0f}%' for x in g['further_fall_values']) or '—'}</td><td>{g['h']['63']['base_median']:+.1f}% · {g['h']['63']['base_share_up']*100:.0f}%</td></tr>")
P.append(f"""</table></div>
<img class="chart" src="charts/q5-1-vst.png" alt="VST" width="100%">
<p><b>In plain words:</b> VST is {abs(vs['drawdown_from_252d_high']):.0f}% under a high it set {vs['sessions_since_high']} sessions ago, so it is not in the fast-knife state (it was last within 5% of its high more than 60 sessions ago: near-high-recent = {q5['vst']['near_hi_recent']}); it is a long slide with a broken 200-day and a Geiger trend of {vs['live_geiger']['trend']:+.2f}. Its own history has {k30['episodes']} spells at 30% under the high, and they were followed by {', '.join(f'{x:+.0f}%' for x in k30['h']['126']['values'])} over 126 sessions, with further falls of {', '.join(f'{x:.0f}%' for x in k30['further_fall_values'])} first. The fundamental picture (contracted nuclear and gas capacity at 20-year terms, guidance intact) and the price picture (a merchant-power de-rating) are both true at once; the price is what is falling, and the history of two or three spells cannot settle it. <b>Thesis status: the misses are accounting noise, the de-rating is real, and the entry question is a tranche question (section 4 of the pullback playbook), not a knife question.</b></p>
<h3>5.2 · ORCL's drop today</h3>
<div class="card"><h3>ORCL {orc['close']:.2f} · {orc['day_pct']:+.1f}% today ({abs(orc['x_usual']):.1f}× its usual day of ±{orc['usual_day']:.1f}%, the {ordn(q5['orcl']['today_pct_of_down_days'])} percentile of its own days) · {orc['drawdown_from_252d_high']:+.0f}% from its high of {orc['high_252_date']} · {orc['dist_200d_pct']:+.0f}% vs 200-day · RSI {orc['rsi']:.0f} · Geiger {orc['live_geiger']['composite']:+.2f}</h3>
<p><b>Why (from today's coverage):</b> Oracle invoked force majeure on the 2.45 GW Project Jupiter data centre in New Mexico over permitting, environmental and gas-pipeline delays, which put the project's debt under rating pressure; S&amp;P has Oracle at BBB− with long bond yields above 8% and CDS at records; a new round of workforce cuts; Larry Ellison raised his pledged shares by 19% to 67 million (over $9bn); and the wider AI-capex worry (Burry on hyperscaler commitments, Oracle's $664bn in the mix). The day's move was −3.3% on the chart API's finished bar (the press says −3.3% to −3.6%). Average analyst target quoted at $246.48 against $132.60.</p>
<p><b>Own history:</b> after a day of −3% or worse ORCL's next 21 sessions were a median {ud(q5['orcl']['after']['day ≤ −3%']['h']['21']['median'])} ({q5['orcl']['after']['day ≤ −3%']['episodes']} spells since 2003); when it was already below its 200-day, {ud(q5['orcl']['after']['day ≤ −3% while below its 200-day']['h']['21']['median'])}; when it was already 25% or more under its year high, {ud(q5['orcl']['after']['day ≤ −3%, already 25%+ under its year high']['h']['21']['median'])} ({q5['orcl']['after']['day ≤ −3%, already 25%+ under its year high']['episodes']} spells, mostly 2000s). Those are bounces inside a fall; the ranges are wide and the stock is {abs(orc['drawdown_from_252d_high']):.0f}% off its high for a reason that is about credit and execution, which price history does not measure.</p></div>
<img class="chart" src="charts/q5-3-orcl.png" alt="ORCL" width="100%">
<h3>5.3 · The software bucket: which fund and which cohort measures it?</h3>
<div class="scroll"><table><tr><th>name</th><th>today</th><th>YTD</th><th>one year</th><th>RSI</th><th>Geiger</th><th>closest fund (correlation)</th><th>tree cohort (24 Sep taxonomy)</th></tr>""")
for s in sw5["bucket"]:
    p_ = sw5["perf"][s]; bf = sw5["best_fund"][s]
    P.append(f"<tr><td>{s}</td><td>{ud(p_['day'])}</td><td>{ud(p_['ytd'],0)}</td><td>{ud(p_['one_year'],0)}</td><td>{p_['rsi']:.0f}</td><td>{ud(p_['geiger'],2,'') if p_['geiger'] is not None else '—'}</td><td>{bf} ({sw5['fund_corr'][s][bf]:.2f})</td><td>{', '.join(c.replace('IND:','').replace('BR:','branch ') for c in sw5['cohorts'][s])}</td></tr>")
pb = sw5["perf"]["BUCKET_EW"]
P.append(f"""<tr><td><b>bucket, equal weight</b></td><td>{ud(pb['day'])}</td><td>{ud(pb['ytd'],0)}</td><td>{ud(pb['one_year'],0) if pb['one_year'] is not None else '—'}</td><td></td><td></td><td><b>{sw5['best_fund']['BUCKET_EW']} ({sw5['fund_corr']['BUCKET_EW'][sw5['best_fund']['BUCKET_EW']]:.2f})</b>, SKYY {sw5['fund_corr']['BUCKET_EW']['SKYY']:.2f}, XLK {sw5['fund_corr']['BUCKET_EW']['XLK']:.2f}, QQQ {sw5['fund_corr']['BUCKET_EW']['QQQ']:.2f}</td><td>branch AI_SOFTWARE (all nine)</td></tr>
<tr><td>IGV</td><td>{ud(sw5['perf']['IGV']['day'])}</td><td>{ud(sw5['perf']['IGV']['ytd'],0)}</td><td>{ud(sw5['perf']['IGV']['one_year'],0)}</td><td>{sw5['perf']['IGV']['rsi']:.0f}</td><td>{ud(sw5['perf']['IGV']['geiger'],2,'')}</td><td colspan="2">iShares Expanded Tech-Software · the fund to read for this bucket</td></tr>
<tr><td>SKYY</td><td>{ud(sw5['perf']['SKYY']['day'])}</td><td>{ud(sw5['perf']['SKYY']['ytd'],0)}</td><td>{ud(sw5['perf']['SKYY']['one_year'],0)}</td><td>{sw5['perf']['SKYY']['rsi']:.0f}</td><td>{ud(sw5['perf']['SKYY']['geiger'],2,'')}</td><td colspan="2">First Trust Cloud Computing · closest for the cloud/data names</td></tr></table></div>
<img class="chart" src="charts/q5-2-software-bucket.png" alt="software bucket" width="100%">
<p><b>In plain words:</b> the fund that measures this bucket is <b>IGV</b>; SKYY is the closest fund for the cloud and data names (MDB, SNOW, SHOP, ORCL, LYFT), NFLX belongs with XLC and HOOD with QQQ. On the tree the nine share the AI_SOFTWARE branch but four industries. Their pairwise correlation is only {sw5['mean_pairwise_corr_inside']:.2f} (minimum {sw5['min_pairwise']:.2f}), so as a cohort they would fail the tree-cohorts lane's co-movement bar (0.5+): it is a <b>theme list</b> ("software that AI may eat or feed"), and the equal-weight bucket is down {abs(pb['ytd']):.0f}% this year against IGV's {sw5['perf']['IGV']['ytd']:+.0f}% and SKYY's {sw5['perf']['SKYY']['ytd']:+.0f}%. The measurement to add to the Hub is a light one: an equal-weight bucket line beside IGV on the Cohort Compare bow tie (follow-up F6).</p>
<p class="q">Sources: chart API daily bars; FMP earnings export with estimates (26–27 Sep lanes); public coverage fetched 28 Sep 23:00Z: Vistra Q4-2025 8-K exhibit (sec.gov), TIKR on Q1 2026, Yahoo/Insider Monkey on the Guggenheim call and Q2 2026, Simply Wall St fair value; ORCL: tradingkey, gurufocus, invezz (the last two gave us only headlines). What could be wrong: press figures for ORCL's move vary (−3.3% to −3.6%); analyst counts are as quoted by those sources, not from FMP; VST's own history is nine years.</p>""")
# ---------------------------------------------------------------- Q6
pats = lm["patterns"]
P.append(f"""<h2 id="q6">6 · Public work: Lo–Mamaysky–Wang rebuilt on our data, and Harvey–Liu haircuts on our rules</h2>
<p class="k">STOLEN FROM</p><p><a href="https://www.nber.org/papers/w7613">Lo, Mamaysky &amp; Wang (2000), Foundations of Technical Analysis, NBER w7613 / J. Finance 55(4)</a> · <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2345489">Harvey &amp; Liu (2015), Backtesting, J. Portfolio Management 42(1)</a> · <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2249314">Harvey, Liu &amp; Zhu (2016), … and the Cross-Section of Expected Returns, RFS</a></p>
<h3>6.1 · Lo–Mamaysky–Wang: the core, replicated</h3>
<p><b>What the paper does.</b> It makes "chart patterns" testable: smooth the price with a kernel regression (a weighted moving average whose weights fall off with distance in days), find the local highs and lows of the smoothed curve, define ten patterns as conditions on the last five of them (head-and-shoulders and its inverse, broadening tops and bottoms, triangle tops and bottoms, rectangle tops and bottoms, double tops and bottoms), then ask one question: is the distribution of returns on the days after a pattern the same as the distribution on all days? They used a {lm['windows'].split(';')[0]} window, chose the bandwidth by cross-validation and shrank it by 0.3 because the cross-validated curve was too smooth to show patterns, and tested with the Kolmogorov–Smirnov statistic. Their finding on 1962–96 US stocks: several patterns' conditional return distributions differ from the unconditional one, most clearly on Nasdaq stocks, but the differences are in shape and they do not claim the patterns are profitable.</p>
<p><b>What we did, the same way:</b> {lm['windows']}; {lm['names']} names (SPY, QQQ, IWM, DIA and the equities and sector funds in this lane's cache) since 2003; the paper's ten definitions with its 1.5% and 0.75% tolerances; the paper's test (one-day standardised return three days after completion, KS against all days, Bonferroni across the ten) and, because that is what we would trade, the next 21 sessions after completion against all days. Median cross-validated bandwidth {lm['median_cv_bandwidth']:.1f} days (× 0.3 for the fit).</p>
<div class="scroll"><table><tr><th>pattern</th><th>found</th><th>per name per year</th><th>mean one-day return after (z)</th><th>KS p (one-day, paper's test)</th><th>Bonferroni p</th><th>next 21 median · up</th><th>base next 21 · up</th><th>KS p (21-day)</th><th>SPY's latest</th></tr>""")
for p_, v in pats.items(): P.append(f"<tr><td>{p_}</td><td>{v['n']:,}</td><td>{v['per_name_per_year']:.1f}</td><td>{f(v['mean_z1'],3,True)}</td><td>{f(v['ks_p'],4)}{' ●' if v['ks_bh_pass_5pct'] else ''}</td><td>{f(v['ks_p_bonferroni'],3)}</td><td>{ud(v['f21_median'])} · {v['f21_share_up']*100:.0f}%</td><td>{f(v['base_f21_median'],1,True)}% · {v['base_f21_share_up']*100:.0f}%</td><td>{f(v['f21_ks_p'],3)}</td><td>{', '.join(v['spy_examples'][-2:])}</td></tr>")
n_sig = sum(1 for v in pats.values() if v["ks_bh_pass_5pct"])
P.append(f"""</table></div>
<img class="chart" src="charts/q6-1-lmw.png" alt="LMW patterns" width="100%">
<img class="chart" src="charts/q6-2-lmw-example.png" alt="LMW example" width="100%">
<p><b>In plain words:</b> the finder works and finds what the paper found: patterns are common (a few per name per year), and for {n_sig} of the ten the day-after return distribution differs from all days at the paper's level (● after Benjamini–Hochberg at 5%). But the difference is in the shape of the distribution, not in its middle: the mean one-day returns after every pattern are within a few hundredths of a standard deviation of zero, and the next-21-session medians sit within a point of the base with the same up-share. <b>So on our data, as in the paper, head-and-shoulders and friends carry information about volatility and skew, not about direction.</b> What is worth keeping is the machinery: a kernel-smoothed extrema finder is a clean, testable replacement for hand-drawn support, resistance and diagonals on Station (follow-up F5).</p>
<h3>6.2 · Harvey–Liu backtest haircuts on the rules published today</h3>
<p><b>What the paper does.</b> A Sharpe ratio measured on a backtest is a t-statistic in disguise (t = SR × √years). If the rule was one of M rules tried, the chance that the best of M looks this good by luck is much higher than the raw p-value says, so the p-value is adjusted (Bonferroni multiplies it by M; Holm and BHY are less severe and use the whole set of p-values) and converted back to a Sharpe. The "haircut" is the share of the Sharpe that does not survive. Their rule of thumb: with the number of tests the profession has run, a strategy needs t near 3 before it deserves belief.</p>
<p><b>What we did:</b> {hl['method']} For each rule, the Sharpe is that of "hold the instrument for the stated sessions after each signal, otherwise cash", on our bars; M is the number of cells the study tried; Holm and BHY use the study's own p-values where this lane produced them.</p>
<div class="scroll"><table><tr><th>rule</th><th>from</th><th>Sharpe</th><th>years</th><th>signals</th><th>t</th><th>p</th><th>tests M</th><th>Bonferroni: p · Sharpe left · haircut</th><th>Holm</th><th>BHY</th></tr>""")
for r in hl["rows"]:
    h = r["hl"]
    if not h: continue
    b = h["bonferroni"]; P.append(f"<tr><td>{r['rule']}</td><td>{r['source']}</td><td>{f(r['sr'],2)}</td><td>{r['years']:.0f}</td><td>{r['signals']}</td><td>{h['t']:.2f}</td><td>{f(h['p'],3)}</td><td>{h['M']}</td><td>{f(b['p_adj'],3)} · {f(b['sr_adj'],2)} · {b['haircut']*100:.0f}%</td><td>{(f(h['holm']['sr_adj'],2) + ' · ' + f(h['holm']['haircut']*100,0) + '%') if 'holm' in h else '—'}</td><td>{(f(h['bhy']['sr_adj'],2) + ' · ' + f(h['bhy']['haircut']*100,0) + '%') if 'bhy' in h else '—'}</td></tr>")
P.append(f"""</table></div>
<img class="chart" src="charts/q6-3-harvey-liu.png" alt="Harvey-Liu" width="100%">
<p><b>In plain words:</b> the two 1928-to-today trend rules (10-month, 200-day) keep about three quarters of their Sharpe after any correction, because 98 years is long and t is above 5: those are the only rules on the Hub today that Harvey–Liu would call believable. Every rule measured on the 2003-to-today window, including this lane's own cells, has t between 1 and 2.3 and loses most or all of its Sharpe once the tests tried are counted; the opposite corner keeps about 40% under Bonferroni only because it has ten signals and a high per-signal return, which is exactly the case the paper warns about; Holm and BHY leave a little to WMT's knife rule and XLU's washout, on Sharpes under 0.4. Buy-and-hold SPY over the same 23 years has a Sharpe of {f([r for r in hl['rows'] if r['rule'].startswith('buy and hold')][0]['sr'],2)} with t = {f([r for r in hl['rows'] if r['rule'].startswith('buy and hold')][0]['hl']['t'],2)}: that is the bar every timing rule has to clear, and none of the short-window rules does. <b>{hl['reading']}</b></p>
<p class="q">Sources: the studies named in each row and their data files; this lane's JSONs for its own p-values. What could be wrong: the overlay Sharpe ignores costs and cash yield; M for the ladder (400) and P5 (340) is the count of cells in those lanes' files; the 1928 index Sharpes are taken from the P5 file, not re-run here.</p>""")
# ---------------------------------------------------------------- follow-ups, not done
P.append(f"""<h2 id="followups">Follow-ups this lane proposes</h2>
<ol>
<li><b>F1 · A "breadth split" gauge on the REGIME strip:</b> the strongest-minus-weakest sector-pair percentile (section 1), with its own-history percentile and the both-tails flag. It is one number, computed from series the Hub already reads, and it is the honest version of "narrowness between sectors".</li>
<li><b>F2 · Backfill the futures' intraday rungs on Fly</b> (ESUSD, NQUSD: 3h/4h/6h/12h to 230 bars each, keyed FMP job) so the Station's futures Geigers stop being a data-length artefact; until then, show the fan-line count beside a futures Geiger.</li>
<li><b>F3 · Geiger speed as a stored series:</b> publish the composite's close-to-close change and its own percentile with the artifact (the "Geiger speed" Alan asked for), and show the intraday path chart of section 2.1 on the Hub's Geiger pop-out. It explains every "why did it move" question in one picture.</li>
<li><b>F4 · First-cut study at index level:</b> pull the S&amp;P financials sector index (FMP ^SP500-40) and credit spreads back to 1990 on Fly so the 1995, 1998 and 2001 cuts join the sample, split by credit calm vs stressed.</li>
<li><b>F5 · Kernel extrema on Station:</b> the LMW smoother + extrema finder as the source for auto-drawn support, resistance and diagonals (Alan's tranche levels), replacing hand-picked pivots; it is 60 lines and already tested here.</li>
<li><b>F6 · Theme lists beside the tree:</b> an off-Hub "theme" object (a list of tickers with an equal-weight line and a nearest fund) for buckets like the software nine that fail the co-movement bar; shown on Cohort Compare beside IGV.</li>
<li><b>F7 · A forward test log:</b> the A&amp;B (fear + spike) rule and the washout rule written as fixed protocols and logged from today, so in six months the question "did it work" has an out-of-sample answer instead of another backtest.</li>
</ol>
<h2 id="notdone">What was not done, and what could be wrong</h2>
<ul>
<li>The point-in-time universe branch has not landed on live; this lane read the N9 cache on this Mac for the leaders basket and says so where used. Q1's sector pairs and Q6's LMW run on served funds and this lane's 60-name cache, not on the point-in-time universe.</li>
<li>Cboe's 28 Sep put/call print, the daily VIX bar, US10Y and DXUSD for 28 Sep were not yet on the chart API at 23:00Z; the VIX close and high for today are Alan's numbers (the API's 30-minute bars agree on the high).</li>
<li>Alan's exact +0.55 / +0.33 / +0.41 readings were not found in a log; section 2.1 reconstructs the path the publisher would have produced at each bar close, and the three readings fall on it.</li>
<li>No analyst-estimate data from FMP was pulled for VST/ORCL (keyed, Fly only); the analyst figures are as quoted by public coverage fetched tonight, with sources listed.</li>
<li>Nothing was deployed; no database was written; no test browser was opened on Alan's screen (screenshots are headless).</li>
</ul>
<p class="q">Code: <code>research/statistics/research-3/</code> (lib.py with the Geiger port, q1…q6, build_page.py, check_geiger.py). Test: <code>tests/research-3-20260928.test.mjs</code>. Data: <code>deliverables/20260928/research-3/data/</code>. Charts: <code>deliverables/20260928/research-3/charts/</code>.</p>
</body></html>""")
open(os.path.join(OUT, "RESEARCH-3.html"), "w").write("\n".join(P)); print("written", os.path.join(OUT, "RESEARCH-3.html"), sum(len(p) for p in P), "chars")
