# GH1 scope: AI / semis / memory / power / REIT names + index, sector and theme funds (CO1's proposed cohorts, 6 Oct).
COHORTS = {
 "AI ACCELERATORS & LOGIC": "ALAB AMD ARM AVGO CBRS GFS INTC MRVL NVDA QCOM RMBS SIMO TSM",
 "MEMORY & STORAGE": "MU NTAP P SNDK STX WDC",
 "SEMICAP, MATERIALS & CHIP DESIGN": "ACMR AMAT AMKR ASML CDNS ENTG FORM KLAC LRCX ONTO SNPS TER UCTT",
 "ANALOG, RF & POWER SEMIS": "ADI MCHP MPWR NVTS NXPI ON QRVO STM SWKS TSEM TXN VSH",
 "AI NETWORKING & OPTICAL": "AAOI ANET APH AXTI CIEN COHR CRDO CSCO FN GLW LITE POET TEL UI",
 "AI SERVERS & DATACENTER KIT": "DELL SHAZ SMCI VRT",
 "NEOCLOUDS & AI MINERS": "APLD BTDR CIFR CORZ CRWV HIVE HUT IREN MARA NBIS RIOT WULF",
 "AI SOFTWARE & DATA PLATFORMS": "ADBE APP CRM DDOG FROG INTU MDB MSFT NOW NTNX ORCL PATH PLTR SNOW TWLO ZETA",
 "MAGNIFICENT 7": "AAPL AMZN GOOG GOOGL META MSFT NVDA TSLA",
 "AI POWERTRAIN": "BE CCJ CEG EOSE GEV LEU NRG OKLO SMR TLN UUUU VST",
 "INDEPENDENT POWER": "CEG NRG TLN VST",
 "GRID & ELECTRICAL EQUIPMENT": "AME EMR ETN FIX GEV HUBB NVT PWR VRT",
 "NUCLEAR & URANIUM": "CCJ LEU OKLO SMR UUUU",
 "SOLAR & RENEWABLE": "AMRC ENPH FSLR NXT RUN SEDG",
 "REGULATED UTILITIES": "AEE AEP ATO CNP D DTE DUK ED ES ETR EVRG EXC FE LNT NEE NI PCG PEG PNW PPL SO SRE WEC XEL",
 "DATACENTER PROPERTY": "DLR EQIX GDS IRM",
 "REITs (property)": "CBRE EXR O PLD PSA RHP SPG VICI VTR WELL",
 "TELECOM TOWERS": "AMT CCI SBAC",
 "INDEX FUNDS": "SPY QQQ IWM DIA RSP",
 "SECTOR FUNDS": "XLK XLF XLV XLY XLP XLE XLI XLB XLU XLRE XLC",
 "THEME FUNDS": "SMH SOXX XSD DRAM IGV SKYY AGIX MAGS URA VNQ ITA ARKX XBI IHI",
}
COHORTS = {k: v.split() for k, v in COHORTS.items()}
PRIORITY = "SPY QQQ MU NVDA AVGO GOOGL AMZN TSM AMD MSFT AAPL SNDK WDC NVTS SMH XLK".split()
ALL = PRIORITY + sorted({s for v in COHORTS.values() for s in v} - set(PRIORITY))
if __name__ == "__main__":
    print(len(ALL), ALL)
