import fs from "node:fs"; import path from "node:path"; import { createRequire } from "node:module";
const require = createRequire("/Users/alanharvey/SCINTILLA 0.5/visual-supervisor/package.json");
const { chromium } = require("playwright-core");
const HUB = "/Users/alanharvey/SCINTILLA 0.5/_worktrees/hub-switch-on-20260928", W = +(process.argv[2]||390);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const b = await chromium.launch({ headless: true });
const ctx = await b.newContext({ viewport: { width: W, height: 844 }, isMobile: W<500, hasTouch: W<500, serviceWorkers: "block" });
await ctx.addInitScript(() => { if (sessionStorage.getItem("i")) return; sessionStorage.setItem("i","1"); localStorage.setItem("hub.company.expanded","0"); localStorage.setItem("hub.company.tab","GEIGER"); });
await ctx.route("**/*", async (route) => { const req = route.request(), u = new URL(req.url());
  if (!["GET","HEAD","OPTIONS"].includes(req.method())) return route.fulfill({ status: 201, body: "[]" });
  if (u.host === "scintillahub.ai" && !u.pathname.startsWith("/api/")) { let f = path.join(HUB, decodeURIComponent(u.pathname)); if (fs.existsSync(f) && fs.statSync(f).isDirectory()) f = path.join(f, "index.html");
    if (!fs.existsSync(f)) return route.fulfill({ status: 404, body: "" }); return route.fulfill({ status: 200, headers: { "content-type": f.endsWith(".html") ? "text/html" : f.endsWith(".js") ? "text/javascript" : "application/octet-stream" }, body: fs.readFileSync(f) }); }
  return route.continue(); });
const p = await ctx.newPage(); const errs = []; p.on("pageerror", (e) => errs.push(e.message));
await p.goto("https://scintillahub.ai/"); await p.waitForSelector('.sc-board__row[data-t="MU"]', { timeout: 60000 }); await sleep(6000);
await p.evaluate(() => document.querySelector('.sc-board__row[data-t="MU"]').click()); await sleep(8000);
const st = () => p.evaluate(() => ({ comp: [...document.querySelectorAll('[data-gs="comp"]')].map((n) => n.textContent + (n.offsetParent ? "(vis)" : "(hid)")), slots: document.querySelectorAll("#coRailContent").length, gsum: document.querySelectorAll(".gsum").length, coData: S.coData && S.coData.t, focusT: S.focusT, tab: S.coTab, g: S.coData && S.coData._gsum && S.coData._gsum.composite }));
console.log("collapsed", JSON.stringify(await st()));
console.log("chip", JSON.stringify(await p.evaluate(() => { const c = document.querySelector("#cvLine .sc-cohwrap [aria-haspopup]"), w = c.parentElement, cs = getComputedStyle(c); const r = c.getBoundingClientRect(), rw = w.getBoundingClientRect();
  return { h: r.height, w: r.width, wh: rw.height, pad: cs.padding, lh: cs.lineHeight, fs: cs.fontSize, disp: cs.display, ws: cs.whiteSpace, saved: getComputedStyle(w.querySelector(".sc-cohsaved")).position, menu: getComputedStyle(w.querySelector(".sc-cohmenu")).display }; })));
await b.close(); process.exit(0);
await p.evaluate(() => document.querySelector("#cvLine .sc-cohwrap [aria-haspopup]").click()); await sleep(500);
console.log("pick", await p.evaluate(() => { const o = [...document.querySelectorAll("#cvLine .sc-cohopt")].find((x) => !x.classList.contains("on")); o.click(); return o.dataset.cohopt; })); await sleep(4000);
console.log("after cohort move", JSON.stringify(await st()));
await p.evaluate(() => document.querySelector('#cvTabs [data-tab="EVENTS"]').click()); await sleep(4000);
await p.keyboard.press("1"); await sleep(800); await p.keyboard.press("ArrowDown"); await sleep(1500); await p.keyboard.press("ArrowUp"); await sleep(1500);
console.log("after keys", JSON.stringify(await st()));
await p.evaluate(() => document.querySelector('#cvLine [data-act="coexpand"]').click()); await sleep(6000);
console.log("expanded", JSON.stringify(await st()));
await p.evaluate(() => document.querySelector('#cvTabs [data-tab="GEIGER"]').click()); await sleep(4000);
console.log("exp+click", JSON.stringify(await st()));
await p.setViewportSize({ width: W, height: 3000 }); await sleep(3000);
console.log("resized", JSON.stringify(await st()));
await p.setViewportSize({ width: W, height: 844 }); await sleep(3000);
console.log("resized back", JSON.stringify(await st()));
console.log(errs.slice(0,5)); await b.close();
