/* CP5 · the page for Alan: deliverables/20261007/comps-default/COMPS-DEFAULT.html — pictures first, plain words. The twelve names side by
   side (live now · the engine with expensive-only outliers · the same with the growth cap), one recommendation for the default, the
   outlier cases, the cap at 30 / 40 / none, Alphabet's set, "not a target", the nightly rebuild and its way back, what was not done.
   Every number is read from the engine's files and the saved reads beside this page; none is typed here.   node build-page.mjs */
import { readFileSync, writeFileSync, existsSync } from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
const HERE = path.dirname(fileURLToPath(import.meta.url)), ROOT = path.resolve(HERE, ".."), OUT = ROOT + "/COMPS-DEFAULT.html", ENG = path.resolve(ROOT, "../comps-engine/data"), SHOTS = ROOT + "/shots";
const J = (p) => JSON.parse(readFileSync(p, "utf8")), IDX = J(ENG + "/comps.json"), full = (t) => J(`${ENG}/names/${t}.json`), LIVE = J(ROOT + "/data/live-hub-at-the-close.json"), SWEEP = J(ROOT + "/data/cap-sweep.json"), GBEFORE = J(ROOT + "/data/alphabet-before.json");
const TESTS = existsSync(ROOT + "/data/tests.json") ? J(ROOT + "/data/tests.json") : null, NIGHT = existsSync(ROOT + "/data/nightly-rehearsal.json") ? J(ROOT + "/data/nightly-rehearsal.json") : null;
const esc = (s) => String(s == null ? "" : s).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));
const pct = (v, d = 0) => { if (v == null || !Number.isFinite(Number(v))) return "—"; const dd = d === 0 && Math.abs(v) < 1 ? 1 : d, txt = Math.abs(v).toFixed(dd); return (Number(txt) === 0 ? "" : v >= 0 ? "+" : "−") + txt + "%"; },   /* under 1% it keeps a decimal, and zero carries no sign */
  peg2 = (v) => (v == null ? "—" : Number(v).toFixed(2)), px = (v) => (v == null ? "—" : v >= 100 ? Math.round(v).toLocaleString("en-US") : Number(v).toFixed(2));
const W = { "000660.KS": "SK hynix", "005930.KS": "Samsung", "285A.T": "Kioxia" }, tk = (t) => W[t] || t, cls = (v) => (v == null ? "" : v >= 0 ? "up" : "dn");
const NAME = { GOOGL: "Alphabet", AMZN: "Amazon", AVGO: "Broadcom", NVDA: "Nvidia", TSM: "TSMC", VST: "Vistra", MU: "Micron", ORCL: "Oracle", DLR: "Digital Realty", EQIX: "Equinix", SNDK: "SanDisk", WDC: "Western Digital" };
const T12 = IDX.twelve, R = Object.fromEntries(T12.map((t) => [t, full(t)])), CAP = IDX.rule.growth_cap_pct, N = (t) => IDX.names[t];
const OKN = Object.entries(IDX.names).filter(([, n]) => n.ok && n.blend && n.blend.centre != null), cnt = (f) => OKN.filter(([t, n]) => f(n, t)).length;

/* ---- one sentence per name: column C against column A. The figures inside come from the files. ---- */
const w = (t, k) => Math.round((R[t].weights[k] || 0) * 100), share = (t, p) => Math.round(((R[t].peers.find((x) => x.ticker === p) || {}).weight_share || 0) * 100), disc = (t) => R[t].debt.discount.pct, bd = (t) => pct(R[t].blend.upside_before_debt_pct), wog = (t) => `${px(R[t].blend.centre_without_growth)} (${pct(R[t].blend.upside_without_growth_pct)})`, cap = (t, c) => pct(R[t].variants.caps[c].upside_pct);
const sameFwd = (t) => { const v = R[t].peers.filter((p) => p.same_business && p.priced && p.pe_fwd > 0).map((p) => p.pe_fwd).sort((a, b) => a - b); return v.length ? `${Math.round(v[0])}–${Math.round(v[v.length - 1])}` : "—"; };
/* how far the live page's own print at the close sits from the live rule run on the 6 Oct close, centre against centre */
const liveGap = T12.map((t) => [t, LIVE.names[t] && LIVE.names[t].centre ? Math.abs(LIVE.names[t].centre / N(t).variants.A.centre - 1) * 100 : null]).filter(([, g]) => g != null).sort((a, b) => a[1] - b[1]), gapMost = liveGap[liveGap.length - 1], gapRest = liveGap[liveGap.length - 2];
const fragPct = (s) => { const m = /moves\s+([+\-−]?\d+)%/.exec(String(s || "")); return m ? Math.abs(Number(m[1].replace("−", "-"))) : null; };
const WHY = {
  GOOGL: `Amazon (${share("GOOGL", "AMZN")}% of the weight) and Microsoft (${share("GOOGL", "MSFT")}%) now sit beside Meta (${share("GOOGL", "META")}%); the growth yardstick weighs most (${w("GOOGL", "peg")}%) and Alphabet grows slower than its peers (${Math.round(R.GOOGL.growth.next_to_following_pct)}% a year against ${Math.round(R.GOOGL.peg.credit.peers)}%), which alone takes the centre from ${wog("GOOGL")} down to ${px(R.GOOGL.blend.centre)}.`,
  AMZN: `The Chinese retailers and the two other clouds price it, and a ${disc("AMZN")}% debt discount comes off the centre; before the discount it reads ${bd("AMZN")}, the live figure.`,
  AVGO: `Arm is left out for being priced far above the group and Qualcomm stays although it is cheap (with Qualcomm out it would read ${pct(R.AVGO.variants.two_sided_rule.upside_pct)}); its ${Math.round(R.AVGO.growth.next_to_following_pct)}% growth is counted to ${CAP}% (at 40 it reads ${cap("AVGO", "40")}, with no cap ${cap("AVGO", "none")}).`,
  NVDA: `Hardly moves, and no cap moves it (${cap("NVDA", "30")} at 30, ${cap("NVDA", "40")} at 40, ${cap("NVDA", "none")} with none): AMD, Marvell and Intel are the only companies in its business here, each a fraction of its size and priced at ${sameFwd("NVDA")} times forward earnings against its ${Math.round(R.NVDA.forward.pe)}. It carries the line “not a target”.`,
  TSM: `The live page prices it on a set written by hand (two foundries and six of its customers). The method finds only two foundries, GlobalFoundries and Intel, so the whole chip set prices it and Intel alone carries ${share("TSM", "INTC")}% of the weight. Marked fragile and “not a target”.`,
  VST: `The same four independent power producers price it; the difference is the ${disc("VST")}% debt discount (net debt ${R.VST.debt.net_debt_ebitda}× EBITDA). Before the discount it reads ${bd("VST")}.`,
  MU: `The same six memory makers; the growth yardstick now weighs most (${w("MU", "peg")}%) and Micron's PEG of ${peg2(R.MU.peg.value)} against the group's ${peg2(R.MU.yardsticks.peg.median)} is its credit. Without the growth yardstick the centre is ${wog("MU")}.`,
  ORCL: `Microsoft and Amazon price it instead of eight names written by hand, and a ${disc("ORCL")}% debt discount comes off (before it ${bd("ORCL")}). Without the growth yardstick the centre is ${wog("ORCL")}, so it carries “not a target”.`,
  DLR: `P/FFO, the property trusts' own yardstick, carries ${w("DLR", "p_ffo")}% of the weight, and an ${disc("DLR")}% debt discount comes off; before the discount it reads ${bd("DLR")}.`,
  EQIX: `The same two landlords price it; an ${disc("EQIX")}% debt discount takes it from ${bd("EQIX")} to ${pct(R.EQIX.blend.upside_pct)}.`,
  SNDK: `The same six memory makers; the growth yardstick (${w("SNDK", "peg")}% of the weight) lifts the centre from the live ${px(N("SNDK").variants.A.centre)} to ${px(R.SNDK.blend.centre)}. Still below the price.`,
  WDC: `The same six; forward P/E and the growth yardstick carry it (${w("WDC", "pe_fwd")}% and ${w("WDC", "peg")}%), its ${Math.round(R.WDC.growth.next_to_following_pct)}% growth counted to ${CAP}%. Both screens mark it fragile; the live page itself printed ${px(LIVE.names.WDC.centre)} at the close.`,
};
const liveLine = (t) => { const l = LIVE.names[t]; return l && l.centre ? `the page at the close: ${px(l.centre)} at ${px(l.price_shown)}, ${pct(l.to_centre_pct, Math.abs(l.to_centre_pct) < 10 ? 1 : 0)}` : ""; };
const cell = (v) => (v && v.centre != null ? `<b class="${cls(v.upside_pct)}">${pct(v.upside_pct)}</b><br><small>centre ${px(v.centre)}</small>` : "—");
const rows12 = T12.map((t) => { const n = N(t), v = n.variants; return `<tr><td><b>${t}</b><br><small>${esc(NAME[t])}</small></td><td>${px(n.price)}</td><td>${cell(v.A)}<br><small>${esc(liveLine(t))}</small></td><td>${cell(v.B)}</td><td class="pick">${cell(v.C)}${n.not_a_target ? `<br><span class="tag">NOT A TARGET</span>` : ""}</td><td class="why"><small>${esc(WHY[t])}</small></td></tr>`; }).join("");

/* ---- the three readings drawn: one bar each, labelled on the bar ---- */
const LO = -50, HI = 160, SPAN = 58, X = (v) => ((Math.max(LO, Math.min(HI, v)) - LO) / (HI - LO)) * SPAN, Z = X(0);   /* the bars use the left 58% of the track: the label after the longest bar still fits inside the box */
const bar = (letter, word, v, strong) => { if (!v || v.upside_pct == null) return ""; const u = v.upside_pct, a = Math.min(Z, X(u)), b = Math.max(Z, X(u));   /* the label always starts to the right of the bar and of the zero line, where there is room */
  return `<div class="bl${strong ? " strong" : ""}"><span class="lt">${letter}</span><div class="trk"><i class="zero" style="left:${Z.toFixed(2)}%"></i><i class="b ${cls(u)}" style="left:${a.toFixed(2)}%;width:${Math.max(0.4, b - a).toFixed(2)}%"></i><em class="${cls(u)}" style="left:calc(${b.toFixed(2)}% + 5px)">${pct(u)} <small>${esc(word)} ${px(v.centre)}</small></em></div></div>`; };
const bars = T12.map((t) => { const n = N(t), v = n.variants; return `<div class="nm"><div class="nh"><b>${t}</b> <small>${esc(NAME[t])} · close ${px(n.price)}${n.not_a_target ? ` · <span class="tag">NOT A TARGET</span>` : ""}</small></div>${bar("A", "live now · centre", v.A)}${bar("B", "outliers fixed · centre", v.B)}${bar("C", `+ growth to ${CAP}% · centre`, v.C, true)}</div>`; }).join("");

/* ---- outliers ---- */
const caseRows = (t) => R[t].outlier_cases.map((c) => `<div class="case ${c.verdict === "kept" ? "kept" : "out"}"><i>${c.verdict === "kept" ? "KEPT" : c.verdict === "left out" ? "LEFT OUT" : "ONE YARDSTICK"}</i>${esc(c.words)}</div>`).join("");
const outTable = T12.map((t) => { const r = R[t], o = r.outlier_cases, list = (f) => o.filter(f).map((c) => `<span class="chip">${esc(c.name)}${c.scope && c.verdict !== "left out" && !c.would_be_cut ? ` <small>${esc(c.scope.replace(/ \(on growth counted to \d+%\)/g, ""))}</small>` : ""}</span>`).join("") || "<small>—</small>";
  return `<tr><td><b>${t}</b></td><td>${list((c) => c.verdict === "left out")}</td><td>${list((c) => c.verdict === "left out of one yardstick")}</td><td>${list((c) => c.verdict === "kept" && c.would_be_cut)}</td><td>${list((c) => c.verdict === "kept" && !c.would_be_cut)}</td></tr>`; }).join("");
const two = OKN.map(([, n]) => (n.variants.two_sided_rule && n.variants.two_sided_rule.upside_pct != null ? n.blend.upside_pct - n.variants.two_sided_rule.upside_pct : null)).filter((x) => x != null), lower = two.filter((x) => x < -0.5).length, higher = two.filter((x) => x > 0.5).length;

/* ---- the cap ---- */
const capRows = T12.map((t) => { const v = N(t).variants, c = (k) => `<td class="${cls(v.caps[k].upside_pct)}${k === String(CAP) ? " pick" : ""}">${k === String(CAP) ? "<b>" : ""}${pct(v.caps[k].upside_pct)}${k === String(CAP) ? "</b>" : ""}<br><small>${px(v.caps[k].centre)}</small></td>`, g = R[t].growth.next_to_following_pct;
  return `<tr><td><b>${t}</b><br><small>grows ${g == null ? "—" : Math.round(g) + "%"} a year · PEG ${peg2(R[t].peg.value)}</small></td>${c("none")}${c("40")}${c("30")}<td>${v.this_afternoon ? pct(v.this_afternoon.upside_pct) : "—"}</td><td><small>${pct(R[t].blend.upside_without_growth_pct)} <span class="dim">(${px(R[t].blend.centre_without_growth)})</span></small></td></tr>`; }).join("");
const sweepRows = SWEEP.caps.map((c) => `<tr><td>${c === "none" ? "no cap" : c + "%"}</td>${T12.map((t) => `<td class="${cls(SWEEP.names[t][c].upside_pct)}${c === String(CAP) ? " pick" : ""}">${pct(SWEEP.names[t][c].upside_pct)}</td>`).join("")}</tr>`).join("");
const d3040 = OKN.map(([, n]) => n.variants.caps["30"].upside_pct - n.variants.caps["40"].upside_pct), over = (c, x) => OKN.filter(([, n]) => n.variants.caps[c].upside_pct > x).length;

/* ---- Alphabet's set, and the sets the check marks fragile ---- */
const G = R.GOOGL, chips = (L, same, seated = []) => L.map((x) => `<span class="chip${same.includes(x) ? " same" : ""}">${esc(tk(x))}${seated.includes(x) ? " <small>cloud seat</small>" : ""}</span>`).join("");
const top = (obj) => Object.entries(obj).sort((a, b) => b[1] - a[1]).slice(0, 5).map(([t, s]) => `${tk(t)} ${Math.round(s * 100)}%`).join(" · "), gNow = Object.fromEntries(G.peers.filter((p) => p.weight_share).map((p) => [p.ticker, p.weight_share]));
const fragWord = (t) => { const f = (R[t].flags.find((x) => /^FRAGILE/.test(x)) || "").replace(/^FRAGILE: /, "").replace(/ \(a peer with ordinary multiples at the pivot of the field: kept\)/, ""); return f ? f.replace(/: it sits in a gap of the field$/, "") : null; };
const fragRows = T12.filter((t) => R[t].blend.fragile).map((t) => { const r = R[t], p = r.sets.pool || {}, more = (p.not_in_set || []).length, byLine = {}; for (const x of r.sets.seated) (byLine[x.line] ||= []).push(NAME[x.ticker] || tk(x.ticker));
  return `<tr><td><b>${t}</b><br><small>${esc(NAME[t])}</small></td><td><small>${esc(fragWord(t))}</small></td><td><small>${esc(p.served == null ? "—" : more ? `${p.in_set} of the ${p.served} companies that share its business are in the set; the set is full at its size` : `all ${p.served} companies the Hub serves that share its business are already in the set`)}</small></td><td><small>${r.sets.seated.length ? "<b>" + esc(Object.entries(byLine).map(([ln, who]) => `${who.join(" and ")} seated on its ${ln} line`).join("; ")) + "</b>" : "nothing: no business line of its own is without a peer"}</small></td></tr>`; }).join("");
const seatedAll = Object.entries(IDX.names).filter(([, n]) => n.ok && n.seated && n.seated.length).map(([t, n]) => `${t} ← ${n.seated.join(" + ")}`);

/* ---- not a target ---- */
const natAll = OKN.filter(([, n]) => n.not_a_target).map(([t, n]) => [t, n]);
const nat12 = T12.filter((t) => R[t].not_a_target).map((t) => `<div class="nat"><b>${t} · NOT A TARGET</b> · ${esc(R[t].not_a_target.words.replace(/^Not a target\.\s*/, ""))}</div>`).join("");
const natRows = natAll.map(([t, n]) => `<tr><td><b>${t}</b></td><td class="${cls(n.blend.upside_pct)}">${pct(n.blend.upside_pct)}</td><td><small>${esc(n.not_a_target.replace(/^Not a target\.\s*/, ""))}</small></td></tr>`).join("");

const shot = (f, capn) => (existsSync(`${SHOTS}/${f}`) ? `<figure><a href="shots/${f}"><img src="shots/${f}" alt="${esc(capn)}" loading="lazy"></a><figcaption>${esc(capn)}</figcaption></figure>` : "");
const NAVF = path.resolve(ROOT, "../../../scripts/scnav-snippet.html"), NAV = existsSync(NAVF) ? readFileSync(NAVF, "utf8") : "";   /* the BACK / CLOSE pair every Hub page carries (scripts/inject-scnav.py places the same snippet) */
const A = (t) => N(t).variants.A, B = (t) => N(t).variants.B, C = (t) => N(t).variants.C, AFT = (t) => N(t).variants.this_afternoon;
const ny = (iso) => new Date(iso).toLocaleTimeString("en-GB", { timeZone: "America/New_York", hour: "2-digit", minute: "2-digit", hour12: false });
const readAt = `${ny(LIVE.read_utc[0])}–${ny(LIVE.read_utc[1])} New York time`;

const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Comps — the default: expensive-only outliers, growth counted to ${CAP}%</title>
<style>:root{--bg:#0e0e12;--panel:#141419;--line:#2a2a33;--txt:#c8c8d0;--dim:#8a8a96;--up:#3c9a5f;--dn:#b04a4a;--flag:#b8a46a}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--txt);font:13px/1.5 ui-monospace,Menlo,monospace}main{max-width:1500px;margin:0 auto;padding:16px}h1{font-size:18px;letter-spacing:.1em;margin:8px 0 4px}h2{font-size:13px;letter-spacing:.14em;color:var(--dim);margin:30px 0 8px;border-bottom:1px solid var(--line);padding-bottom:4px}p,li{max-width:1020px}table{border-collapse:collapse;width:100%;background:var(--panel)}th{text-align:left;color:var(--dim);font-weight:500;font-size:11px;letter-spacing:.08em;padding:6px 8px;border-bottom:1px solid var(--line);vertical-align:bottom}td{padding:6px 8px;border-bottom:1px solid #1e1e26;vertical-align:top;font-size:12px}td.why{min-width:300px}td.pick,th.pick{background:#191920}small{color:var(--dim);font-size:11px}.dim{color:var(--dim)}.up{color:var(--up)}.dn{color:var(--dn)}.scroll{overflow-x:auto}.chip{display:inline-block;border:1px dashed #3a3a46;border-radius:10px;padding:0 6px;margin:1px 2px;font-size:11px;color:#9a9aa6}.chip.same{border-style:solid;border-color:#8a8a96;color:var(--txt)}figure{margin:0;background:var(--panel);border:1px solid var(--line);border-radius:6px;padding:6px}figure img{width:100%;display:block;max-height:560px;object-fit:cover;object-position:top}figcaption{color:var(--dim);font-size:11px;padding:6px 2px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.rec{border:1px solid #6e6440;border-radius:6px;background:#1a1810;color:#d2c48e;padding:10px 14px;max-width:1020px}.rec b{letter-spacing:.06em}.rec ol{margin:6px 0 0;padding-left:20px}.nat{margin:8px 0;padding:7px 10px;border:1px solid #6e6440;border-radius:6px;color:#d2c48e;background:#1a1810;max-width:1020px}.tag{display:inline-block;border:1px solid #6e6440;border-radius:4px;padding:0 5px;font-size:11px;letter-spacing:.06em;color:#d2c48e}.case{margin:4px 0;max-width:1020px}.case i{font-style:normal;color:var(--dim);letter-spacing:.06em;font-size:11px;margin-right:6px}.case.out i{color:var(--dn)}.case.kept i{color:var(--up)}
.bars{display:grid;grid-template-columns:1fr 1fr;gap:6px 26px;background:var(--panel);border:1px solid var(--line);border-radius:6px;padding:12px 14px;overflow:hidden}.nm{min-width:0}.nm{padding:4px 0 8px;border-bottom:1px solid #1e1e26}.nh{margin-bottom:3px}.bl{display:flex;align-items:center;gap:8px;height:19px}.bl .lt{width:12px;color:var(--dim);font-size:11px}.bl.strong .lt{color:var(--txt);font-weight:700}.trk{position:relative;flex:1;height:19px}.trk i{position:absolute;top:5px;height:9px;display:block}.trk i.zero{top:0;height:19px;width:1px;background:#4a4a56}.trk i.b.up{background:var(--up)}.trk i.b.dn{background:var(--dn)}.bl:not(.strong) .trk i.b{opacity:.5}.trk em{position:absolute;top:0;font-style:normal;font-size:11px;line-height:19px;white-space:nowrap}.bl.strong .trk em{font-weight:700;font-size:12px}
details{margin:10px 0}details summary{cursor:pointer;color:var(--dim);letter-spacing:.1em;font-size:11px}details.sc-pagespecs{margin-top:30px}code{color:#a8a8b4}a{color:#a8a8b4}
@media (max-width:900px){.grid{grid-template-columns:1fr 1fr}.bars{grid-template-columns:1fr}}@media (max-width:560px){.grid{grid-template-columns:1fr}main{padding:12px 16px}td,th{padding:5px 6px}.trk em small{display:none}}</style></head><body><main>
${NAV}<div data-scnav-slot style="display:flex;gap:8px;min-height:40px;margin:0 0 6px"></div>
<h1>COMPS — THE DEFAULT TO ROLL WITH</h1><p><small>7 October 2026 · every reading on the 6 October close · ${IDX.counts.ok} companies priced by the one comps engine, built at ${esc(ny(IDX.built_utc))} New York time · the live Hub read at ${esc(readAt)} · nothing on this page is live: it is a branch, for Alan's go.</small></p>
<div class="rec"><b>THE RECOMMENDATION — TAKE COLUMN C.</b><ol><li><b>Outliers: only the expensive ones.</b> A peer is left out only when it is priced far above its group. A cheap peer always stays.</li><li><b>The growth yardstick counts growth up to ${CAP}% a year</b>, for the company and for every peer alike.</li><li><b>A business with no peer of its own in the set gets its two best.</b> Alphabet's cloud now has Amazon and Microsoft beside Meta.</li><li><b>A centre that is not a target says so</b>, in one line, with the reason.</li></ol></div>

<h2>THE TWELVE NAMES, SIDE BY SIDE</h2>
<p><b>A</b> is what the Hub's COMPS tab shows today. <b>B</b> is the engine with the outlier rule fixed and no cap on growth. <b>C</b> is B with growth counted to ${CAP}%. Each bar is the distance from the 6 October close to the centre; the label on it is that distance and the centre in dollars.</p>
<div class="bars">${bars}</div>
<div class="scroll" style="margin-top:12px"><table><thead><tr><th>name</th><th>close</th><th>A · live now</th><th>B · outliers fixed, no cap</th><th class="pick">C · B + growth to ${CAP}%</th><th>C against A, in one sentence</th></tr></thead><tbody>${rows12}</tbody></table></div>
<p><small>Column A is the live rule run on the 6 October close, so the three columns are on one price; under it is what the live page itself printed when it was read at the close today (${esc(readAt)}), on today's prices. The two centres agree within ${gapRest[1].toFixed(1)}% on ${liveGap.length - 1} names and differ by ${gapMost[1].toFixed(0)}% on ${esc(NAME[gapMost[0]])}, which both mark fragile.</small></p>
<p>Against the engine as it stood this afternoon, four names move by more than three points: Broadcom ${pct(AFT("AVGO").upside_pct)} → ${pct(C("AVGO").upside_pct)}, Nvidia ${pct(AFT("NVDA").upside_pct)} → ${pct(C("NVDA").upside_pct)}, Alphabet ${pct(AFT("GOOGL").upside_pct)} → ${pct(C("GOOGL").upside_pct)} and Western Digital ${pct(AFT("WDC").upside_pct)} → ${pct(C("WDC").upside_pct)}. The other eight are within three points.</p>

<h2>PICTURES</h2><div class="grid">
${shot("live-hub-NVDA-1680.png", `LIVE NOW — the Hub itself with Nvidia's COMPS tab open at the close today: ${pct(LIVE.names.NVDA.to_centre_pct)} to a centre of ${px(LIVE.names.NVDA.centre)}, and no line saying it is not a target.`)}
${shot("hub-tab-NVDA-1680.png", "THIS BRANCH — Nvidia's COMPS tab: the NOT A TARGET line under the number, the growth yardstick's row saying it counts 30%, and the outlier cases written out (Arm left out).")}
${shot("hub-tab-AVGO-1680.png", "THIS BRANCH — Broadcom: +56%. Arm is left out for being priced far above the group; Qualcomm stays although it is cheap, with the reason.")}
${shot("hub-tab-GOOGL-1680.png", "THIS BRANCH — Alphabet: Meta 24%, Microsoft 23% and Amazon 20% of the weight; the two clouds are marked “seated on its cloud line”.")}
${shot("hub-tab-NVDA-390.png", "THIS BRANCH on a phone (390 wide) — Nvidia's tab.")}
${shot("tool-core-1680.png", "THE ALLOCATION TOOL, this branch — the card table reads the engine's cards: Nvidia and TSMC carry the NOT A TARGET tag.")}
${shot("tool-AVGO-1680.png", "THE ALLOCATION TOOL, this branch — Broadcom's ticker pressed: the same reading, the same cases.")}
${shot("tool-NVDA-390.png", "THE ALLOCATION TOOL on a phone — Nvidia.")}
${shot("page-1680.png", "This page at 1680.")}${shot("page-390.png", "This page on a phone.")}</div>

<h2>1 · OUTLIERS: ONLY THE EXPENSIVE ONES</h2>
<p>The rule Alan approved on 5 October is kept — far from the group on a log scale, and far on three or more of the five yardsticks to be left out everywhere — and is now one-sided. A peer or a single multiple is left out only when it sits far <b>above</b> the group. One that sits far below stays in and counts. Leaving a cheap peer out lifts the centre, so keeping it is the conservative choice.</p>
<p><b>Broadcom's set shows both cases:</b></p>${caseRows("AVGO")}${R.AVGO.outlier_note ? `<div class="case"><small>${esc(R.AVGO.outlier_note)}</small></div>` : ""}
<div class="scroll" style="margin-top:10px"><table><thead><tr><th>name</th><th>left out of every yardstick<br>(priced far above the group)</th><th>one multiple left out<br>of its own yardstick</th><th>cheap peer that now stays<br>(the old rule left it out)</th><th>cheap multiple that stays</th></tr></thead><tbody>${outTable}</tbody></table></div>
<p>Across all ${OKN.length} companies priced: ${IDX.counts.with_a_peer_left_out} have at least one peer or multiple left out for being dear, and ${IDX.counts.with_a_cheap_peer_spared} have a cheap peer that the two-sided rule used to leave out and that now stays. Against the two-sided rule on the same peers, the reading is lower on ${lower} names and higher on ${higher}. The ${higher} are names where the peer that stays is cheap on some yardsticks and ordinary or dear on others.</p>

<h2>2 · THE GROWTH YARDSTICK'S CAP: 30, 40 OR NONE</h2>
<p><b>Recommendation: ${CAP}.</b> It is the only one of the three that takes Broadcom out of “double the price” territory, and it keeps Micron's credit whole.</p>
<div class="scroll"><table><thead><tr><th>name</th><th>no cap</th><th>growth to 40%</th><th class="pick">growth to 30%</th><th>the engine<br>this afternoon</th><th>without the growth<br>yardstick at all</th></tr></thead><tbody>${capRows}</tbody></table></div>
<ul>
<li><b>Broadcom:</b> ${cap("AVGO", "none")} with no cap, ${cap("AVGO", "40")} at 40, <b>${cap("AVGO", "30")} at 30</b>. The step is not smooth: 35 gives ${pct(SWEEP.names.AVGO["35"].upside_pct)} and 40 gives ${pct(SWEEP.names.AVGO["40"].upside_pct)}. A cap of 40 sits right on that edge; 25 to 35 is level ground.</li>
<li><b>Micron keeps its credit under either cap:</b> ${cap("MU", "30")} at 30 and at 40, against ${cap("MU", "none")} with none. Its own growth (${Math.round(R.MU.growth.next_to_following_pct)}%) is under both caps and is counted in full; the cap only stops the peers that grow 55–60% from making growth look cheap.</li>
<li><b>Nvidia is not a growth story in this arithmetic.</b> It reads ${cap("NVDA", "30")}, ${cap("NVDA", "40")} and ${cap("NVDA", "none")}. Without the growth yardstick at all its centre is ${wog("NVDA")}. What lifts it is its peers' prices on every yardstick, so no cap can bring it down; that is why its line gives a different reason.</li>
<li><b>A slip found and fixed.</b> The engine this afternoon was set to count growth to 40%, but the moment the outlier rule left one peer out of the growth yardstick, the company was priced on its full growth again while its peers stayed capped. That is exactly what happened on Broadcom and Nvidia (Arm left out), the two names the cap was written for, and it is the main reason they read ${pct(AFT("AVGO").upside_pct)} and ${pct(AFT("NVDA").upside_pct)} this afternoon. With 40 really applied and the outlier rule fixed they read ${cap("AVGO", "40")} and ${cap("NVDA", "40")}.</li>
</ul>
<p>Across all ${OKN.length} companies: readings above double the price number ${over("none", 100)} with no cap, ${over("40", 100)} at 40 and ${over("30", 100)} at 30. Between 30 and 40, ${d3040.filter((x) => Math.abs(x) <= 1).length} names do not move, ${d3040.filter((x) => x < -1).length} read lower at 30 and ${d3040.filter((x) => x > 1).length} read higher (a lower cap makes the fast-growing peers dearer per point of growth, which lifts a steady grower). ${d3040.filter((x) => Math.abs(x) > 10).length} move by more than ten points.</p>
<details><summary>THE CAP FROM 20% TO 50%, AND NONE — THE TWELVE NAMES</summary><div class="scroll"><table><thead><tr><th>growth counted to</th>${T12.map((t) => `<th>${t}</th>`).join("")}</tr></thead><tbody>${sweepRows}</tbody></table></div></details>

<h2>3 · ALPHABET'S SET: ADVERTISING AND CLOUD</h2>
<p>Alphabet's revenue is advertising ${Math.round(G.sets.seat_lines.advertising.share_pct)}%, cloud ${Math.round(G.sets.seat_lines.cloud.share_pct)}%, other ${Math.round(G.sets.seat_lines["internet platforms"].share_pct)}%. Its set held seven advertising companies and no cloud company at all, so Meta, the only one near its size, carried it. The rule added: <b>a business that is at least a tenth of the company's revenue and has no peer of its own in the set seats its two best.</b> Cloud seats Amazon and Microsoft.</p>
<div class="scroll"><table><thead><tr><th></th><th>the peers (solid border = same business)</th><th>who carries the weight</th><th>if one peer is taken out</th><th>reading</th></tr></thead><tbody>
<tr><td>this afternoon</td><td>${chips(GBEFORE.set, GBEFORE.same_business)}</td><td><small>${esc(top(GBEFORE.weight_share))}</small></td><td><small>${esc((GBEFORE.fragile || "").replace(/^FRAGILE: /, "").replace(/ \(a peer.*$/, ""))}</small></td><td class="${cls(GBEFORE.upside_pct)}">${pct(GBEFORE.upside_pct)}<br><small>${px(GBEFORE.centre)}</small></td></tr>
<tr><td><b>now</b></td><td>${chips(G.sets.now, G.sets.same_business, G.sets.seated.map((s) => s.ticker))}</td><td><small>${esc(top(gNow))}</small></td><td><small>${esc(fragWord("GOOGL"))}</small></td><td class="${cls(G.blend.upside_pct)}"><b>${pct(G.blend.upside_pct)}</b><br><small>${px(G.blend.centre)}</small></td></tr></tbody></table></div>
<p>Advertising peers hold ${Math.round(G.sets.seat_lines.advertising.weight_share * 100)}% of the weight and cloud peers ${Math.round(G.sets.seat_lines.cloud.weight_share * 100)}%. It is still marked fragile: taking Meta out moved the centre ${fragPct(GBEFORE.fragile)}% this afternoon and moves it ${fragPct(R.GOOGL.flags.find((x) => /^FRAGILE/.test(x)))}% now.</p>
<p><b>The same rule on every set the check marks fragile.</b> It ran on all ${IDX.counts.ok} companies and changed ${seatedAll.length} sets (${esc(seatedAll.join(" · "))}). For the other fragile sets among the twelve it had nothing to do — no business line is without a peer — and, Broadcom aside, every company the Hub serves in that business is already in the set:</p>
<div class="scroll"><table><thead><tr><th>name</th><th>why the check marks it fragile</th><th>same-business companies the Hub serves</th><th>what the rule did</th></tr></thead><tbody>${fragRows}</tbody></table></div>
<p><small>A seat puts a peer in the set; how much it counts is the method's own rule, unchanged. Amazon and Microsoft count in full for Alphabet because 15 cents or more of the revenue dollar is in lines they share with it (cloud and advertising). A seated peer below that blends in at the lower, adjacent weight — UPS and FedEx on Uber's freight line, for one.</small></p>

<h2>4 · “NOT A TARGET”</h2>
<p>The line appears under the number on the Hub's tab, in the tool's click-through, and as a tag on the card table. Two reasons, each said in its own words, and only when the centre is well above the price:</p>
<ul><li><b>Growth:</b> more than half of the gap between the price and the centre comes from the growth yardstick, and the centre is at least 25% above the price. This is the rule asked for.</li>
<li><b>Size:</b> every company that shares its business is under a quarter of its size, and the centre is at least 50% above the price. I added this one, because the first rule does not catch Nvidia: its reading does not rest on growth.</li></ul>
${nat12}
<p>Broadcom does not carry the line at a cap of 30: without the growth yardstick it reads ${pct(R.AVGO.blend.upside_without_growth_pct)}, with it ${pct(R.AVGO.blend.upside_pct)}. At a cap of 40 it would. ${natAll.length} of the ${OKN.length} companies carry the line.</p>
<details><summary>ALL ${natAll.length} NAMES THAT CARRY THE LINE</summary><div class="scroll"><table><thead><tr><th>name</th><th>to the centre</th><th>the line</th></tr></thead><tbody>${natRows}</tbody></table></div></details>

<h2>5 · REBUILT AFTER EVERY CLOSE — DESIGNED, NOT INSTALLED</h2>
<p>Today the cards are a record of one close. The step is written and was rehearsed; it is not switched on. One run: wait until the close has settled; read the closes and the Hub's public tables; run the same engine; check the result; send the new files as a branch for a person to deploy. It never deploys by itself and it writes no table.</p>
<ul>${NIGHT ? `<li><b>Rehearsed</b> on the saved 6 October inputs, publishing nothing: all ${NIGHT.rehearsal.names} companies rebuilt in ${NIGHT.rehearsal.seconds} seconds; ${NIGHT.rehearsal.name_files_differing === 0 ? "every per-company file came out identical to the one on this branch" : NIGHT.rehearsal.name_files_differing + " per-company files differed from this branch"}; the check passed; nothing was committed or sent.</li>
<li><b>The settle check works</b>, run live today: ${NIGHT.settle_checks.map((c) => `${c.minutes_after_the_bell} minutes after the bell it found ${c.closed_today} of ${c.stocks} stocks settled — ${c.result.startsWith("not") ? "it built nothing" : "enough to go on"}`).join("; ")}.</li>` : ""}
<li><b>The check before anything is sent:</b> every name has a centre and weights that add to one; nobody is left out for being cheap; the cards carry exactly the engine's number; and no more than a tenth of the names may jump by more than 25% on a quiet price. No check is about a level.</li>
<li><b>When:</b> market days at 18:30 and 21:00 New York time, with a catch-up at 07:30. Each start does nothing once the night is built.</li>
<li><b>The way back:</b> stop the schedule in one minute; put last night's files back with one command; or delete an unsent night. Written before anything is installed: <a href="nightly/ROLLBACK.md">nightly/ROLLBACK.md</a>, with the design in <a href="nightly/DESIGN.md">nightly/DESIGN.md</a>.</li></ul>

<h2>WHAT COULD BE WRONG</h2>
<ul><li><b>The centre can jump.</b> It is the middle of a cloud of prices. When a rule moves a group of them across the middle, the centre steps instead of sliding — Broadcom between a cap of 35 and 40 is the clearest case. Read a centre with its range.</li>
<li><b>TSMC's ${pct(R.TSM.blend.upside_pct)} rests on two foundries that are not like it.</b> Intel carries ${share("TSM", "INTC")}% of the weight on depressed earnings. The live page, which prices TSMC on its customers by a hand-written set, reads ${pct(A("TSM").upside_pct)}. The page marks the new reading fragile and not a target.</li>
<li><b>Oracle is priced by two companies</b>, Microsoft and Amazon: ${esc(fragWord("ORCL"))}. Alphabet's cloud is ${G.sets.seat_lines.cloud.share_pct}% of its revenue, just under the 15% the method asks, so Alphabet does not join Oracle's set.</li>
<li><b>Nvidia is not fixed by anything on this page.</b> The outlier rule and the cap do what was asked; its number comes from its peer set.</li>
<li><b>The prices are the 6 October close</b> and the tables were read on 7 October. Until the nightly step runs, these numbers age.</li></ul>

<h2>WHAT WAS NOT DONE</h2>
<ul><li>Nothing was deployed and no table was written. The live Hub and the live tool are exactly as they were at 15:10 New York time; the Hub's tab still prices on the earlier rule (column A).</li>
<li>The nightly step is not installed, and its weekly part (each name's Geiger year and long-term channel) is not designed.</li>
<li>The knockout page was not re-run on the new readings; its input file was rebuilt.</li>
<li>Pictures were taken in a headless browser only: not Safari, not the iPhone.</li>
<li>Found and fixed along the way, both from the earlier round and neither live: the tool's card table was still reading this morning's cards, and the tool's comps sheet covered the whole page when it loaded.</li></ul>
${TESTS ? `<p><small>Tests — Hub: ${TESTS.hub.tests.toLocaleString("en-US")} run, ${TESTS.hub.fail} fail; ${TESTS.hub.new_failing_names.length ? "new failing: " + esc(TESTS.hub.new_failing_names.join("; ")) : `all ${TESTS.hub.fail} also fail on the live line, which run the same hour had ${TESTS.hub.on_the_live_line.fail} failing of ${TESTS.hub.on_the_live_line.tests.toLocaleString("en-US")}`}. Allocation tool: ${TESTS.tool.tests} run without the three files that are allowed to write, ${TESTS.tool.fail} fail (${esc(TESTS.tool.failing.join("; "))}); both also fail on the earlier commit, run the same hour.</small></p>` : ""}

<details class="sc-pagespecs"><summary>PAGE SPECS</summary><div>
<p>Where each number comes from: one program, the comps engine (<code>deliverables/20261007/comps-engine/tools/engine.mjs</code>), prices every company on the 6 October close from the Hub's own public tables (read 7 October) and writes one file per company. This page reads those files and the saved reads beside it (<code>data/live-hub-at-the-close.json</code>, <code>data/cap-sweep.json</code>, <code>data/alphabet-before.json</code>); nothing is typed in. Column A is the comps tab's live rule (same-business peers written by hand for eight names, the two-sided outlier rule, no cap, no debt discount) run on the same close; the line under it is the live page's own print, read in a headless browser on one page with every request that is not a read blocked (none was attempted).</p>
<p>The outlier rule in numbers: on the log of the peers' multiples, the middle is the median and the typical spread is the median absolute deviation. A multiple is left out of its yardstick when it is more than 3.5 spreads above the middle. A peer is left out of every yardstick when it is that far above on three or more of the five (trailing and forward P/E count as one; EV/EBITDA, EV/sales, P/S, PEG), or on half of those it has and at least two, or more than 2.5 spreads above on four of the five; or when taking it out alone lowers the centre by more than 10% and it is marked above. Growth and margins never count. A column with fewer than five peers judges no one.</p>
<p>The growth yardstick prices a company at its peers' PEG × its own growth × its earnings. With a cap of ${CAP}, growth above ${CAP}% a year is counted as ${CAP}, for the company and for each peer. Growth beyond the cap still adds to the yardstick's weight (up to three times), not to its price. The PEG printed for a company or a peer is always forward P/E ÷ growth; the yardstick's row says when it counts less growth.</p>
<p>Weights: the growth yardstick 2.0, forward P/E 1.5, EV/EBITDA 1.0, trailing P/E 0.6, EV/sales 0.5, P/S 0.4 (P/FFO 2.0 leads for a property trust), each × the share of peers carrying it × how well it prices the peers themselves, then cut where its price sits more than 1.5× from the other yardsticks'. The centre is the weighted middle of every peer's price on every yardstick; low and high are the weighted quarter marks; the debt discount comes off last.</p>
<p>The switches, one line each, and what is live: <code>expensiveOnly</code>, <code>pegCap</code> and <code>lineSeats</code> in <code>deliverables/20261005/comps-c6/outliers.mjs</code> and <code>deliverables/20261003/comps-c5/lines.mjs</code>. The configuration the live Hub reads carries none of them, and its answers are unchanged on all ${IDX.counts.ok} companies.</p>
</div></details>
</main></body></html>`;
writeFileSync(OUT, html); console.log("page →", OUT, html.length, "bytes");
