/* CP5 · pictures of this round's page itself at 1680 and at 390 — headless, from the file on disk, nothing fetched but its own pictures. */
import path from "node:path"; import { fileURLToPath, pathToFileURL } from "node:url"; import { createRequire } from "node:module";
const require = createRequire("/Users/alanharvey/SCINTILLA 0.5/visual-supervisor/package.json"); const { chromium } = require("playwright-core");
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."), PAGE = pathToFileURL(ROOT + "/COMPS-DEFAULT.html").href;
const browser = await chromium.launch({ headless: true });
try { for (const [w, h, file] of [[1680, 1050, "page-1680.png"], [390, 844, "page-390.png"]]) {
  const ctx = await browser.newContext({ viewport: { width: w, height: h }, deviceScaleFactor: 1 }), page = await ctx.newPage(), errors = []; page.on("pageerror", (e) => errors.push(String(e.message).slice(0, 160)));
  await page.goto(PAGE, { waitUntil: "load" }); await page.evaluate(async () => { for (const i of document.images) { i.loading = "eager"; if (!i.complete) await new Promise((ok) => { i.onload = i.onerror = ok; }); } }); await page.waitForTimeout(700);   /* the pictures load as a reader scrolls; for the whole-page picture they are loaded up front */
  const f = await page.evaluate(() => { const leaf = [...document.querySelectorAll("main *")].filter((e) => e.children.length === 0 && e.textContent.trim() && e.getClientRects().length); const nav = document.querySelector(".scnav"); const cols = new Set(); for (const e of document.querySelectorAll("main *")) { const c = getComputedStyle(e).color.match(/\d+/g).map(Number); cols.add(c.slice(0, 3).join(",")); }
    return { sideways: document.documentElement.scrollWidth > window.innerWidth + 1, scrollWidth: document.documentElement.scrollWidth, under11px: leaf.filter((e) => parseFloat(getComputedStyle(e).fontSize) < 11).map((e) => e.tagName + ":" + e.textContent.trim().slice(0, 24)).slice(0, 6), back_close: nav ? [...nav.querySelectorAll("button")].map((b) => b.innerText.trim()) : null, images: [...document.images].filter((i) => !(i.complete && i.naturalWidth > 0)).map((i) => i.getAttribute("src")), brightest: Math.max(...[...cols].map((c) => Math.max(...c.split(",").map(Number)))), height: document.documentElement.scrollHeight }; });
  await page.screenshot({ path: `${ROOT}/shots/${file}`, fullPage: false });
  if (w > 1000) { const hs = await page.evaluate(() => [...document.querySelectorAll("main h2")].map((h) => h.getBoundingClientRect().top + window.scrollY)); for (const [i, y] of hs.entries()) { await page.evaluate((yy) => window.scrollTo(0, Math.max(0, yy - 12)), y); await page.waitForTimeout(250); await page.screenshot({ path: `${ROOT}/shots/page-1680-part${i + 1}.png`, fullPage: false }); } await page.evaluate(() => window.scrollTo(0, 0)); } await page.screenshot({ path: `${ROOT}/shots/${file.replace(".png", "-whole.png")}`, fullPage: true });
  console.log(file, JSON.stringify({ ...f, errors })); await ctx.close(); } } finally { await browser.close(); }
