/* PA2 · writes PA2-ALLOCATION.html for Alan from today's data, the chain and the headless facts: pictures first, what each slider does
   in one line, today's picks after the baselines, two product calls. node report-pa2.mjs */
import { readFileSync, writeFileSync } from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
import { DIALS, heat, knockout, dedupePicks, fullChain, howMuch, book } from "./chain.mjs";
const HERE = path.dirname(fileURLToPath(import.meta.url));
const D = JSON.parse(readFileSync(path.join(HERE, "data-latest.json"), "utf8")), F = JSON.parse(readFileSync(path.join(HERE, "shots/pa2-facts.json"), "utf8"));
const esc = (s) => String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const sg = (v, d = 2) => v == null ? "—" : (v >= 0 ? "+" : "−") + Math.abs(v).toFixed(d), pc = (v) => v == null ? "—" : (v >= 0 ? "+" : "−") + Math.abs(v).toFixed(0) + "%", p1 = (v) => v == null ? "—" : v.toFixed(1) + "%", xx = (v) => v == null ? "—" : v.toFixed(1) + "×";
const px = (v) => v == null ? "—" : Math.abs(v) >= 1000 ? "$" + Math.round(v).toLocaleString("en-US") : "$" + (+v).toFixed(2);
const short = (s) => String(s).replace(/ · OUR NAMES$/, "").replace(/ - GENERAL$/, "").replace(/MANUFACTURERS/, "MFRS");
const H = heat(D.sectors, DIALS), bySec = Object.fromEntries(H.ranked.map((s) => [s.key, s]));
const kos = D.knockouts.filter((k) => !k.error).map((k) => { const c = D.cohorts.find((x) => x.id === k.cohort) || {}; return { ...k, cohortRow: c, K: knockout(k.members, DIALS) }; });
const rows = kos.flatMap((k) => k.K.members.filter((m) => m.score != null).map((m) => ({ ...m, cohort: k.cohortRow, sector_key: k.sector_key, sector: bySec[k.sector_key] || null, ko_label: k.label })));
const own = howMuch(D.sectors, DIALS), B = book(H, kos, DIALS, own.invested), picks = dedupePicks(rows.filter((r) => H.hot.includes(r.sector_key) && r.verdict === "SURVIVES")).map((r) => ({ ...r, share: B.names[r.ticker] || 0 })), FC = fullChain(rows, H.ranked, DIALS);
const reason = (p) => [`${p.sector.label} is hot #${p.sector.heat_rank}`, `in the ${short(p.ko_label)} ring it places #${p.place} of ${p.cohort.companies}`, p.comps_upside != null ? `the comps price ${px(p.comps_centre)} is ${pc(p.comps_upside)} from here` : "no comps price", p.growth != null ? `growth ${p1(p.growth)}` : null, p.margins != null ? `margins ${p1(p.margins)}` : null, p.leverage != null ? `net debt ${xx(p.leverage)} EBITDA` : null, p.target_upside != null ? `${p.target_n} firms see ${pc(p.target_upside)}` : "no target consensus", p.revision != null ? `revisions ${p.revision > 0 ? "up" : p.revision < 0 ? "down" : "flat"}` : null, `Geiger ${sg(p.geiger)}, ${sg(p.geiger_rel)} against the ring`].filter(Boolean).join(" · ");
const SLIDERS = [
  ["HOW MUCH TO OWN · What counts as the market's reading", "AVERAGE SCORE = the mean live Geiger of every served company (454 today); HOW MANY RISING = the share reading above zero, scaled −1 … +1. Baseline AVERAGE SCORE."],
  ["HOW MUCH TO OWN · A flat market means this much invested", "the anchor: the invested share when the reading is zero. Baseline 50 %."],
  ["HOW MUCH TO OWN · How hard the reading moves that number", "at 1.0× a full reading (+1.0) adds 50 points to the anchor, −1.0 takes 50 off. Baseline 1.0×."],
  ["HOW MUCH TO OWN · Cash you always keep", "the invested share never passes 100 minus this. Baseline 0 %."],
  ["WHICH SECTORS CARRY IT · How many sectors carry weight", "the top N by heat are HOT and hold the book; the bottom N are COLD. Baseline 3 (3 read today; a higher N needs the next read for its rings)."],
  ["WHICH SECTORS CARRY IT · The most any one sector may hold", "a cap on a sector's share of the book; the excess goes to the other hot sectors, what cannot be placed stays in cash and is printed. Baseline 40 %."],
  ["WHICH SECTORS CARRY IT · How far back a sector has to prove itself", "the tape leg uses the sector fund's 72-session return against SPY (one swing cycle) or the 16-session one. Baseline 72."],
  ["WHICH SECTORS CARRY IT · Our names · the sector funds · the tape · the bow tie", "the four legs of the heat: each sector's rank on each leg is averaged with these weights. Baselines 1 · 1 · 1 · 0 (the bow tie is printed on hover, ranked only above 0 — NEW as a weight)."],
  ["WHICH NAMES INSIDE THEM · Themes that run a ring in each sector", "the K soundest themes of each hot and cold sector. Baseline 3 (3 read today). NEW."],
  ["WHICH NAMES INSIDE THEM · Names held in each ring", "how many survive the ring and go to the picks. Baseline 3."],
  ["WHICH NAMES INSIDE THEM · Kick off the outliers", "a member whose comps upside sits further than this many MADs from the ring's middle sits out of the ranking (C5's rule; 0 = off). Baseline 3 MAD. NEW."],
  ["WHICH NAMES INSIDE THEM · How the book splits inside a sector", "EQUAL: rings and names split evenly; TILT TO STRENGTH: by their scores. Baseline EQUAL."],
  ["THE RING'S READINGS · The multiples against its peers", "C5's way-C comps price (the business-first peers' implied prices, outliers out) against today's price. Baseline 50."],
  ["THE RING'S READINGS · Growth", "the mean of revenue growth TTM, revenue growth next FY and EPS growth next FY. Baseline 10. NEW."],
  ["THE RING'S READINGS · Margins", "the mean of gross, operating and free-cash-flow margin. Baseline 10. NEW."],
  ["THE RING'S READINGS · Leverage", "net debt / EBITDA, lower is better (blank when EBITDA is not positive). Baseline 10. NEW."],
  ["THE RING'S READINGS · The analysts' target against the price", "the clean consensus (each firm's newest note inside 183 days, 3 firms at least) against today's price. Baseline 20. NEW."],
  ["THE RING'S READINGS · The revisions", "raised minus lowered over the firms that moved in the last 30 days. Baseline 10. NEW."],
  ["THE RING'S READINGS · The Geiger against the ring", "the name's live Geiger minus the ring's mean — oversold, but less than the others. Baseline 20. Ties on the score go to this, then to the target."],
  ["THE DISCUSSION · The sector's heat · the name's ring score", "the full chain for the five strongest and five weakest: sector heat × 1 + ring score × 2. Baselines 1 · 2."],
];
const pic = (f, cap) => `<figure><img src="shots/${f}" alt="${esc(cap)}" loading="lazy"><figcaption>${esc(cap)}</figcaption></figure>`;
const f1680 = F["1680"], f1920 = F["1920"], f390 = F["390"];
const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>PA2 · PORTFOLIO ALLOCATION · THE EQUALIZER</title><meta name="robots" content="noindex">
<style>:root{--bg:#0A0A0F;--panel:#0D0D14;--line:#1A1A2A;--line2:#252538;--ink:#C6C8DE;--ink3:#9A9AB6;--dim:#868AAA;--crk:#00D4FF;--bull:#00FFA3;--bear:#FF2D55;--mono:"SF Mono","JetBrains Mono",ui-monospace,Menlo,monospace;--sans:ui-sans-serif,-apple-system,"Helvetica Neue",sans-serif}
*{box-sizing:border-box}html,body{margin:0;background:var(--bg);color:var(--ink)}body{font:14px/1.6 var(--sans);padding:0 0 60px}.wrap{max-width:1240px;margin:0 auto;padding:0 18px}
header{display:flex;align-items:center;gap:12px;padding:12px 18px;border-bottom:1px solid var(--line);position:sticky;top:0;background:var(--bg);z-index:5}header .brand{font:700 11px var(--mono);letter-spacing:.18em;color:var(--crk);text-transform:uppercase;margin-left:150px}header .brand span{color:var(--ink3)}
h1{font:600 15px var(--mono);letter-spacing:.16em;text-transform:uppercase;color:var(--ink);margin:26px 0 6px}h2{font:600 11px var(--mono);letter-spacing:.2em;text-transform:uppercase;color:var(--ink3);margin:30px 0 10px;border-bottom:1px solid var(--line2);padding-bottom:6px}
p{max-width:900px;margin:8px 0}p.lead{font-size:16px;color:var(--ink)}figure{margin:14px 0}figure img{width:100%;border:1px solid var(--line2);border-radius:4px;display:block}figcaption{font:10px var(--mono);letter-spacing:.1em;text-transform:uppercase;color:var(--dim);margin-top:6px}
.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(max-width:800px){.two{grid-template-columns:1fr}}
table{border-collapse:collapse;width:100%;font:12px var(--mono);margin:8px 0}th{font:600 9px var(--mono);letter-spacing:.14em;text-transform:uppercase;color:var(--dim);text-align:left;padding:6px 8px;border-bottom:1px solid var(--line2)}td{padding:6px 8px;border-bottom:1px solid var(--line);vertical-align:top}td.t{font-weight:700;letter-spacing:.1em;color:var(--bull);white-space:nowrap}td.n{text-align:right;white-space:nowrap}
.up{color:var(--bull)}.dn{color:var(--bear)}.kv{display:grid;grid-template-columns:auto 1fr;gap:4px 16px;font:12px var(--mono);max-width:900px}.kv b{color:var(--ink3);font-weight:500;letter-spacing:.08em;text-transform:uppercase;white-space:nowrap}
.call{border-left:2px solid var(--crk);padding:6px 14px;margin:12px 0;max-width:900px}.call b{display:block;font:600 10px var(--mono);letter-spacing:.16em;text-transform:uppercase;color:var(--crk);margin-bottom:4px}
.num{font:300 44px/1 var(--mono);color:var(--ink)}.num small{font:600 10px var(--mono);letter-spacing:.2em;color:var(--dim);margin-left:8px}
details.sc-pagespecs{margin-top:26px;border-top:1px solid var(--line2);padding-top:8px;color:var(--ink3)}details.sc-pagespecs>summary{cursor:pointer;font:600 10px var(--mono);letter-spacing:.18em;text-transform:uppercase;color:var(--dim);padding:6px 0}details.sc-pagespecs h4{font:600 10px var(--mono);letter-spacing:.14em;text-transform:uppercase;color:var(--ink3);margin:14px 0 4px}code{font:12px var(--mono);color:var(--ink)}</style></head><body>
<header><span data-scnav-slot></span><span class="brand">SCINTILLA <span>· PA2 · PORTFOLIO ALLOCATION · THE EQUALIZER</span></span></header>
<div class="wrap">
<h1>The allocation page under your equalizer — 5 Oct 2026</h1>
<p class="lead">The page now opens on the answer: <b>${own.invested}% invested, ${100 - own.invested}% cash</b> as of ${esc(D.today)} (the Geiger read ${esc(D.sources.geiger_live.as_of.slice(11, 16))}Z), then the sector percentages — ${B.sectors.map((s) => `${s.label} ${p1(s.share)}`).join(" · ")} — the themes inside them, the ring inside each theme, and the names. Your knobs sit under the first screen; every one has its baseline marked and a RESET; moving one re-runs the page in the browser. Pie charts: sectors outside, themes inside, cash as the dark slice. How to deploy the purchases is not built — you bring that.</p>
<h2>Pictures first</h2>
${pic("pa2-now-1680.png", "the first screen at 1680 × 1050 — what it says now: the invested share, the cash, the sector percentages with their rings and names, the two-ring pie; the equalizer starts under it")}
<div class="two">${pic("pa2-equalizer-1680.png", "the equalizer, your five groups · the tick under each slider is the baseline · NEW marks a knob the new chain needed")}${pic("pa2-now-moved-1680.png", "three knobs moved (HOW MANY RISING · the sector cap at 10 % · one name held per ring): 38 % invested, 8 % held back by the cap stays in cash")}</div>
${pic("pa2-ring-1680.png", "one ring's fundamentals table (ENERGY, 25 names): growth · margins · debt/EBITDA first, then the multiples with the peers' median under each, then the target, the revisions, the Geiger; the first eight rows show, the whole ring unfolds; it scrolls sideways")}
<div class="two">${pic("pa2-heat-1680.png", "HEAT — the sector name, one bar, one number, HOT / COLD — and the THEMES chips: the name, the companies, one Geiger number")}${pic("pa2-picks-1680.png", "PICKS — one line of plain words each, the levels, the share of the book, ENTRY LEVEL · OPERATOR")}</div>
<div class="two">${pic("pa2-page-1680-full.png", `the whole page at 1680 × 1050 · ${f1680.height.toLocaleString()} px = ${f1680.screens} screens (the rings folded but the first)`)}${pic("pa2-page-1920-full.png", `the whole page at 1920 × 1080 · ${f1920.height.toLocaleString()} px = ${f1920.screens} screens`)}</div>
<div class="two">${pic("pa2-now-390.png", "the phone, 390 wide: the first screen")}${pic("pa2-ring-390.png", "the phone: a ring's table scrolls sideways")}</div>
<h2>What each slider does, one line</h2>
<table><thead><tr><th>knob</th><th>what it does</th></tr></thead><tbody>${SLIDERS.map(([k, w]) => `<tr><td style="white-space:nowrap;color:var(--ink3)">${esc(k)}</td><td>${esc(w)}</td></tr>`).join("")}</tbody></table>
<p>Your knobs from the September allocation page keep their names and groups (HOW MUCH TO OWN · WHICH SECTORS CARRY IT · WHICH NAMES INSIDE THEM); the ring's weights are the new chain's and are marked NEW. The Hub's own OPERATOR · EQUALIZER (timeframe × family weights, saved to operator_weights) shapes the Geiger itself and is not touched; this page's equalizer is kept in your browser only — nothing is written.</p>
<h2>Today's picks, under the baselines</h2>
<div class="kv"><b>invested</b><span>${own.invested}% · the market's reading ${sg(own.reading)} (the average Geiger of ${own.names_n} served names; ${own.rising} rising) · flat market 50% · speed 1× · cash kept 0%</span><b>hot</b><span>${H.ranked.filter((s) => H.hot.includes(s.key)).map((s) => `${s.label} (#${s.heat_rank}, our names ${sg(s.names)})`).join(" · ")}</span><b>cold</b><span>${H.ranked.filter((s) => H.cold.includes(s.key)).map((s) => `${s.label} (#${s.heat_rank}, ${sg(s.names)})`).join(" · ")}</span><b>the book</b><span>${B.sectors.map((s) => `${s.label} ${p1(s.share)} → ${s.cohorts.map((c) => `${short(c.label)} ${p1(c.share)}`).join(", ")}`).join(" · ")} · cash ${p1(B.cash)}</span></div>
<table><thead><tr><th>name</th><th>of the book</th><th>why, in one line</th></tr></thead><tbody>${picks.map((p) => `<tr><td class="t">${esc(p.ticker)}</td><td class="n">${p1(p.share)}</td><td>${esc(p.name)} · ${esc(reason(p))}</td></tr>`).join("")}</tbody></table>
<p>The rings today: ${kos.map((k) => `<b>${esc(short(k.label))}</b> ${k.members.length} names, holds ${esc(k.K.survivors.join(" "))}${k.K.outliers.out.length ? `, ${k.K.outliers.out.length} outlier${k.K.outliers.out.length > 1 ? "s" : ""} off (${esc(k.K.outliers.out.map((o) => o.ticker).join(" "))})` : ""}`).join(" · ")}.</p>
<p>The market discussion (the full chain, ${FC.all.length} names ran a ring): strongest ${FC.strongest.map((r) => r.ticker).join(" · ")}; weakest ${FC.weakest.map((r) => r.ticker).join(" · ")}.</p>
<h2>Two calls for you</h2>
<div class="call"><b>1 · The invested share's dial</b>Today the simplest form of your July sheet runs it: anchor 50 % + speed × the market's reading. The sheet's five conditions and the 100 / 80 / 50 / 30 / 15 policy are not rebuilt. Recommendation: keep this form for a week of readings, then decide whether the five-condition ladder replaces it as a chip row (FLAT · U · HUMP style) on the same knob.</div>
<div class="call"><b>2 · Which knobs survive</b>24 knobs is the full set your page had plus what the new chain needed. Recommendation: after you have moved them, retire the ones you never touch into PAGE SPECS as fixed baselines (my guess: the bow tie weight, the lookback, the discussion pair) so the equalizer is one screen on the phone too.</div>
<details class="sc-pagespecs"><summary>PAGE SPECS</summary>
<h4>What was built</h4><p>deliverables/20261005/pa1-allocation/index.html (the page), chain.mjs (the arithmetic, pure; the tests import it), build.mjs (the data read, 13 s, reads only, now with every ring member's fundamentals and its peers' medians), data-latest.json (${esc(D.taken)}), METHOD.md (PA1 + the PA2 section), SCHEDULE.md + jobs/allocation-data.yml (the nightly + hourly rebuild, staged, not active), shots-pa2.mjs (the headless pictures), tests/pa2-allocation-20261005.test.mjs (10 tests) and PA1's 11 kept. The ALLOCATION master tab in index.html now points at this page; the previous page stays at /allocation/ until 12 Oct 2026 and is linked from the page's PAGE SPECS.</p>
<h4>Evidence</h4><p>Headless Chromium (never a window), the branch served under the Hub's hostname, every non-GET answered locally: ${F.writes} writes, ${F.errors.length} page errors. 1680 × 1050: ${f1680.height} px (${f1680.screens} screens), no sideways scroll, smallest text ${f1680.minFont} px, ${f1680.knobs} knob controls (${f1680.sliders} sliders, ${f1680.chips} chips), ${f1680.pieArcs} pie arcs, ${f1680.heatCards} heat cards, ${f1680.ringTables} rings, ${f1680.ringCols} columns in the open ring, no developer codes in the content. A slider moved: the sector cap at 10 % → ${esc(f1680.capAt10.book.join(" · "))}, ${f1680.capAt10.unplaced} % held back into cash; one name held per ring → ${esc(f1680.held1.join(" "))}; HOW MANY RISING → ${f1680.breadth.invested} % invested; RESET → ${f1680.afterReset.invested} % and ${f1680.afterReset.picks} picks again (restores: ${f1680.resetRestores}). The open ring folds to ${f1680.ringFoldedRows} rows and unfolds to ${f1680.ringUnfoldedRows}. 1920 × 1080: ${f1920.height} px (${f1920.screens} screens). Phone 390: ${f390.height} px, no sideways scroll of the page (the tables scroll inside).</p>
<h4>Not done</h4><p>Nothing deployed; nothing written to a table; the schedule is staged, not active; the old page's other knobs (the search, the favourites, the tranches, the liquidity and earnings guards) are not wired — they belong to the deployment Alan brings. The five-condition ladder of the July sheet is not rebuilt. A higher "sectors carry weight" or "themes per sector" than 3 needs a new data read to show its rings.</p>
<h4>Where</h4><p>Branch hub/pa1-allocation-20261005 · deliverables/20261005/pa1-allocation/ · this report is built by report-pa2.mjs from the data and the facts.</p></details>
</div>
${readFileSync(path.join(HERE, "../../../scripts/scnav-snippet.html"), "utf8")}
</body></html>`;
writeFileSync(path.join(HERE, "PA2-ALLOCATION.html"), html); console.log("wrote PA2-ALLOCATION.html", html.length, "picks", picks.map((p) => p.ticker).join(" "));
