/* PA1 · writes PA1-ALLOCATION.html for Alan from data-latest.json + chain.mjs: pictures first, the method in plain words with
   characters, the picks of the day with reasons, two product calls with one recommendation each. node report.mjs */
import { readFileSync, writeFileSync } from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
import { DIALS, heat, knockout, dedupePicks, fullChain, reasonLine } from "./chain.mjs";
const HERE = path.dirname(fileURLToPath(import.meta.url)), D = JSON.parse(readFileSync(path.join(HERE, "data-latest.json"), "utf8")), TODAY_MD = readFileSync(path.join(HERE, "TODAY.md"), "utf8");
const SCNAV = readFileSync(path.resolve(HERE, "../../../scripts/scnav-snippet.html"), "utf8");   /* the BACK / CLOSE pair every Hub sub-page carries (scripts/inject-scnav.py places the same snippet) */
const esc = (s) => String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const sg = (v, d = 2) => v == null ? "—" : (v >= 0 ? "+" : "−") + Math.abs(v).toFixed(d), pc = (v) => v == null ? "—" : (v >= 0 ? "+" : "−") + Math.abs(v).toFixed(0) + "%", px = (v) => v == null ? "—" : Math.abs(v) >= 1000 ? "$" + Math.round(v).toLocaleString("en-US") : "$" + (+v).toFixed(2);
const H = heat(D.sectors, DIALS), bySec = Object.fromEntries(H.ranked.map((s) => [s.key, s]));
const kos = D.knockouts.filter((k) => !k.error).map((k) => ({ ...k, cohortRow: D.cohorts.find((x) => x.id === k.cohort) || {}, K: knockout(k.members, DIALS) }));
const rows = kos.flatMap((k) => k.K.members.filter((m) => m.score != null).map((m) => ({ ...m, cohort: k.cohortRow, sector_key: k.sector_key, sector: bySec[k.sector_key] || null, ko_label: k.label })));
const picks = dedupePicks(rows.filter((r) => H.hot.includes(r.sector_key) && r.verdict === "SURVIVES")), FC = fullChain(rows, H.ranked, DIALS);
const md = (t) => t.split(/\n{2,}/).map((p) => p.startsWith("# ") ? "" : "<p>" + esc(p).replace(/\*\*(.+?)\*\*/g, "<b>$1</b>").replace(/`(.+?)`/g, "<code>$1</code>") + "</p>").join("\n");
const pic = (src, cap) => `<figure><img src="${src}" alt="${esc(cap)}" loading="lazy"><figcaption>${esc(cap)}</figcaption></figure>`;
const hotWords = H.ranked.filter((s) => H.hot.includes(s.key)).map((s) => s.label).join(", "), coldWords = H.ranked.filter((s) => H.cold.includes(s.key)).map((s) => s.label).join(", ");
const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>SCINTILLA · PA1 · PORTFOLIO ALLOCATION · 5 OCT</title><meta name="robots" content="noindex">
<style>:root{--bg:#0A0A0F;--panel:#0D0D14;--line:#1A1A2A;--line2:#252538;--ink:#C6C8DE;--ink3:#9A9AB6;--dim:#868AAA;--crk:#00D4FF;--bull:#00FFA3;--bear:#FF2D55;--warn:#e0a24a;--mono:"SF Mono","JetBrains Mono",ui-monospace,Menlo,monospace;--sans:ui-sans-serif,-apple-system,"Helvetica Neue",sans-serif}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.6 var(--sans)}.wrap{max-width:1240px;margin:0 auto;padding:18px 20px 80px}
h1{font:700 13px var(--mono);letter-spacing:.2em;text-transform:uppercase;color:var(--crk);margin:30px 0 4px}h1 small{display:block;color:var(--dim);font-weight:400;letter-spacing:.08em;margin-top:4px}
h2{font:600 11px var(--mono);letter-spacing:.18em;text-transform:uppercase;color:var(--ink3);margin:34px 0 10px;border-bottom:1px solid var(--line2);padding-bottom:6px}
figure{margin:14px 0;background:var(--panel);border:1px solid var(--line);border-radius:4px;padding:6px}figure img{width:100%;height:auto;display:block;border-radius:2px}figcaption{font:11px var(--mono);color:var(--dim);padding:8px 4px 2px}
p{margin:8px 0;max-width:980px}b{color:var(--ink)}code{font:13px var(--mono);color:var(--ink3)}.up{color:var(--bull)}.dn{color:var(--bear)}
table{width:100%;border-collapse:collapse;font:12px var(--mono);margin:8px 0}th{font:600 9px var(--mono);letter-spacing:.1em;text-transform:uppercase;color:var(--dim);text-align:left;padding:5px 8px;border-bottom:1px solid var(--line2)}td{padding:5px 8px;border-bottom:1px solid var(--line);vertical-align:top}td.tk{font-weight:700;color:var(--ink);white-space:nowrap}
.card{background:var(--panel);border:1px solid var(--line);border-left:2px solid var(--crk);border-radius:4px;padding:12px 14px;margin:10px 0}.card h3{font:600 11px var(--mono);letter-spacing:.14em;text-transform:uppercase;margin:0 0 6px;color:var(--ink)}.rec{color:var(--warn)}
.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:800px){.two{grid-template-columns:1fr}}
.chars dt{font:600 11px var(--mono);letter-spacing:.14em;text-transform:uppercase;color:var(--crk);margin-top:12px}.chars dd{margin:2px 0 0}
</style></head><body><div class="wrap">
${SCNAV}
<h1>SCINTILLA · PA1 · PORTFOLIO ALLOCATION, REBUILT ON WHAT WE NOW HAVE<small>5 Oct 2026 · branch hub/pa1-allocation-20261005 · not deployed · the working page is <a href="index.html" style="color:var(--crk)">index.html</a> beside this report (and <a href="index.html?view=discussion" style="color:var(--crk)">?view=discussion</a>)</small></h1>
<p><b>In one paragraph.</b> Portfolio allocation now runs Alan's chain end to end on today's live data: <b>heat</b> from the sector compare (our names, three cap-weight fund families, the equal-weight bow tie, the 72-session rotation, B1's market read where sound) → <b>themes</b> inside the hot sectors (only cohorts T12 calls sound) → a <b>knockout</b> in each cohort on the C5 comps (business-first peers, outliers out, the price from the whole field), A4's cleaned analyst targets, the 30-day revision direction and the Geiger against the cohort → <b>picks</b> with one line of reasons each, the entry level left to the operator. Today, ${esc(D.today)}, the heat says <b>${esc(hotWords)}</b> are hot and <b>${esc(coldWords)}</b> cold; ${kos.length} knockouts ran over ${rows.length} names; ${picks.length} survive in the hot sectors. One page, two views, every dial with its baseline, 0 table writes.</p>

<h2>1 · what the ALLOCATION tab says today — and why it is a disaster</h2>
${pic("shots/today-allocation-1680.png", "Today's /allocation/ at 1680 × 1050, headless, 11:37 ET: 'Own 40% and keep 60% in cash' from Friday's Geiger averaged over 454 names, then a contrarian screen (FSLR, PDD, KGC, SBAC) and, 'kept for comparison', the old leaders screen (Technology 35%, Energy 35%, Healthcare 30%).")}
<div class="two">${pic("shots/today-allocation-1680-slice2.png", "A middle screen: a sector table on Friday's data, five more dials, then 'LAYER THREE — 189 names went in, 9 came out'.")}${pic("shots/today-allocation-1680-whole-1to16.png", "The whole scroll at 1:16 — 53,858 px, 51 screens, 35 headings, 52 dials, 121,264 characters of prose.")}</div>
${md(TODAY_MD)}

<h2>2 · the new page — THE CHAIN · 1680 × 1050 and 1920 × 1080</h2>
${pic("shots/pa1-chain-1680.png", "THE CHAIN at 1680 × 1050: the heat map on top (11 sectors hot → cold with the four legs and B1's verdict), the hot sectors' themes with T12's soundness, then the first knockout ring.")}
${pic("shots/pa1-chain-1920.png", "The same at 1920 × 1080.")}
${pic("shots/pa1-knockout-1680.png", "The knockout rings: every member with its comps rank (way C upside and centre), target upside, median and firms, 30-day revisions, Geiger and Geiger vs the cohort, the score and the verdict — SURVIVES · OUT · OUTLIER (◌, beyond the 3-MAD fence) · BLANK.")}
${pic("shots/pa1-picks-1680.png", "The picks: one card per survivor with the one-line reasons and the levels (price · way C low/centre/high · target low/median/high) — the entry is the operator's. Below: the dials with their baselines, then PAGE SPECS.")}

<h2>3 · the MARKET DISCUSSION view — one screen to talk from</h2>
${pic("shots/pa1-discussion-1680.png", "MARKET DISCUSSION at 1680 × 1050: the heat in one line, then the five strongest and five weakest names by the full chain, each with its reasons and the arithmetic of its score. It fits one screen at 1680 and 1920.")}
${pic("shots/pa1-discussion-1920.png", "The same at 1920 × 1080.")}

<h2>4 · the method in plain words — the characters</h2>
<dl class="chars">
<dt>The heat map</dt><dd>Eleven sectors in one strip, hottest left. Each column reads four things live: <b>our names</b> (the Hub's Geiger averaged over the sector's served companies), <b>funds</b> (the mean of three cap-weight sector funds — State Street, iShares, Vanguard — "more than just the State Street"), the <b>bow tie</b> (the equal-weight fund minus that cap-weight mean: below zero the giants carry the sector) and <b>rot 72</b> (the sector fund's 72-session return over SPY). The column's heat is its average rank on names, funds and rotation; the top three are HOT, the bottom three COLD. B1's market-wide read (every computed name at the ${esc(D.sources.b1.as_of)} close) sits under each column with its SOUND / THIN verdict and is shown, never used where THIN.</dd>
<dt>The themes</dt><dd>Inside each hot sector, the Hub's cohorts (tabs, registry, T12's candidates) with T12's soundness: eight or more names read, standard error at or under 0.10, held on each of the six closes, one industry at 60% or more. A thin theme is listed grey with why; a MIXED one (under half its companies in one sector, like BLUE CHIP or THEMATIC) is listed, never run. The three soundest run. When a sector has no sound theme today (Energy, Discretionary, Staples), its own served names run as one ring, marked FALLBACK.</dd>
<dt>The knockout ring</dt><dd>Every member of a theme steps in with four readings. <b>Comps</b>: C5's business-first peer set, the field with the outliers out, the way-C centre (every peer's implied price on every priced measure, weighted, the median of them all) — the reading is the upside from today's price. <b>Target</b>: the firms' newest cleaned note inside 183 days — the median's upside and how many firms. <b>Revisions</b>: raised minus lowered in the last 30 days. <b>Geiger</b>: the member's live Geiger against the ring's average ("oversold, but less than the others"). Each reading becomes a rank inside the ring (0 worst … 1 best) — no universal threshold anywhere — and the score is the weighted mean of the ranks the member has (comps 50 · target 20 · revisions 10 · Geiger 20; a blank is a named blank, not a zero). <b>The simple way to kick off outliers</b>: a member whose comps upside sits more than 3 MAD from the ring's median upside is a CANDIDATE FOR ELIMINATION — hollow, with its value, out of the ranking (today: MU +316%, F +1,287%, PDD, GM, QCOM, SIMO …). The top three survive.</dd>
<dt>The picks</dt><dd>The survivors of the hot sectors' rings, one card each, with the reasons in one line and the levels the operator still decides: today's price, the way-C low · centre · high, the target low · median · high. No line is drawn.</dd>
<dt>The discussion</dt><dd>Every name that stepped into a ring today (hot and cold sectors) scored by the full chain — the sector's heat rank (weight 1) and its knockout score (weight 2) — and the five strongest and five weakest named with their reasons. The discussion starts from the model, not from a blank.</dd>
<dt>The dials</dt><dd>Hot/cold sectors 3 · cohorts per sector 3 · heat weights 1/1/1 (bow tie 0) · knockout weights 50/20/10/20 · outlier fence 3 MAD · survivors 3 · chain weights 1/2. The page shows the answer under the baselines and re-runs when a dial moves; RESET brings the baselines back.</dd>
</dl>

<h2>5 · today's picks, with reasons (${esc(D.today)}, Geiger live ${esc(D.sources.geiger_live.as_of.slice(11, 16))}Z, bars to ${esc(D.sources.bars.to)})</h2>
<p>Heat, hot → cold: ${H.ranked.map((s) => `<b>${esc(s.label)}</b> ${sg(s.names)} names · ${sg(s.funds)} funds · ${sg(s.rotation, 1)} rot`).join(" · ")}.</p>
<table><thead><tr><th>pick</th><th>ring</th><th>price</th><th>comps C</th><th>target</th><th>Geiger</th><th>the line</th></tr></thead><tbody>
${picks.map((p) => `<tr><td class="tk">${esc(p.ticker)}</td><td>${esc(p.ko_label)}${p.cohort.fallback ? " (fallback)" : ""}</td><td>${px(p.price)}</td><td>${pc(p.comps_upside)} → ${px(p.comps_centre)}</td><td>${p.target_upside == null ? "—" : pc(p.target_upside) + " → " + px(p.target_median) + " (" + p.target_n + ")"}</td><td class="${p.geiger >= 0 ? "up" : "dn"}">${sg(p.geiger)}</td><td>${esc(reasonLine(p, p.cohort, p.sector))}</td></tr>`).join("")}
</tbody></table>
<div class="two"><div><h2>the five strongest by the full chain</h2><table><tbody>${FC.strongest.map((r, i) => `<tr><td>${i + 1}</td><td class="tk">${esc(r.ticker)}</td><td>${r.chain.toFixed(2)}</td><td>${esc(reasonLine(r, r.cohort, r.sector))}</td></tr>`).join("")}</tbody></table></div>
<div><h2>the five weakest by the full chain</h2><table><tbody>${FC.weakest.map((r, i) => `<tr><td>${i + 1}</td><td class="tk">${esc(r.ticker)}</td><td>${r.chain.toFixed(2)}</td><td>${esc(reasonLine(r, r.cohort, r.sector))}</td></tr>`).join("")}</tbody></table></div></div>
<p><b>Outliers kicked off today</b> (beyond 3 MAD on comps upside, out of the ranking, shown hollow): ${kos.map((k) => k.K.outliers.out.length ? `${esc(k.label)}: ${k.K.outliers.out.map((o) => esc(o.ticker) + " " + pc(o.value)).join(", ")}` : null).filter(Boolean).join(" · ") || "none"}.</p>

<h2>6 · where each number comes from, and what could be wrong</h2>
<p>Geiger: the Hub's live reading (<code>/geiger</code>) for the 590 served symbols and the 44 sector funds, ${esc(D.sources.geiger_live.as_of)}. Bars: the chart API's daily bars to ${esc(D.sources.bars.to)} (today's session is not a finished daily bar, so rotation is as of Friday's close). Comps: C5's method and code on this branch's files (segments pulled on Fly 3 Oct), one table read per ring over the union of the members' sets. Targets: <code>analyst_target_news</code> with A4's quality columns, ${D.sources.targets.rows} clean rows for ${D.sources.targets.names} names. Cohorts and soundness: T12's measured file of 3 Oct. B1: the 2 Oct close. The data file took ${D.elapsed_s} s, ${D.calls.chart_api} chart API calls and ${D.calls.tables} table reads; it is dated and the page prints every age.</p>
<p>What could be wrong: the comps upside depends on the business-first set (a set under two peers is a blank); many upsides are large because the field's centre sits far from the price for whole industries (semiconductors today) — the fence handles the extremes, the rank handles the rest, and the operator reads the centre, not the percentage. A target with few firms is a blank under three. A sector's rotation is its fund's, a cohort's is its median member's. The fallback rings (sector's own names) have no six-close test. The heat moves during the session with the live Geiger; T12 and B1 are dated. Nothing here sizes a position or sets cash: the July MODEL sheet's heat → condition → % invested stays step 1 and was not re-invented.</p>
<p>What was not done: the ALLOCATION master tab still points at <code>/allocation/</code> — index.html is untouched on this branch (nothing changes on the Hub without Alan's approval). No table was written. The page reads a dated data file built from this Mac; a scheduled rebuild (a Fly job or an edge function) is not set up.</p>

<h2>7 · two product calls for Alan</h2>
<div class="card"><h3>1 · what the ALLOCATION tab opens</h3><p>Today it opens the 51-screen page. Options: (a) point the master tab at this page (THE CHAIN), with MARKET DISCUSSION as its second view; (b) keep the old page one click away under the dials for a week; (c) leave the tab as is. <span class="rec">Recommendation: (a) — point the tab here; the old page's one useful step (heat → % invested, the July MODEL) comes back as this page's first dial once you have talked it through, not as 50 screens.</span></p></div>
<div class="card"><h3>2 · a sector with no sound theme</h3><p>Energy is the hottest sector today and has no T12-sound cohort (OIL MAJORS EP fails by a hair: standard error 0.107). The page ran the sector's own 25 served names as a ring marked FALLBACK. Options: (a) keep the fallback, marked, as it is; (b) never run a knockout where no theme is sound and show the sector empty; (c) build the missing Energy theme (OIL MAJORS EP + the integrateds) as a proper cohort so it passes. <span class="rec">Recommendation: (a) now, (c) as the next cohort to settle in the tree — a hot sector with an empty ring would start the discussion from a blank, which is the thing this page is for.</span></p></div>
</div></body></html>`;
writeFileSync(path.join(HERE, "PA1-ALLOCATION.html"), html);
console.log(JSON.stringify({ hot: H.hot, cold: H.cold, picks: picks.map((p) => p.ticker), strongest: FC.strongest.map((r) => r.ticker), weakest: FC.weakest.map((r) => r.ticker), outliers: kos.map((k) => [k.label, k.K.outliers.out.map((o) => o.ticker)]) }));
