/* U2 (2 Oct 2026) · the served set decided by its parents — the page. Reads measure.json and served-set.json (written by
   build.mjs) and writes SERVED-SET.html: pictures first, plain words, the tables, the rule, the decisions.
   Usage: node deliverables/20261002/served-set/page.mjs   (from the Hub root, after build.mjs) */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const DIR = dirname(fileURLToPath(import.meta.url));
const M = JSON.parse(readFileSync(join(DIR, "measure.json"), "utf8"));
const S = JSON.parse(readFileSync(join(DIR, "served-set.json"), "utf8"));
const esc = (s) => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const g = (x) => (x == null ? '<span class="mute">—</span>' : `<span class="${x > 0 ? "up" : x < 0 ? "dn" : ""}">${x > 0 ? "+" : ""}${x.toFixed(2)}</span>`);
const nN = (x) => (typeof x === "number" ? String(x) : `<span class="dim">${esc(x)}</span>`);
const pct = (x) => (x == null ? "—" : x.toFixed(1) + "%");
const measured = M.parents.filter((p) => p.holdings_on_file);
const unmeasured = M.parents.filter((p) => !p.holdings_on_file);
const R = S.recommended, C = S.counts, T = M.today_strong;
const shots = ["desktop-1680.png", "phone-390.png"].filter((f) => existsSync(join(DIR, "shots", f)));

/* ── the picture: per parent, strong-N (weight-blended, tolerance 0.05) against the names served today ── */
function barChart() {
  const rows = measured.slice().sort((a, b) => (a.role === b.role ? 0 : a.role === "broad" ? -1 : a.role === "sector" ? (b.role === "broad" ? 1 : -1) : 1));
  const W = 1180, left = 150, right = 230, rowH = 17, top = 46, H = top + rows.length * rowH + 30, cap = 100;
  const x = (v) => left + (Math.min(v, cap) / cap) * (W - left - right);
  let s = `<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg" font-family="SF Mono,JetBrains Mono,ui-monospace,Menlo,monospace" font-size="11">`;
  s += `<rect width="${W}" height="${H}" fill="#141414"/>`;
  for (const v of [0, 20, 40, 60, 80, 100]) s += `<line x1="${x(v)}" y1="${top - 8}" x2="${x(v)}" y2="${H - 24}" stroke="#2a2a2a"/><text x="${x(v)}" y="${top - 14}" fill="#8c8c8c" text-anchor="middle">${v}${v === 100 ? "+" : ""}</text>`;
  s += `<text x="${left}" y="16" fill="#cfcfcf" font-weight="600" letter-spacing="2">NAMES PER PARENT — served today (grey) against the strong-N it needs (light, weight-blended, tolerance 0.05)</text>`;
  rows.forEach((p, i) => {
    const y = top + i * rowH;
    const n = typeof p.strong.w === "number" ? p.strong.w : cap, over = typeof p.strong.w !== "number";
    s += `<text x="${left - 8}" y="${y + 12}" fill="#cfcfcf" text-anchor="end">${esc(p.ticker)}</text>`;
    s += `<text x="${left - 62}" y="${y + 12}" fill="#6c6c6c" text-anchor="end" font-size="9" letter-spacing="1">${esc(p.role.toUpperCase())}</text>`;
    s += `<rect x="${left}" y="${y + 2}" width="${Math.max(0, x(p.served.count) - left)}" height="6" fill="#5a5a5a"/>`;
    s += `<rect x="${left}" y="${y + 9}" width="${Math.max(0, x(n) - left)}" height="6" fill="${over ? "none" : "#c4c7cb"}" stroke="${over ? "#c4c7cb" : "none"}" stroke-dasharray="${over ? "3 2" : "0"}"/>`;
    s += `<text x="${x(Math.max(n, p.served.count)) + 6}" y="${y + 12}" fill="#acacac" font-size="10">${p.served.count} today · needs ${over ? "100+ (spread out)" : n}</text>`;
  });
  s += `<text x="${left}" y="${H - 8}" fill="#8c8c8c" font-size="10">A dashed open bar = the ladder (5…100 names) cannot reproduce this parent: it is spread out the way IWM is. Broad funds first, then sectors, then industries.</text>`;
  return s + "</svg>";
}

/* ── the second picture: the size of the Hub under the rule, by tolerance, with and without the cap ── */
function sizeChart() {
  const tols = ["0.05", "0.075", "0.1", "0.15"];
  const W = 1180, H = 250, left = 90, bottom = 40, top = 40, max = 1100;
  const bw = 48, group = (W - left - 40) / tols.length;
  const y = (v) => H - bottom - (v / max) * (H - bottom - top);
  let s = `<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg" font-family="SF Mono,JetBrains Mono,ui-monospace,Menlo,monospace" font-size="11"><rect width="${W}" height="${H}" fill="#141414"/>`;
  s += `<text x="${left}" y="16" fill="#cfcfcf" font-weight="600" letter-spacing="2">HOW BIG THE HUB WOULD BE — lines served, by tolerance: no cap (light) · cap 30 (grey) · today (dashed line)</text>`;
  for (const v of [0, 250, 500, 750, 1000]) s += `<line x1="${left}" y1="${y(v)}" x2="${W - 30}" y2="${y(v)}" stroke="#2a2a2a"/><text x="${left - 8}" y="${y(v) + 4}" fill="#8c8c8c" text-anchor="end">${v}</text>`;
  s += `<line x1="${left}" y1="${y(C.served_now)}" x2="${W - 30}" y2="${y(C.served_now)}" stroke="#c4c7cb" stroke-dasharray="4 3"/><text x="${W - 34}" y="${y(C.served_now) - 4}" fill="#c4c7cb" text-anchor="end">today ${C.served_now}</text>`;
  tols.forEach((t, i) => {
    const sv = S.sensitivity[t], x0 = left + i * group + group / 2;
    const a = sv.no_cap.w.proposed, b = sv.cap_30.w.proposed;
    s += `<rect x="${x0 - bw - 4}" y="${y(a)}" width="${bw}" height="${H - bottom - y(a)}" fill="#c4c7cb"/><text x="${x0 - 4 - bw / 2}" y="${y(a) - 5}" fill="#cfcfcf" text-anchor="middle">${a}</text>`;
    s += `<rect x="${x0 + 4}" y="${y(b)}" width="${bw}" height="${H - bottom - y(b)}" fill="#5a5a5a"/><text x="${x0 + 4 + bw / 2}" y="${y(b) - 5}" fill="#cfcfcf" text-anchor="middle">${b}</text>`;
    s += `<text x="${x0}" y="${H - 14}" fill="#acacac" text-anchor="middle">tolerance ±${t}${t === "0.1" ? " (recommended, with the cap)" : ""}</text>`;
  });
  return s + "</svg>";
}

const parentRows = measured.map((p) => `<tr${p.ticker === "IWM" ? ' class="me"' : ""}><td class="k">${esc(p.ticker)}</td><td>${esc(p.role)}</td><td>${esc(p.heading_label)}</td><td class="r">${p.count_in_fund}</td><td class="r">${p.readable}</td><td class="r">${p.served.count}</td><td class="r">${pct(p.served.share_of_fund_pct)}</td><td class="r">${g(p.own.seven)}</td><td class="r">${g(p.full.w)}</td><td class="r">${g(p.served.w)}</td><td class="r">${g(p.gap_today.served_vs_full_w)}</td><td class="r">${p.served_today_draws.w}/${p.served_today_draws.of}</td><td class="r">${nN(p.strong.w)}</td><td class="r">${nN(p.strong.eq)}</td><td class="r">${nN(p.strong_by_tolerance["0.1"].w)}</td><td class="r">${p.spread.sd == null ? "—" : p.spread.sd.toFixed(2)}</td></tr>`).join("");
const headingRows = M.headings.map((h) => `<tr><td class="k">${esc(h.label)}</td><td>${esc(h.sector_fund)}</td><td class="r">${h.served_names}</td><td class="r">${h.served_holdings_of_fund ?? "—"}</td><td class="r">${pct(h.served_share_of_fund_pct)}</td><td class="r">${g(h.served_eq)}</td><td class="r">${g(h.fund_full_eq)}</td><td class="r">${g(h.gap_served_names_vs_fund_full_eq)}</td><td class="r">${g(h.fund_own_seven)}</td><td class="r">${nN(h.strong_w)}</td></tr>`).join("");
const iwm = M.iwm;
const iwmBoth = iwm.both_homes.slice(0, 40).map((x) => `<tr><td class="k">${esc(x.ticker)}</td><td class="r">${x.weight_pct.toFixed(2)}%</td><td>${x.homes.join(" · ")}</td></tr>`).join("");
const iwmOnly = iwm.iwm_only.slice(0, 25).map((x) => `<tr><td class="k">${esc(x.ticker)}</td><td class="r">${x.weight_pct.toFixed(2)}%</td></tr>`).join("");
const outRows = (rows) => rows.map((r) => `<tr><td class="k">${esc(r.ticker)}</td><td>${esc(r.name || "")}</td><td>${r.best_rank ? `${esc(r.best_rank.fund)} #${r.best_rank.rank} (${r.best_rank.weight_pct}%)` : "—"}</td><td>${r.parents.slice(0, 6).map((p) => esc(p.fund)).join(" · ")}${r.parents.length > 6 ? " …" : ""}</td><td class="r">${g(r.seven)}</td><td>${esc(r.seven_session || "no reading")}${r.seven_rungs != null ? " · " + r.seven_rungs + " rungs" : ""}</td><td class="r">${g(r.hub)}</td></tr>`).join("");
const inRows = (rows) => rows.map((r) => `<tr><td class="k">${esc(r.ticker)}</td><td>${r.needed_by.slice(0, 4).map((p) => `${esc(p.parent)} #${p.rank} (${p.weight_pct.toFixed(2)}%)`).join(" · ")}${r.needed_by.length > 4 ? " …" : ""}${r.lists.length ? ' <span class="tag on">' + r.lists.join(" · ") + "</span>" : ""}${r.cohort.length ? ' <span class="tag">' + esc(r.cohort.join(" · ")) + "</span>" : ""}</td><td class="r">${g(r.seven)}</td><td>${esc(r.seven_session || "no reading on file")}${r.seven_rungs != null ? " · " + r.seven_rungs + " rungs" : ""}</td></tr>`).join("");
const underRows = M.under_served.map((u) => `<tr><td class="k">${esc(u.ticker)}</td><td>${esc(u.role)}</td><td class="r">${u.strong_w}</td><td class="r">${u.missing.length}</td><td>${u.missing.slice(0, 12).map(([t, w]) => `${esc(t)} (${w}%)`).join(" · ")}${u.missing.length > 12 ? " …" : ""}</td></tr>`).join("");
const sensRows = Object.entries(S.sensitivity).map(([t, v]) => `<tr${t === "0.1" ? ' class="kept"' : ""}><td class="k">±${t}</td><td class="r">${v.no_cap.w.proposed}</td><td class="r">${v.no_cap.w.out}</td><td class="r">${v.no_cap.w.in}</td><td class="r">${v.no_cap.w.spread_out.length}</td><td class="r">${v.cap_30.w.proposed}</td><td class="r">${v.cap_30.w.out}</td><td class="r">${v.cap_30.w.in}</td><td class="r">${v.cap_30.w.spread_out.length}</td><td class="r">${v.no_cap.eq.proposed}</td><td class="r">${v.cap_30.eq.proposed}</td></tr>`).join("");

const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Served Set</title><meta name="description" content="U2 · the served set decided by its parents: how many names each fund and sector needs on the Hub for a strong aggregate, the IWM rule, what could move off-Hub — analysis and proposal, 2 Oct 2026."><style>
:root{color-scheme:dark;--bg:#0e0e0e;--panel:#141414;--line:#2a2a2a;--line2:#383838;--ink:#cfcfcf;--ink2:#acacac;--dim:#8c8c8c;--mute:#6c6c6c;--up:#4fae6a;--dn:#d0554a;--mono:"SF Mono","JetBrains Mono",ui-monospace,Menlo,Consolas,monospace}
*{box-sizing:border-box;min-width:0}html,body{margin:0;background:var(--bg);color:var(--ink2)}
body{font-family:var(--mono);font-size:13px;line-height:1.6;letter-spacing:.02em;-webkit-font-smoothing:antialiased}
.wrap{max-width:1240px;margin:0 auto;padding:0 20px 90px;overflow-x:hidden}
.top{padding:18px 0 12px;border-bottom:1px solid var(--line);display:flex;gap:14px;align-items:center;flex-wrap:wrap}
.brand{font:400 12px/1.4 var(--mono);letter-spacing:.2em;color:var(--dim)}.brand b{color:var(--ink);font-weight:600}
.stamp{margin-left:auto;font:400 11px/1.5 var(--mono);color:var(--dim);letter-spacing:.06em;text-align:right}
.proposed{display:inline-block;border:1px solid var(--line2);padding:1px 8px;font-size:10px;letter-spacing:.2em;color:var(--ink);margin-left:8px;vertical-align:middle}
h1{font:600 15px/1.4 var(--mono);letter-spacing:.24em;color:var(--ink);margin:26px 0 6px;text-transform:uppercase}
h2{font:600 12px/1.4 var(--mono);letter-spacing:.22em;color:var(--ink);margin:36px 0 8px;text-transform:uppercase;border-bottom:1px solid var(--line);padding-bottom:6px}
h2 small{font-weight:400;letter-spacing:.06em;color:var(--dim);text-transform:none;margin-left:10px;font-size:12px}
.panel{border:1px solid var(--line);background:var(--panel);margin:10px 0}
.words{padding:12px 16px 14px;font-size:12.5px;line-height:1.7}.words b{color:var(--ink);font-weight:600}
.words ul,.words ol{margin:4px 0 8px;padding-left:22px}.words li{margin:5px 0}.words li::marker{color:var(--mute)}
.words q{quotes:"\\201C" "\\201D";color:var(--ink)}.up{color:var(--up)}.dn{color:var(--dn)}.dim{color:var(--dim)}.mute{color:var(--mute)}code{font-size:12px;color:var(--ink)}
.lead{font-size:13.5px;color:var(--ink);max-width:1000px}
.tiles{display:flex;gap:10px;flex-wrap:wrap;margin:10px 0}.tile{border:1px solid var(--line);background:var(--panel);padding:8px 14px;min-width:120px}
.tile b{display:block;font-size:22px;color:var(--ink);font-variant-numeric:tabular-nums;font-weight:600}.tile span{font-size:10px;color:var(--dim);letter-spacing:.12em;text-transform:uppercase}
table.t{width:100%;border-collapse:collapse;font-size:12px;font-variant-numeric:tabular-nums}
table.t th,table.t td{padding:5px 10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}
table.t th{font:400 10px/1.4 var(--mono);letter-spacing:.14em;color:var(--mute);text-transform:uppercase;white-space:nowrap}
table.t td{color:var(--ink2)}table.t td.k,table.t th.k{color:var(--ink)}table.t td.r,table.t th.r{text-align:right;white-space:nowrap}
table.t tr.kept td{background:#181818;color:var(--ink)}table.t tr.me td{color:var(--ink);background:#1a1a1a}
.tw{overflow-x:auto;padding:0 16px 10px}
.tag{display:inline-block;border:1px solid var(--line2);padding:0 6px;font-size:10px;letter-spacing:.12em;color:var(--ink2);margin-right:4px;white-space:nowrap}.tag.on{color:var(--ink);border-color:var(--ink2)}
.svgwrap{padding:12px 16px}.svgwrap svg{width:100%;height:auto;display:block}
.dec{border:1px solid var(--line2);background:var(--panel);margin:8px 0;padding:10px 14px}.dec b{color:var(--ink)}
.shot{padding:12px 16px 14px}.shot img{display:block;width:100%;height:auto;border:1px solid var(--line2)}.shot .clip{max-height:900px;overflow:hidden;border:1px solid var(--line2)}.shot .clip img{border:0}.shot .clip.phone{width:390px;max-width:100%}.shot small{display:block;margin-top:6px;font-size:11px;color:var(--dim)}
.two{display:grid;grid-template-columns:1fr 1fr;gap:0}.two > div + div{border-left:1px solid var(--line)}
.toc{columns:2;column-gap:30px;font-size:12px;padding:10px 16px}.toc a{color:var(--ink2);text-decoration:none;display:block;padding:2px 0}.toc a:hover{color:var(--ink)}
a{color:var(--ink)}
@media(max-width:760px){.wrap{padding:0 12px 60px}.two{grid-template-columns:1fr}.two > div + div{border-left:0;border-top:1px solid var(--line)}.stamp{margin-left:0;text-align:left}.toc{columns:1}.tile b{font-size:18px}}
</style></head><body><div class="wrap">
<div class="top"><div data-scnav-slot></div><div class="brand"><b>SCINTILLA</b> · THE SERVED SET, DECIDED BY ITS PARENTS <span class="proposed">PROPOSED · 2 OCT 2026</span></div><div class="stamp">U2 · 2 Oct 2026 · branch hub/u2-served-set-20261002<br>readings: seven-rung close of 1 Oct · holdings: FMP 26 Sep · lists read 2 Oct</div></div>

<h1>How many names each fund and sector needs on the Hub, what could move off-Hub, and the IWM rule</h1>
<div class="panel"><div class="words lead">Alan, 2 Oct: <q>I feel I over-added companies to the Hub that could be off-Hub. We should go through this at a parent level — ETF level, sector level — tracking enough tickers for each parent that the aggregate is statistically strong enough; weight matters where it makes sense. IWM is so spread out — I would put the IWM names that belong to other areas where they coincide. That's the rule.</q><br><br>
<b>The short answer.</b> Measured the brief's way (every parent's bar within ±0.05 of the bar ALL its holdings would give), the Hub is not over-served — it is <b>under-served</b>: the equal-weighted industry funds (banks KBE, biotech IBB, retail XRT, pharma XPH, low-vol SPLV, drillers XOP, builders XHB) cannot be pinned by any small top-N, and they alone would ask for about 400 more names. Only <b>${C.out} names</b> on the Hub today are needed by no parent, no list and no cohort. Today's served names already give <b>${T.within_tol_on_close_w} of ${T.of}</b> measured parents a bar within ±0.05 of the full one on the close, because the served names are the heavy ones.<br><br>
<b>The proposal</b> is the rule in section 5 with a tolerance of <b>±0.10</b> and a <b>cap of 30 names per parent</b>: a parent that needs more than 30 names is read <b>off-Hub, nightly, from all its holdings</b> (exact, from the seven-rung close that already covers 5,560 instruments) instead of admitting dozens of live lines; its own fund line stays on the Hub as its bar. That gives <b>${C.served_now} → ${R.counts.proposed}</b> lines (${R.counts.out} out, ${R.counts.in} in). The brief's literal setting (±0.05, no cap) would give ${C.served_now} → ${C.proposed}. The three decisions are at the end.</div></div>

<div class="tiles"><div class="tile"><b>${C.served_now}</b><span>served now (${C.names_now} names + ${C.funds_now} funds)</span></div><div class="tile"><b>${R.counts.proposed}</b><span>proposed · ±0.10 · cap 30</span></div><div class="tile"><b>${R.counts.out}</b><span>out · off-Hub to the nightly reading</span></div><div class="tile"><b>${R.counts.in}</b><span>in · names a parent needs</span></div><div class="tile"><b>${C.proposed}</b><span>the brief's literal setting · ±0.05 · no cap</span></div><div class="tile"><b>${measured.length}</b><span>parents measured (funds with holdings)</span></div><div class="tile"><b>${unmeasured.length}</b><span>funds without holdings on file</span></div><div class="tile"><b>${T.within_tol_on_close_w}/${T.of}</b><span>parents within ±0.05 today (close)</span></div><div class="tile"><b>${T.w}/${T.of}</b><span>parents strong today on all 12 draws</span></div></div>

<div class="toc panel"><a href="#s1">1 · Picture: names per parent, today against the need</a><a href="#s2">2 · Picture: how big the Hub would be</a><a href="#s3">3 · Coverage and strong-N, parent by parent</a><a href="#s4">4 · The IWM rule</a><a href="#s5">5 · The rule, in numbered lines</a><a href="#s6">6 · What it would change today: out and in</a><a href="#s7">7 · Over-served and under-served</a><a href="#s8">8 · Where every number comes from · what could be wrong · what was not done</a><a href="#s9">9 · The three decisions</a><a href="#s10">10 · The page, as shot</a></div>

<h2 id="s1">1 · Names per parent <small>served today (grey) against the strong-N (light) — weight-blended, tolerance ±0.05</small></h2>
<div class="panel"><div class="svgwrap">${barChart()}</div><div class="words">How to read it: each parent is a fund on the tree with a holdings file. The grey bar is how many of its holdings the Hub serves today. The light bar is the <b>strong-N</b>: the smallest number of its biggest holdings whose Geiger average stays within ±0.05 of the average of ALL its holdings — on the 1 Oct seven-rung close and on at least 90% of 12 extra draws (its seven rungs and five daily closes). A dashed open bar means no number up to 100 does it: the parent is spread out like IWM. <b>Spread-out parents at ±0.05: ${esc(S.spread_out_parents.join(", "))}.</b></div></div>

<h2 id="s2">2 · How big the Hub would be <small>under the rule, by tolerance — weight-blended</small></h2>
<div class="panel"><div class="svgwrap">${sizeChart()}</div><div class="tw"><table class="t"><thead><tr><th class="k">tolerance</th><th class="r">no cap · lines</th><th class="r">out</th><th class="r">in</th><th class="r">spread-out parents</th><th class="r">cap 30 · lines</th><th class="r">out</th><th class="r">in</th><th class="r">spread-out</th><th class="r">equal-weight · no cap</th><th class="r">equal-weight · cap 30</th></tr></thead><tbody>${sensRows}</tbody></table></div><div class="words">Why the tolerance matters so much: inside one fund the Geigers spread about ±0.4 (the last column of the table in section 3 is each parent's spread). To pin an average to ±0.05 takes roughly (0.4 / 0.05)² ≈ 64 names; to ±0.10 about 16. That is why ±0.05 asks for a bigger Hub and ±0.10 lets it shrink. The equal-weight definition always asks for more, because the biggest holdings are not a fair sample of an equal-weight average.</div></div>

<h2 id="s3">3 · Coverage and strong-N, parent by parent <small>${measured.length} funds with holdings · readings = the seven-rung close of 1 Oct</small></h2>
<div class="panel"><div class="tw"><table class="t"><thead><tr><th class="k">parent</th><th>role</th><th>heading</th><th class="r">holdings</th><th class="r">readable</th><th class="r">served today</th><th class="r">served weight</th><th class="r">own Geiger</th><th class="r">full (all holdings)</th><th class="r">served aggregate</th><th class="r">gap served − full</th><th class="r">today on 12 draws</th><th class="r">strong-N ±0.05</th><th class="r">equal-weight N</th><th class="r">N at ±0.10</th><th class="r">spread</th></tr></thead><tbody>${parentRows}</tbody></table></div><div class="words">Columns in words: <b>holdings</b> = lines in the fund; <b>readable</b> = how many of them the seven-rung reading covers (foreign lines in VXUS, VT and GDX have no reading, and the page never fills them in); <b>served today</b> = how many are on the Hub, and the share of the fund's weight they carry; <b>own Geiger</b> = the fund's own seven-rung reading; <b>full</b> = the weight-blended Geiger of ALL readable holdings; <b>served aggregate</b> = the same over the served ones; <b>gap</b> = served − full (positive: the served names read stronger than the whole fund); <b>today on 12 draws</b> = on how many of the 12 draws today's served names stay within ±0.05 of the full; <b>strong-N</b> = the names the parent needs (weight-blended, then equal-weight, then at ±0.10); <b>spread</b> = the standard deviation of the holdings' Geigers. The Hub's live Geiger (intraday, 2 Oct) is in the JSON beside each parent as a second clock, never mixed into these aggregates.<br><br><b>Funds without a holdings file (${unmeasured.length}):</b> ${esc(unmeasured.map((p) => p.ticker).join(", "))} — not measured; they keep their served names until their holdings are fetched (FMP holdings covered 51 funds on 26 Sep; the database's holdings table holds one fund).</div></div>

<div class="panel"><div class="words"><b>The sector headings, read through their sector fund.</b> A heading has no holdings of its own; its sector SPDR is the market-cap picture of the sector, so the heading's full aggregate is the SPDR's. "Served names" here are the tree's names under the heading (every served company has a sector), which is a wider set than the SPDR's served holdings.</div><div class="tw"><table class="t"><thead><tr><th class="k">heading</th><th>sector fund</th><th class="r">served names under it</th><th class="r">served holdings of the fund</th><th class="r">served share of the fund</th><th class="r">served names, equal-weight</th><th class="r">fund full, equal-weight</th><th class="r">gap</th><th class="r">fund's own Geiger</th><th class="r">strong-N ±0.05</th></tr></thead><tbody>${headingRows}</tbody></table></div></div>

<h2 id="s4">4 · The IWM rule <small>IWM's names are served only where another parent needs them</small></h2>
<div class="tiles"><div class="tile"><b>${iwm.full.count}</b><span>IWM holdings with a reading</span></div><div class="tile"><b>${iwm.both_homes.length}</b><span>also in a sector or industry fund we serve</span></div><div class="tile"><b>${iwm.iwm_only.length}</b><span>IWM-only names · ${pct(iwm.iwm_only_weight_pct)} of IWM</span></div><div class="tile"><b>${iwm.served_today}</b><span>IWM names on the Hub today</span></div><div class="tile"><b>${g(iwm.full.w)}</b><span>IWM full aggregate (weight-blended)</span></div><div class="tile"><b>${g(iwm.inherited.w)}</b><span>from the ${iwm.inherited.count} names it would inherit</span></div><div class="tile"><b>${g(iwm.gap.w)}</b><span>what IWM loses (gap)</span></div></div>
<div class="panel"><div class="words">IWM holds ${iwm.full.count} readable names and its own Geiger reads ${g(measured.find((p) => p.ticker === "IWM").own.seven)}. No top-N up to 100 reproduces its full aggregate at ±0.05 (it is the most spread-out parent of all: its biggest line is 0.4% of the fund). ${iwm.both_homes.length} of its names (${pct(iwm.both_weight_pct)} of its weight) also sit in a sector or industry fund we serve — those are the ones Alan would put "where they coincide". ${iwm.iwm_only.length} names (${pct(iwm.iwm_only_weight_pct)} of IWM) live nowhere else among the served funds. If IWM keeps no own names and only inherits the ${iwm.inherited.count} it would get through other parents, Alan's lists and the cohorts (the proposed set at ±0.05), its aggregate reads ${g(iwm.inherited.w)} against the full ${g(iwm.full.w)}: a gap of ${g(iwm.gap.w)} (weight-blended) and ${g(iwm.gap.eq)} (equal-weight) — inside the tolerance today. Of the ${iwm.served_today} IWM names served today, ${iwm.served_today_out} are needed by nothing else at ±0.05 and would move off-Hub. The full IWM bar stays available every night off-Hub from all ${iwm.full.count} names.</div>
<div class="two"><div><div class="words"><b>Also at home in a sector or industry fund</b> (the 40 heaviest of ${iwm.both_homes.length}; the whole list is in the JSON)</div><div class="tw"><table class="t"><thead><tr><th class="k">name</th><th class="r">weight in IWM</th><th>other homes</th></tr></thead><tbody>${iwmBoth}</tbody></table></div></div><div><div class="words"><b>IWM-only</b> (the 25 heaviest of ${iwm.iwm_only.length})</div><div class="tw"><table class="t"><thead><tr><th class="k">name</th><th class="r">weight in IWM</th></tr></thead><tbody>${iwmOnly}</tbody></table></div></div></div></div>

<h2 id="s5">5 · The rule <small>numbered, plain lines — proposed, nothing applied</small></h2>
<div class="panel"><div class="words"><ol>${S.rule.map((r) => `<li>${esc(r.replace(/^\d+\.\s*/, ""))}</li>`).join("")}</ol><b>The recommended setting of the rule:</b> tolerance ±0.10, the weight-blended aggregate, and a cap of 30 names per parent — a parent whose strong-N is above 30 is a spread-out parent under line 4 (read off-Hub nightly, exact, from all its holdings; its own line stays on the Hub as its bar). With that setting the spread-out parents today are: ${esc(R.spread_out_parents.join(", "))}.</div></div>

<h2 id="s6">6 · What it would change today <small>${C.served_now} → ${R.counts.proposed} under the recommended setting · the literal ±0.05 / no-cap lists are in <a href="served-set.json">served-set.json</a></small></h2>
<div class="panel"><div class="words"><b>The cost side.</b> The Hub's Geiger runner computed ${M.cost.geiger_runner_rung_computations_now} rung readings on its last run (${C.served_now} lines × 7 rungs); under the recommended setting it computes ${M.recommended.cost.geiger_runner_rung_computations_proposed} (${R.counts.proposed} × 7). The stream serves ${M.cost.stream_live_lines_now} live lines today and would serve ${M.recommended.cost.stream_live_lines_proposed}. Under the literal ±0.05 / no-cap rule both grow: ${M.cost.geiger_runner_rung_computations_proposed} rung readings and ${M.cost.stream_live_lines_proposed} live lines. Everything that leaves the live set is still read once a night by the seven-rung close (5,560 instruments today) and still shows on the tree.</div>
<div class="words"><b>OUT — ${R.counts.out} names on the Hub that no parent needs at ±0.10 / cap 30, that are on none of Alan's lists and in no adopted cohort.</b> Each with its best home (the fund where it ranks highest), its other parents, its seven-rung reading and freshness, and the Hub's live Geiger.</div><div class="tw"><table class="t"><thead><tr><th class="k">name</th><th>company</th><th>best home · rank · weight</th><th>other parents</th><th class="r">seven-rung</th><th>freshness</th><th class="r">Hub live</th></tr></thead><tbody>${outRows(R.out)}</tbody></table></div>
<div class="words"><b>IN — ${R.counts.in} names a parent needs at ±0.10 / cap 30 that the Hub does not serve.</b> With the parent(s) that need them, rank and weight there, and whether the seven-rung reading has them (the two without a reading, BTCUSD and GCUSD, are Alan's list entries that are not stock lines — no change for them).</div><div class="tw"><table class="t"><thead><tr><th class="k">name</th><th>needed by · rank · weight</th><th class="r">seven-rung</th><th>freshness</th></tr></thead><tbody>${inRows(R.in)}</tbody></table></div></div>

<h2 id="s7">7 · Over-served and under-served <small>at the brief's ±0.05 — the parents whose strong-N is not met today</small></h2>
<div class="panel"><div class="words"><b>Over-served:</b> at ±0.05 with no cap, ${C.out} served names are needed by no parent, no list and no cohort (${esc(S.out.map((r) => r.ticker).join(", "))}). <b>Under-served:</b> ${M.under_served.length} parents have strong-N names the Hub does not serve; the table gives, per parent, how many are missing and the heaviest of them. The equal-weighted industry funds dominate: that is where the recommended cap applies.</div><div class="tw"><table class="t"><thead><tr><th class="k">parent</th><th>role</th><th class="r">strong-N ±0.05</th><th class="r">missing</th><th>the heaviest missing names (weight in the fund)</th></tr></thead><tbody>${underRows}</tbody></table></div></div>

<h2 id="s8">8 · Where every number comes from · what could be wrong · what was not done</h2>
<div class="panel"><div class="words"><b>Sources (dated snapshots, all in <code>data/</code> beside this page).</b><ul>
<li><b>The seven-rung close reading</b>: chart API <code>/v1/scout-geiger?reading=seven</code>, run ${esc(S.sources.seven.run_id)}, as of the ${esc(S.sources.seven.as_of)} close (5,641 rows; 5,560 with a seven-rung reading), plus the per-rung composites of the same run from <code>massive_stocks.scout_geiger_seven</code>.</li>
<li><b>The five daily closes</b> (${esc(S.sources.daily_three_rung.join(", "))}): the three-rung daily reading, <code>massive_stocks.scout_geiger_daily</code> — the extra draws.</li>
<li><b>Holdings</b>: FMP holdings updated ${esc(S.sources.holdings)}, the file the tree was built from (51 funds, every line with its weight).</li>
<li><b>The tree</b> (built ${esc(S.sources.tree_built)}): the 138 funds, their roles and headings, the 476 names and their sectors, the adopted cohorts.</li>
<li><b>The Hub's live Geiger</b>: chart API <code>/geiger</code>, computed ${esc(S.sources.hub_geiger_computed_utc)} (590 lines, seven rungs) — shown as a second clock only.</li>
<li><b>The universe</b>: chart API <code>/universe</code> (590, sha ${esc(S.sources.universe_sha256.slice(0, 12))}…). <b>Alan's lists</b> read ${esc(S.sources.lists_read)}: LIKED = <code>public.hub_favorites</code> (141), FAVORITES (57) and RADAR (17) = <code>public.station_lists</code>.</li></ul>
<b>What could be wrong.</b><ul>${M.limits.map((l) => `<li>${esc(l)}</li>`).join("")}
<li>The holdings are a week old (26 Sep) and FMP's file lists part of some funds (VT is capped at 4,000 lines; DRAM lists 9 of 26). Weights are used as listed, re-scaled over the readable lines; nothing is filled in.</li>
<li>Readings of −1…+1 at one close are a single day's state. The strong-N moves with the market's dispersion; the rule re-measures nightly and the five-close guard (line 7) is there so one day cannot move a name.</li></ul>
<b>What was not done.</b> Nothing live was changed: no table, no universe, no registry, no tree, no admission or removal. The 87 funds without holdings were not measured. No name was actually moved — the lists in section 6 are proposals. The "9 days out of 10" test proper was not possible with one seven-rung close; it was stood in for by 12 draws, as said above.</div></div>

<h2 id="s9">9 · The three decisions <small>each with the recommendation</small></h2>
<div class="dec"><b>1 · The tolerance.</b> ±0.05 (the brief) makes the Hub grow to ${C.proposed} lines, or ${S.sensitivity["0.05"].cap_30.w.proposed} with the cap; ±0.10 gives ${S.sensitivity["0.1"].no_cap.w.proposed} without the cap and ${R.counts.proposed} with it; ±0.15 gives ${S.sensitivity["0.15"].cap_30.w.proposed} with the cap. <b>Recommendation: ±0.10 with the cap of 30.</b> A tenth of the Geiger's range is about what the eye reads as "the same bar"; the cap keeps the live Hub the size it is while every spread-out parent still gets its exact bar nightly off-Hub.</div>
<div class="dec"><b>2 · Weight-blended or equal-weight.</b> Weight-blended (bigger holdings count more) is what a fund's own price does, needs fewer names everywhere (section 3), and today's served names already pass it for ${T.within_tol_on_close_w} of ${T.of} parents. Equal-weight treats every line alike and asks for ${S.sensitivity["0.1"].cap_30.eq.proposed} lines at ±0.10 with the cap. <b>Recommendation: weight-blended for every cap-weighted parent; equal-weight only where the fund itself is equal-weighted (RSP, QQEW, the RSPx family, XRT, XPH, KBE, SPLV) — which the cap already sends off-Hub.</b></div>
<div class="dec"><b>3 · Alan's lists.</b> LIKED (141), FAVORITES (57) and RADAR (17) are kept served whatever the parents say; they add ${S.recommended.in.filter((r) => r.needed_by.length === 0 && r.lists.length).length} names today that no parent needs (${esc(S.recommended.in.filter((r) => r.needed_by.length === 0 && r.lists.length).map((r) => r.ticker).join(", ") || "none")}). <b>Recommendation: keep all three as an unconditional "serve" — they are Alan's hand, and ${S.out.filter((r) => r.lists.length).length} of the out-candidates would otherwise be on a list.</b> The alternative (only FAVORITES and RADAR hold a name on the Hub; LIKED does not) is a smaller Hub by a few dozen names and is one line to change in the builder.</div>

<h2 id="s10">10 · The page, as shot <small>headless, 1680 and 390 wide — examined before this was committed</small></h2>
${shots.length ? `<div class="panel"><div class="two">${shots.map((f) => `<div class="shot"><div class="clip${f.includes("390") ? " phone" : ""}"><img src="shots/${f}" alt="${f}"></div><small>shots/${f}</small></div>`).join("")}</div></div>` : '<div class="panel"><div class="words">Shots are taken after the first build; rerun page.mjs once shots/ exists.</div></div>'}
<div class="panel"><div class="words">Files beside this page: <a href="served-set.json">served-set.json</a> (the rule, the counts, the in/out lists at the brief's setting and at the recommended one, the sensitivity), <a href="measure.json">measure.json</a> (every table above, every parent's ladder), <code>maths.mjs</code> (the maths, tested by <code>tests/served-set-u2.test.mjs</code>), <code>build.mjs</code> and <code>page.mjs</code> (rebuild: <code>node deliverables/20261002/served-set/build.mjs && node deliverables/20261002/served-set/page.mjs</code>), <code>data/</code> (the dated snapshots).</div></div>
</div></body></html>`;
writeFileSync(join(DIR, "SERVED-SET.html"), html);
console.log("wrote SERVED-SET.html", html.length, "bytes; shots:", shots);
