import { chromium, EXE, sleep } from "./rig.mjs";
import fs from "node:fs";
const root = process.env.STATION_ROOT;
const MIME = { html: "text/html; charset=utf-8", js: "text/javascript", mjs: "text/javascript", css: "text/css", json: "application/json" };
const browser = await chromium.launch({ executablePath: EXE, headless: true, args: ["--no-sandbox"] });
const context = await browser.newContext({ viewport: { width: 1680, height: 1050 } });
await context.route("**/*", (route) => { const req = route.request(), u = new URL(req.url());
  if (!["GET", "HEAD", "OPTIONS"].includes(req.method())) return route.abort();
  if (u.host === "station.scintillahub.ai") { let p = decodeURIComponent(u.pathname); if (p.endsWith("/")) p += "index.html"; let f = root + p;
    if (fs.existsSync(f) && fs.statSync(f).isDirectory()) f += "/index.html";
    if (fs.existsSync(f)) return route.fulfill({ status: 200, contentType: MIME[f.split(".").pop()] || "application/octet-stream", body: fs.readFileSync(f) }); }
  return route.continue(); });
const page = await context.newPage();
page.on("pageerror", (e) => console.log("pageerror", String(e).slice(0, 200)));
page.on("console", (m) => { if (/H3DBG/.test(m.text())) console.log(m.text()); });
await context.addInitScript(() => { if (window.top !== window) return; window.__h3 = []; });
await page.goto("https://station.scintillahub.ai/deck/?scene=wkMacro", { waitUntil: "domcontentloaded" });
await sleep(3000);
console.log(JSON.stringify(await page.evaluate(() => ({ fn: typeof deckCloudPrefetch, many: typeof (window.SC_PROVIDER || {}).candlesMany, CLOUDS: typeof CLOUDS !== "undefined" ? CLOUDS : "undef", CHARTS: CHARTS.slice(0, 8), CHART_COUNT, RANGE, SLOT_RANGES, SLOT_BARS, SCENE }))));
await browser.close();
