-- GENERATED by scripts/build-canonical-universe.mjs (provider repo) for the set 116c79f2e6f7cbdadceac1a2574595fc396d88cb283fce2932c926e86673eabe
-- (590 names). Do not edit by hand: re-run the builder. Needs 20260927_admission_v2_role.sql first.
delete from public.tickers where source = 'admission-v3-20260928';
do $$
declare n int;
begin
  select count(*) into n from public.tickers where active = true and (type is null or type not in ('crypto','future','index','rate'));
  raise notice 'admission v2 rollback: % active equity names remain', n;
end $$;
