-- GENERATED by scripts/build-canonical-universe.mjs --retire (provider repo) for the set c0f72aab4110b1587923523e5ee1b54e2e4e024dfc927fa431ffe7695b2e339e
-- (589 names). Do not edit by hand: re-run the builder. Needs Alan's word: it changes what the Hub shows.
update public.tickers set active = false, retired_at = now(), retired_reason = case ticker
    when 'QRVO' then 'Retired 2026-10-05: Skyworks Solutions completed its acquisition of Qorvo on 5 Oct 2026 (per Qorvo share: 32.50 USD cash + 0.960 SWKS); QRVO no longer trades. Successor: SWKS. All QRVO data is kept.'
  end
where ticker in ('QRVO') and active = true;

-- PROOF: the Hub's active equity list is now exactly the provider's set, by count.
do $$
declare n int;
begin
  select count(*) into n from public.tickers where active = true and (type is null or type not in ('crypto','future','index','rate'));
  if n <> 589 then raise exception 'retirement: expected 589 active equity names, found %', n; end if;
end $$;
