-- GENERATED by scripts/build-canonical-universe.mjs (provider repo) for the set 223dbb0ff58eda0363c7882d493ad09bef932fbf953f80d6849882242ecc316e
-- (486 names). Do not edit by hand: re-run the builder. Needs 20260927_admission_v2_role.sql first.
-- OVERWRITE (Alan's yes required): these rows exist switched off. Run BEFORE the main file.
update public.tickers set active = true, role = 'geiger_only' where ticker in ('UUP','VXX') and active = false;
