-- GENERATED by scripts/build-canonical-universe.mjs --retire (provider repo) for the set be8c2cd8b57bbc9b6cb8650a323471a3e30e863e6b9419b5c85bb3d6b8d32568
-- (588 names). Do not edit by hand: re-run the builder. Needs Alan's word: it changes what the Hub shows.
update public.tickers set active = true, retired_at = null, retired_reason = null where ticker in ('WBD') and active = false;
do $$
declare n int;
begin
  select count(*) into n from public.tickers where active = true and (type is null or type not in ('crypto','future','index','rate'));
  if n <> 589 then raise exception 'retirement rollback: expected 589 active equity names, found %', n; end if;
end $$;
