-- GENERATED by scripts/build-canonical-universe.mjs (provider repo) for the set 6e82721ba4f25c85ad29a60d9bda60a442b2631abc6c2d0be249eb95ac14c9f2
-- (487 names). Do not edit by hand: re-run the builder. Needs 20260927_admission_v2_role.sql first.
-- OVERWRITE (Alan's yes required): these rows exist switched off. Run BEFORE the main file.
update public.tickers set active = true, role = 'geiger_only' where ticker in ('UUP','VXX') and active = false;
