-- TR1 (6 Oct 2026) · THE COHORT TREE — rollback. GENERATED by scripts/cohort-tree-loader.mjs.
-- Drops exactly what 20261006_tr1_cohort_tree.sql creates: two policies, one index, two tables (their rows go with
-- them). Nothing else was created or changed: no other table, no view, no function, no cron, no row elsewhere.
drop policy if exists cohort_tree_members_read on public.cohort_tree_members;
drop policy if exists cohort_tree_read on public.cohort_tree;
drop table if exists public.cohort_tree_members;
drop table if exists public.cohort_tree;
