-- TR2 (6 Oct 2026) · THE WAY BACK FROM TR1'S AFTER-ADMISSION STEP. GENERATED by scripts/cohort-tree-revise-sql.mjs
-- from TR1's own tree (scripts/cohort-tree-loader.mjs, buildTree); do not edit by hand.
-- WHY THIS FILE EXISTS. 20261006_tr1_cohort_tree_AFTER_ADMISSION.sql says its way back is "re-run the LOAD file".
-- Once TR2 is applied that way is closed on purpose (the LOAD file empties cohort_tree and would undo the revision).
-- This is the targeted way back, and it is right with or without TR2 applied: it marks TR1's 10 funds
-- pending_admission again and puts the 4 spine hand-overs (ASIA_PACIFIC, CANADA, LATAM, IDX_WORLD) back as TR1 loaded
-- them. It writes nothing else. ONE TRANSACTION; safe to run twice; refuses if a spine is neither as TR1 loaded it
-- nor as TR1's after-admission step left it.
begin;
do $$
declare
  k int; odd text;
begin
  select string_agg(format('%s (spine_fund %s, spine_fund_next %s)', t.cohort, coalesce(t.spine_fund, 'null'), coalesce(t.spine_fund_next, 'null')), '; ') into odd
  from (values
    ('ASIA_PACIFIC'::text,'EWJ'::text,'EWT'::text),
    ('CANADA','EFA','EWC'),
    ('LATAM','EEM','EWZ'),
    ('IDX_WORLD','VT','ACWI')
  ) as v(cohort, spine_fund, spine_fund_next)
  join public.cohort_tree t on t.cohort = v.cohort
  where not ((t.spine_fund is not distinct from v.spine_fund and t.spine_fund_next is not distinct from v.spine_fund_next)
          or (t.spine_fund is not distinct from v.spine_fund_next and t.spine_fund_next is null));
  if odd is not null then raise exception 'undo of TR1''s after-admission step refused, nothing changed: a spine is in neither of TR1''s two states — %', odd; end if;

  update public.cohort_tree_members x set status = 'pending_admission'
  from (values
    ('IDX_STYLE'::text,'SPYG'::text),
    ('IDX_STYLE','SPYV'),
    ('IDX_FACTOR','USMV'),
    ('IDX_FACTOR','VLUE'),
    ('IDX_WORLD','ACWI'),
    ('IDX_WORLD','URTH'),
    ('IDX_COUNTRIES','EWT'),
    ('IDX_COUNTRIES','INDA'),
    ('IDX_COUNTRIES','EWZ'),
    ('IDX_COUNTRIES','EWC')
  ) as v(cohort, ticker)
  where x.cohort = v.cohort and x.ticker = v.ticker and x.role = 'index_fund';
  get diagnostics k = row_count;
  if k <> 10 then raise exception 'undo of TR1''s after-admission step refused, nothing changed: expected TR1''s 10 funds, found %', k; end if;

  update public.cohort_tree t set spine_fund = v.spine_fund, spine_fund_next = v.spine_fund_next
  from (values
    ('ASIA_PACIFIC'::text,'EWJ'::text,'EWT'::text),
    ('CANADA','EFA','EWC'),
    ('LATAM','EEM','EWZ'),
    ('IDX_WORLD','VT','ACWI')
  ) as v(cohort, spine_fund, spine_fund_next)
  where t.cohort = v.cohort;
  get diagnostics k = row_count;
  if k <> 4 then raise exception 'undo of TR1''s after-admission step refused, nothing changed: expected 4 spine rows, found %', k; end if;

  -- PROOF: exactly TR1's 10 pending rows and 4 waiting spines, no more
  select count(*) into k from public.cohort_tree_members where status = 'pending_admission';
  if k <> 10 then raise exception 'undo of TR1''s after-admission step, proof: expected 10 pending rows, found %', k; end if;
  select count(*) into k from public.cohort_tree where spine_fund_next is not null;
  if k <> 4 then raise exception 'undo of TR1''s after-admission step, proof: expected 4 waiting spines, found %', k; end if;
end $$;
commit;
