-- GENERATED by scripts/build-cohort-rules-step1.py from deliverables/20260928/tree-cohorts. Do not edit by hand.
-- COHORT RULES, STEP 1 (Alan, 28 Sep 2026: "adopt the tree-derived cohort rules in two separate steps, parents and merges first").
-- ADDITIVE: one new table. No row of public.ticker_membership, public.tickers or public.hub_favorites is touched, so no
-- name moves and no board tab changes; readers adopt the table in their own reviewed change. Splits and moves are step 2.
-- Export taken first: _archive/admission-v3-20260928/rollback/ticker_membership-before.json (1,443 rows).
-- ROLLBACK: 20260928_cohort_rules_step1_ROLLBACK.sql (drops this table only).
create table if not exists public.cohort_registry (
  label            text primary key,
  display_label    text not null,
  kind             text not null check (kind in ('cohort','merged','filter')),
  parent           text,
  parent_reason    text,
  merged_into      text references public.cohort_registry(label) deferrable initially deferred,
  filter_attribute text check (filter_attribute in ('cap_tranche','style')),
  filter_value     text,
  rule             text,
  cohesion         numeric,
  null95           numeric,
  step2_pending    text,
  source           text not null default 'tree-cohorts-20260928 step 1',
  adopted_at       timestamptz not null default now(),
  check ((kind = 'cohort') = (parent is not null)),
  check ((kind = 'merged') = (merged_into is not null)),
  check ((kind = 'filter') = (filter_attribute is not null))
);
comment on table public.cohort_registry is 'Tree-derived cohort rules (tree-cohorts 28 Sep), step 1: every cohort label with its one parent (R1), the merges (R4) and the size/style labels that became filters (R2). Membership stays in ticker_membership.';
alter table public.cohort_registry enable row level security;
drop policy if exists cohort_registry_read on public.cohort_registry;
create policy cohort_registry_read on public.cohort_registry for select using (true);

begin;
set constraints all deferred;
insert into public.cohort_registry (label, display_label, kind, parent, parent_reason, merged_into, filter_attribute, filter_value, rule, cohesion, null95, step2_pending) values
  ('AI_ACCELERATORS', 'AI ACCELERATORS', 'cohort', 'SMH', 'R1: SMH tracked the mean at 0.892 over 750 sessions (sector fund XLK 0.867)', null, null, null, 'R1', 0.371, 0.189, null),
  ('AI_DATACENTER', 'AI DATACENTER', 'cohort', 'SEC_TECH', 'R1: no fund beat the sector fund XLK (0.693); hangs under the heading', null, null, null, 'R1', 0.359, 0.259, 'split into data-centre property and neoclouds & miners'),
  ('AI_HARDWARE', 'AI HARDWARE', 'cohort', 'SMH', 'R1: SMH tracked the mean at 0.940 over 750 sessions (sector fund XLK 0.844)', null, null, null, 'R1', 0.426, 0.172, 'split into accelerators, memory & semicap, photonics, neoclouds & miners'),
  ('AI_POWER', 'AI POWER', 'cohort', 'VPU', 'R1: VPU tracked the mean at 0.941 over 750 sessions (sector fund XLU 0.936)', null, null, null, 'R1', 0.335, 0.183, 'regulated utilities split out to the XLU fund cohort; the generators then hang under SEC_UTIL (R1 on today''s 27 names picks VPU)'),
  ('AI_POWERTRAIN', 'AI POWERTRAIN', 'merged', null, 'merged into AI_POWER', 'AI_POWER', null, null, 'R4', 0.374, 0.259, null),
  ('AI_SOFTWARE', 'AI SOFTWARE', 'cohort', 'IGV', 'IGV tracked the cohort mean at 0.88 over 750 sessions (sector fund XLK 0.70)', null, null, null, 'R1', 0.299, 0.214, null),
  ('BANKS_MARKETS', 'BANKS MARKETS', 'cohort', 'IYG', 'R1: IYG tracked the mean at 0.931 over 750 sessions (sector fund XLF 0.898)', null, null, null, 'R1', 0.366, 0.182, 'split into money-centre banks and capital markets'),
  ('BLUE_CHIP', 'BLUE CHIP', 'filter', null, 'a filter is an attribute of a name, not a node on the tree', null, 'style', 'VALUE_QUALITY', 'R2', 0.179, 0.153, null),
  ('COPPER_STEEL', 'COPPER STEEL', 'cohort', 'IYM', 'IYM tracked the cohort mean at 0.79 over 750 sessions (sector fund XLB 0.67)', null, null, null, 'R1', 0.581, 0.327, null),
  ('CRITICAL_MINERALS', 'CRITICAL MINERALS', 'cohort', 'REMX', 'REMX tracked the cohort mean at 0.90 over 750 sessions (sector fund XLB 0.39)', null, null, null, 'R1', 0.509, 0.245, null),
  ('CRYPTO', 'CRYPTO', 'merged', null, 'merged into CRYPTO_EQUITIES', 'CRYPTO_EQUITIES', null, null, 'R4', 0.761, 0.472, null),
  ('CRYPTO_EQUITIES', 'CRYPTO EQUITIES', 'cohort', 'CRYPTO', 'COIN, MSTR and HOOD move with each other and with the generators CEG and VST (one group, 0.66), not with the miners; the cohort hangs under the CRYPTO heading with the coins', null, null, null, 'R1', 0.457, 0.259, 'split into exchanges & treasuries and neoclouds & miners'),
  ('CYBER', 'CYBER', 'merged', null, 'merged into SECURITY_DATA', 'SECURITY_DATA', null, null, 'R4', 0.717, 0.358, null),
  ('DEFENCE_AEROSPACE', 'DEFENCE AEROSPACE', 'cohort', 'ITA', 'ITA tracked the cohort mean at 0.84 over 750 sessions (sector fund XLI 0.61)', null, null, null, 'R1', 0.338, 0.232, null),
  ('EVTOL_AUTONOMY', 'EVTOL AUTONOMY', 'cohort', 'SEC_DISC', 'no fund tracked it (ARKX 0.74, XLY 0.61 for the old mean); the cohort hangs under the discretionary heading. Cohesion 0.29 against 0.23 for random sets: a cohort, but a loose one.', null, null, null, 'R1', 0.286, 0.228, null),
  ('GROWTH', 'GROWTH', 'cohort', 'IGV', 'IGV tracked the cohort mean at 0.88 over 750 sessions (sector fund XLK 0.62)', null, null, null, 'R1', 0.371, 0.18, null),
  ('INDEXES', 'INDEXES', 'cohort', 'US_BROAD', 'a cohort of index funds hangs under the broad-market heading, not under a fund (today: no parent)', null, null, null, 'R1', 0.739, 0.232, null),
  ('INTL', 'WORLD', 'cohort', 'WORLD', 'funds and ADRs of other markets hang under WORLD (today: no parent). Two groups inside: the China names (BABA, JD, PDD, BIDU, FXI, MCHI, ASHR) reproduce together; the developed-market funds are the other.', null, null, null, 'R1', 0.453, 0.214, 'CHINA split out under MCHI'),
  ('LARGE_CAP', 'LARGE CAP', 'filter', null, 'a filter is an attribute of a name, not a node on the tree', null, 'cap_tranche', 'LARGE', 'R2', 0.141, 0.147, null),
  ('MACRO', 'MACRO', 'cohort', 'MACRO', 'a cohort of macro funds hangs under the MACRO heading (today: no parent). GLD and SLV also sit in METALS, where the rotation Alan wants to see lives.', null, null, null, 'R1', 0.154, 0.228, null),
  ('MEGACAP', 'MEGACAP', 'cohort', 'VUG', 'VUG tracked the cohort mean at 0.90 over 750 sessions (sector fund XLK 0.85)', null, null, null, 'R1', 0.293, 0.203, null),
  ('MEGACAP_PLATFORMS', 'MEGACAP PLATFORMS', 'cohort', 'FDN', 'FDN tracked the cohort mean at 0.79 over 750 sessions (sector fund XLY 0.63)', null, null, null, 'R1', 0.302, 0.206, 'becomes INTERNET & CONSUMER PLATFORMS (AAPL, META, NFLX stay in MEGACAP)'),
  ('MEGA_CAP', 'MEGA CAP', 'filter', null, 'a filter is an attribute of a name, not a node on the tree', null, 'cap_tranche', 'MEGA', 'R2', 0.168, 0.162, null),
  ('MEMORY_STORAGE', 'MEMORY STORAGE', 'merged', null, 'merged into MEMORY_SEMICAP', 'MEMORY_SEMICAP', null, null, 'R4', 0.719, 0.259, null),
  ('METALS', 'METALS · GOLD & SILVER', 'cohort', 'GDX', 'GDX tracked the 17 at 0.98; METALS and PRECIOUS METALS were the same list', null, null, null, 'R1', 0.761, 0.201, null),
  ('MID_CAP', 'MID CAP', 'filter', null, 'a filter is an attribute of a name, not a node on the tree', null, 'cap_tranche', 'MID', 'R2', 0.298, 0.181, null),
  ('NUCLEAR_URANIUM', 'NUCLEAR URANIUM', 'cohort', 'URA', 'URA tracked the cohort mean at 0.84 over 750 sessions (sector fund XLE -0.04)', null, null, null, 'R1', 0.631, 0.283, null),
  ('PAYMENTS_FINTECH', 'PAYMENTS FINTECH', 'cohort', 'IPAY', 'IPAY tracked the cohort mean at 0.84 over 750 sessions (sector fund XLF 0.81)', null, null, null, 'R1', 0.531, 0.259, null),
  ('PHOTONICS_OPTICAL', 'PHOTONICS OPTICAL', 'cohort', 'IYZ', 'R1: IYZ tracked the mean at 0.703 over 750 sessions (sector fund XLK 0.534)', null, null, null, 'R1', 0.599, 0.358, null),
  ('PRECIOUS_METALS', 'PRECIOUS METALS', 'merged', null, 'merged into METALS', 'METALS', null, null, 'R4', 0.761, 0.201, null),
  ('QUANTUM', 'QUANTUM', 'cohort', 'QTUM', 'QTUM tracked the cohort mean at 0.65 over 750 sessions (sector fund XLK 0.47)', null, null, null, 'R1', 0.731, 0.327, null),
  ('SEMI_EQUIPMENT', 'SEMI EQUIPMENT', 'merged', null, 'merged into MEMORY_SEMICAP', 'MEMORY_SEMICAP', null, null, 'R4', 0.718, 0.283, null),
  ('SMALL_CAP', 'SMALL CAP', 'filter', null, 'a filter is an attribute of a name, not a node on the tree', null, 'cap_tranche', 'SMALL', 'R2', 0.319, 0.259, null),
  ('SOLAR_RENEWABLE', 'SOLAR RENEWABLE', 'cohort', 'TAN', 'three served names in three groups (cohesion 0.22 against 0.36 for random sets of 3): not a cohort until ENPH, SEDG, RUN, NXT and AMRC are served; until then the fund TAN is the cohort', null, null, null, 'R1', 0.215, 0.358, null),
  ('SPACE', 'SPACE', 'cohort', 'ARKX', 'ARKX tracked the cohort mean at 0.82 over 750 sessions (sector fund XLI 0.42)', null, null, null, 'R1', 0.324, 0.259, null),
  ('THEMATIC', 'THEMATIC', 'cohort', 'ARKX', 'R1: ARKX tracked the mean at 0.832 over 750 sessions (sector fund XLK 0.494)', null, null, null, 'R1', 0.288, 0.18, 'dissolved into its five theme cohorts (ARKX is R1 on the mean but holds 5 of 23)'),
  ('MEMORY_SEMICAP', 'MEMORY & SEMI EQUIPMENT', 'cohort', 'SMH', 'one co-movement group of ten (reproducibility 0.92): the memory makers and the equipment makers move as one; SMH holds 8 of them; DRAM holds 4', null, null, null, 'R1+R4', null, null, null),
  ('SECURITY_DATA', 'SECURITY & DATA PLATFORMS', 'cohort', 'CIBR', 'CIBR tracked CYBER at 0.85 and IGV at 0.78; the seven names (CRWD DDOG MDB PANW PATH SNOW ZS) are one group (0.67)', null, null, null, 'R1+R4', null, null, 'DDOG, MDB, SNOW, PATH join (moves)')
on conflict (label) do nothing;
commit;

do $$
declare n int; f int; m int;
begin
  select count(*) into n from public.cohort_registry where source = 'tree-cohorts-20260928 step 1';
  select count(*) into f from public.cohort_registry where kind = 'filter';
  select count(*) into m from public.cohort_registry where kind = 'merged';
  if n <> 38 then raise exception 'cohort rules step 1: expected 38 rows, found %', n; end if;
  if f <> 5 then raise exception 'cohort rules step 1: expected 5 filters, found %', f; end if;
  if m <> 6 then raise exception 'cohort rules step 1: expected 6 merged labels, found %', m; end if;
end $$;
