-- TR2 (6 Oct 2026) · THE NEXT FUND BATCH — tree rows, ROLLBACK. GENERATED by scripts/cohort-tree-next-funds-sql.mjs; do not edit by hand.
-- funds: 26 · index-set rows: 26 · reference rows: 10 · spine hand-overs: 7
-- held: none
-- BLOCK 1 (this is what runs): takes out this batch's PENDING rows and clears the 7 waiting spines it set. It REFUSES
-- if any of the funds is already served: then the rows are no longer a plan, and the way back is block 2.
-- Writes ONLY public.cohort_tree_members (delete) and public.cohort_tree.spine_fund_next. One transaction.
begin;
do $$
declare x text;
begin
  select string_agg(distinct ticker, ', ' order by ticker) into x from public.cohort_tree_members where ticker in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG') and status = 'served';
  if x is not null then raise exception 'TR2-NEXT rollback refused: already served (%). To undo an admission, run block 2 of this file on purpose, then this block; nothing was changed.', x; end if;
end $$;
delete from public.cohort_tree_members where ticker in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG') and status = 'pending_admission' and source = 'TR2-NEXT-20261006';
update public.cohort_tree t set spine_fund_next = null from (values ('CRYPTO_EQUITIES','IBIT'),('CHINA','KWEB'),('GRID_ELECTRICAL','GRID'),('DEFENCE_TECH','SHLD'),('OIL_MIDSTREAM','MLPX'),('BIG_BANKS_BROKERS','KBWB'),('NEOCLOUDS_MINERS','WGMI')) v(cohort, fund) where t.cohort = v.cohort and t.spine_fund_next = v.fund;
do $$
declare m int; s int;
begin
  select count(*) into m from public.cohort_tree_members where ticker in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG');
  select (select count(*)::int from public.cohort_tree t where (t.cohort, t.spine_fund_next) in (('CRYPTO_EQUITIES','IBIT'),('CHINA','KWEB'),('GRID_ELECTRICAL','GRID'),('DEFENCE_TECH','SHLD'),('OIL_MIDSTREAM','MLPX'),('BIG_BANKS_BROKERS','KBWB'),('NEOCLOUDS_MINERS','WGMI'))) into s;
  if m <> 0 then raise exception 'TR2-NEXT rollback: % rows of this batch remain', m; end if;
  if s <> 0 then raise exception 'TR2-NEXT rollback: % spines are still waiting for this batch', s; end if;
end $$;
commit;
select 'TR2-NEXT rolled back' as step, count(*)::int as rows_left from public.cohort_tree_members where ticker in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG');

-- ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
-- BLOCK 2 — ONLY ON PURPOSE. The reverse of 20261006_tr2_next_funds_tree_AFTER_ADMISSION.sql: the 26 funds go back
-- to pending and the 7 spines go back to the fund each cohort had on 6 Oct, with this batch's fund waiting again.
-- It is commented out so that running this file never does it by accident. To use it: copy the lines below without
-- their leading "-- ", run them, then run block 1. (Also the way back if TR1's blanket step was run by mistake while
-- this batch was pending.)
-- begin;
-- update public.cohort_tree_members set status = 'pending_admission' where ticker in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG') and status = 'served' and source = 'TR2-NEXT-20261006';
-- update public.cohort_tree t set spine_fund = v.was, spine_fund_next = v.fund from (values ('CRYPTO_EQUITIES','IBIT',null::text),('CHINA','KWEB','FXI'::text),('GRID_ELECTRICAL','GRID','PAVE'::text),('DEFENCE_TECH','SHLD','ITA'::text),('OIL_MIDSTREAM','MLPX','XLE'::text),('BIG_BANKS_BROKERS','KBWB','IYG'::text),('NEOCLOUDS_MINERS','WGMI',null::text)) v(cohort, fund, was) where t.cohort = v.cohort and t.spine_fund = v.fund and t.spine_fund_next is null;
-- commit;
