-- GENERATED by scripts/build-canonical-universe.mjs (provider repo) for the set 10ebf89cd6be183747b163fd48d7f42e6fe7b4f147b1daf88bad202c64682546
-- (598 names). Do not edit by hand: re-run the builder. Needs 20260927_admission_v2_role.sql first.
-- ADDITIVE: inserts only names that have no row (NOT EXISTS), marked source='admission-tr1-index-20261006'.
insert into public.tickers (ticker, cohort, type, currency, active, source, role)
select v.ticker, v.cohort, v.type, 'USD', true, 'admission-tr1-index-20261006', v.role
from (values
  ('URTH','FUNDS','etf','geiger_only'),
  ('ACWI','FUNDS','etf','geiger_only'),
  ('SPYG','FUNDS','etf','geiger_only'),
  ('SPYV','FUNDS','etf','geiger_only'),
  ('USMV','FUNDS','etf','geiger_only'),
  ('VLUE','FUNDS','etf','geiger_only'),
  ('EWT','FUNDS','etf','geiger_only'),
  ('INDA','FUNDS','etf','geiger_only'),
  ('EWZ','FUNDS','etf','geiger_only'),
  ('EWC','FUNDS','etf','geiger_only')
) as v(ticker, cohort, type, role)
where not exists (select 1 from public.tickers t where t.ticker = v.ticker);

-- PROOF: the Hub's active equity list is now exactly the provider's set, by count and by tier.
do $$
declare n int; g int;
begin
  select count(*) into n from public.tickers where active = true and (type is null or type not in ('crypto','future','index','rate'));
  if n <> 598 then raise exception 'admission v2: expected 598 active equity names, found %', n; end if;
  select count(*) into g from public.tickers where active = true and (type is null or type not in ('crypto','future','index','rate')) and role = 'geiger_only';
  if g <> 76 then raise exception 'admission v2: expected 76 geiger-only names, found %', g; end if;
end $$;
