-- GENERATED by scripts/build-canonical-universe.mjs (provider repo) for the set 87769613d9c3457306b5d6cbe44079e81f5300722b6f4c14f86e2f3405cf9628
-- (599 names). Do not edit by hand: re-run the builder. Needs 20260927_admission_v2_role.sql first.
delete from public.tickers where source = 'admission-tr1-index-20261006';
do $$
declare n int;
begin
  select count(*) into n from public.tickers where active = true and (type is null or type not in ('crypto','future','index','rate'));
  raise notice 'admission v2 rollback: % active equity names remain', n;
end $$;
