-- GENERATED by scripts/build-canonical-universe.mjs --retire (provider repo) for the set be8c2cd8b57bbc9b6cb8650a323471a3e30e863e6b9419b5c85bb3d6b8d32568
-- (588 names). Do not edit by hand: re-run the builder. Needs Alan's word: it changes what the Hub shows.
update public.tickers set active = false, retired_at = now(), retired_reason = case ticker
    when 'WBD' then 'Retired 2026-10-06: Paramount Skydance completed its takeover of Warner Bros. Discovery on 6 Oct 2026; WBD no longer trades after 6 Oct. Successor: PSKY. All WBD data is kept.'
  end
where ticker in ('WBD') and active = true;

-- PROOF: the Hub's active equity list is now exactly the provider's set, by count.
do $$
declare n int;
begin
  select count(*) into n from public.tickers where active = true and (type is null or type not in ('crypto','future','index','rate'));
  if n <> 588 then raise exception 'retirement: expected 588 active equity names, found %', n; end if;
end $$;
