-- TR2 (6 Oct 2026) · THE NEXT FUND BATCH — tree rows, PENDING. GENERATED by scripts/cohort-tree-next-funds-sql.mjs; do not edit by hand.
-- funds: 26 · index-set rows: 26 · reference rows: 10 · spine hand-overs: 7
-- held: none
-- NOT FOR TONIGHT. Run it at the sitting that admits this batch, and only AFTER 20261006_tr1_cohort_tree_AFTER_ADMISSION.sql
-- has run. That step is blanket (every pending row becomes served): rows loaded here before it would be marked served
-- without anyone admitting the funds. This file checks, and refuses if any other fund is still pending.
-- Writes ONLY public.cohort_tree_members (36 rows) and public.cohort_tree.spine_fund_next (7 cohorts). One transaction;
-- safe to run twice. Every node it writes to is in TR1's tree and in the revised one, so it runs on either.
-- Way back: 20261006_tr2_next_funds_tree_ROLLBACK.sql
begin;
do $$
declare x text;
begin
  select string_agg(distinct ticker, ', ' order by ticker) into x from public.cohort_tree_members
   where status = 'pending_admission' and ticker not in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG');
  if x is not null then raise exception 'TR2-NEXT refused: other funds are still pending admission (%). Run TR1''s after-admission step first; nothing was changed.', x; end if;
  select string_agg(c, ', ' order by c) into x from unnest(array['BIG_BANKS_BROKERS','CHINA','COPPER_STEEL','CRYPTO_EQUITIES','DEFENCE_PRIMES','DEFENCE_TECH','GRID_ELECTRICAL','IDX_COUNTRIES','IDX_FACTOR','IDX_MACRO','IDX_STYLE','IDX_THEME_FUNDS','IDX_WORLD','NEOCLOUDS_MINERS','OIL_MIDSTREAM','SOLAR_RENEWABLE']) c
   where not exists (select 1 from public.cohort_tree t where t.cohort = c);
  if x is not null then raise exception 'TR2-NEXT refused: the tree has no node %; nothing was changed.', x; end if;
  select string_agg(distinct ticker, ', ' order by ticker) into x from public.cohort_tree_members
   where ticker in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG') and (status <> 'pending_admission' or source <> 'TR2-NEXT-20261006');
  if x is not null then raise exception 'TR2-NEXT refused: already in the tree, served or put there by another load (%); nothing was changed.', x; end if;
  select string_agg(t.cohort || ' waits for ' || t.spine_fund_next, ', ' order by t.cohort) into x from public.cohort_tree t
   join (values ('CRYPTO_EQUITIES','IBIT'),('CHINA','KWEB'),('GRID_ELECTRICAL','GRID'),('DEFENCE_TECH','SHLD'),('OIL_MIDSTREAM','MLPX'),('BIG_BANKS_BROKERS','KBWB'),('NEOCLOUDS_MINERS','WGMI')) v(cohort, fund) on v.cohort = t.cohort
   where t.spine_fund_next is not null and t.spine_fund_next <> v.fund;
  if x is not null then raise exception 'TR2-NEXT refused: a spine is already promised to another fund (%); nothing was changed.', x; end if;
end $$;
insert into public.cohort_tree_members (cohort,ticker,role,status,near_copy_of,why,source) values
  ('IDX_FACTOR','SPHB','index_fund','pending_admission',null,'the cleanest risk-on / risk-off line there is, from two funds cut out of the same 500 stocks','TR2-NEXT-20261006'),
  ('IDX_MACRO','TIP','index_fund','pending_admission',null,'an inflation-expectations line; today nothing on the board says whether a rate move is about inflation or about growth','TR2-NEXT-20261006'),
  ('IDX_MACRO','IBIT','index_fund','pending_admission',null,'the coin itself, so CRYPTO EQUITIES and NEOCLOUDS & MINERS can be coloured against what drives them','TR2-NEXT-20261006'),
  ('IDX_THEME_FUNDS','ARKK','index_fund','pending_admission',null,'a speculation gauge (ARKK divided by QQQ), and the yardstick for the story-stock block that used to be FRONTIER: space, quantum and eVTOL moved together 0.37 this half-year and have no line of their own','TR2-NEXT-20261006'),
  ('IDX_MACRO','CPER','index_fund','pending_admission',null,'the copper-to-gold line, a growth-versus-fear read that does not use any share price','TR2-NEXT-20261006'),
  ('IDX_MACRO','EMB','index_fund','pending_admission',null,'a second credit line that is about countries, not US companies, so a credit warning can be told apart: home or abroad','TR2-NEXT-20261006'),
  ('IDX_MACRO','FXY','index_fund','pending_admission',null,'the yen on its own; UUP is mostly the euro, so a yen shock is hidden inside it','TR2-NEXT-20261006'),
  ('IDX_WORLD','EMXC','index_fund','pending_admission',null,'splits the emerging-market line in two, so world participation is not one country''s story','TR2-NEXT-20261006'),
  ('IDX_WORLD','VGK','index_fund','pending_admission',null,'the only single line that covers every home country of our 8 European names (NL, GB, SE, BE, CH); EZU leaves out GB, SE and CH','TR2-NEXT-20261006'),
  ('IDX_STYLE','IWO','index_fund','pending_admission',null,'the small-company end of growth against value; today that split exists for large companies only','TR2-NEXT-20261006'),
  ('IDX_STYLE','IWN','index_fund','pending_admission',null,'the small-value corner, where rallies broaden last','TR2-NEXT-20261006'),
  ('IDX_STYLE','IWP','index_fund','pending_admission',null,'the middle row of a 3 by 2 grid (large, mid, small by growth, value) that shows how far down a move reaches','TR2-NEXT-20261006'),
  ('IDX_STYLE','IWS','index_fund','pending_admission',null,'the mid-value box; completes the six-box grid','TR2-NEXT-20261006'),
  ('IDX_COUNTRIES','EWW','index_fund','pending_admission',null,'a second Latin American line and one more country in the world count','TR2-NEXT-20261006'),
  ('IDX_COUNTRIES','EWA','index_fund','pending_admission',null,'a country line for the Australian names in ASIA-PACIFIC and one more country in the world count','TR2-NEXT-20261006'),
  ('IDX_COUNTRIES','EWL','index_fund','pending_admission',null,'a defensive European line and one more country in the world count','TR2-NEXT-20261006'),
  ('IDX_THEME_FUNDS','KWEB','index_fund','pending_admission',null,'the right yardstick for our CHINA cohort, which is mostly internet names (BABA, BIDU, JD, PDD)','TR2-NEXT-20261006'),
  ('IDX_THEME_FUNDS','XME','index_fund','pending_admission',null,'a US line for the steel half of COPPER & STEEL; COPX covers copper only and is mostly foreign','TR2-NEXT-20261006'),
  ('IDX_THEME_FUNDS','GRID','index_fund','pending_admission',null,'a line made for GRID & ELECTRICAL; PAVE, its spine today, is mostly roads, rail and materials','TR2-NEXT-20261006'),
  ('IDX_THEME_FUNDS','SHLD','index_fund','pending_admission',null,'a spine for DEFENCE TECH, which today borrows ITA, a fund dominated by the primes','TR2-NEXT-20261006'),
  ('IDX_THEME_FUNDS','MLPX','index_fund','pending_admission',null,'a spine for OIL MIDSTREAM; all four of our names (WMB, KMI, OKE, TRGP) are in its top six','TR2-NEXT-20261006'),
  ('IDX_THEME_FUNDS','KBWB','index_fund','pending_admission',null,'a pure big-bank line; KBE, served, is equal weight and so is mostly regional banks','TR2-NEXT-20261006'),
  ('IDX_THEME_FUNDS','ICLN','index_fund','pending_admission',null,'widens SOLAR & RENEWABLE beyond solar, as CO1''s spine note asks','TR2-NEXT-20261006'),
  ('IDX_THEME_FUNDS','WGMI','index_fund','pending_admission',null,'the only fund that defines NEOCLOUDS & MINERS (12 names, no fund today)','TR2-NEXT-20261006'),
  ('IDX_THEME_FUNDS','XAR','index_fund','pending_admission',null,'an equal-weight twin for ITA, the same read the Hub already makes for the 11 sectors','TR2-NEXT-20261006'),
  ('IDX_MACRO','UNG','index_fund','pending_admission',null,'the gas price, the one big energy input the board cannot see','TR2-NEXT-20261006'),
  ('CRYPTO_EQUITIES','IBIT','reference','pending_admission',null,'reference line: the open fund this cohort is measured against','TR2-NEXT-20261006'),
  ('CHINA','KWEB','reference','pending_admission',null,'reference line: the open fund this cohort is measured against','TR2-NEXT-20261006'),
  ('COPPER_STEEL','XME','reference','pending_admission',null,'reference line: the open fund this cohort is measured against','TR2-NEXT-20261006'),
  ('GRID_ELECTRICAL','GRID','reference','pending_admission',null,'reference line: the open fund this cohort is measured against','TR2-NEXT-20261006'),
  ('DEFENCE_TECH','SHLD','reference','pending_admission',null,'reference line: the open fund this cohort is measured against','TR2-NEXT-20261006'),
  ('OIL_MIDSTREAM','MLPX','reference','pending_admission',null,'reference line: the open fund this cohort is measured against','TR2-NEXT-20261006'),
  ('BIG_BANKS_BROKERS','KBWB','reference','pending_admission',null,'reference line: the open fund this cohort is measured against','TR2-NEXT-20261006'),
  ('SOLAR_RENEWABLE','ICLN','reference','pending_admission',null,'reference line: the open fund this cohort is measured against','TR2-NEXT-20261006'),
  ('NEOCLOUDS_MINERS','WGMI','reference','pending_admission',null,'reference line: the open fund this cohort is measured against','TR2-NEXT-20261006'),
  ('DEFENCE_PRIMES','XAR','reference','pending_admission',null,'reference line: the open fund this cohort is measured against','TR2-NEXT-20261006')
on conflict (cohort, ticker) do nothing;
update public.cohort_tree t set spine_fund_next = v.fund from (values ('CRYPTO_EQUITIES','IBIT'),('CHINA','KWEB'),('GRID_ELECTRICAL','GRID'),('DEFENCE_TECH','SHLD'),('OIL_MIDSTREAM','MLPX'),('BIG_BANKS_BROKERS','KBWB'),('NEOCLOUDS_MINERS','WGMI')) v(cohort, fund) where t.cohort = v.cohort and t.spine_fund_next is null;
do $$
declare i int; r int; d int; s int; o int;
begin
  select count(*) filter (where role = 'index_fund'), count(*) filter (where role = 'reference'), count(distinct ticker) into i, r, d
    from public.cohort_tree_members where ticker in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG') and status = 'pending_admission' and source = 'TR2-NEXT-20261006';
  select count(*) into o from public.cohort_tree_members where status = 'pending_admission' and ticker not in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG');
  select (select count(*)::int from public.cohort_tree t where (t.cohort, t.spine_fund_next) in (('CRYPTO_EQUITIES','IBIT'),('CHINA','KWEB'),('GRID_ELECTRICAL','GRID'),('DEFENCE_TECH','SHLD'),('OIL_MIDSTREAM','MLPX'),('BIG_BANKS_BROKERS','KBWB'),('NEOCLOUDS_MINERS','WGMI'))) into s;
  if i <> 26 then raise exception 'TR2-NEXT: expected 26 pending index-set rows, found %', i; end if;
  if r <> 10 then raise exception 'TR2-NEXT: expected 10 pending reference rows, found %', r; end if;
  if d <> 26 then raise exception 'TR2-NEXT: expected 26 distinct pending funds, found %', d; end if;
  if s <> 7 then raise exception 'TR2-NEXT: expected 7 spines waiting, found %', s; end if;
  if o <> 0 then raise exception 'TR2-NEXT: % pending rows belong to other funds', o; end if;
end $$;
commit;
select 'TR2-NEXT pending' as step, count(*) filter (where role = 'index_fund')::int as index_fund_rows, count(*) filter (where role = 'reference')::int as reference_rows,
  count(distinct ticker)::int as pending_funds, (select count(*)::int from public.cohort_tree t where (t.cohort, t.spine_fund_next) in (('CRYPTO_EQUITIES','IBIT'),('CHINA','KWEB'),('GRID_ELECTRICAL','GRID'),('DEFENCE_TECH','SHLD'),('OIL_MIDSTREAM','MLPX'),('BIG_BANKS_BROKERS','KBWB'),('NEOCLOUDS_MINERS','WGMI'))) as spines_waiting
  from public.cohort_tree_members where ticker in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG') and status = 'pending_admission';
