-- 2026-09-24 · M39 ALLOCATION — keep Alan's own swipes.
--
-- WHY. Alan, 23 Sep: "the point is that i have to have an operator input gameified
-- playful tinder like process of going through opportunities that allocation and its
-- sub tools say and we build my personal preferences". The allocation page now deals
-- the opportunities as a card stack: right is interest, left is a pass, up is a watch.
-- Those choices are the only input on the page that is his and not the market's, so
-- they have to outlive a browser.
--
-- WHAT THIS DOES. One new table. Nothing is renamed, dropped or overwritten, and no
-- existing row is touched. The page writes through the operator-write function, the
-- same path the board uses for favourites, so the anon key never writes this table
-- directly and row-level security stays closed.
--
-- ROLLBACK is the last statement in this file (commented out).

create table if not exists public.allocation_operator_votes (
  id           bigint generated by default as identity primary key,
  owner_id     uuid        not null default '00000000-0000-0000-0000-000000000000'::uuid,
  ticker       text        not null,
  choice       text        not null check (choice in ('right', 'left', 'up')),
  -- what the page was showing when the choice was made, so a vote can be read back in
  -- context instead of being a bare thumbs-up with no idea what it was aimed at
  sector       text        null,
  cohorts      text[]      null,
  kinds        text[]      null,
  score        numeric     null,
  quality      integer     null,
  dist_200d    numeric     null,
  voted_at     timestamptz not null default now(),
  created_at   timestamptz not null default now()
);

comment on table public.allocation_operator_votes is
  'M39 — the operator''s own swipes on the allocation page: right = interested, left = pass, up = watch. Written by the operator-write edge function, read by the allocation page to weight its own ordering.';

create index if not exists allocation_operator_votes_owner_ticker_idx
  on public.allocation_operator_votes (owner_id, ticker, voted_at desc);
create index if not exists allocation_operator_votes_voted_at_idx
  on public.allocation_operator_votes (voted_at desc);

alter table public.allocation_operator_votes enable row level security;

-- Read is open to the anon role, exactly like hub_favorites: the page has to be able to
-- show what it has learned. Writing stays with the service role, which is what the
-- operator-write function runs as.
drop policy if exists allocation_operator_votes_read on public.allocation_operator_votes;
create policy allocation_operator_votes_read
  on public.allocation_operator_votes for select
  to anon, authenticated
  using (true);

-- ROLLBACK (removes exactly what this migration added, nothing else):
-- drop policy if exists allocation_operator_votes_read on public.allocation_operator_votes;
-- drop table if exists public.allocation_operator_votes;

-- THE ONE PIECE THIS MIGRATION CANNOT CARRY: the operator-write function does not live
-- in this repository, so it has to learn one new action. Until it does, the page keeps
-- every swipe on the device and says how many are waiting. The case is this, beside the
-- existing fav_add / fav_remove / cohort_set / weights_save cases:
--
--   case "allocation_vote":
--     await sb.from("allocation_operator_votes").insert({
--       ticker: String(body.ticker).toUpperCase(),
--       choice: body.choice,                       // 'right' | 'left' | 'up'
--       sector: body.sector ?? null,
--       cohorts: body.cohorts ?? null,
--       kinds: body.kinds ?? null,
--       score: body.score ?? null,
--       quality: body.quality ?? null,
--       dist_200d: body.dist_200d ?? null,
--       voted_at: body.at ?? new Date().toISOString(),
--     });
--     return ok();
