-- 2026-10-03 · F1 (full Hub treatment) · FUNDAMENTALS / FINANCIALS / CAPITAL / REVENUE: fmp-fundamentals run for 69 companies with no statements
-- fmp-fundamentals walks fmp_full_universe 10 names every 6 h (cron 10), so these v3 names wait up to ~13 days (U4b B2). FMP answers for every one (counts read 2026-10-03T16:14:08.827Z).
-- ADDITIVE (pre-approved class, F1 brief): nothing is deleted or overwritten. Rollback beside this file (_ROLLBACK).
-- Built by deliverables/20261003/f1-full-treatment/build-loads.mjs from reads taken 2026-10-03T16:19:40.557Z.
-- HOW: the function's own run, one call per 10 names, reusing cron job 10's stored request headers INSIDE the database — no key is copied anywhere.
-- Each call deletes nothing these names have (they have no rows) and writes fundamentals_history, balance_history, cashflow_history, ratios_history and
-- the fundamentals row. Run the statements below one at a time, ~2 minutes apart (the function holds a 3-minute busy lock only in offset mode).
select net.http_post(url := 'https://wadinxqplrggagkvrdag.supabase.co/functions/v1/fmp-fundamentals?sym=ACMR,ACN,ALNY,AMRC,ARGX,ATI,AXON,BIIB,BTSG,CATY', headers := (regexp_match(command, 'headers:=''([^'']+)''::jsonb'))[1]::jsonb, timeout_milliseconds := 150000) from cron.job where jobid = 10;
select net.http_post(url := 'https://wadinxqplrggagkvrdag.supabase.co/functions/v1/fmp-fundamentals?sym=CI,CIEN,CLF,CNP,CVBF,DHI,DXCM,EAT,ENPH,ENTG', headers := (regexp_match(command, 'headers:=''([^'']+)''::jsonb'))[1]::jsonb, timeout_milliseconds := 150000) from cron.job where jobid = 10;
select net.http_post(url := 'https://wadinxqplrggagkvrdag.supabase.co/functions/v1/fmp-fundamentals?sym=EVRG,EW,FE,FIS,FN,FORM,FROG,FTI,FTNT,FULT', headers := (regexp_match(command, 'headers:=''([^'']+)''::jsonb'))[1]::jsonb, timeout_milliseconds := 150000) from cron.job where jobid = 10;
select net.http_post(url := 'https://wadinxqplrggagkvrdag.supabase.co/functions/v1/fmp-fundamentals?sym=GDS,GEHC,GFS,GKOS,GPN,HALO,HCA,HEI,RHP,RIVN', headers := (regexp_match(command, 'headers:=''([^'']+)''::jsonb'))[1]::jsonb, timeout_milliseconds := 150000) from cron.job where jobid = 10;
select net.http_post(url := 'https://wadinxqplrggagkvrdag.supabase.co/functions/v1/fmp-fundamentals?sym=RMD,RS,RUN,RVMD,S,SEDG,SFNC,SM,SNAP,SNX', headers := (regexp_match(command, 'headers:=''([^'']+)''::jsonb'))[1]::jsonb, timeout_milliseconds := 150000) from cron.job where jobid = 10;
select net.http_post(url := 'https://wadinxqplrggagkvrdag.supabase.co/functions/v1/fmp-fundamentals?sym=SWKS,SYF,TER,TGTX,TLN,TOST,TRMK,TWLO,TWST,TXG', headers := (regexp_match(command, 'headers:=''([^'']+)''::jsonb'))[1]::jsonb, timeout_milliseconds := 150000) from cron.job where jobid = 10;
select net.http_post(url := 'https://wadinxqplrggagkvrdag.supabase.co/functions/v1/fmp-fundamentals?sym=UAL,UCTT,UI,UMBF,USFD,VSAT,XPEV,XPO,XYZ', headers := (regexp_match(command, 'headers:=''([^'']+)''::jsonb'))[1]::jsonb, timeout_milliseconds := 150000) from cron.job where jobid = 10;
-- READ BACK: select ticker, count(*) from public.fundamentals_history where ticker in ($f1$ACMR$f1$, $f1$ACN$f1$, $f1$ALNY$f1$, $f1$AMRC$f1$, $f1$ARGX$f1$, $f1$ATI$f1$, $f1$AXON$f1$, $f1$BIIB$f1$, $f1$BTSG$f1$, $f1$CATY$f1$, $f1$CI$f1$, $f1$CIEN$f1$, $f1$CLF$f1$, $f1$CNP$f1$, $f1$CVBF$f1$, $f1$DHI$f1$, $f1$DXCM$f1$, $f1$EAT$f1$, $f1$ENPH$f1$, $f1$ENTG$f1$, $f1$EVRG$f1$, $f1$EW$f1$, $f1$FE$f1$, $f1$FIS$f1$, $f1$FN$f1$, $f1$FORM$f1$, $f1$FROG$f1$, $f1$FTI$f1$, $f1$FTNT$f1$, $f1$FULT$f1$, $f1$GDS$f1$, $f1$GEHC$f1$, $f1$GFS$f1$, $f1$GKOS$f1$, $f1$GPN$f1$, $f1$HALO$f1$, $f1$HCA$f1$, $f1$HEI$f1$, $f1$RHP$f1$, $f1$RIVN$f1$, $f1$RMD$f1$, $f1$RS$f1$, $f1$RUN$f1$, $f1$RVMD$f1$, $f1$S$f1$, $f1$SEDG$f1$, $f1$SFNC$f1$, $f1$SM$f1$, $f1$SNAP$f1$, $f1$SNX$f1$, $f1$SWKS$f1$, $f1$SYF$f1$, $f1$TER$f1$, $f1$TGTX$f1$, $f1$TLN$f1$, $f1$TOST$f1$, $f1$TRMK$f1$, $f1$TWLO$f1$, $f1$TWST$f1$, $f1$TXG$f1$, $f1$UAL$f1$, $f1$UCTT$f1$, $f1$UI$f1$, $f1$UMBF$f1$, $f1$USFD$f1$, $f1$VSAT$f1$, $f1$XPEV$f1$, $f1$XPO$f1$, $f1$XYZ$f1$) group by 1 order by 1;
