-- GENERATED by scripts/build-canonical-universe.mjs --retire (provider repo) for the set c0f72aab4110b1587923523e5ee1b54e2e4e024dfc927fa431ffe7695b2e339e
-- (589 names). Do not edit by hand: re-run the builder. Needs Alan's word: it changes what the Hub shows.
update public.tickers set active = true, retired_at = null, retired_reason = null where ticker in ('QRVO') and active = false;
do $$
declare n int;
begin
  select count(*) into n from public.tickers where active = true and (type is null or type not in ('crypto','future','index','rate'));
  if n <> 590 then raise exception 'retirement rollback: expected 590 active equity names, found %', n; end if;
end $$;
