-- TR2 (6 Oct 2026) · THE TREE REVISED ON ALAN'S NOTES — rollback. GENERATED by scripts/cohort-tree-revise-sql.mjs;
-- do not edit by hand.
-- The exact inverse of 20261006_tr2_tree_revision.sql, row by row: the 10 added member rows go, the 60 moved rows
-- go back, the 5 removed nodes return from the stash with their original source and loaded_at, the 20 changed
-- nodes get TR1's values back, the 19 added nodes go. Then it drops what the forward file created: three tables,
-- one check, five columns. ONE TRANSACTION. Not applied → it says so and does nothing; safe to run twice.
-- It leaves status, spine_fund and spine_fund_next of every row the revision did not change exactly as it finds
-- them: if TR1's after-admission step has run, the result is TR1's tree after that step.
-- Every step counts its rows and refuses the whole rollback (changing nothing) if the count is not the generator's.
begin;
do $$
declare
  k int; n int; m int; pending_at_entry int; drift text;
begin
  if not exists (select 1 from public.cohort_tree where cohort = 'SECTOR_XLK') then
    raise notice 'TR2 rollback: the revision is not applied (no row SECTOR_XLK). Nothing changed.';
    return;
  end if;
  select count(*) into pending_at_entry from public.cohort_tree_members where status = 'pending_admission';

  -- the links and candidates go first: they hold the foreign keys that pin the revised rows
  delete from public.cohort_tree_fund_links;
  get diagnostics k = row_count;
  if k <> 357 then raise exception 'TR2 rollback refused, nothing changed: expected 357 links, found %', k; end if;
  delete from public.cohort_tree_candidates;
  get diagnostics k = row_count;
  if k <> 75 then raise exception 'TR2 rollback refused, nothing changed: expected 75 candidates, found %', k; end if;

  -- the 10 member rows the revision added
  delete from public.cohort_tree_members x using (values
    ('PACKAGED_FOODS'::text,'XLP'::text),
    ('BEVERAGES','XLP'),
    ('HOUSEHOLD_PERSONAL','XLP'),
    ('TOBACCO','XLP'),
    ('FOOD_DISTRIBUTION','XLP'),
    ('AGRI_PRODUCTS','XLP'),
    ('STAPLES_RETAIL','WMT'),
    ('STAPLES_RETAIL','COST'),
    ('STAPLES_RETAIL','TGT'),
    ('STAPLES_RETAIL','XLP')
  ) as v(cohort, ticker) where x.cohort = v.cohort and x.ticker = v.ticker and x.source = 'TR2-20261006';
  get diagnostics k = row_count;
  if k <> 10 then raise exception 'TR2 rollback refused, nothing changed: expected to take out 10 added member rows, found %', k; end if;

  -- the 5 removed nodes come back from the stash, with the source and loaded_at they had
  insert into public.cohort_tree (cohort,label,kind,parent_1,parent_2,spine,spine_fund,spine_fund_next,source,loaded_at)
  select cohort,label,kind,parent_1,parent_2,spine,spine_fund,spine_fund_next,source,loaded_at from public.cohort_tree_tr2_removed where cohort in ('FRONTIER','IDX_SECTOR_SPDR','IDX_SECTOR_EQUAL_WEIGHT','IDX_SECTOR_VANGUARD','IDX_SECTOR_ISHARES');
  get diagnostics k = row_count;
  if k <> 5 then raise exception 'TR2 rollback refused, nothing changed: expected 5 rows in the stash, found %', k; end if;

  -- the 60 moved member rows go back where TR1 put them
  update public.cohort_tree_members x set cohort = v.to_cohort
  from (values
    ('ADM'::text,'member'::text,'AGRI_PRODUCTS'::text,'STAPLES'::text),
    ('BYND','member','PACKAGED_FOODS','STAPLES'),
    ('CL','member','HOUSEHOLD_PERSONAL','STAPLES'),
    ('KDP','member','BEVERAGES','STAPLES'),
    ('KMB','member','HOUSEHOLD_PERSONAL','STAPLES'),
    ('KO','member','BEVERAGES','STAPLES'),
    ('KR','member','STAPLES_RETAIL','STAPLES'),
    ('KVUE','member','HOUSEHOLD_PERSONAL','STAPLES'),
    ('MDLZ','member','PACKAGED_FOODS','STAPLES'),
    ('MNST','member','BEVERAGES','STAPLES'),
    ('MO','member','TOBACCO','STAPLES'),
    ('PEP','member','BEVERAGES','STAPLES'),
    ('PG','member','HOUSEHOLD_PERSONAL','STAPLES'),
    ('PM','member','TOBACCO','STAPLES'),
    ('SYY','member','FOOD_DISTRIBUTION','STAPLES'),
    ('USFD','member','FOOD_DISTRIBUTION','STAPLES'),
    ('XLK','index_fund','SECTOR_XLK','IDX_SECTOR_SPDR'),
    ('RSPT','index_fund','SECTOR_XLK','IDX_SECTOR_EQUAL_WEIGHT'),
    ('VGT','index_fund','SECTOR_XLK','IDX_SECTOR_VANGUARD'),
    ('IYW','index_fund','SECTOR_XLK','IDX_SECTOR_ISHARES'),
    ('XLF','index_fund','SECTOR_XLF','IDX_SECTOR_SPDR'),
    ('RSPF','index_fund','SECTOR_XLF','IDX_SECTOR_EQUAL_WEIGHT'),
    ('VFH','index_fund','SECTOR_XLF','IDX_SECTOR_VANGUARD'),
    ('IYF','index_fund','SECTOR_XLF','IDX_SECTOR_ISHARES'),
    ('XLE','index_fund','SECTOR_XLE','IDX_SECTOR_SPDR'),
    ('RSPG','index_fund','SECTOR_XLE','IDX_SECTOR_EQUAL_WEIGHT'),
    ('VDE','index_fund','SECTOR_XLE','IDX_SECTOR_VANGUARD'),
    ('IYE','index_fund','SECTOR_XLE','IDX_SECTOR_ISHARES'),
    ('XLV','index_fund','SECTOR_XLV','IDX_SECTOR_SPDR'),
    ('RSPH','index_fund','SECTOR_XLV','IDX_SECTOR_EQUAL_WEIGHT'),
    ('VHT','index_fund','SECTOR_XLV','IDX_SECTOR_VANGUARD'),
    ('IYH','index_fund','SECTOR_XLV','IDX_SECTOR_ISHARES'),
    ('XLI','index_fund','SECTOR_XLI','IDX_SECTOR_SPDR'),
    ('RSPN','index_fund','SECTOR_XLI','IDX_SECTOR_EQUAL_WEIGHT'),
    ('VIS','index_fund','SECTOR_XLI','IDX_SECTOR_VANGUARD'),
    ('IYJ','index_fund','SECTOR_XLI','IDX_SECTOR_ISHARES'),
    ('XLY','index_fund','SECTOR_XLY','IDX_SECTOR_SPDR'),
    ('RSPD','index_fund','SECTOR_XLY','IDX_SECTOR_EQUAL_WEIGHT'),
    ('VCR','index_fund','SECTOR_XLY','IDX_SECTOR_VANGUARD'),
    ('IYC','index_fund','SECTOR_XLY','IDX_SECTOR_ISHARES'),
    ('XLP','index_fund','SECTOR_XLP','IDX_SECTOR_SPDR'),
    ('RSPS','index_fund','SECTOR_XLP','IDX_SECTOR_EQUAL_WEIGHT'),
    ('VDC','index_fund','SECTOR_XLP','IDX_SECTOR_VANGUARD'),
    ('IYK','index_fund','SECTOR_XLP','IDX_SECTOR_ISHARES'),
    ('XLU','index_fund','SECTOR_XLU','IDX_SECTOR_SPDR'),
    ('RSPU','index_fund','SECTOR_XLU','IDX_SECTOR_EQUAL_WEIGHT'),
    ('VPU','index_fund','SECTOR_XLU','IDX_SECTOR_VANGUARD'),
    ('IDU','index_fund','SECTOR_XLU','IDX_SECTOR_ISHARES'),
    ('XLB','index_fund','SECTOR_XLB','IDX_SECTOR_SPDR'),
    ('RSPM','index_fund','SECTOR_XLB','IDX_SECTOR_EQUAL_WEIGHT'),
    ('VAW','index_fund','SECTOR_XLB','IDX_SECTOR_VANGUARD'),
    ('IYM','index_fund','SECTOR_XLB','IDX_SECTOR_ISHARES'),
    ('XLRE','index_fund','SECTOR_XLRE','IDX_SECTOR_SPDR'),
    ('RSPR','index_fund','SECTOR_XLRE','IDX_SECTOR_EQUAL_WEIGHT'),
    ('VNQ','index_fund','SECTOR_XLRE','IDX_SECTOR_VANGUARD'),
    ('IYR','index_fund','SECTOR_XLRE','IDX_SECTOR_ISHARES'),
    ('XLC','index_fund','SECTOR_XLC','IDX_SECTOR_SPDR'),
    ('RSPC','index_fund','SECTOR_XLC','IDX_SECTOR_EQUAL_WEIGHT'),
    ('VOX','index_fund','SECTOR_XLC','IDX_SECTOR_VANGUARD'),
    ('IYZ','index_fund','SECTOR_XLC','IDX_SECTOR_ISHARES')
  ) as v(ticker, role, from_cohort, to_cohort)
  where x.cohort = v.from_cohort and x.ticker = v.ticker and x.role = v.role;
  get diagnostics k = row_count;
  if k <> 60 then raise exception 'TR2 rollback refused, nothing changed: expected to move 60 member rows back, moved %', k; end if;

  -- the 20 changed nodes: TR1's values back, only in the columns the revision changed
  update public.cohort_tree set parent_1 = 'MARKET' where cohort = 'AI';
  update public.cohort_tree set parent_2 = null where cohort = 'SOFTWARE_INTERNET';
  update public.cohort_tree set parent_1 = 'MARKET', parent_2 = null where cohort = 'ENERGY_POWER';
  update public.cohort_tree set parent_1 = 'MARKET' where cohort = 'FINANCE';
  update public.cohort_tree set parent_1 = 'MARKET' where cohort = 'HEALTH';
  update public.cohort_tree set parent_1 = 'MARKET' where cohort = 'MATERIALS_METALS';
  update public.cohort_tree set parent_1 = 'MARKET' where cohort = 'INDUSTRIAL';
  update public.cohort_tree set parent_1 = 'MARKET', parent_2 = null where cohort = 'CONSUMER';
  update public.cohort_tree set parent_1 = 'MARKET', parent_2 = null where cohort = 'CRYPTO';
  update public.cohort_tree set parent_1 = 'MARKET' where cohort = 'INTERNATIONAL';
  update public.cohort_tree set label = 'INDEX LAYER (reference lines)' where cohort = 'INDEX_LAYER';
  update public.cohort_tree set label = 'TECHNOLOGY (sector)', parent_1 = 'MARKET', parent_2 = null where cohort = 'TECH';
  update public.cohort_tree set label = 'REAL ESTATE (sector)', parent_1 = 'MARKET' where cohort = 'REAL_ESTATE';
  update public.cohort_tree set parent_1 = 'FRONTIER' where cohort = 'SPACE';
  update public.cohort_tree set parent_1 = 'FRONTIER' where cohort = 'QUANTUM';
  update public.cohort_tree set parent_1 = 'FRONTIER' where cohort = 'AUTONOMY_EVTOL';
  update public.cohort_tree set parent_1 = 'FRONTIER', parent_2 = 'INDUSTRIAL' where cohort = 'DEFENCE_TECH';
  update public.cohort_tree set parent_1 = 'MARKET' where cohort = 'MAG7';
  update public.cohort_tree set parent_1 = 'INDUSTRIAL' where cohort = 'DEFENCE_PRIMES';
  update public.cohort_tree set kind = 'cohort', parent_2 = null, spine = 'FMP Consumer Defensive industries minus the discount stores (which sit in RETAIL) (XLP/VDC spine)', spine_fund = 'XLP' where cohort = 'STAPLES';

  -- the 19 added nodes go only when nothing is left in them or hanging from them
  select count(*) into k from public.cohort_tree_members where cohort in ('SECTOR_XLK','SECTOR_XLC','SECTOR_XLY','SECTOR_XLP','SECTOR_XLF','SECTOR_XLV','SECTOR_XLI','SECTOR_XLE','SECTOR_XLU','SECTOR_XLB','SECTOR_XLRE','AEROSPACE_DEFENCE','PACKAGED_FOODS','BEVERAGES','HOUSEHOLD_PERSONAL','TOBACCO','FOOD_DISTRIBUTION','AGRI_PRODUCTS','STAPLES_RETAIL');
  if k <> 0 then raise exception 'TR2 rollback refused, nothing changed: % member rows still sit in a node the revision added', k; end if;
  select count(*) into k from public.cohort_tree where (parent_1 in ('SECTOR_XLK','SECTOR_XLC','SECTOR_XLY','SECTOR_XLP','SECTOR_XLF','SECTOR_XLV','SECTOR_XLI','SECTOR_XLE','SECTOR_XLU','SECTOR_XLB','SECTOR_XLRE','AEROSPACE_DEFENCE','PACKAGED_FOODS','BEVERAGES','HOUSEHOLD_PERSONAL','TOBACCO','FOOD_DISTRIBUTION','AGRI_PRODUCTS','STAPLES_RETAIL') or parent_2 in ('SECTOR_XLK','SECTOR_XLC','SECTOR_XLY','SECTOR_XLP','SECTOR_XLF','SECTOR_XLV','SECTOR_XLI','SECTOR_XLE','SECTOR_XLU','SECTOR_XLB','SECTOR_XLRE','AEROSPACE_DEFENCE','PACKAGED_FOODS','BEVERAGES','HOUSEHOLD_PERSONAL','TOBACCO','FOOD_DISTRIBUTION','AGRI_PRODUCTS','STAPLES_RETAIL')) and cohort not in ('SECTOR_XLK','SECTOR_XLC','SECTOR_XLY','SECTOR_XLP','SECTOR_XLF','SECTOR_XLV','SECTOR_XLI','SECTOR_XLE','SECTOR_XLU','SECTOR_XLB','SECTOR_XLRE','AEROSPACE_DEFENCE','PACKAGED_FOODS','BEVERAGES','HOUSEHOLD_PERSONAL','TOBACCO','FOOD_DISTRIBUTION','AGRI_PRODUCTS','STAPLES_RETAIL');
  if k <> 0 then raise exception 'TR2 rollback refused, nothing changed: % nodes still hang from a node the revision added', k; end if;
  delete from public.cohort_tree where cohort in ('SECTOR_XLK','SECTOR_XLC','SECTOR_XLY','SECTOR_XLP','SECTOR_XLF','SECTOR_XLV','SECTOR_XLI','SECTOR_XLE','SECTOR_XLU','SECTOR_XLB','SECTOR_XLRE','AEROSPACE_DEFENCE','PACKAGED_FOODS','BEVERAGES','HOUSEHOLD_PERSONAL','TOBACCO','FOOD_DISTRIBUTION','AGRI_PRODUCTS','STAPLES_RETAIL');
  get diagnostics k = row_count;
  if k <> 19 then raise exception 'TR2 rollback refused, nothing changed: expected to remove 19 added nodes, removed %', k; end if;

  -- PROOF
  set constraints all immediate;   -- the parent and member keys are checked here, not at commit
  select count(*) into n from public.cohort_tree;
  select count(*) into m from public.cohort_tree_members;
  if n <> 91 or m <> 771 then raise exception 'TR2 rollback proof: expected 91 nodes and 771 member rows, found % and %', n, m; end if;
  if not exists (select 1 from public.cohort_tree where cohort = 'FRONTIER') then raise exception 'TR2 rollback proof: FRONTIER is not back'; end if;
  select count(*) into k from public.cohort_tree where parent_1 is null;
  if k <> 1 then raise exception 'TR2 rollback proof: expected one root, found %', k; end if;
  select string_agg(format('%s.%s is %s (TR1 loaded %s)', b.cohort, b.col, coalesce(quote_literal(to_jsonb(t) ->> b.col), 'null'), coalesce(quote_literal(b.val), 'null')), '; ') into drift
  from (values
    ('AI'::text,'label'::text,'AI'::text),
    ('AI','kind','heading'),
    ('AI','parent_1','MARKET'),
    ('AI','parent_2',null),
    ('AI','spine','Alan: ''we have AI''. The theme heading; its cohorts also hang under the sector they came from.'),
    ('AI','spine_fund',null),
    ('AI','spine_fund_next',null),
    ('SOFTWARE_INTERNET','label','SOFTWARE & INTERNET'),
    ('SOFTWARE_INTERNET','kind','heading'),
    ('SOFTWARE_INTERNET','parent_1','TECH'),
    ('SOFTWARE_INTERNET','parent_2',null),
    ('SOFTWARE_INTERNET','spine','GICS: Technology / Communication Services'),
    ('SOFTWARE_INTERNET','spine_fund',null),
    ('SOFTWARE_INTERNET','spine_fund_next',null),
    ('ENERGY_POWER','label','ENERGY & POWER'),
    ('ENERGY_POWER','kind','heading'),
    ('ENERGY_POWER','parent_1','MARKET'),
    ('ENERGY_POWER','parent_2',null),
    ('ENERGY_POWER','spine','Alan: ''AI powertrain … is a mix of AI and energy'''),
    ('ENERGY_POWER','spine_fund',null),
    ('ENERGY_POWER','spine_fund_next',null),
    ('FINANCE','label','FINANCE'),
    ('FINANCE','kind','heading'),
    ('FINANCE','parent_1','MARKET'),
    ('FINANCE','parent_2',null),
    ('FINANCE','spine','GICS: Financial Services'),
    ('FINANCE','spine_fund',null),
    ('FINANCE','spine_fund_next',null),
    ('HEALTH','label','HEALTH'),
    ('HEALTH','kind','heading'),
    ('HEALTH','parent_1','MARKET'),
    ('HEALTH','parent_2',null),
    ('HEALTH','spine','GICS: Healthcare'),
    ('HEALTH','spine_fund',null),
    ('HEALTH','spine_fund_next',null),
    ('MATERIALS_METALS','label','MATERIALS & METALS'),
    ('MATERIALS_METALS','kind','heading'),
    ('MATERIALS_METALS','parent_1','MARKET'),
    ('MATERIALS_METALS','parent_2',null),
    ('MATERIALS_METALS','spine','GICS: Basic Materials'),
    ('MATERIALS_METALS','spine_fund',null),
    ('MATERIALS_METALS','spine_fund_next',null),
    ('INDUSTRIAL','label','INDUSTRIAL'),
    ('INDUSTRIAL','kind','heading'),
    ('INDUSTRIAL','parent_1','MARKET'),
    ('INDUSTRIAL','parent_2',null),
    ('INDUSTRIAL','spine','GICS: Industrials'),
    ('INDUSTRIAL','spine_fund',null),
    ('INDUSTRIAL','spine_fund_next',null),
    ('CONSUMER','label','CONSUMER'),
    ('CONSUMER','kind','heading'),
    ('CONSUMER','parent_1','MARKET'),
    ('CONSUMER','parent_2',null),
    ('CONSUMER','spine','GICS: Consumer Cyclical / Defensive / Communication'),
    ('CONSUMER','spine_fund',null),
    ('CONSUMER','spine_fund_next',null),
    ('CRYPTO','label','CRYPTO'),
    ('CRYPTO','kind','heading'),
    ('CRYPTO','parent_1','MARKET'),
    ('CRYPTO','parent_2',null),
    ('CRYPTO','spine','GICS: none (coins + equities)'),
    ('CRYPTO','spine_fund',null),
    ('CRYPTO','spine_fund_next',null),
    ('INTERNATIONAL','label','INTERNATIONAL'),
    ('INTERNATIONAL','kind','heading'),
    ('INTERNATIONAL','parent_1','MARKET'),
    ('INTERNATIONAL','parent_2',null),
    ('INTERNATIONAL','spine','INTL split by region and listing; the index funds of each region are its reference lines'),
    ('INTERNATIONAL','spine_fund',null),
    ('INTERNATIONAL','spine_fund_next',null),
    ('INDEX_LAYER','label','INDEX LAYER (reference lines)'),
    ('INDEX_LAYER','kind','heading'),
    ('INDEX_LAYER','parent_1','MARKET'),
    ('INDEX_LAYER','parent_2',null),
    ('INDEX_LAYER','spine','GICS: none'),
    ('INDEX_LAYER','spine_fund',null),
    ('INDEX_LAYER','spine_fund_next',null),
    ('TECH','label','TECHNOLOGY (sector)'),
    ('TECH','kind','heading'),
    ('TECH','parent_1','MARKET'),
    ('TECH','parent_2',null),
    ('TECH','spine','GICS: Technology'),
    ('TECH','spine_fund',null),
    ('TECH','spine_fund_next',null),
    ('REAL_ESTATE','label','REAL ESTATE (sector)'),
    ('REAL_ESTATE','kind','heading'),
    ('REAL_ESTATE','parent_1','MARKET'),
    ('REAL_ESTATE','parent_2',null),
    ('REAL_ESTATE','spine','GICS: Real Estate'),
    ('REAL_ESTATE','spine_fund',null),
    ('REAL_ESTATE','spine_fund_next',null),
    ('SPACE','label','SPACE'),
    ('SPACE','kind','cohort'),
    ('SPACE','parent_1','FRONTIER'),
    ('SPACE','parent_2',null),
    ('SPACE','spine','ARKX holdings ∩ ours + FMP ''Aerospace & Defense'' satellite/launch names'),
    ('SPACE','spine_fund','ARKX'),
    ('SPACE','spine_fund_next',null),
    ('QUANTUM','label','QUANTUM'),
    ('QUANTUM','kind','cohort'),
    ('QUANTUM','parent_1','FRONTIER'),
    ('QUANTUM','parent_2',null),
    ('QUANTUM','spine','QTUM holdings, pure-play subset (QTUM also holds enablers such as NVDA, which stay home)'),
    ('QUANTUM','spine_fund','QTUM'),
    ('QUANTUM','spine_fund_next',null),
    ('AUTONOMY_EVTOL','label','AUTONOMY, eVTOL & DRONES'),
    ('AUTONOMY_EVTOL','kind','cohort'),
    ('AUTONOMY_EVTOL','parent_1','FRONTIER'),
    ('AUTONOMY_EVTOL','parent_2',null),
    ('AUTONOMY_EVTOL','spine','FMP ''Aerospace & Defense'' + ''Airlines'' eVTOL names and the autonomy names in THEMATIC'),
    ('AUTONOMY_EVTOL','spine_fund',null),
    ('AUTONOMY_EVTOL','spine_fund_next',null),
    ('DEFENCE_TECH','label','DEFENCE TECH'),
    ('DEFENCE_TECH','kind','cohort'),
    ('DEFENCE_TECH','parent_1','FRONTIER'),
    ('DEFENCE_TECH','parent_2','INDUSTRIAL'),
    ('DEFENCE_TECH','spine','the new-generation defence names (drones, software, sensors) — ITA''s small end plus PLTR/AXON'),
    ('DEFENCE_TECH','spine_fund','ITA'),
    ('DEFENCE_TECH','spine_fund_next',null),
    ('MAG7','label','MAGNIFICENT 7'),
    ('MAG7','kind','cohort'),
    ('MAG7','parent_1','MARKET'),
    ('MAG7','parent_2',null),
    ('MAG7','spine','MAGS (Roundhill Magnificent Seven ETF) holdings — the seven, both Alphabet lines'),
    ('MAG7','spine_fund','MAGS'),
    ('MAG7','spine_fund_next',null),
    ('DEFENCE_PRIMES','label','AEROSPACE & DEFENCE PRIMES'),
    ('DEFENCE_PRIMES','kind','cohort'),
    ('DEFENCE_PRIMES','parent_1','INDUSTRIAL'),
    ('DEFENCE_PRIMES','parent_2',null),
    ('DEFENCE_PRIMES','spine','ITA holdings ∩ ours, the primes and their suppliers (FMP ''Aerospace & Defense'' minus space/eVTOL/drones)'),
    ('DEFENCE_PRIMES','spine_fund','ITA'),
    ('DEFENCE_PRIMES','spine_fund_next',null),
    ('STAPLES','label','CONSUMER STAPLES'),
    ('STAPLES','kind','cohort'),
    ('STAPLES','parent_1','CONSUMER'),
    ('STAPLES','parent_2',null),
    ('STAPLES','spine','FMP Consumer Defensive industries minus the discount stores (which sit in RETAIL) (XLP/VDC spine)'),
    ('STAPLES','spine_fund','XLP'),
    ('STAPLES','spine_fund_next',null),
    ('FRONTIER','label','FRONTIER'),
    ('FRONTIER','kind','heading'),
    ('FRONTIER','parent_1','MARKET'),
    ('FRONTIER','parent_2',null),
    ('FRONTIER','spine','THEMATIC split by topic: space, quantum, autonomy, defence tech'),
    ('FRONTIER','spine_fund',null),
    ('FRONTIER','spine_fund_next',null),
    ('IDX_SECTOR_SPDR','label','SPDR SECTORS (the keep)'),
    ('IDX_SECTOR_SPDR','kind','index'),
    ('IDX_SECTOR_SPDR','parent_1','IDX_SECTOR_FUNDS'),
    ('IDX_SECTOR_SPDR','parent_2',null),
    ('IDX_SECTOR_SPDR','spine','the eleven S&P 500 sector funds the Hub compares against today'),
    ('IDX_SECTOR_SPDR','spine_fund',null),
    ('IDX_SECTOR_SPDR','spine_fund_next',null),
    ('IDX_SECTOR_EQUAL_WEIGHT','label','EQUAL-WEIGHT SECTORS'),
    ('IDX_SECTOR_EQUAL_WEIGHT','kind','index'),
    ('IDX_SECTOR_EQUAL_WEIGHT','parent_1','IDX_SECTOR_FUNDS'),
    ('IDX_SECTOR_EQUAL_WEIGHT','parent_2',null),
    ('IDX_SECTOR_EQUAL_WEIGHT','spine','Invesco: the same sectors with every name counted the same'),
    ('IDX_SECTOR_EQUAL_WEIGHT','spine_fund',null),
    ('IDX_SECTOR_EQUAL_WEIGHT','spine_fund_next',null),
    ('IDX_SECTOR_VANGUARD','label','VANGUARD SECTORS (copies)'),
    ('IDX_SECTOR_VANGUARD','kind','index'),
    ('IDX_SECTOR_VANGUARD','parent_1','IDX_SECTOR_FUNDS'),
    ('IDX_SECTOR_VANGUARD','parent_2',null),
    ('IDX_SECTOR_VANGUARD','spine','near-copies of the SPDR eleven; kept as second opinions, not as separate lines'),
    ('IDX_SECTOR_VANGUARD','spine_fund',null),
    ('IDX_SECTOR_VANGUARD','spine_fund_next',null),
    ('IDX_SECTOR_ISHARES','label','iSHARES SECTORS (copies)'),
    ('IDX_SECTOR_ISHARES','kind','index'),
    ('IDX_SECTOR_ISHARES','parent_1','IDX_SECTOR_FUNDS'),
    ('IDX_SECTOR_ISHARES','parent_2',null),
    ('IDX_SECTOR_ISHARES','spine','near-copies of the SPDR eleven, except IYZ (telecom only)'),
    ('IDX_SECTOR_ISHARES','spine_fund',null),
    ('IDX_SECTOR_ISHARES','spine_fund_next',null)
  ) as b(cohort, col, val)
  left join public.cohort_tree t on t.cohort = b.cohort
  where t.cohort is null or (to_jsonb(t) ->> b.col) is distinct from b.val;
  if drift is not null then raise exception 'TR2 rollback proof: a row is not back to what TR1 loaded — %', drift; end if;
  select count(*) into k from public.cohort_tree where source = 'TR2-20261006';
  select count(*) into n from public.cohort_tree_members where source = 'TR2-20261006';
  if k <> 0 or n <> 0 then raise exception 'TR2 rollback proof: % nodes and % member rows written by TR2 are still there', k, n; end if;
  select count(*) into k from public.cohort_tree_members where status = 'pending_admission';
  if k <> pending_at_entry then raise exception 'TR2 rollback proof: % rows were pending at entry, % are now', pending_at_entry, k; end if;

  -- drop what the forward file created, and nothing else
  drop table public.cohort_tree_fund_links;
  drop table public.cohort_tree_candidates;
  drop table public.cohort_tree_tr2_removed;
  alter table public.cohort_tree drop constraint if exists cohort_tree_hub_pick_check;
  alter table public.cohort_tree drop column if exists layer, drop column if exists parent_why, drop column if exists hub_pick, drop column if exists hub_pick_source, drop column if exists hub_pick_note;
end $$;
commit;
