-- GENERATED by scripts/build-canonical-universe.mjs (provider repo) for the set 0c2abd57a836845ee120eba1e465cdb61db6a2cca5b3da1fcecbdc591936bb20
-- (420 names). Do not edit by hand: re-run the builder. Needs 20260927_admission_v2_role.sql first.
-- ADDITIVE: inserts only names that have no row (NOT EXISTS), marked source='admission-v2-20260927'.
insert into public.tickers (ticker, cohort, type, currency, active, source, role)
select v.ticker, v.cohort, v.type, 'USD', true, 'admission-v2-20260927', v.role
from (values
  ('AAOI','AI_HARDWARE','stock','full'),
  ('ACHR','THEMATIC','stock','full'),
  ('ALB','MATERIALS','stock','full'),
  ('AMKR','AI_HARDWARE','stock','full'),
  ('ARKX','FUNDS','etf','full'),
  ('AVAV','THEMATIC','stock','full'),
  ('BKSY','THEMATIC','stock','full'),
  ('BOTZ','FUNDS','etf','full'),
  ('BTDR','CRYPTO','stock','full'),
  ('CIBR','FUNDS','etf','full'),
  ('COHR','AI_HARDWARE','stock','full'),
  ('CRML','THEMATIC','stock','full'),
  ('FDN','FUNDS','etf','full'),
  ('FINX','FUNDS','etf','full'),
  ('GLW','AI_HARDWARE','stock','full'),
  ('HIVE','CRYPTO','stock','full'),
  ('HUBB','BLUE_CHIP','stock','full'),
  ('IGV','FUNDS','etf','full'),
  ('IHI','FUNDS','etf','full'),
  ('ITA','FUNDS','etf','full'),
  ('ITB','FUNDS','etf','full'),
  ('IYT','FUNDS','etf','full'),
  ('JETS','FUNDS','etf','full'),
  ('KIE','FUNDS','etf','full'),
  ('KRE','FUNDS','etf','full'),
  ('KTOS','THEMATIC','stock','full'),
  ('LEU','THEMATIC','stock','full'),
  ('LIT','FUNDS','etf','full'),
  ('LUNR','THEMATIC','stock','full'),
  ('NOK','AI_HARDWARE','stock','full'),
  ('NVTS','AI_HARDWARE','stock','full'),
  ('OUST','THEMATIC','stock','full'),
  ('PAVE','FUNDS','etf','full'),
  ('PEJ','FUNDS','etf','full'),
  ('PL','THEMATIC','stock','full'),
  ('POET','AI_HARDWARE','stock','full'),
  ('QTUM','FUNDS','etf','full'),
  ('RDW','THEMATIC','stock','full'),
  ('REMX','FUNDS','etf','full'),
  ('REZ','FUNDS','etf','full'),
  ('RIOT','CRYPTO','stock','full'),
  ('SATL','THEMATIC','stock','full'),
  ('SERV','THEMATIC','stock','full'),
  ('SIDU','THEMATIC','stock','full'),
  ('SPIR','THEMATIC','stock','full'),
  ('SQM','MATERIALS','stock','full'),
  ('STM','AI_HARDWARE','stock','full'),
  ('SYM','THEMATIC','stock','full'),
  ('TAN','FUNDS','etf','full'),
  ('TECK','MATERIALS','stock','full'),
  ('TSEM','AI_HARDWARE','stock','full'),
  ('URA','FUNDS','etf','full'),
  ('UUUU','THEMATIC','stock','full'),
  ('VSH','AI_HARDWARE','stock','full'),
  ('XBI','FUNDS','etf','full'),
  ('XSD','FUNDS','etf','full')
) as v(ticker, cohort, type, role)
where not exists (select 1 from public.tickers t where t.ticker = v.ticker);

-- PROOF: the Hub's active equity list is now exactly the provider's set, by count and by tier.
do $$
declare n int; g int;
begin
  select count(*) into n from public.tickers where active = true and (type is null or type not in ('crypto','future','index','rate'));
  if n <> 420 then raise exception 'admission v2: expected 420 active equity names, found %', n; end if;
  select count(*) into g from public.tickers where active = true and (type is null or type not in ('crypto','future','index','rate')) and role = 'geiger_only';
  if g <> 0 then raise exception 'admission v2: expected 0 geiger-only names, found %', g; end if;
end $$;
