-- TR2 (6 Oct 2026) · THE NEXT FUND BATCH — tree rows, AFTER ADMISSION. GENERATED by scripts/cohort-tree-next-funds-sql.mjs; do not edit by hand.
-- funds: 26 · index-set rows: 26 · reference rows: 10 · spine hand-overs: 7
-- held: none
-- Run ONLY once these 26 funds are admitted and /universe lists them. TARGETED, never blanket: it marks served only
-- the funds named here, and hands a spine over only on the 7 cohorts this batch set and only where the cohort is
-- still waiting for this batch's fund. Writes ONLY public.cohort_tree_members.status and public.cohort_tree's two
-- spine columns. One transaction; refuses unless the PENDING file has run.
-- Way back: the second block of 20261006_tr2_next_funds_tree_ROLLBACK.sql
begin;
do $$
declare n int;
begin
  select count(distinct ticker) into n from public.cohort_tree_members where ticker in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG') and role = 'index_fund';
  if n <> 26 then raise exception 'TR2-NEXT refused: only % of the 26 funds have a row in the tree. Run the PENDING file first; nothing was changed.', n; end if;
end $$;
update public.cohort_tree_members set status = 'served' where ticker in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG') and status = 'pending_admission';
update public.cohort_tree t set spine_fund = t.spine_fund_next, spine_fund_next = null from (values ('CRYPTO_EQUITIES','IBIT'),('CHINA','KWEB'),('GRID_ELECTRICAL','GRID'),('DEFENCE_TECH','SHLD'),('OIL_MIDSTREAM','MLPX'),('BIG_BANKS_BROKERS','KBWB'),('NEOCLOUDS_MINERS','WGMI')) v(cohort, fund) where t.cohort = v.cohort and t.spine_fund_next = v.fund;
do $$
declare i int; r int; p int; s int;
begin
  select count(*) filter (where role = 'index_fund' and status = 'served'), count(*) filter (where role = 'reference' and status = 'served'),
         count(*) filter (where status = 'pending_admission') into i, r, p
    from public.cohort_tree_members where ticker in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG');
  select (select count(*)::int from public.cohort_tree t where (t.cohort, t.spine_fund) in (('CRYPTO_EQUITIES','IBIT'),('CHINA','KWEB'),('GRID_ELECTRICAL','GRID'),('DEFENCE_TECH','SHLD'),('OIL_MIDSTREAM','MLPX'),('BIG_BANKS_BROKERS','KBWB'),('NEOCLOUDS_MINERS','WGMI')) and t.spine_fund_next is null) into s;
  if i <> 26 then raise exception 'TR2-NEXT: expected 26 served index-set rows, found %', i; end if;
  if r <> 10 then raise exception 'TR2-NEXT: expected 10 served reference rows, found %', r; end if;
  if p <> 0 then raise exception 'TR2-NEXT: % rows of this batch are still pending', p; end if;
  if s <> 7 then raise exception 'TR2-NEXT: expected 7 spines handed over, found % (a cohort was no longer waiting for this batch''s fund); nothing was changed.', s; end if;
end $$;
commit;
select 'TR2-NEXT served' as step, count(*) filter (where role = 'index_fund')::int as index_fund_rows, count(*) filter (where role = 'reference')::int as reference_rows,
  count(distinct ticker)::int as served_funds, (select count(*)::int from public.cohort_tree t where (t.cohort, t.spine_fund) in (('CRYPTO_EQUITIES','IBIT'),('CHINA','KWEB'),('GRID_ELECTRICAL','GRID'),('DEFENCE_TECH','SHLD'),('OIL_MIDSTREAM','MLPX'),('BIG_BANKS_BROKERS','KBWB'),('NEOCLOUDS_MINERS','WGMI')) and t.spine_fund_next is null) as spines_handed_over
  from public.cohort_tree_members where ticker in ('SPHB','TIP','IBIT','ARKK','CPER','EMB','FXY','EMXC','VGK','IWO','IWN','IWP','IWS','EWW','EWA','EWL','KWEB','XME','GRID','SHLD','MLPX','KBWB','ICLN','WGMI','XAR','UNG') and status = 'served';
