-- GENERATED by scripts/build-canonical-universe.mjs (provider repo) for the set 6e82721ba4f25c85ad29a60d9bda60a442b2631abc6c2d0be249eb95ac14c9f2
-- (487 names). Do not edit by hand: re-run the builder. Needs 20260927_admission_v2_role.sql first.
delete from public.tickers where source = 'admission-v2-20260927';
do $$
declare n int;
begin
  select count(*) into n from public.tickers where active = true and (type is null or type not in ('crypto','future','index','rate'));
  raise notice 'admission v2 rollback: % active equity names remain', n;
end $$;
