-- GENERATED by scripts/build-canonical-universe.mjs (provider repo) for the set 10ebf89cd6be183747b163fd48d7f42e6fe7b4f147b1daf88bad202c64682546
-- (598 names). Do not edit by hand: re-run the builder. Needs 20260927_admission_v2_role.sql first.
delete from public.tickers where source = 'admission-tr1-index-20261006';
do $$
declare n int;
begin
  select count(*) into n from public.tickers where active = true and (type is null or type not in ('crypto','future','index','rate'));
  raise notice 'admission v2 rollback: % active equity names remain', n;
end $$;
