-- TR1 (6 Oct 2026) · THE COHORT TREE — schema. GENERATED by scripts/cohort-tree-loader.mjs; do not edit by hand.
-- ADDITIVE (pre-approved class: new tables). Two NEW tables that no Hub or Station page reads. public.ticker_cohorts
-- — the table the Hub's cohort tabs are built from — is not read, written or referenced here.
-- Rollback: 20261006_tr1_cohort_tree_ROLLBACK.sql
create table if not exists public.cohort_tree (
  cohort          text primary key,
  label           text not null,
  kind            text not null check (kind in ('heading','cohort','index')),
  parent_1        text references public.cohort_tree(cohort) deferrable initially deferred,
  parent_2        text references public.cohort_tree(cohort) deferrable initially deferred,
  spine           text,
  spine_fund      text,
  spine_fund_next text,
  source          text not null default 'TR1-20261006',
  loaded_at       timestamptz not null default now()
);
comment on table public.cohort_tree is 'TR1 6 Oct 2026: the theme tree beside the GICS sectors. One row per node; up to two parents; spine_fund = the served fund the cohort is measured against; spine_fund_next = the fund that takes over once admitted. Not read by the Hub.';
create table if not exists public.cohort_tree_members (
  cohort       text not null references public.cohort_tree(cohort) on delete cascade deferrable initially deferred,
  ticker       text not null,
  role         text not null check (role in ('member','reference','index_fund')),
  status       text not null check (status in ('served','pending_admission')),
  near_copy_of text,
  why          text,
  source       text not null default 'TR1-20261006',
  loaded_at    timestamptz not null default now(),
  primary key (cohort, ticker)
);
comment on table public.cohort_tree_members is 'TR1 6 Oct 2026: who sits in each cohort_tree node and why. role member = a company; reference = the fund a topic cohort is measured against; index_fund = a market aggregate. Not read by the Hub.';
create index if not exists cohort_tree_members_ticker_idx on public.cohort_tree_members (ticker);
alter table public.cohort_tree enable row level security;
alter table public.cohort_tree_members enable row level security;
drop policy if exists cohort_tree_read on public.cohort_tree;
create policy cohort_tree_read on public.cohort_tree for select to anon, authenticated using (true);
drop policy if exists cohort_tree_members_read on public.cohort_tree_members;
create policy cohort_tree_members_read on public.cohort_tree_members for select to anon, authenticated using (true);
grant select on public.cohort_tree, public.cohort_tree_members to anon, authenticated;
grant select, insert, update, delete on public.cohort_tree, public.cohort_tree_members to service_role;
