/* C6b · the report page, built from four-names-c5b-c6-c6b.json, the knockout before/after and the headless shots: node report.mjs → COMPS-C6B.html */
import { readFileSync, writeFileSync } from "node:fs"; import { fileURLToPath } from "node:url"; import path from "node:path";
const HERE = path.dirname(fileURLToPath(import.meta.url)), J = (f) => JSON.parse(readFileSync(path.join(HERE, f), "utf8")), D = J("four-names-c5b-c6-c6b.json"), KB = J("knockout-before-pa5.json").k, KA = J("knockout-after-pa5b.json").k;
const css = readFileSync(path.join(HERE, "../../20261003/comps-c5/COMPS-C5.html"), "utf8").match(/<style>[\s\S]*?<\/style>/)[0];
const esc = (s) => String(s ?? "").replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));
const P = (v) => v == null ? "—" : "$" + (v >= 1000 ? Math.round(v).toLocaleString("en-US") : v >= 100 ? v.toFixed(0) : v.toFixed(2));
const X = (v) => v == null ? "—" : (Math.abs(v) >= 100 ? v.toFixed(0) : v.toFixed(1)) + "×";
const NAMES = ["MU", "NVDA", "CRWV", "CBRS"], KEYS = [["pe_ttm", "P/E"], ["pe_fwd", "P/E forward"], ["ev_ebitda", "EV/EBITDA"], ["ev_sales", "EV/sales"], ["ps", "P/S"], ["peg", "PEG"]];
const shot = (src, cap, max = "") => `<div class="shot"><div class="clip"${max ? ` style="max-width:${max}"` : ""}><img loading="lazy" src="${src}" alt="${esc(cap)}"></div><small>${cap}</small></div>`;
const outs = (a) => a.map((o) => `<b>${o.peer}</b>`).join(", ") || "none";
const sum = NAMES.map((t) => { const n = D.names[t], b = n.c6b.business; return `<tr><td class="k"><b>${t}</b><br><small>today ${P(n.price)}</small></td><td>${P(n.c5b.band.centre)}<br><small>${n.c5b.cells_out.length} single cells dropped</small></td><td>${P(n.c6.without.centre)}<br><small>out: ${outs(n.c6.outliers)}</small></td><td class="k"><b>${P(n.c6b.without.centre)}</b><br><small>out: ${outs(n.c6b.outliers)}</small></td><td>${P(n.c6b.with.centre)}</td><td>${b.same.length} of ${b.n} share ${esc(b.line)}${b.mostlyDifferent ? "<br><b>mostly different business</b>" : ""}</td></tr>`; }).join("");
const medTable = (t) => { const n = D.names[t]; return `<div class="tw"><table class="t"><thead><tr><th>${t} · peers' median</th><th>C5b</th><th>C6</th><th>C6b</th><th>${t}'s price at that median: C5b → C6 → C6b</th></tr></thead><tbody>${KEYS.map(([k, l]) => { const a = n.c5b.medians[k], b = n.c6.medians[k], c = n.c6b.medians[k]; return `<tr><td class="k">${l}</td><td>${X(a.median)} <small>${a.n} peers</small></td><td>${X(b.median)} <small>${b.n}</small></td><td class="k"><b>${X(c.median)}</b> <small>${c.n}</small></td><td>${a.price == null && c.price == null ? `<small>${t} cannot be priced on this row</small>` : `${P(a.price)} → ${P(b.price)} → <b>${P(c.price)}</b>`}</td></tr>`; }).join("")}<tr><td class="k">THE CENTRE (way C)</td><td>${P(n.c5b.band.centre)}</td><td>${P(n.c6.without.centre)}</td><td class="k"><b>${P(n.c6b.without.centre)}</b></td><td>low ${P(n.c6b.without.lo)} · high ${P(n.c6b.without.hi)}</td></tr></tbody></table></div>`; };
const marks = (t) => { const n = D.names[t], f = (x) => `${esc(x.column)} <small>(${Math.abs(x.distance).toFixed(1)} spreads ${x.distance > 0 ? "above" : "below"})</small>`; return `<div class="tw"><table class="t wrap"><thead><tr><th>${t}'s peer</th><th>verdict</th><th>price marks (these vote)</th><th>other marks (information only)</th></tr></thead><tbody>${n.c6b.marked.map((m) => `<tr><td class="k">${m.outlier ? `<b>${m.peer}</b>` : m.peer}</td><td>${m.outlier ? `<b>OUTLIER</b> · ${m.votes.length} of ${m.votes_have} multiples` : `in · 0 of ${m.votes_have} multiples`}</td><td>${m.votes.map(f).join(", ") || "none"}</td><td>${m.info.map(f).join(", ") || "none"}</td></tr>`).join("")}</tbody></table></div>`; };
const sect = (t, note) => `<h2>${t} <small>${note}</small></h2>
<div class="panel"><div class="two"><div>${shot(`../comps-c6/shots/after/${t}-set-1680.png`, "BEFORE (C6) · the set as C6 left it")}</div><div>${shot(`shots/${t}-set-1680.png`, "AFTER (C6b) · the set: under the header, how many peers share the business; an outlier only when the price is far out")}</div></div></div>
<div class="panel"><div class="two"><div>${shot(`../comps-c6/shots/after/${t}-range-1680.png`, "BEFORE (C6) · the range")}</div><div>${shot(`shots/${t}-range-1680.png`, "AFTER (C6b) · the range, centre with / without outliers")}</div></div></div>
<div class="panel">${shot(`shots/${t}-table-1680.png`, "AFTER (C6b) · the table: bright bold cells are price marks (they vote); the fainter cyan cells under growth, margins, balance sheet and capex are information only. Laid over the whole window here; in the Hub it sits in the company panel and scrolls sideways.")}</div>
<div class="panel">${medTable(t)}</div><div class="panel">${marks(t)}</div>`;
const B = Object.fromEntries(KB.entrants.map((e) => [e.sym, e])), top = [...KA.entrants].sort((a, b) => a.seed - b.seed).slice(0, 10);
const ko = top.map((e) => `<tr><td class="k"><b>${e.sym}</b></td><td>${B[e.sym] ? B[e.sym].seed : "—"} → <b>${e.seed}</b></td><td>${B[e.sym] ? B[e.sym].score.toFixed(3) : "—"} → <b>${e.score.toFixed(3)}</b></td><td>${B[e.sym] ? B[e.sym].outliers + " single cells" : "—"} → <b>${e.outliers} peers</b>${e.who && e.who.length ? " (" + e.who.join(", ") + ")" : ""}</td></tr>`).join("");
const withOut = KA.entrants.filter((e) => e.outliers).map((e) => `${e.sym}: ${e.who.join(", ")}`).join("; ") || "none";
const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow">
<title>SCINTILLA · COMPS · C6b · OUTLIERS ON PRICE ONLY · 5 OCT</title>
${css}</head>
<body><div class="wrap">
<div class="top"><span class="brand"><b>SCINTILLA</b> · COMPS · C6b · AN OUTLIER IS A STRANGE PRICE, NOT FAST GROWTH</span><span data-scnav-slot></span><span class="stamp">C6b · 5 Oct 2026 · branch hub/c6b-outliers-price-only-20261005 · on top of C6 · not deployed</span></div>

<h2>The four names <small>the price the peers imply · C5b → C6 → C6b · prices of 5 Oct, the same figures on every side</small></h2>
<div class="panel"><div class="tw" style="padding-top:10px"><table class="t wrap"><thead><tr><th>company</th><th>C5b</th><th>C6 · without outliers</th><th>C6b · without outliers</th><th>C6b · with outliers</th><th>same business?</th></tr></thead><tbody>${sum}</tbody></table></div></div>

${sect("NVDA", "Arm is the one outlier: 313× earnings, 71× sales")}
${sect("MU", "SanDisk and Nvidia are back in — and the set is named: 2 of 12 are memory")}
${sect("CRWV", "the four AI-compute builders are back in")}
${sect("CBRS", "Credo and Astera are back in")}

<h2>On a phone <small>390 wide</small></h2>
<div class="panel"><div class="two"><div>${shot("shots/MU-390.png", "MU · the business line and the range", "390px")}</div><div>${shot("shots/NVDA-set-390.png", "NVDA · the set", "390px")}</div></div></div>

<h2>The allocation tool's knockout <small>branch pa5b-outliers-20261005 · cohort ${esc(KA.cohort)} · tonight's live figures, before → after</small></h2>
<div class="panel">${shot("shots/knockout-pa5b-1680.png", "AFTER (PA5b) · the knockout tonight, headless at 1680: the last rounds and the cards; each card says how many peers were left out on price (none for these names)")}</div>
<div class="panel"><div class="tw" style="padding-top:10px"><table class="t wrap"><thead><tr><th>name (top ten seeds after)</th><th>seed</th><th>fundamentals score</th><th>left out of its peers' medians</th></tr></thead><tbody>${ko}</tbody></table></div>
<div class="tw"><table class="t wrap"><tbody><tr><td class="k">the final</td><td>before: ${KB.final.a} beat ${KB.final.b} (${KB.final.as.toFixed(2)} v ${KB.final.bs.toFixed(2)})</td><td class="k"><b>after: ${KA.final.a} beat ${KA.final.b} (${KA.final.as.toFixed(2)} v ${KA.final.bs.toFixed(2)})</b></td></tr><tr><td class="k">names with an outlier peer</td><td>before: ${KB.entrants.filter((e) => e.outliers).length} of ${KB.entrants.length} had single cells dropped</td><td class="k"><b>after: ${esc(withOut)}</b></td></tr></tbody></table></div></div>

<details class="sc-pagespecs" open><summary>PAGE SPECS</summary><div class="words">
<p><b>The rule, in two sentences.</b> An outlier is a peer whose price is strange next to the group: in each valuation multiple (log scale) a peer more than 3.5 typical spreads from the peers' median is marked, trailing and forward P/E count as one vote, and a peer marked on 3 or more votes — or on at least half the votes it has, and at least two — is greyed, left out of every median and of the implied price, never deleted, one click keeps it. Growth, margin, capex and leverage cells are still marked when far out, as information only, and never count.</p>
<p><b>The votes.</b> Five on the Hub's comps tab: P/E (trailing or forward), EV/EBITDA, EV/sales, P/S, PEG — the multiples C5 shows; it has no forward EV/sales and no P/FCF. Three in the allocation tool, which carries fewer columns: P/E (trailing or forward), P/S, P/B.</p>
<p><b>What changed on the four names.</b> C6 removed nine peers; eight of them were fast growers with ordinary multiples and are back in (MU: SNDK, NVDA · CRWV: NBIS, WULF, APLD, HUT · CBRS: CRDO, ALAB). Their growth and capex cells are still marked, fainter. ARM stays out of NVDA's set, now on three price votes (P/E, EV/sales, P/S); its gross-margin mark no longer counts. MU, CRWV and CBRS return to the centre they had with every peer in.</p>
<p><b>Same business?</b> A peer shares the company's business when at least 15% of its revenue sits in a line it shares exactly with the company (C5's own membership bar), not merely the same family. When fewer than half the peers do, the set is named “peer set mostly different business — fix the peers, not the outliers”, and the outlier rule does not cut the peers that do share it. Tonight: <b>MU 2 of 12 (memory) and NVDA 3 of 12 (data-center chips) are named</b>; CBRS 12 of 12 is not; <b>CRWV 7 of 12 share “ai cloud &amp; hosting” and is not named</b> — on C5's lines its set is five infrastructure-software names and seven AI hosts (five of them bitcoin miners turned hosts), so it is not “mostly software”. FMP's own industry label was not used for this test: it files CoreWeave under “Software - Infrastructure”, which would call the software names the right ones.</p>
<p><b>The allocation tool.</b> The knockout's four readings, and the COMPARABLES table, measured each name against its peers after dropping single cells (C5's old rule, 3 spreads, ratios only). They now drop whole peers on the same price-only rule. In ${esc(KA.cohort)} tonight, ${KB.entrants.filter((e) => e.outliers).length} of ${KB.entrants.length} names had single cells dropped from their peers before; after, one peer is left out in one name's set (${esc(withOut)}). Seeds move a little; the final is ${KA.final.a} over ${KA.final.b} where it was ${KB.final.a} over ${KB.final.b}. Two other medians in that tool still use C5's single-cell rule and were not touched: the sector-wide CHEAP / EXPENSIVE read and the implied-price table.</p>
<p><b>Where each number comes from.</b> The four sets are C6's fixtures (C5's business-first sets, prices from the chart API on 5 Oct after the close, figures from the Hub's tables with C5b's one-currency rule). C5b and C6 are recomputed by the same code on the same figures; C6's first rule is kept reproducible in the code. The knockout rows are the live allocation page run headless, main against the branch, minutes apart. Pictures: headless, 1680 and 390 wide, the Hub served from the branch under its own hostname; every write the page attempted was answered locally (2, both from the keep click and its undo on NVDA at 390).</p>
<p><b>What could be wrong.</b> (1) EV/sales and P/S are still two votes although they say nearly the same thing; counting them once leaves the four names unchanged (ARM is then out on 2 of 4). (2) A peer that loses money has few multiples: with only two, both must be far out. (3) NVDA's set is named “mostly different business” because nine of its twelve peers are equipment, analog, foundry and IP names; that is what the test measures, and it may read as noise on a company with few true peers. (4) The same-business protection did not act on any of the four sets tonight; it is covered by a made-up case in the tests only. (5) The group is measured once, and the company itself is not tested.</p>
<p><b>Not done.</b> Nothing is deployed; index.html is untouched; no table was written. No peer set was changed — MU's and NVDA's are named, not fixed. C6's own report page and its pictures are left as they were.</p>
<p><b>Tests.</b> Hub: tests/comps-c6b.test.mjs, 8 tests (a fast grower with normal multiples is not an outlier; a 300× P/E peer is; trailing and forward P/E are one vote; growth marks never tip a verdict; the four names; the business test; the tab). tests/comps-c6.test.mjs, 11 tests, now run C6's first rule by name. Allocation: tests/pa5b.test.mjs, 5 tests.</p>
</div></details>
</div></body></html>
`;
writeFileSync(path.join(HERE, "COMPS-C6B.html"), html);
console.log("COMPS-C6B.html", html.length);
